Repository PipedreamHQ/pipedream, pull requests merged in 2022-07, with the labels that each got.

#3278 Sendgrid: Fix an error trying to assign to an undefined object when using the Reply To parameters
  components/sendgrid/actions/send-email-multiple-recipients/send-email-multiple-recipients.mjs
  components/sendgrid/actions/send-email-single-recipient/send-email-single-recipient.mjs
Labels: triaged, User submitted

#3240 #938 - pCloud new actions and source
  components/pcloud/actions/common/base.mjs
  components/pcloud/actions/copy-file/copy-file.mjs
  components/pcloud/actions/copy-folder/copy-folder.mjs
  components/pcloud/actions/create-folder/create-folder.mjs
  components/pcloud/actions/download-files/download-files.mjs
  components/pcloud/actions/list-contents/list-contents.mjs
  components/pcloud/actions/upload-file/upload-file.mjs
  components/pcloud/package.json
  components/pcloud/pcloud.app.mjs
  components/pcloud/sources/watch-folder/watch-folder.mjs
  pnpm-lock.yaml
Labels: triaged, User submitted

#3300 Gitpodify!
  .gitpod.Dockerfile
  .gitpod.yml
  scripts/gitpod_api_wizard.sh
Labels: triaged, User submitted

#3317 Crove App - fixed spelling error
  components/crove_app/actions/generate_pdf_from_document/generate_pdf_from_document.mjs
Labels: triaged, User submitted

#3214 Add Verifalia verify-email action
  components/verifalia/.gitignore
  components/verifalia/actions/verify-email/verify-email.mjs
  components/verifalia/app/verifalia.app.ts
  components/verifalia/common.mjs
  components/verifalia/package-lock.json
  components/verifalia/package.json
  components/verifalia/verifalia.app.mjs
  pnpm-lock.yaml
Labels: triaged, User submitted

#3318 Sendinblue fix send transactional email add params prop
  components/sendinblue/actions/send-transactional-email/send-transactional-email.mjs
  components/sendinblue/sendinblue.app.mjs
Labels: enhancement, triaged

#3216 Feedbin new sources
  components/feedbin/actions/get-subscriptions/get-subscriptions.mjs
  components/feedbin/common/constants.mjs
  components/feedbin/common/utils.mjs
  components/feedbin/feedbin.app.mjs
  components/feedbin/package-lock.json
  components/feedbin/package.json
  components/feedbin/sources/common.mjs
  components/feedbin/sources/liked-item/liked-item.mjs
  components/feedbin/sources/new-search/new-search.mjs
  components/feedbin/sources/saved-item/saved-item.mjs
  pnpm-lock.yaml
Labels: trigger / source, triaged, User submitted

#3377 fix check null for previous version
  .github/workflows/publish-components.yaml
Labels: triaged

#3359 @pipedream/platform axios console.log if unable to export
  platform/dist/axios.js
  platform/lib/axios.ts
  platform/package-lock.json
  platform/package.json
Labels: enhancement, triaged

#3410 apply default directory structure to shopify partner
  components/shopify_partner/common/common.mjs
  components/shopify_partner/sources/new-app-charges/new-app-charges.mjs
  components/shopify_partner/sources/new-app-installs/new-app-installs.mjs
  components/shopify_partner/sources/new-app-relationship-events/new-app-relationship-events.mjs
  components/shopify_partner/sources/new-app-uninstalls/new-app-uninstalls.mjs
Labels: triaged

#3418 Update get-invoice.mjs
  components/quickbooks/actions/get-invoice/get-invoice.mjs
Labels: triaged, User submitted

#3361 Create Payment #3352
  components/quickbooks/actions/create-bill/create-bill.mjs
  components/quickbooks/actions/create-customer/create-customer.mjs
  components/quickbooks/actions/create-invoice/create-invoice.mjs
  components/quickbooks/actions/create-payment/create-payment.mjs
  components/quickbooks/actions/get-bill/get-bill.mjs
  components/quickbooks/actions/get-customer/get-customer.mjs
  components/quickbooks/actions/get-invoice/get-invoice.mjs
  components/quickbooks/actions/get-my-company/get-my-company.mjs
  components/quickbooks/actions/get-purchase-order/get-purchase-order.mjs
  components/quickbooks/actions/get-purchase/get-purchase.mjs
  components/quickbooks/actions/get-sales-receipt/get-sales-receipt.mjs
  components/quickbooks/actions/get-time-activity/get-time-activity.mjs
  components/quickbooks/actions/sandbox-search-invoices/sandbox-search-invoices.mjs
  components/quickbooks/actions/search-accounts/search-accounts.mjs
  components/quickbooks/actions/search-customers/search-customers.mjs
  components/quickbooks/actions/search-items/search-items.mjs
  components/quickbooks/actions/search-products/search-products.mjs
  components/quickbooks/actions/search-query/search-query.mjs
  components/quickbooks/actions/search-time-activities/search-time-activities.mjs
  components/quickbooks/actions/search-vendors/search-vendors.mjs
  components/quickbooks/actions/update-customer/update-customer.mjs
  components/quickbooks/package-lock.json
  components/quickbooks/package.json
  components/quickbooks/quickbooks.app.mjs
  pnpm-lock.yaml
Labels: action

#3426 Google Sheets update-rows thanks to @dreammonkey & fixed linter errors
  components/google_sheets/actions/update-rows/update-rows.mjs
Labels: triaged, User submitted

#3394 [TRIGGER] stripe #3338
  components/stripe/package.json
  components/stripe/sources/common/constants.mjs
  components/stripe/sources/custom-webhook-events/custom-webhook-events.mjs
  components/stripe/stripe.app.mjs
Labels: refactor

#3435 [New Action] Shopify addTags mutation
  components/shopify/actions/add-tags/add-tags.mjs
  components/shopify/shopify.app.mjs
Labels: triaged, User submitted

#3450 Republish - Ghost Admin new Actions
  components/ghost_org_admin_api/actions/create-member/create-member.mjs
  components/ghost_org_admin_api/actions/update-member/update-member.mjs
Labels: triaged

#3401 Fixed isssue with dinamic options in additionsProps app function
  components/airtable/actions/create-or-update-record/create-or-update-record.mjs
  components/airtable/actions/create-single-record/create-single-record.mjs
  components/airtable/actions/get-record-or-create/get-record-or-create.mjs
  components/airtable/actions/get-record/get-record.mjs
  components/airtable/actions/update-record/update-record.mjs
  components/airtable/common/utils.mjs
Labels: bug

#3183 Add triggercmd trigger-command action
  components/triggercmd/actions/trigger-command/trigger-command.mjs
  components/triggercmd/triggercmd.app.mjs
Labels: triaged, User submitted

#3473 Incrementing the versions to test deploy in typescript [Expensify]
  components/expensify/actions/create-expense/create-expense.ts
  components/expensify/actions/export-report-to-pdf/export-report-to-pdf.ts
  pnpm-lock.yaml
Labels: refactor

#3477 Fixed the quotation marks on version [Triggercmd]
  components/triggercmd/actions/trigger-command/trigger-command.mjs
  pnpm-lock.yaml
Labels: refactor

#3431 Paytrace actions, refactored @isaiahtaylor's PR
  components/paytrace/actions/batch-summary/batch-summary.mjs
  components/paytrace/actions/list-batch-transactions/list-batch-transactions.mjs
  components/paytrace/actions/list-batches/list-batches.mjs
  components/paytrace/actions/list-transactions/list-transactions.mjs
  components/paytrace/common/common.mjs
  components/paytrace/package.json
  components/paytrace/paytrace.app.mjs
  pnpm-lock.yaml
Labels: triaged, User submitted

#3516 Fixing source on adalo [ADALO]
  components/adalo/adalo.app.mjs
  components/adalo/package.json
  components/adalo/sources/new-record/new-record.mjs
Labels: refactor

#3517 Fix activecampaign create and uppdate contact actions
  components/activecampaign/actions/common/base-contact.mjs
  components/activecampaign/actions/create-contact/create-contact.mjs
  components/activecampaign/actions/create-or-update-contact/create-or-update-contact.mjs
  components/activecampaign/activecampaign.app.mjs
  components/activecampaign/common/constants.mjs
  components/activecampaign/common/utils.mjs
Labels: bug

#3495 [FEATURE] postgresql custom query to find row #3174
  components/postgresql/actions/find-row-custom-query/find-row-custom-query.mjs
  components/postgresql/postgresql.app.mjs
Labels: action

#3499 [BUG] [ACTION] SendGrid: Send Email Single Single Recipient is missing Template ID prop #3405
  components/sendgrid/actions/send-email-single-recipient/send-email-single-recipient.mjs
  components/sendgrid/sendgrid.app.mjs
Labels: refactor
