Repository PipedreamHQ/pipedream, pull requests merged in 2022-03, with the labels that each got.

#2299 [Action] symbl_ai -- Add submit video URL
  components/symbl_ai/actions/submit-video-url/post-video-url.mjs
  components/symbl_ai/package.json
  components/symbl_ai/symbl_ai.app.mjs
Labels: User submitted

#2086 Fix deduping unique Zoho CRM events
  components/zoho_crm/sources/common/http-based/base.js
  components/zoho_crm/sources/new-contact/new-contact.mjs
  components/zoho_crm/sources/new-event/new-event.mjs
  components/zoho_crm/sources/new-lead/new-lead.mjs
  components/zoho_crm/sources/new-module-entry/new-module-entry.mjs
  components/zoho_crm/sources/new-or-updated-contact/new-or-updated-contact.mjs
  components/zoho_crm/sources/new-or-updated-lead/new-or-updated-lead.mjs
  components/zoho_crm/sources/new-or-updated-module-entry/new-or-updated-module-entry.mjs
  components/zoho_crm/sources/new-user/new-user.mjs
  components/zoho_crm/sources/updated-module-entry/updated-module-entry.mjs
Labels: bug

#2190 [ACTION] Microsoft Outlook - Send Email
  components/microsoft_outlook/actions/send-email/send-email.mjs
  components/microsoft_outlook/microsoft_outlook.app.mjs
Labels: User submitted

#2379 Fix TypeError in Slack send-message-private-channel action
  components/slack/actions/send-message-private-channel/send-message-private-channel.mjs
Labels: bug

#2303 [ACTION] New actions for IP2Location and IP2Proxy
  components/ip2location/actions/query-ip-info/query-ip-info.mjs
  components/ip2location/common/constants.mjs
  components/ip2location/ip2location.app.mjs
  components/ip2location/package.json
  components/ip2proxy/actions/query-ip-info/query-ip-info.mjs
  components/ip2proxy/common/constants.mjs
  components/ip2proxy/ip2proxy.app.mjs
  components/ip2proxy/package.json
Labels: User submitted

#2320 [ACTION] New action for IP2WHOIS
  components/ip2whois/actions/query-domain-info/query-domain-info.mjs
  components/ip2whois/ip2whois.app.mjs
  components/ip2whois/package.json
Labels: User submitted

#2377 New Symbl.ai Get Job Status Action
  components/symbl_ai/actions/get-job-status/get-job-status.mjs
  components/symbl_ai/actions/post-video-url/post-video-url.mjs
  components/symbl_ai/symbl_ai.app.mjs
Labels: User submitted

#2317 [ACTION] New actions for FraudlabsPro
  components/fraudlabs_pro/actions/send-sms-verification/send-sms-verification.mjs
  components/fraudlabs_pro/actions/verify-otp/verify-otp.mjs
  components/fraudlabs_pro/fraudlabs_pro.app.mjs
  components/fraudlabs_pro/package.json
Labels: User submitted

#2393 Added Basic Conversation API Functionality
  components/symbl_ai/actions/get-action-items/get-action-items.mjs
  components/symbl_ai/actions/get-follow-ups/get-follow-ups.mjs
  components/symbl_ai/actions/get-job-status/get-job-status.mjs
  components/symbl_ai/actions/get-questions/get-questions.mjs
  components/symbl_ai/actions/get-speech-to-text/get-speech-to-text.mjs
  components/symbl_ai/actions/get-topics/get-topics.mjs
  components/symbl_ai/symbl_ai.app.mjs
Labels: User submitted

#2155 [ACTIONS] Monday new actions
  components/monday/actions/create-board/create-board.mjs
  components/monday/actions/create-group/create-group.mjs
  components/monday/actions/create-item/create-item.mjs
  components/monday/actions/create-update/create-update.mjs
  components/monday/actions/update-item-name/update-item-name.mjs
  components/monday/common/constants.mjs
  components/monday/common/mutations.mjs
  components/monday/common/queries.mjs
  components/monday/common/utils.mjs
  components/monday/monday.app.mjs
  components/monday/package-lock.json
  components/monday/package.json
Labels: help wanted, good first issue, action

#2436 [ACTION] Google Drive - Create document from template
  components/google_drive/actions/create-file-from-template/create-file-from-template.mjs
Labels: User submitted

#2445 fix for [warning] object was filtered for serialization in Tweet code
  components/twitter/sources/common/tweets.mjs
  components/twitter/sources/my-tweets/my-tweets.mjs
  components/twitter/sources/new-tweet-in-list/new-tweet-in-list.mjs
  components/twitter/sources/user-tweets/user-tweets.mjs
  components/twitter/sources/watch-retweets-of-me/watch-retweets-of-me.mjs
  components/twitter/sources/watch-retweets-of-my-tweet/watch-retweets-of-my-tweet.mjs
  components/twitter/sources/watch-retweets-of-user-tweet/watch-retweets-of-user-tweet.mjs
Labels: User submitted

#2464 Added GET Entities, Analytics, Conversation and All Conversations actions
  components/symbl_ai/actions/constants.mjs
  components/symbl_ai/actions/get-analytics/get-analytics.mjs
  components/symbl_ai/actions/get-conversation/get-conversation.mjs
  components/symbl_ai/actions/get-conversations/get-conversations.mjs
  components/symbl_ai/actions/get-entities/get-entities.mjs
  components/symbl_ai/symbl_ai.app.mjs
Labels: User submitted

#2473 Added channel metadata prop
  components/symbl_ai/actions/post-video-url/post-video-url.mjs
Labels: User submitted

#2481 Updated Conversation API actions
  components/symbl_ai/actions/delete-conversation/delete-conversation.mjs
  components/symbl_ai/actions/get-members/get-members.mjs
  components/symbl_ai/actions/get-trackers/get-trackers.mjs
  components/symbl_ai/symbl_ai.app.mjs
Labels: User submitted

#2474 Add opensea events source
  components/opensea/opensea.app.mjs
  components/opensea/sources/events/events.mjs
Labels: User submitted

#2485 Added POST Trackers and Analytics Summary UI Action
  components/symbl_ai/actions/post-trackers-analytics-ui/post-trackers-analytics-ui.mjs
  components/symbl_ai/actions/post-video-summary-ui/post-video-summary-ui.mjs
  components/symbl_ai/symbl_ai.app.mjs
Labels: User submitted

#2503 Removed illegal characters
  components/medium/actions/create-post/create-post.mjs
Labels: User submitted
