Repository PipedreamHQ/pipedream, pull requests merged in 2022-09, with the labels that each got.

#4141 [Gmail] Reduced scopes
  components/gmail/.gitignore
  components/gmail/actions/add-label-to-email/add-label-to-email.mjs
  components/gmail/actions/find-email/find-email.mjs
  components/gmail/actions/send-email/send-email.mjs
  components/gmail/app/gmail.app.ts
  components/gmail/gmail.app.mjs
  components/gmail/sources/common/polling.mjs
  components/gmail/sources/new-attachment/new-attachment.mjs
  components/gmail/sources/new-email/new-email.mjs
Labels: triaged

#4130 Added Harvest Source for new time entries
  components/harvest/sources/new-timeentry-entry/new-timeentry-entry.mjs
Labels: triaged, User submitted

#4164 Add dev.to new reading list item event
  components/dev_to/dev_to.app.mjs
  components/dev_to/sources/reading-list/reading-list.mjs
Labels: triaged, User submitted

#4144 Adding actions to send single emails with body and template.
  components/smtp2go/actions/common.ts
  components/smtp2go/actions/send-single-email-with-template/send-single-email-with-template.ts
  components/smtp2go/actions/send-single-email/send-single-email.ts
  components/smtp2go/app/smtp2go.app.ts
  components/smtp2go/package.json
  components/smtp2go/smtp2go.app.ts
Labels: triaged, User submitted

#4092 StatusCake #3793
  components/statuscake/package.json
  components/statuscake/sources/new-uptime-alert/new-uptime-alert.mjs
  components/statuscake/sources/new-uptime/new-uptime.mjs
  components/statuscake/statuscake.app.mjs
  pnpm-lock.yaml
Labels: trigger / source

#4163 feat: Ecwid Updates
  components/ecwid/app/ecwid.app.ts
  components/ecwid/commons/commons.mjs
  components/ecwid/ecwid.app.mjs
  components/ecwid/package.json
  components/ecwid/sources/get-paid-orders/get-paid-orders.mjs
Labels: triaged, User submitted

#4124 SupportBee #3797
  components/supportbee/actions/create-ticket/create-ticket.mjs
  components/supportbee/package.json
  components/supportbee/sources/common/common.mjs
  components/supportbee/sources/new-agent-reply/new-agent-reply.mjs
  components/supportbee/sources/new-comment/new-comment.mjs
  components/supportbee/sources/new-customer-reply/new-customer-reply.mjs
  components/supportbee/sources/new-ticket/new-ticket.mjs
  components/supportbee/supportbee.app.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#4175 Removed a duplicate Harvest source for new timesheet entries
  components/harvest/sources/new-invoice-entry/new-invoice-entry.mjs
  components/harvest/sources/new-timeentry-entry/new-timeentry-entry.mjs
  components/harvest/sources/new-timesheet-entry/new-timesheet-entry.mjs
Labels: triaged, User submitted

#4098 [ACTIONS/SOURCES] Zoho Projects new actions and sources
  components/zoho_projects/actions/add-log-time/add-log-time.mjs
  components/zoho_projects/actions/create-bug/create-bug.mjs
  components/zoho_projects/actions/create-milestone/create-milestone.mjs
  components/zoho_projects/actions/create-project/create-project.mjs
  components/zoho_projects/actions/create-task-list/create-task-list.mjs
  components/zoho_projects/actions/create-task/create-task.mjs
  components/zoho_projects/actions/find-project/find-project.mjs
  components/zoho_projects/actions/update-project/update-project.mjs
  components/zoho_projects/actions/upload-file/upload-file.mjs
  components/zoho_projects/common/constants.mjs
  components/zoho_projects/common/utils.mjs
  components/zoho_projects/package.json
  components/zoho_projects/sources/common.mjs
  components/zoho_projects/sources/new-bug/new-bug.mjs
  components/zoho_projects/sources/new-log-time/new-log-time.mjs
  components/zoho_projects/sources/new-milestone/new-milestone.mjs
  components/zoho_projects/sources/new-project/new-project.mjs
  components/zoho_projects/sources/new-task-list/new-task-list.mjs
  components/zoho_projects/sources/new-task/new-task.mjs
  components/zoho_projects/zoho_projects.app.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#4256 Re-add go version to docs
  docs/docs/.vuepress/configs/envVars.js
Labels: triaged, User submitted

#4223 [ACTIONS/SOURCES] Zoho desk new sources and actions
  components/zoho_desk/actions/add-ticket-attachment/add-ticket-attachment.mjs
  components/zoho_desk/actions/add-ticket-comment/add-ticket-comment.mjs
  components/zoho_desk/actions/create-account/create-account.mjs
  components/zoho_desk/actions/create-contact/create-contact.mjs
  components/zoho_desk/actions/create-ticket/create-ticket.mjs
  components/zoho_desk/actions/find-contact/find-contact.mjs
  components/zoho_desk/actions/find-or-create-contact/find-or-create-contact.mjs
  components/zoho_desk/actions/search-ticket/search-ticket.mjs
  components/zoho_desk/actions/send-email-reply/send-email-reply.mjs
  components/zoho_desk/actions/update-contact/update-contact.mjs
  components/zoho_desk/actions/update-ticket/update-ticket.mjs
  components/zoho_desk/common/constants.mjs
  components/zoho_desk/common/utils.mjs
  components/zoho_desk/package.json
  components/zoho_desk/sources/changed-ticket-status/changed-ticket-status.mjs
  components/zoho_desk/sources/common.mjs
  components/zoho_desk/sources/new-account/new-account.mjs
  components/zoho_desk/sources/new-agent/new-agent.mjs
  components/zoho_desk/sources/new-contact/new-contact.mjs
  components/zoho_desk/sources/new-ticket-attachment/new-ticket-attachment.mjs
  components/zoho_desk/sources/new-ticket-comment/new-ticket-comment.mjs
  components/zoho_desk/sources/new-ticket-message/new-ticket-message.mjs
  components/zoho_desk/sources/new-ticket/new-ticket.mjs
  components/zoho_desk/sources/updated-ticket/updated-ticket.mjs
  components/zoho_desk/zoho_desk.app.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#4289 Rise #3766
  components/rise/actions/common/constants.ts
  components/rise/actions/create-invitation/create-invitation.ts
  components/rise/actions/find-invitations/find-invitations.ts
  components/rise/actions/find-users/find-users.ts
  components/rise/app/rise.app.ts
  components/rise/package.json
  components/rise/tsconfig.json
  pnpm-lock.yaml
Labels: action

#4282 Rebrandly #3755
  components/rebrandly/actions/create-link/create-link.mjs
  components/rebrandly/actions/update-link/update-link.mjs
  components/rebrandly/package.json
  components/rebrandly/rebrandly.app.mjs
  components/rebrandly/sources/new-link/new-link.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#4342 Salesforce: fix loading Object Type options in Updated Field on Record
  components/salesforce_rest_api/package.json
  components/salesforce_rest_api/sources/common.mjs
  components/salesforce_rest_api/sources/new-object/new-object.mjs
  components/salesforce_rest_api/sources/object-deleted/object-deleted.mjs
  components/salesforce_rest_api/sources/object-updated/object-updated.mjs
  components/salesforce_rest_api/sources/updated-field-on-record/updated-field-on-record.mjs
Labels: bug

#4335 Pocket #3733
  components/pocket/actions/save-to-later/save-to-later.mjs
  components/pocket/package.json
  components/pocket/pocket.app.mjs
  components/pocket/sources/common/common.mjs
  components/pocket/sources/common/constants.mjs
  components/pocket/sources/new-archived-item/new-archived-item.mjs
  components/pocket/sources/new-favorited-item/new-favorited-item.mjs
  components/pocket/sources/new-item/new-item.mjs
  components/pocket/sources/new-tagged-item/new-tagged-item.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#4346 [Salesforce] Webhooks README Instructions
  components/helper_functions/actions/xml-to-json/xml-to-json.mjs
  components/helper_functions/package.json
  components/salesforce_rest_api/README.md
  components/salesforce_rest_api/actions/convert-soap-xml-to-json/convert-soap-xml-to-json.mjs
  components/salesforce_rest_api/package.json
  pnpm-lock.yaml
Labels: triaged

#4358 Fix README Typos
  components/salesforce_rest_api/README.md
  docs/docs/components/api/README.md
Labels: triaged

#4365 Rename README files to uppercase
  components/hacker_news/README.md
  components/http/README.md
  components/twitter/README.md
Labels: bug, docs

#4341 Fixed tasks requests and made it optional in sources
  components/asana/actions/add-task-to-section/add-task-to-section.mjs
  components/asana/actions/create-project/create-project.mjs
  components/asana/actions/create-subtask/create-subtask.mjs
  components/asana/actions/create-task-comment/create-task-comment.mjs
  components/asana/actions/create-task/create-task.mjs
  components/asana/actions/delete-task/delete-task.mjs
  components/asana/actions/find-task-by-id/find-task-by-id.mjs
  components/asana/actions/search-projects/search-projects.mjs
  components/asana/actions/search-sections/search-sections.mjs
  components/asana/actions/search-tasks/search-tasks.mjs
  components/asana/actions/search-user-projects/search-user-projects.mjs
  components/asana/actions/update-task/update-task.mjs
  components/asana/asana.app.mjs
  components/asana/package.json
  components/asana/sources/common/common.mjs
  components/asana/sources/new-completed-task/new-completed-task.mjs
  components/asana/sources/new-project/new-project.mjs
  components/asana/sources/new-story/new-story.mjs
  components/asana/sources/new-subtask/new-subtask.mjs
  components/asana/sources/new-tag/new-tag.mjs
  components/asana/sources/new-task/new-task.mjs
  components/asana/sources/new-team/new-team.mjs
  components/asana/sources/new-user/new-user.mjs
  components/asana/sources/new-workspace/new-workspace.mjs
  components/asana/sources/tag-added-to-task/tag-added-to-task.mjs
  components/asana/sources/task-updated-in-project/task-updated-in-project.mjs
Labels: bug

#4359 feat: Ecwid get order and update order status actions added
  components/ecwid/actions/ecwid-get-order.mjs
  components/ecwid/actions/ecwid-update-order-status.mjs
  components/ecwid/package.json
Labels: triaged, User submitted

#4369 Auto-generated marketplace docs
  components/airtable/README.md
  components/asana/README.md
  components/aws/README.md
  components/bitbucket/README.md
  components/calendly/README.md
  components/chat_api_for_whatsapp/README.md
  components/clickup/README.md
  components/coinmarketcap/README.md
  components/discord/README.md
  components/discord_bot/README.md
  components/discord_webhook/README.md
  components/dropbox/README.md
  components/firebase_admin_sdk/README.md
  components/google/README.md
  components/google_calendar/README.md
  components/google_classroom/README.md
  components/google_cloud/README.md
  components/google_drive/README.md
  components/google_sheets/README.md
  components/jira/README.md
  components/jotform/README.md
  components/mailchimp/README.md
  components/microsoft_teams/README.md
  components/mongodb/README.md
  components/mysql/README.md
  components/netlify/README.md
  components/pipedream/README.md
  components/postgresql/README.md
  components/reddit/README.md
  components/sendgrid/README.md
  components/shopify/README.md
  components/slack/README.md
  components/spotify/README.md
  components/stripe/README.md
  components/telegram_bot_api/README.md
  components/todoist/README.md
  components/trello/README.md
  components/twilio/README.md
  components/twitch/README.md
  components/typeform/README.md
  components/webflow/README.md
  components/woocommerce/README.md
  components/youtube_data_api/README.md
Labels: enhancement, docs, actions-and-sources-docs

#4317 Ninox
  components/ninox/actions/create-record/create-record.ts
  components/ninox/actions/update-record/update-record.ts
  components/ninox/app/ninox.app.ts
  components/ninox/package.json
  components/ninox/sources/common/common.ts
  components/ninox/sources/new-record/new-record.ts
  components/ninox/sources/new-updated-record/new-updated-record.ts
  components/ninox/tsconfig.json
  pnpm-lock.yaml
Labels: action, trigger / source

#4312 Zenler new actions and sources
  components/zenler/actions/create-user/create-user.mjs
  components/zenler/actions/enroll-user/enroll-user.mjs
  components/zenler/actions/register-live-class/register-live-class.mjs
  components/zenler/actions/register-live-webinar/register-live-webinar.mjs
  components/zenler/actions/subscribe-funnel/subscribe-funnel.mjs
  components/zenler/actions/unenroll-user/unenroll-user.mjs
  components/zenler/common/constants.mjs
  components/zenler/common/utils.mjs
  components/zenler/package.json
  components/zenler/sources/common.mjs
  components/zenler/sources/course-complete/course-complete.mjs
  components/zenler/sources/lesson-complete/lesson-complete.mjs
  components/zenler/sources/new-funnel-subscription/new-funnel-subscription.mjs
  components/zenler/sources/new-live-class-registration/new-live-class-registration.mjs
  components/zenler/sources/new-live-interactive-webinar-registration/new-live-interactive-webinar-registration.mjs
  components/zenler/sources/new-user/new-user.mjs
  components/zenler/zenler.app.mjs
  pnpm-lock.yaml
Labels: action, trigger / source
