Repository PipedreamHQ/pipedream, pull requests merged in 2022-08, with the labels that each got.

#3884 elmah.io #3861
  components/elmah_io/elmah_io.app.mjs
  components/elmah_io/package.json
  components/elmah_io/sources/common/constants.mjs
  components/elmah_io/sources/new-error/new-error.mjs
  pnpm-lock.yaml
Labels: trigger / source

#3471 Namely #3400
  components/namely/actions/create-user/create-user.ts
  components/namely/actions/get-user/get-user.ts
  components/namely/actions/update-user/update-user.ts
  components/namely/app/common/constants.ts
  components/namely/app/namely.app.ts
  components/namely/package.json
  components/namely/sources/common/base-user.ts
  components/namely/sources/created-user/created-user.ts
  components/namely/sources/updated-user/updated-user.ts
  components/namely/tsconfig.json
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: action, trigger / source

#3505 Google calendar: Add ability to send updates
  components/google_calendar/actions/create-event/create-event.mjs
Labels: triaged, User submitted

#3914 [ADALO] Added timer and pagination
  components/adalo/sources/new-record/new-record.mjs
Labels: triaged, refactor

#3478 Add Verifalia actions
  components/verifalia/actions/delete-job/delete-job.mjs
  components/verifalia/actions/get-balance/get-balance.mjs
  components/verifalia/actions/verify-email/verify-email.mjs
  components/verifalia/package.json
Labels: triaged, User submitted

#3879 [BUG] Datadog - New Monitor Event Trigger async options broken #3459
  components/datadog/actions/post-metric-data/post-metric-data.mjs
  components/datadog/datadog.app.mjs
  components/datadog/package.json
  components/datadog/sources/new-monitor-event/new-monitor-event.mjs
  pnpm-lock.yaml
Labels: refactor

#3918 eSignatures.io #3857
  components/esignatures_io/actions/create-contract/create-contract.mjs
  components/esignatures_io/esignatures_io.app.mjs
  components/esignatures_io/package.json
  pnpm-lock.yaml
Labels: action

#3948 Update dateTime format
  components/google_calendar/actions/create-event/create-event.mjs
Labels: triaged, User submitted

#3956 Fix elmah.io source
  components/elmah_io/package.json
  components/elmah_io/sources/new-error/new-error.mjs
Labels: triaged, User submitted

#3923 awork #3855
  components/awork/actions/create-client/create-client.mjs
  components/awork/actions/create-project/create-project.mjs
  components/awork/actions/find-users-by-email/find-users-by-email.mjs
  components/awork/awork.app.mjs
  components/awork/package.json
  components/awork/sources/common/common.mjs
  components/awork/sources/new-task/new-task.mjs
  components/awork/sources/new-time-entry/new-time-entry.mjs
  components/awork/sources/new-updated-time-entry/new-updated-time-entry.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#3962 Workast #3839
  components/workast/actions/common/constants.ts
  components/workast/actions/create-space/create-space.ts
  components/workast/actions/create-task/create-task.ts
  components/workast/app/workast.app.ts
  components/workast/package.json
  components/workast/sources/new-task/new-task.ts
  components/workast/tsconfig.json
  pnpm-lock.yaml
Labels: action, trigger / source

#3978 OneDrive - Get table from Excel spreadsheet
  components/microsoft_onedrive/actions/get-table/get-table.mjs
  components/microsoft_onedrive/package.json
  pnpm-lock.yaml
Labels: triaged, User submitted

#3913 Fix axios debug export printing
  platform/dist/axios.js
  platform/lib/axios.ts
  platform/package-lock.json
  platform/package.json
  pnpm-lock.yaml
Labels: bug, enhancement, triaged

#3987 WebinarGeek #3835
  components/webinargeek/package.json
  components/webinargeek/sources/new-payment/new-payment.mjs
  components/webinargeek/sources/new-registration/new-registration.mjs
  components/webinargeek/sources/new-replay-watched/new-replay-watched.mjs
  components/webinargeek/sources/new-unsubscribed/new-unsubscribed.mjs
  components/webinargeek/sources/new-webinar-watched/new-webinar-watched.mjs
  components/webinargeek/webinargeek.app.mjs
  pnpm-lock.yaml
Labels: trigger / source

#3994 Tolstoy #3814
  components/tolstoy/app/tolstoy.app.ts
  components/tolstoy/package.json
  components/tolstoy/sources/common/common.ts
  components/tolstoy/sources/new-lead/new-lead.ts
  components/tolstoy/sources/new-response/new-response.ts
  components/tolstoy/tsconfig.json
  pnpm-lock.yaml
Labels: trigger / source

#4001 [ACTION] Get Word Definition using Dictionary API
  components/dictionary_api/actions/get-word-definition/get-word-definition.mjs
  components/dictionary_api/dictionary_api.app.mjs
Labels: triaged, User submitted

#3945 3877 notion page property item
  components/notion/actions/retrieve-page-property-item/retrieve-page-property-item.mjs
  components/notion/notion.app.mjs
Labels: triaged, User submitted

#3919 noCRM.io #3865
  components/nocrm_io/actions/common/constants.mjs
  components/nocrm_io/actions/create-lead/create-lead.mjs
  components/nocrm_io/actions/get-lead/get-lead.mjs
  components/nocrm_io/actions/update-lead-status/update-lead-status.mjs
  components/nocrm_io/nocrm_io.app.mjs
  components/nocrm_io/package.json
  components/nocrm_io/sources/common/common.mjs
  components/nocrm_io/sources/new-lead-status-changed/new-lead-status-chnaged.mjs
  components/nocrm_io/sources/new-lead/new-lead.mjs
  components/nocrm_io/sources/new-prospect/new-prospect.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#4010 [JIRA] fix optional props for creating issues
  components/jira/actions/create-issue/create-issue.mjs
Labels: bug, triaged, User submitted

#4011 WOXO #3833
  components/woxo/package.json
  components/woxo/sources/new-video/new-video.mjs
  components/woxo/woxo.app.mjs
  pnpm-lock.yaml
Labels: trigger / source

#4018 Tick #3810
  components/tick/actions/create-client/create-client.mjs
  components/tick/actions/create-project/create-project.mjs
  components/tick/actions/create-task/create-task.mjs
  components/tick/actions/create-time-entry/create-time-entry.mjs
  components/tick/actions/create-user/create-user.mjs
  components/tick/package.json
  components/tick/sources/common/common.mjs
  components/tick/sources/new-client/new-client.mjs
  components/tick/sources/new-project/new-project.mjs
  components/tick/sources/new-task/new-task.mjs
  components/tick/sources/new-time-entry/new-time-entry.mjs
  components/tick/tick.app.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#4026 SurveyMethods #3798
  components/surveymethods/actions/add-contact-to-email-list/add-contact-to-email-list.mjs
  components/surveymethods/actions/common/constants.mjs
  components/surveymethods/actions/create-email-list/create-email-list.mjs
  components/surveymethods/package.json
  components/surveymethods/sources/new-response/new-response.mjs
  components/surveymethods/sources/new-survey-created/new-survey-created.mjs
  components/surveymethods/surveymethods.app.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#4046 add validate google recaptcha action
  components/google_recaptcha/actions/validate-recaptcha/validate-recaptcha.ts
  components/google_recaptcha/app/google_recaptcha.app.ts
  components/google_recaptcha/package.json
  components/google_recaptcha/tsconfig.json
  pnpm-lock.yaml
Labels: triaged, User submitted

#4041 Added a Jira action for adding multiple attachments to an issue
  components/jira/actions/add-attachment-to-issue/add-attachment-to-issue.mjs
  components/jira/actions/add-multiple-attachments-to-issue/add-multiple-attachments-to-issue.mjs
Labels: triaged, User submitted

#4062 update zerotier api
  components/zerotier/actions/authorize-network-member/authorize-network-member.mjs
  components/zerotier/actions/create-network/create-network.mjs
  components/zerotier/actions/delete-network-member/delete-network-member.mjs
  components/zerotier/actions/get-network-node/get-network-node.mjs
  components/zerotier/actions/get-network-nodes/get-network-nodes.mjs
  components/zerotier/actions/get-network/get-network.mjs
  components/zerotier/actions/get-networks/get-networks.mjs
  components/zerotier/actions/get-status/get-status.mjs
  components/zerotier/actions/get-user/get-user.mjs
  components/zerotier/actions/update-network-member/update-network-member.mjs
  components/zerotier/package.json
  components/zerotier/sources/new-node-join/new-node-join.mjs
  components/zerotier/sources/new-node-left/new-node-left.mjs
  components/zerotier/sources/new-node-offline/new-node-offline.mjs
  components/zerotier/sources/new-node-online/new-node-online.mjs
  components/zerotier/zerotier.app.mjs
Labels: triaged, User submitted

#4069 Uploadcare #3825
  components/uploadcare/actions/common/constants.mjs
  components/uploadcare/actions/upload-file/upload-file.mjs
  components/uploadcare/package.json
  components/uploadcare/sources/common/common.mjs
  components/uploadcare/sources/new-uploaded-file/new-uploaded-file.mjs
  components/uploadcare/uploadcare.app.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#3378 Ghost new actions
  components/ghost_org_admin_api/actions/create-member/create-member.mjs
  components/ghost_org_admin_api/actions/create-post/create-post.mjs
  components/ghost_org_admin_api/actions/update-member/update-member.mjs
  components/ghost_org_admin_api/common/constants.mjs
  components/ghost_org_admin_api/ghost_org_admin_api.app.mjs
  components/ghost_org_admin_api/package.json
  components/ghost_org_admin_api/sources/common-webhook.mjs
  components/ghost_org_admin_api/sources/member-created/member-created.mjs
  components/ghost_org_admin_api/sources/member-deleted/member-deleted.mjs
  components/ghost_org_admin_api/sources/member-updated/member-updated.mjs
  components/ghost_org_admin_api/sources/new-tag/new-tag.mjs
  components/ghost_org_admin_api/sources/page-published/page-published.mjs
  components/ghost_org_admin_api/sources/post-published/post-published.mjs
  components/ghost_org_content_api/actions/find-author/find-author.mjs
  components/ghost_org_content_api/common/constants.mjs
  components/ghost_org_content_api/common/utils.mjs
  components/ghost_org_content_api/ghost_org_content_api.app.js
  components/ghost_org_content_api/ghost_org_content_api.app.mjs
  components/ghost_org_content_api/package.json
  components/ghost_org_content_api/sources/common/timer-based.mjs
  components/ghost_org_content_api/sources/new-author/new-author.js
  components/ghost_org_content_api/sources/new-author/new-author.mjs
  components/triggercmd/triggercmd.app.mjs
  pnpm-lock.yaml
Labels: action

#4082 Include props for Emergency priority
  components/pushover/actions/emergency-push-notification/emergency-push-notification.mjs
  components/pushover/actions/push-notification/push-notification.mjs
  components/pushover/common/constants.mjs
  components/pushover/pushover.app.mjs
Labels: triaged

#4061 4035 update bitlink
  components/bitly/actions/update-bitlink/update-bitlink.mjs
  components/bitly/bitly.app.mjs
Labels: triaged, User submitted

#4063 Fix Google Calendar creation
  components/google_calendar/actions/create-event/create-event.mjs
Labels: triaged, User submitted

#4067 fix: Fix zoho server name by using properties
  components/zoho_mail/actions/create-task/create-task.mjs
  components/zoho_mail/actions/send-email/send-email.mjs
  components/zoho_mail/package.json
  components/zoho_mail/sources/new-email/new-email.mjs
  components/zoho_mail/zoho_mail.app.mjs
Labels: triaged, User submitted

#4058 TextIt #3807
  components/textit/actions/start-flow/start-flow.mjs
  components/textit/package.json
  components/textit/sources/new-flow-event/new-flow-event.mjs
  components/textit/textit.app.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#4071 Totango #3816
  components/totango/package.json
  components/totango/sources/common/common.mjs
  components/totango/sources/new-account/new-account.mjs
  components/totango/sources/new-user/new-user.mjs
  components/totango/totango.app.mjs
  pnpm-lock.yaml
Labels: trigger / source

#4088 Adding option and logic to optionally skip folder creation
  components/google_drive/actions/create-folder/create-folder.mjs
Labels: triaged, User submitted

#4097 Updated IP2WHOIS API.
  components/ip2whois/actions/query-domain-info/query-domain-info.mjs
  components/ip2whois/ip2whois.app.mjs
Labels: triaged, User submitted

#4108 Small updates to Slack components
  components/slack/actions/add-star/add-star.mjs
  components/slack/actions/archive-channel/archive-channel.mjs
  components/slack/actions/common/send-message.mjs
  components/slack/actions/complete-reminder/complete-reminder.mjs
  components/slack/actions/create-channel/create-channel.mjs
  components/slack/actions/create-reminder/create-reminder.mjs
  components/slack/actions/delete-file/delete-file.mjs
  components/slack/actions/delete-message/delete-message.mjs
  components/slack/actions/delete_reminder/delete-reminder.mjs
  components/slack/actions/find-message/find-message.mjs
  components/slack/actions/find-user-by-email/find-user-by-email.mjs
  components/slack/actions/get-channel/get-channel.mjs
  components/slack/actions/get-file/get-file.mjs
  components/slack/actions/get-reminder/get-reminder.mjs
  components/slack/actions/invite-user-to-channel/invite-user-to-channel.mjs
  components/slack/actions/join-channel/join-channel.mjs
  components/slack/actions/kick-user/kick-user.mjs
  components/slack/actions/leave-channel/leave-channel.mjs
  components/slack/actions/list-channels/list-channels.mjs
  components/slack/actions/list-files/list-files.mjs
  components/slack/actions/list-members-in-channel/list-members-in-channel.mjs
  components/slack/actions/list-reminders/list-reminders.mjs
  components/slack/actions/list-replies/list-replies.mjs
  components/slack/actions/list-users/list-users.mjs
  components/slack/actions/remove-star/remove-star.mjs
  components/slack/actions/reply-to-a-message-thread/reply-to-a-message-thread.mjs
  components/slack/actions/send-block-kit-message/send-block-kit-message.mjs
  components/slack/actions/send-custom-message/send-custom-message.mjs
  components/slack/actions/send-direct-message/send-direct-message.mjs
  components/slack/actions/send-group-message/send-group-message.mjs
  components/slack/actions/send-large-message/send-large-message.mjs
  components/slack/actions/send-message-private-channel/send-message-private-channel.mjs
  components/slack/actions/send-message-public-channel/send-message-public-channel.mjs
  components/slack/actions/set-channel-topic/set-channel-topic.mjs
  components/slack/actions/set-purpose-of-channel/set-purpose-of-channel.mjs
  components/slack/actions/unarchive-channel/unarchive-channel.mjs
  components/slack/actions/update-message/update-message.mjs
  components/slack/actions/update-profile/update-profile.mjs
  components/slack/actions/upload-file/upload-file.mjs
  components/slack/slack.app.mjs
  components/slack/sources/new-direct-message/new-direct-message.mjs
  components/slack/sources/new-mention/new-mention.mjs
  components/slack/sources/new-message-in-channels/new-message-in-channels.mjs
  components/slack/sources/new-reaction-added/new-reaction-added.mjs
  components/slack/sources/new-star-added/new-star-added.mjs
Labels: triaged

#4084 TimeCamp #3812
  components/timecamp/actions/common/constants.mjs
  components/timecamp/actions/create-task/create-task.mjs
  components/timecamp/actions/create-time-entry/create-time-entry.mjs
  components/timecamp/package.json
  components/timecamp/sources/new-task/new-task.mjs
  components/timecamp/sources/new-time-entry/new-time-entry.mjs
  components/timecamp/timecamp.app.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#4115 Fixed postgres event
  components/postgresql/actions/delete-rows/delete-rows.mjs
  components/postgresql/actions/execute-custom-query/execute-custom-query.mjs
  components/postgresql/actions/find-row-custom-query/find-row-custom-query.mjs
  components/postgresql/actions/find-row/find-row.mjs
  components/postgresql/actions/new-row/new-row.mjs
  components/postgresql/actions/update-row/update-row.mjs
  components/postgresql/postgresql.app.mjs
  components/postgresql/sources/common.mjs
  components/postgresql/sources/new-column/new-column.mjs
  components/postgresql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/postgresql/sources/new-row-custom-query/new-row-custom-query.mjs
  components/postgresql/sources/new-row/new-row.mjs
  components/postgresql/sources/new-table/new-table.mjs
Labels: triaged, refactor

#4132 [docs] Update README.md
  docs/docs/code/go/README.md
Labels: triaged, User submitted
