Repository PipedreamHQ/pipedream, pull requests merged in 2022-12, with the labels that each got.

#4821 Auto-generated documentation for apps
  components/getscreenshot/README.md
  components/ghost_org_admin_api/README.md
  components/ghost_org_content_api/README.md
  components/gift_up/README.md
  components/giphy/README.md
  components/gist/README.md
  components/gitea/README.md
  components/gitlab/README.md
  components/gitter/README.md
  components/givebutter/README.md
  components/gobio_link/README.md
  components/gocanvas/README.md
  components/godaddy/README.md
  components/godial/README.md
  components/gohighlevel/README.md
  components/goodreads/README.md
  components/google_ads/README.md
  components/google_analytics/README.md
  components/google_appsheet/README.md
  components/google_cloud_translate/README.md
  components/google_contacts/README.md
  components/google_dialogflow/README.md
  components/google_directory/README.md
  components/google_docs/README.md
  components/google_photos/README.md
  components/google_recaptcha/README.md
  components/google_search_console/README.md
  components/google_slides/README.md
  components/google_tasks/README.md
  components/google_workspace/README.md
  pnpm-lock.yaml
Labels: docs

#4840 Auto-generated documentation for apps
  components/gorgias/README.md
  components/gorgias_oauth/README.md
  components/gosquared/README.md
  components/graphhopper/README.md
  components/greenhouse/README.md
  components/grist/README.md
  components/growsurf/README.md
  components/gumroad/README.md
  components/guru/README.md
  components/habitica/README.md
  components/happyfox_chat/README.md
  components/harry_potter_api/README.md
  components/harvest/README.md
  components/headless_testing/README.md
  components/heap/README.md
  components/heartbeat/README.md
  components/helcim/README.md
  components/helium/README.md
  components/hellosign/README.md
  components/help_scout/README.md
  components/helper_functions/README.md
  components/helpwise/README.md
  components/here/README.md
  components/heroku/README.md
  components/heysummit/README.md
  components/highrise/README.md
  components/hiveage/README.md
  components/home_assistant/README.md
  components/honeybadger/README.md
  components/hotspotsystem/README.md
Labels: docs

#4865 [BUG] this.getFormattedBlocks is not a function (notion_append_block) #4854
  components/notion/actions/append-block/append-block.mjs
  components/notion/package.json
Labels: bug

#4866 [BUG] Hubspot - update sources to avoid missing events #4843
  components/hubspot/package.json
  components/hubspot/sources/common.mjs
  components/hubspot/sources/company-updated/company-updated.mjs
  components/hubspot/sources/contact-updated/contact-updated.mjs
  components/hubspot/sources/deal-updated/deal-updated.mjs
  components/hubspot/sources/delete-blog-article/delete-blog-article.mjs
  components/hubspot/sources/line-item-updated/line-item-updated.mjs
  components/hubspot/sources/new-blog-article/new-blog-article.mjs
  components/hubspot/sources/new-company/new-company.mjs
  components/hubspot/sources/new-contact-in-list/new-contact-in-list.mjs
  components/hubspot/sources/new-contact/new-contact.mjs
  components/hubspot/sources/new-deal-in-stage/new-deal-in-stage.mjs
  components/hubspot/sources/new-deal/new-deal.mjs
  components/hubspot/sources/new-email-event/new-email-event.mjs
  components/hubspot/sources/new-email-subscriptions-timeline/new-email-subscriptions-timeline.mjs
  components/hubspot/sources/new-engagement/new-engagement.mjs
  components/hubspot/sources/new-event/new-event.mjs
  components/hubspot/sources/new-form-submission/new-form-submission.mjs
  components/hubspot/sources/new-line-item/new-line-item.mjs
  components/hubspot/sources/new-or-updated-crm-object/new-or-updated-crm-object.mjs
  components/hubspot/sources/new-product/new-product.mjs
  components/hubspot/sources/new-social-media-message/new-social-media-message.mjs
  components/hubspot/sources/new-task/new-task.mjs
  components/hubspot/sources/new-ticket/new-ticket.mjs
  components/hubspot/sources/product-updated/product-updated.mjs
  components/hubspot/sources/updated-blog-article/updated-blog-article.mjs
Labels: bug

#4884 Hubspot new-form-submission source not emitting all events
  components/hubspot/package.json
  components/hubspot/sources/new-form-submission/new-form-submission.mjs
Labels: triaged

#4860 Auto-generated documentation for apps
  components/html_css_to_image/README.md
  components/humanitix/README.md
  components/hunter/README.md
  components/ibm_cloud_speech_to_text/README.md
  components/idealpostcodes/README.md
  components/idealspot/README.md
  components/ifttt/README.md
  components/imap/README.md
  components/imgbb/README.md
  components/imgur/README.md
  components/impression/README.md
  components/influxdb_cloud/README.md
  components/infobip/README.md
  components/infusionsoft/README.md
  components/inksprout/README.md
  components/insightly/README.md
  components/instabot_chatbot_platform/README.md
  components/instapaper/README.md
  components/intercom/README.md
  components/interseller/README.md
  components/intuiface/README.md
  components/invoice_ninja/README.md
  components/invoiced/README.md
  components/ip2location/README.md
  components/ip2proxy/README.md
  components/ip2whois/README.md
  components/ipdata_co/README.md
  components/iqair_airvisual/README.md
  components/isn/README.md
  components/itemize/README.md
  components/iterate/README.md
  components/jellyreach/README.md
Labels: docs

#4914 Auto-generated documentation for apps
  components/linear_app/README.md
  components/linkish/README.md
  components/linode/README.md
  components/linqs_cc/README.md
  components/listen_notes/README.md
  components/lob/README.md
  components/locate/README.md
  components/lodgify/README.md
  components/loggly_send_data/README.md
  components/logoraisr/README.md
  components/looker/README.md
  components/loomio/README.md
  components/loyaltylion/README.md
  components/lucid/README.md
  components/lusha/README.md
  components/magnetic/README.md
  components/mailbox_power/README.md
  components/mailboxvalidator/README.md
  components/mailerlite/README.md
  components/mailersend/README.md
  components/mailgun/README.md
  components/mailify/README.md
  components/mailjet/README.md
  components/mailmodo/README.md
  components/mailrefine/README.md
  components/mandrill/README.md
  components/manifestly_checklists/README.md
  components/mapbox/README.md
  components/marketing_master_io/README.md
  components/marketplacer/README.md
  components/markettime/README.md
  components/mattermost/README.md
  components/mautic/README.md
  components/mediatoolkit/README.md
  components/medium/README.md
  components/meetup/README.md
  components/megaventory/README.md
  components/meistertask/README.md
  components/memberstack/README.md
Labels: docs

#4893 Crove App - Updates generate pdf from template action to use new api
  components/crove_app/actions/complete-document/complete-document.mjs
  components/crove_app/actions/create-document/create-document.mjs
  components/crove_app/actions/create-invitation-link/create-invitation-link.mjs
  components/crove_app/actions/generate-pdf-from-document/generate-pdf-from-document.mjs
  components/crove_app/actions/generate-template-pdf/generate-template-pdf.mjs
  components/crove_app/actions/generate_template_pdf/generate_template_pdf.mjs
  components/crove_app/actions/get-document-details/get-document-details.mjs
  components/crove_app/actions/send-document/send-document.mjs
  components/crove_app/actions/submit-document/submit-document.mjs
  components/crove_app/actions/update-document-details/update-document-details.mjs
  components/crove_app/actions/update-document/update-document.mjs
  components/crove_app/crove_app.app.mjs
  components/crove_app/package.json
  components/crove_app/sources/document-completed/document-completed.mjs
  components/crove_app/sources/document-created/document-created.mjs
  components/crove_app/sources/document-submitted/document-submitted.mjs
Labels: triaged, User submitted

#4898 Updates to support new auth implementation for WhatsApp Business
  components/whatsapp_business/actions/list-message-templates/list-message-templates.mjs
  components/whatsapp_business/actions/send-text-message/send-text-message.mjs
  components/whatsapp_business/actions/send-text-using-template/send-text-using-template.mjs
  components/whatsapp_business/package.json
  components/whatsapp_business/whatsapp_business.app.mjs
Labels: triaged

#4935 Auto-generated documentation for apps
  components/membervault/README.md
  components/mercury/README.md
  components/message_bird/README.md
  components/mews/README.md
  components/microsoft_365/README.md
  components/microsoft_graph_api/README.md
  components/microsoft_onedrive/README.md
  components/microsoft_outlook/README.md
  components/microsoft_teams_admin/README.md
  components/middesk/README.md
  components/miestro/README.md
  components/mixmax/README.md
  components/mixpanel/README.md
  components/modern_treasury/README.md
  components/mojo_helpdesk/README.md
  components/monday/README.md
  components/moneybird/README.md
  components/monkeylearn/README.md
  components/moonclerk/README.md
  components/moosend/README.md
  components/moskit/README.md
  components/msg91/README.md
  components/murlist/README.md
  components/mux/README.md
  components/myphoner/README.md
  components/namely/README.md
  components/nectar_crm/README.md
  components/nethunt_crm/README.md
  components/neutrino/README.md
  components/neverbounce/README.md
  components/new_relic/README.md
  components/newsapi/README.md
  components/nextdns/README.md
Labels: docs

#4904 [ACTION] Discord Bot - Send Message #4868
  components/discord_bot/actions/create-user-dm/create-user-dm.mjs
  components/discord_bot/actions/send-message/send-message.mjs
  components/discord_bot/package.json
Labels: refactor

#4886 Auto-generated documentation for apps
  components/jobnimbus/README.md
  components/joomla/README.md
  components/junip/README.md
  components/kaggle/README.md
  components/kanban_tool/README.md
  components/kanbanflow/README.md
  components/kanbanize/README.md
  components/karbon/README.md
  components/keen/README.md
  components/klaviyo/README.md
  components/knack/README.md
  components/knowbe4/README.md
  components/kucoin_futures/README.md
  components/kvdb/README.md
  components/labs64_netlicensing/README.md
  components/lagrowthmachine/README.md
  components/laposta/README.md
  components/larger_io/README.md
  components/launch27/README.md
  components/launch_darkly_oauth/README.md
  components/launchdarkly/README.md
  components/lawmatics/README.md
  components/leadfeeder/README.md
  components/leadpops/README.md
  components/lemlist/README.md
  components/let_s_enhance/README.md
  components/lifx/README.md
  components/lighthouse/README.md
  components/lime_go/README.md
  components/line/README.md
  components/linear/README.md
Labels: docs

#4765 Direct7 SMS Integration request
  components/d7_networks/.gitignore
  components/d7_networks/actions/send-sms/send-sms.mjs
  components/d7_networks/app/d7_networks.app.ts
  components/d7_networks/common/constants.mjs
  components/d7_networks/d7_networks.app.mjs
  components/d7_networks/package.json
  pnpm-lock.yaml
Labels: triaged, User submitted

#4883 [FEATURE] Add list of authorized Jira cloud IDs as an async option for each Jira trigger / action #4858
  components/jira/actions/add-attachment-to-issue/add-attachment-to-issue.mjs
  components/jira/actions/add-comment-to-issue/add-comment-to-issue.mjs
  components/jira/actions/add-multiple-attachments-to-issue/add-multiple-attachments-to-issue.mjs
  components/jira/actions/add-watcher-to-issue/add-watcher-to-issue.mjs
  components/jira/actions/assign-issue/assign-issue.mjs
  components/jira/actions/create-issue/create-issue.mjs
  components/jira/actions/create-version/create-version.mjs
  components/jira/actions/delete-project/delete-project.mjs
  components/jira/actions/get-all-projects/get-all-projects.mjs
  components/jira/actions/get-issue/get-issue.mjs
  components/jira/actions/get-task/get-task.mjs
  components/jira/actions/get-transitions/get-transitions.mjs
  components/jira/actions/get-user/get-user.mjs
  components/jira/actions/list-issue-comments/list-issue-comments.mjs
  components/jira/actions/transition-issue/transition-issue.mjs
  components/jira/actions/update-comment/update-comment.mjs
  components/jira/actions/update-issue/update-issue.mjs
  components/jira/jira.app.mjs
  components/jira/package.json
  components/jira/sources/common/common.mjs
  components/jira/sources/events/events.mjs
  components/jira/sources/issue-created/issue-created.mjs
  components/jira/sources/issue-deleted/issue-deleted.mjs
  components/jira/sources/issue-updated/issue-updated.mjs
Labels: refactor

#4859 [TRIGGER] RingCentral New Message trigger - include message content #4847
  components/ringcentral/package.json
  components/ringcentral/sources/common/http-based.mjs
  components/ringcentral/sources/missed-inbound-call/missed-inbound-call.mjs
  components/ringcentral/sources/new-event/new-event.mjs
  components/ringcentral/sources/new-inbound-call/new-inbound-call.mjs
  components/ringcentral/sources/new-inbound-fax/new-inbound-fax.mjs
  components/ringcentral/sources/new-inbound-message/new-inbound-message.mjs
  components/ringcentral/sources/new-inbound-sms/new-inbound-sms.mjs
  components/ringcentral/sources/new-outbound-call/new-outbound-call.mjs
  components/ringcentral/sources/new-outbound-message/new-outbound-message.mjs
  components/ringcentral/sources/new-voicemail-message/new-voicemail-message.mjs
Labels: trigger / source

#4954 [ACTION] OpenAI #4926
  components/openai/actions/common/constants.mjs
  components/openai/actions/create-image/create-image.mjs
  components/openai/actions/send-prompt/send-prompt.mjs
  components/openai/openai.app.mjs
  components/openai/package.json
  pnpm-lock.yaml
Labels: action

#4971 GatherUp #3631
  components/gatherup/actions/create-customer/create-customer.mjs
  components/gatherup/gatherup.app.mjs
  components/gatherup/package.json
  components/gatherup/sources/common/common.mjs
  components/gatherup/sources/new-feedback-received/new-feedback-received.mjs
  components/gatherup/sources/new-negative-feedback-received/new-negative-feedback-received.mjs
  components/gatherup/sources/new-positive-feedback-received/new-positive-feedback-received.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#4940 [ACTION] Add inReplyTo & references to gmail-send-email
  components/gmail/actions/send-email/send-email.mjs
  components/gmail/gmail.app.mjs
  components/gmail/package.json
  components/gmail_custom_oauth/actions/send-email/send-email.mjs
  components/gmail_custom_oauth/package.json
Labels: triaged, User submitted

#4927 Fix adding labels to tasks in Todoist API migration
  components/todoist/actions/create-filter/create-filter.mjs
  components/todoist/actions/create-label/create-label.mjs
  components/todoist/actions/create-project-comment/create-project-comment.mjs
  components/todoist/actions/create-project/create-project.mjs
  components/todoist/actions/create-section/create-section.mjs
  components/todoist/actions/create-task-comment/create-task-comment.mjs
  components/todoist/actions/create-task/create-task.mjs
  components/todoist/actions/delete-comment/delete-comment.mjs
  components/todoist/actions/delete-filter/delete-filter.mjs
  components/todoist/actions/delete-label/delete-label.mjs
  components/todoist/actions/delete-project/delete-project.mjs
  components/todoist/actions/delete-section/delete-section.mjs
  components/todoist/actions/delete-task/delete-task.mjs
  components/todoist/actions/export-tasks/export-tasks.mjs
  components/todoist/actions/find-project/find-project.mjs
  components/todoist/actions/find-task/find-task.mjs
  components/todoist/actions/find-user/find-user.mjs
  components/todoist/actions/get-label/get-label.mjs
  components/todoist/actions/get-project-comment/get-project-comment.mjs
  components/todoist/actions/get-project/get-project.mjs
  components/todoist/actions/get-section/get-section.mjs
  components/todoist/actions/get-task-comment/get-task-comment.mjs
  components/todoist/actions/get-task/get-task.mjs
  components/todoist/actions/import-tasks/import-tasks.mjs
  components/todoist/actions/invite-user-to-project/invite-user-to-project.mjs
  components/todoist/actions/list-filters/list-filters.mjs
  components/todoist/actions/list-labels/list-labels.mjs
  components/todoist/actions/list-project-comments/list-project-comments.mjs
  components/todoist/actions/list-projects/list-projects.mjs
  components/todoist/actions/list-sections/list-sections.mjs
  components/todoist/actions/list-task-comments/list-task-comments.mjs
  components/todoist/actions/list-uncompleted-tasks/list-uncompleted-tasks.mjs
  components/todoist/actions/mark-task-completed/mark-task-completed.mjs
  components/todoist/actions/move-task-to-section/move-task-to-section.mjs
  components/todoist/actions/uncomplete-task/uncomplete-task.mjs
  components/todoist/actions/update-comment/update-comment.mjs
  components/todoist/actions/update-filter/update-filter.mjs
  components/todoist/actions/update-label/update-label.mjs
  components/todoist/actions/update-project/update-project.mjs
  components/todoist/actions/update-section/update-section.mjs
  components/todoist/actions/update-task/update-task.mjs
  components/todoist/package.json
  components/todoist/sources/completed-task/completed-task.mjs
  components/todoist/sources/incomplete-task/incomplete-task.mjs
  components/todoist/sources/new-or-modified-project/new-or-modified-project.mjs
  components/todoist/sources/new-or-modified-task/new-or-modified-task.mjs
  components/todoist/sources/new-project/new-project.mjs
  components/todoist/sources/new-section/new-section.mjs
  components/todoist/sources/new-task/new-task.mjs
  components/todoist/sources/sync-resources/sync-resources.mjs
  components/todoist/todoist.app.mjs
Labels: triaged, User submitted

#4988 [Gmail OAuth] Add update signature for org email
  components/gmail_custom_oauth/actions/add-label-to-email/add-label-to-email.mjs
  components/gmail_custom_oauth/actions/find-email/find-email.mjs
  components/gmail_custom_oauth/actions/send-email/send-email.mjs
  components/gmail_custom_oauth/actions/update-org-signature/update-org-signature.mjs
  components/gmail_custom_oauth/actions/update-primary-signature/update-primary-signature.mjs
  components/gmail_custom_oauth/actions/update-signature/update-signature.mjs
  components/gmail_custom_oauth/gmail_custom_oauth.app.mjs
  components/gmail_custom_oauth/package.json
  components/gmail_custom_oauth/sources/new-attachment-received/new-attachment-received.mjs
  components/gmail_custom_oauth/sources/new-email-received/new-email-received.mjs
  pnpm-lock.yaml
Labels: triaged

#4990 Fixing some old bugs to emit events
  components/airbrake/package.json
  components/airbrake/sources/new-error-occurred/new-error-occurred.mjs
  components/curated/package.json
  components/curated/sources/common/common.mjs
  components/curated/sources/new-email-subscribed/new-email-subscribed.mjs
  components/curated/sources/new-email-unsubscribed/new-email-unsubscribed.mjs
  components/curated/sources/new-issue-published/new-issue-published.mjs
  components/curated/sources/new-link-created/new-link-created.mjs
  components/gatherup/package.json
  components/gatherup/sources/common/common.mjs
  components/gatherup/sources/new-feedback-received/new-feedback-received.mjs
  components/gatherup/sources/new-negative-feedback-received/new-negative-feedback-received.mjs
  components/gatherup/sources/new-positive-feedback-received/new-positive-feedback-received.mjs
  components/gumroad/package.json
  components/gumroad/sources/common/common.mjs
  components/gumroad/sources/new-cancellation/new-cancellation.mjs
  components/gumroad/sources/new-product/new-product.mjs
  components/gumroad/sources/new-refund/new-refund.mjs
  components/gumroad/sources/new-sale/new-sale.mjs
  components/heysummit/package.json
  components/heysummit/sources/common/common.mjs
  components/heysummit/sources/new-attendee-registered/new-attendee-registered.mjs
  components/heysummit/sources/new-talk-attendee-registered/new-talk-attendee-registered.mjs
  components/iterate/package.json
  components/iterate/sources/common/common.mjs
  components/iterate/sources/new-question-answer-received/new-question-answer-received.mjs
  components/iterate/sources/new-survey-response-received/new-survey-response-received.mjs
Labels: refactor

#4989 Snappy #3787
  components/snappy/actions/create-wall-post/create-wall-post.mjs
  components/snappy/package.json
  components/snappy/snappy.app.mjs
  components/snappy/sources/common/common.mjs
  components/snappy/sources/new-ticket-assigned-to-me/new-ticket-assigned-to-me.mjs
  components/snappy/sources/new-ticket-created/new-ticket-created.mjs
  components/snappy/sources/new-waiting-ticket-created/new-waiting-ticket-created.mjs
  components/snappy/sources/new-wall-post-created/new-wall-post-created.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#5030 Bingx generic method update
  components/bingx/actions/generic-api-call/generic-api-call.mjs
  components/bingx/package.json
Labels: triaged, User submitted

#5029 [Drip] Fix label and value when using custom expression
  components/drip/actions/start-someone-on-workflow/start-someone-on-workflow.mjs
  components/drip/package.json
  components/drip/sources/new-subscriber-added/new-subscriber-added.mjs
Labels: triaged

#5042 Broken link fix on the documentation
  docs/docs/README.md
Labels: triaged, User submitted

#5037 [ACTION] Github - Create branch #4917
  components/github/actions/create-branch/create-branch.mjs
  components/github/actions/create-issue-comment/create-issue-comment.mjs
  components/github/actions/create-issue/create-issue.mjs
  components/github/actions/create-or-update-file-contents/create-or-update-file-contents.mjs
  components/github/actions/create-repository/create-repository.mjs
  components/github/actions/get-issue-assignees/get-issue-assignees.mjs
  components/github/actions/get-repository-content/get-repository-content.mjs
  components/github/actions/get-repository/get-repository.mjs
  components/github/actions/get-reviewers/get-reviewers.mjs
  components/github/actions/search-issues-and-pull-requests/search-issues-and-pull-requests.mjs
  components/github/actions/update-issue/update-issue.mjs
  components/github/github.app.mjs
  components/github/package.json
  components/github/sources/new-card-in-column/new-card-in-column.mjs
  components/github/sources/new-commit/new-commit.mjs
  components/github/sources/new-gist/new-gist.mjs
  components/github/sources/new-issue-with-status/new-issue-with-status.mjs
  components/github/sources/new-mention/new-mention.mjs
  components/github/sources/new-notification/new-notification.mjs
  components/github/sources/new-organization/new-organization.mjs
  components/github/sources/new-repository/new-repository.mjs
  components/github/sources/new-review-request/new-review-request.mjs
  components/github/sources/new-security-alert/new-security-alert.mjs
  components/github/sources/new-team/new-team.mjs
  components/github/sources/webhook-events/webhook-events.mjs
Labels: action

#5052 Laposta #3671
  components/laposta/.gitignore
  components/laposta/actions/create-relation/create-relation.mjs
  components/laposta/actions/delete-relation/delete-relation.mjs
  components/laposta/actions/update-relation/update-relation.mjs
  components/laposta/app/laposta.app.ts
  components/laposta/laposta.app.mjs
  components/laposta/package.json
  components/laposta/sources/common/common.mjs
  components/laposta/sources/new-relation-created/new-relation-created.mjs
  components/laposta/sources/new-relation-deleted/new-relation-deleted.mjs
  components/laposta/sources/new-relation-updated/new-relation-updated.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#5021 Auto-generated documentation for apps
  components/pipedrive/README.md
  components/pipefy/README.md
  components/pipeline/README.md
  components/pipeliner_crm/README.md
  components/pivotal_tracker/README.md
  components/pizzly/README.md
  components/placekey/README.md
  components/plaid/README.md
  components/planning_center/README.md
  components/planview_leankit/README.md
  components/planyo_online_booking/README.md
  components/plivo/README.md
  components/pocket/README.md
  components/podio/README.md
  components/podio_custom_app/README.md
  components/pointagram/README.md
  components/pointerpro/README.md
  components/pokeapi/README.md
  components/polly/README.md
  components/postmark/README.md
  components/practitest/README.md
  components/prerender/README.md
  components/pretix/README.md
  components/printavo/README.md
  components/printful/README.md
  components/printful_oauth/README.md
  components/process_street/README.md
  components/procore/README.md
  components/prodpad/README.md
  components/product_hunt/README.md
  components/productboard/README.md
  components/profitwell/README.md
  components/project_bubble/README.md
Labels: docs
