Repository PipedreamHQ/pipedream, pull requests merged in 2022-11, with the labels that each got.

#4627 [Gmail] Fix sending single emails
  components/gmail/actions/send-email/send-email.mjs
  components/gmail/package.json
  components/gmail_custom_oauth/actions/send-email/send-email.mjs
  components/gmail_custom_oauth/package.json
Labels: triaged

#4617 [ACTION] IPinfo.io #4607
  components/ipinfo_io/.gitignore
  components/ipinfo_io/actions/lookup-asn/lookup-asn.mjs
  components/ipinfo_io/actions/lookup-ip/lookup-ip.mjs
  components/ipinfo_io/app/ipinfo_io.app.ts
  components/ipinfo_io/ipinfo_io.app.mjs
  components/ipinfo_io/package.json
  pnpm-lock.yaml
Labels: action

#4620 [Action] Discourse #4590
  components/discourse/actions/create-post/create-post.mjs
  components/discourse/discourse.app.mjs
  components/discourse/package.json
  components/discourse/sources/new-posts-added/new-posts-added.mjs
  components/discourse/sources/new-topics-added/new-topics-added.mjs
  components/discourse/sources/new-users-added/new-users-added.mjs
Labels: action

#4624 Auto-generated documentation for apps
  components/breezy_hr/README.md
  components/brex/README.md
  components/brex_staging/README.md
  components/bridge/README.md
  components/brosix/README.md
  components/browserless/README.md
  components/browserstack/README.md
  components/bruzu/README.md
  components/bubble/README.md
  components/bugherd/README.md
  components/buildkite/README.md
  components/bunnycdn/README.md
  components/bybit/README.md
  components/cal_com/README.md
  components/calendarhero/README.md
  components/calendly_v2/README.md
  components/callingly/README.md
  components/canny/README.md
  components/canvas/README.md
  components/capsule/README.md
  components/captaindata/README.md
  components/cartes/README.md
  components/castingwords/README.md
  components/cdc_national_environmental_public_health_tracking/README.md
  components/celoxis/README.md
  components/channeladvisor/README.md
  components/chaport/README.md
  components/chargebee/README.md
  components/chargeover/README.md
  components/chargify/README.md
  components/chartmogul/README.md
Labels: docs

#4622 [ACTION] expofp #4596
  components/expofp/.gitignore
  components/expofp/actions/get-booth/get-booth.mjs
  components/expofp/actions/get-exhibitor/get-exhibitor.mjs
  components/expofp/actions/update-booth/update-booth.mjs
  components/expofp/actions/update-exhibitor/update-exhibitor.mjs
  components/expofp/app/expofp.app.ts
  components/expofp/expofp.app.mjs
  components/expofp/package.json
  pnpm-lock.yaml
Labels: action

#4609 Fix microsoft outlook 'end' field description
  components/microsoft_outlook/actions/create-calendar-event/create-calendar-event.mjs
  components/microsoft_outlook/actions/create-contact/create-contact.mjs
  components/microsoft_outlook/actions/create-draft-email/create-draft-email.mjs
  components/microsoft_outlook/actions/find-contacts/find-contacts.mjs
  components/microsoft_outlook/actions/list-contacts/list-contacts.mjs
  components/microsoft_outlook/actions/send-email/send-email.mjs
  components/microsoft_outlook/actions/update-contact/update-contact.mjs
  components/microsoft_outlook/microsoft_outlook.app.mjs
  components/microsoft_outlook/package.json
  components/microsoft_outlook/sources/new-calendar-event/new-calendar-event.mjs
  components/microsoft_outlook/sources/new-contact/new-contact.mjs
  components/microsoft_outlook/sources/new-email/new-email.mjs
  components/microsoft_outlook/sources/updated-calendar-event/updated-calendar-event.mjs
Labels: triaged, User submitted

#4660 [BUG] Jira Create Issue action should not mandate assignee be completed, or should allow for Automatic / Unassigned #4631
  components/jira/actions/create-issue/create-issue.mjs
  components/jira/package.json
Labels: bug

#4663 Auto-generated documentation for apps
  components/chatbot/README.md
  components/chatforma/README.md
  components/chatfuel_dashboard_api_/README.md
  components/chatra/README.md
  components/chatrace/README.md
  components/checkvist/README.md
  components/chucknorris/README.md
  components/cincopa/README.md
  components/circle/README.md
  components/circleci/README.md
  components/cisco_webex/README.md
  components/cisco_webex_custom_app/README.md
  components/clearbit/README.md
  components/clickmeeting/README.md
  components/clicksend/README.md
  components/cliengo/README.md
  components/clinchpad/README.md
  components/cliniko/README.md
  components/clio/README.md
  components/clockify/README.md
  components/close/README.md
  components/cloud_convert/README.md
  components/cloudbees/README.md
  components/cloudfill/README.md
  components/cloudflare_api_key/README.md
  components/cloudinary/README.md
  components/cloudlayer/README.md
  components/cloudmersive/README.md
  components/cloudtables/README.md
  components/cloudtalk/README.md
  components/cobalt/README.md
  components/coda/README.md
Labels: docs

#4635 Iterate #3663
  components/iterate/iterate.app.mjs
  components/iterate/package.json
  components/iterate/sources/common/common.mjs
  components/iterate/sources/new-question-answer/new-question-answer.mjs
  components/iterate/sources/new-survey-response/new-survey-response.mjs
  pnpm-lock.yaml
Labels: action, component ee

#4666 Fixing source keys and folders name
  components/iterate/package.json
  components/iterate/sources/new-question-answer-received/new-question-answer-received.mjs
  components/iterate/sources/new-survey-response-received/new-survey-response-received.mjs
Labels: refactor

#4632 Getresponse new actions and sources
  components/getresponse/actions/create-contact/create-contact.mjs
  components/getresponse/actions/create-newsletter/create-newsletter.mjs
  components/getresponse/actions/create-or-update-contact/create-or-update-contact.mjs
  components/getresponse/actions/find-campaign-list/find-campaign-list.mjs
  components/getresponse/actions/find-contact/find-contact.mjs
  components/getresponse/common/constants.mjs
  components/getresponse/common/utils.mjs
  components/getresponse/getresponse.app.mjs
  components/getresponse/package.json
  components/getresponse/sources/common.mjs
  components/getresponse/sources/new-contact/new-contact.mjs
  components/getresponse/sources/new-form/new-form.mjs
  components/getresponse/sources/new-landing-page/new-landing-page.mjs
  components/getresponse/sources/new-newsletter/new-newsletter.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#4667 [FEATURE] Possibility to filter results if google-drive-list_files action #4447
  components/google_drive/actions/list-files/list-files.mjs
  components/google_drive/package.json
Labels: refactor

#4658 [ACTION] Discourse: New Topic #4638
  components/discourse/actions/create-post/create-post.mjs
  components/discourse/actions/create-topic/create-topic.mjs
  components/discourse/discourse.app.mjs
  components/discourse/package.json
  components/discourse/sources/new-posts-added/new-posts-added.mjs
  components/discourse/sources/new-topics-added/new-topics-added.mjs
  components/discourse/sources/new-users-added/new-users-added.mjs
Labels: action

#4693 GH Action - check app prop
  .github/workflows/pull-request-checks.yaml
  package-lock.json
  package.json
  pnpm-lock.yaml
  scripts/checkComponentAppProp.js
  scripts/findBadKeys.js
  scripts/findDuplicateKeys.js
Labels: triaged

#4701 Adding Slack Interactivity support for the official Pipedream Slack Bot
  components/slack/package.json
  components/slack/sources/new-interaction-event-received/new-interaction-event-received.mjs
Labels: triaged

#4706 Airbrake #3546
  components/airbrake/airbrake.app.mjs
  components/airbrake/package.json
  components/airbrake/sources/new-error-occurred/new-error-occurred.mjs
  pnpm-lock.yaml
Labels: trigger / source

#4714 Workbooks CRM new Actions and Sources
  components/workbooks_crm/actions/create-customer-order/create-customer-order.mjs
  components/workbooks_crm/actions/create-organisation/create-organisation.mjs
  components/workbooks_crm/actions/create-person/create-person.mjs
  components/workbooks_crm/actions/find-or-create-order/find-or-create-order.mjs
  components/workbooks_crm/actions/update-person/update-person.mjs
  components/workbooks_crm/common/constants.mjs
  components/workbooks_crm/common/utils.mjs
  components/workbooks_crm/package.json
  components/workbooks_crm/sources/common-webhook.mjs
  components/workbooks_crm/sources/new-organisation/new-organisation.mjs
  components/workbooks_crm/sources/new-person/new-person.mjs
  components/workbooks_crm/sources/posted-credit-note/posted-credit-note.mjs
  components/workbooks_crm/sources/posted-invoice/posted-invoice.mjs
  components/workbooks_crm/workbooks_crm.app.mjs
  pnpm-lock.yaml
Labels: action, trigger / source, triaged

#4759 Refactored the rest of polling sources to redeploy
  components/ahrefs/actions/get-backlinks-one-per-domain/get-backlinks-one-per-domain.js
  components/ahrefs/actions/get-backlinks/get-backlinks.js
  components/ahrefs/actions/get-referring-domains/get-referring-domains.js
  components/ahrefs/package.json
  components/airbrake/package.json
  components/airbrake/sources/new-error-occurred/new-error-occurred.mjs
  components/confection/package.json
  components/confection/sources/common.mjs
  components/confection/sources/new-event/new-event.mjs
  components/confection/sources/new-field-value/new-field-value.mjs
  components/confection/sources/new-updated-leads/new-updated-leads.mjs
  components/gitlab/package.json
  components/gitlab/sources/new-audit-event/new-audit-event.mjs
  components/google_drive/package.json
  components/google_drive/sources/new-shared-drive/new-shared-drive.mjs
  components/heysummit/package.json
  components/heysummit/sources/common/common.mjs
  components/heysummit/sources/new-attendee-registered/new-attendee-registered.mjs
  components/heysummit/sources/new-talk-attendee-registered/new-talk-attendee-registered.mjs
  components/siteleaf/package.json
  components/siteleaf/sources/common/base.mjs
  components/siteleaf/sources/new-collection/new-collection.mjs
  components/siteleaf/sources/new-document/new-document.mjs
  components/siteleaf/sources/new-page/new-page.mjs
  components/siteleaf/sources/new-site/new-site.mjs
  components/transform/package.json
  components/transform/sources/form-response-submitted/form-response-submitted.mjs
  components/vision6/package.json
  components/vision6/sources/common/base.mjs
  components/vision6/sources/contact-activated/contact-activated.mjs
  components/vision6/sources/contact-deactivated/contact-deactivated.mjs
  components/vision6/sources/contact-subscribed/contact-subscribed.mjs
  components/vision6/sources/contact-unsubscribed/contact-unsubscribed.mjs
  components/vision6/sources/contact-updated/contact-updated.mjs
  components/vision6/sources/new-contact/new-contact.mjs
  pnpm-lock.yaml
Labels: refactor

#4772 Auto-generated documentation for apps
  components/erpnext/README.md
  components/escrow/README.md
  components/esignatures_io/README.md
  components/esputnik/README.md
  components/estreamdesk/README.md
  components/etermin/README.md
  components/ethereum/README.md
  components/evenium/README.md
  components/eventbrite/README.md
  components/eventzilla/README.md
  components/everhour/README.md
  components/eversign/README.md
  components/everwebinar/README.md
  components/exact/README.md
  components/expensify/README.md
  components/expofp/README.md
  components/f15five/README.md
  components/facturadirecta/README.md
  components/faros/README.md
  components/feathery/README.md
  components/fedex/README.md
  components/feedbin/README.md
  components/feedblitz/README.md
  components/feedier/README.md
  components/fibery/README.md
  components/figma/README.md
  components/files_com/README.md
  components/filter/README.md
  components/firmalyzer_iotvas/README.md
  components/fitbit/README.md
  components/flexie/README.md
Labels: docs

#4736 Auto-generated documentation for apps
  components/docusign/README.md
  components/docusign_developer/README.md
  components/donately/README.md
  components/doppler_marketing_automation/README.md
  components/dots_/README.md
  components/draftable/README.md
  components/dribbble/README.md
  components/drift/README.md
  components/drip/README.md
  components/dynamics_365_business_central_api/README.md
  components/dynatrace_api/README.md
  components/e_conomic/README.md
  components/e_goi/README.md
  components/easydns/README.md
  components/easyship/README.md
  components/ecwid/README.md
  components/edapp/README.md
  components/elmah_io/README.md
  components/elopage/README.md
  components/emailoctopus/README.md
  components/enedis/README.md
  components/engagebay/README.md
  components/enigma/README.md
  components/enormail/README.md
Labels: docs

#4717 Auto-generated documentation for apps
  components/darksky_api/README.md
  components/darwinbox/README.md
  components/data247/README.md
  components/data_stores/README.md
  components/databox/README.md
  components/datadog/README.md
  components/datanews/README.md
  components/datarobot/README.md
  components/datascope/README.md
  components/datawaves/README.md
  components/datumbox/README.md
  components/dear/README.md
  components/deepgram/README.md
  components/deepl/README.md
  components/degreed/README.md
  components/delay/README.md
  components/delighted/README.md
  components/demio/README.md
  components/deputy/README.md
  components/detrack/README.md
  components/dev_to/README.md
  components/dialmycalls/README.md
  components/dialpad/README.md
  components/dictionary_api/README.md
  components/digicert/README.md
  components/digital_ocean/README.md
  components/directus/README.md
  components/discourse/README.md
  components/dispatch/README.md
  components/docparser/README.md
  components/docupilot/README.md
Labels: docs

#4770 Notion duplicate-page action improvements
  components/notion/actions/append-block/append-block.mjs
  components/notion/actions/common/base-page-builder.mjs
  components/notion/actions/create-page-from-database/create-page-from-database.mjs
  components/notion/actions/create-page/create-page.mjs
  components/notion/actions/duplicate-page/duplicate-page.mjs
  components/notion/actions/update-page/update-page.mjs
  components/notion/package.json
Labels: triaged

#4727 Pipdreive fix polling sources
  components/pipedrive/actions/add-activity/add-activity.mjs
  components/pipedrive/actions/add-deal/add-deal.mjs
  components/pipedrive/actions/add-note/add-note.mjs
  components/pipedrive/actions/add-organization/add-organization.mjs
  components/pipedrive/actions/add-person/add-person.mjs
  components/pipedrive/actions/search-persons/search-persons.mjs
  components/pipedrive/actions/update-deal/update-deal.mjs
  components/pipedrive/common/constants.mjs
  components/pipedrive/common/utils.mjs
  components/pipedrive/package.json
  components/pipedrive/pipedrive.app.mjs
  components/pipedrive/sources/common/base.mjs
  components/pipedrive/sources/new-deal/new-deal.mjs
  components/pipedrive/sources/new-person/new-person.mjs
  components/pipedrive/sources/updated-deal/updated-deal.mjs
  components/pipedrive/sources/updated-person/updated-person.mjs
Labels: bug, trigger / source

#4797 Auto-generated documentation for apps
  components/followup/README.md
  components/fomo/README.md
  components/formcarry/README.md
  components/formspree/README.md
  components/formstack/README.md
  components/formtitan/README.md
  components/foursquare/README.md
  components/foxy/README.md
  components/frame/README.md
  components/frappe/README.md
  components/fraudlabs_pro/README.md
  components/freeagent/README.md
  components/freelancer/README.md
  components/freshbooks/README.md
  components/freshdesk/README.md
  components/freshping/README.md
  components/freshsales/README.md
  components/freshservice/README.md
  components/freshstatus/README.md
  components/frontapp/README.md
  components/full_contact/README.md
  components/fullstory/README.md
  components/gatherup/README.md
  components/gemini_public/README.md
  components/gender_api/README.md
  components/generated_photos/README.md
  components/geocodio/README.md
  components/getform/README.md
  components/getprospect/README.md
  components/getresponse/README.md
Labels: docs

#4753 Databox #3604
  components/databox/actions/send-custom-data/send-custom-data.mjs
  components/databox/databox.app.mjs
  components/databox/package.json
  pnpm-lock.yaml
Labels: action

#4792 Dribbble #3610
  components/dribbble/dribbble.app.mjs
  components/dribbble/package.json
  components/dribbble/sources/new-shot-created/new-shot-created.mjs
  pnpm-lock.yaml
Labels: trigger / source

#4755 Curated #3602
  components/curated/.gitignore
  components/curated/actions/create-link/create-link.mjs
  components/curated/app/curated.app.ts
  components/curated/curated.app.mjs
  components/curated/package.json
  components/curated/sources/common/common.mjs
  components/curated/sources/new-email-subscribed/new-email-subscribed.mjs
  components/curated/sources/new-email-unsubscribed/new-email-unsubscribed.mjs
  components/curated/sources/new-issue-published/new-issue-published.mjs
  components/curated/sources/new-link-created/new-link-created.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#4810 Ably #3532
  components/ably/ably.app.mjs
  components/ably/actions/publish-message/publish-message.mjs
  components/ably/actions/publish-push-notification/publish-push-notification.mjs
  components/ably/package.json
  package-lock.json
  pnpm-lock.yaml
Labels: action

#4853 Phrase #3724
  components/phrase/package.json
  components/phrase/phrase.app.mjs
  components/phrase/sources/common/common.mjs
  components/phrase/sources/new-job-completed/new-job-completed.mjs
  components/phrase/sources/new-job-created/new-job-created.mjs
  components/phrase/sources/new-job-started/new-job-started.mjs
  pnpm-lock.yaml
Labels: trigger / source
