Repository PipedreamHQ/pipedream, pull requests merged in 2022-02, with the labels that each got.

#2243 New converted legacy actions
  components/frontapp/actions/send-new-message/send-new-message.mjs
  components/imgbb/actions/upload-picture/upload-picture.mjs
  components/ipdata_co/actions/get-carrier/get-carrier.mjs
  components/ipdata_co/actions/get-ip-data/get-ip-data.mjs
  components/ipdata_co/actions/get-time-zone/get-time-zone.mjs
  components/kvdb/actions/get-key-value/get-key-value.mjs
  components/kvdb/actions/set-key-value/set-key-value.mjs
  components/mandrill/actions/send-email/send-email.mjs
  components/reddit/actions/search-reddit-comments/search-reddit-comments.mjs
  components/reddit/actions/search-reddit-posts/search-reddit-posts.mjs
  components/remove_bg/actions/remove-background/remove-background.mjs
  components/rockset/actions/add-documents/add-documents.mjs
  components/rockset/actions/create-api-key/create-api-key.mjs
  components/rockset/actions/create-integration/create-integration.mjs
  components/segment/actions/alias/alias.mjs
  components/segment/actions/group/group.mjs
  components/segment/actions/identify/identify.mjs
  components/segment/actions/page/page.mjs
  components/segment/actions/screen/screen.mjs
  components/segment/actions/track/track.mjs
  components/sendpulse/actions/retrieve-info-for-email-address/retrieve-info-for-email-address.mjs
  components/sendpulse/actions/unsubscribe-contact-from-mailing-list/unsubscribe-contact-from-mailing-list.mjs
Labels: enhancement

#1975 [SOURCE] Order Created
  components/dear/common/constants.mjs
  components/dear/dear.app.mjs
  components/dear/package-lock.json
  components/dear/package.json
  components/dear/sources/common.mjs
  components/dear/sources/new-authorized-sale-order/new-authorized-sale-order.mjs
Labels: help wanted, good first issue, trigger / source

#1964 Zendesk ticket events
  components/zendesk/constants.mjs
  components/zendesk/package-lock.json
  components/zendesk/package.json
  components/zendesk/sources/common/base.mjs
  components/zendesk/sources/common/ticket.mjs
  components/zendesk/sources/new-ticket/new-ticket.mjs
  components/zendesk/sources/ticket-closed/ticket-closed.mjs
  components/zendesk/sources/ticket-pended/ticket-pended.mjs
  components/zendesk/sources/ticket-solved/ticket-solved.mjs
  components/zendesk/zendesk.app.mjs
Labels: help wanted, trigger / source

#2270 Fix errors publishing converted s3 & gitlab action
  components/aws/actions/stream-file-to-s3/stream-file-to-s3.mjs
  components/gitlab/actions/list-project-issues/list-project-issues.mjs
Labels: bug

#2310 Fix reference errors with named exports in converted legacy actions
  components/asana/actions/search-user-projects/search-user-projects.mjs
  components/frontapp/actions/import-message/import-message.mjs
  components/frontapp/actions/update-conversation/update-conversation.mjs
  components/webflow/actions/get-collection-item/get-collection-item.mjs
  components/xero_accounting_api/actions/download-invoice/download-invoice.mjs
Labels: bug

#2316 Update end-workflow.mjs
  components/helper_functions/actions/email-me/email-me.mjs
  components/helper_functions/actions/end-workflow/end-workflow.mjs
Labels: User submitted

#2321 Fix Salesforce new-outbound-message source with batched notifications
  components/salesforce_rest_api/sources/new-outbound-message/new-outbound-message.mjs
Labels: User submitted
