Repository PipedreamHQ/pipedream, pull requests merged in 2022-04, with the labels that each got.

#2516 Added POST Formatted Transcript action
  components/symbl_ai/actions/constants.mjs
  components/symbl_ai/actions/post-formatted-transcript/post-formatted-transcript.mjs
  components/symbl_ai/symbl_ai.app.mjs
Labels: User submitted

#2495 Refactoring Symbl.ai reused props into prop definitions
  components/symbl_ai/actions/post-trackers-analytics-ui/post-trackers-analytics-ui.mjs
  components/symbl_ai/actions/post-video-summary-ui/post-video-summary-ui.mjs
  components/symbl_ai/symbl_ai.app.mjs
Labels: User submitted

#2593 Strava custom events bug
  components/strava/sources/custom-events/custom-events.mjs
Labels: bug

#2510 Added PUT Conversation metadata action
  components/symbl_ai/actions/put-conversation/put-conversation.mjs
  components/symbl_ai/symbl_ai.app.mjs
Labels: User submitted

#2234 [ACTIONS/SOURCES] Linear new sources and actions
  components/linear/actions/create-issue/create-issue.mjs
  components/linear/actions/get-teams/get-teams.mjs
  components/linear/actions/search-issues/search-issues.mjs
  components/linear/actions/update-issue/update-issue.mjs
  components/linear/common/utils.mjs
  components/linear/linear.app.mjs
  components/linear/package-lock.json
  components/linear/package.json
  components/linear/sources/issue-created-instant/issue-created-instant.mjs
  components/linear/sources/issue-updated-instant/issue-updated-instant.mjs
  components/linear_app/actions/create-issue/create-issue.mjs
  components/linear_app/actions/get-teams/get-teams.mjs
  components/linear_app/actions/issue-create/issue-create.mjs
  components/linear_app/actions/search-issues/search-issues.mjs
  components/linear_app/actions/update-issue/update-issue.mjs
  components/linear_app/common/constants.mjs
  components/linear_app/linear_app.app.mjs
  components/linear_app/package-lock.json
  components/linear_app/package.json
  components/linear_app/sources/common/webhook.mjs
  components/linear_app/sources/issue-created-instant/issue-created-instant.mjs
  components/linear_app/sources/issue-updated-instant/issue-updated-instant.mjs
Labels: help wanted, action, trigger / source

#2574 Update HTTP actions to use http_request prop
  components/helper_functions/actions/send-http-request/send-http-request.mjs
  components/http/actions/custom-request/custom-request.mjs
  components/http/actions/get-request/get-request.mjs
  components/http/actions/post-request/post-request.mjs
  components/http/actions/put-request/put-request.mjs
  components/http/http.app.mjs
Labels: enhancement

#2579 Update video url trackers property
  components/symbl_ai/actions/post-video-url/post-video-url.mjs
  components/symbl_ai/actions/utils.mjs
Labels: User submitted

#2523 [ACTIONS/SOURCE] new actions and source with webhook
  components/cisco_webex/actions/create-message/create-message.mjs
  components/cisco_webex/actions/create-room/create-room.mjs
  components/cisco_webex/actions/list-messages/list-messages.mjs
  components/cisco_webex/cisco_webex.app.mjs
  components/cisco_webex/common/constants.mjs
  components/cisco_webex/package-lock.json
  components/cisco_webex/package.json
  components/cisco_webex/sources/common/webhook.mjs
  components/cisco_webex/sources/new-message/new-message.mjs
Labels: action, trigger / source

#2614 More Stripe actions
  components/stripe/actions/retrieve-checkout-line-items/retrieve-checkout-line-items.js
  components/stripe/actions/retrieve-product/retrieve-product.js
Labels: User submitted

#2512 Added PUT Member action
  components/symbl_ai/actions/put-member/put-member.mjs
  components/symbl_ai/actions/put-speaker-events/put-speaker-events.mjs
  components/symbl_ai/actions/utils.mjs
  components/symbl_ai/symbl_ai.app.mjs
Labels: User submitted

#2644 Create Tally actions and sources, and updated some .js files to .mjs
  components/tally/actions/get-form-fields/get-form-fields.mjs
  components/tally/actions/get-forms/get-forms.mjs
  components/tally/actions/get-responses/get-responses.mjs
  components/tally/contants.mjs
  components/tally/package-lock.json
  components/tally/package.json
  components/tally/sources/common/common.mjs
  components/tally/sources/new-response/new-response.mjs
  components/tally/tally.app.mjs
  docs/docs/components/guidelines/README.md
Labels: action, trigger / source
