Repository PipedreamHQ/pipedream, pull requests merged in 2023-12, with the labels that each got.

#9085 New Components - printify
  components/printify/actions/create-product/create-product.mjs
  components/printify/actions/submit-order/submit-order.mjs
  components/printify/actions/update-product/update-product.mjs
  components/printify/common/constants.mjs
  components/printify/common/utils.mjs
  components/printify/package.json
  components/printify/printify.app.mjs
  components/printify/sources/watch-events-instant/watch-events-instant.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9145 New Components - postman
  components/postman/.gitignore
  components/postman/actions/create-environment/create-environment.mjs
  components/postman/actions/run-monitor/run-monitor.mjs
  components/postman/actions/update-variable/update-variable.mjs
  components/postman/app/postman.app.ts
  components/postman/package.json
  components/postman/postman.app.mjs
  components/postman/sources/monitor-run-completed/monitor-run-completed.mjs
  components/postman/sources/monitor-run-completed/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9156 New Components - shoprocket
  components/shoprocket/actions/create-customer/create-customer.mjs
  components/shoprocket/package.json
  components/shoprocket/shoprocket.app.mjs
  components/shoprocket/sources/common/base.mjs
  components/shoprocket/sources/new-customer-instant/new-customer-instant.mjs
  components/shoprocket/sources/new-order-instant/new-order-instant.mjs
  components/shoprocket/sources/new-product-instant/new-product-instant.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9204 New Components - browserhub
  components/browserhub/actions/run-automation/run-automation.mjs
  components/browserhub/browserhub.app.mjs
  components/browserhub/package.json
  components/browserhub/sources/new-finished-automation-run/new-finished-automation-run.mjs
  components/browserhub/sources/new-finished-automation-run/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9186 [Components] documint #9160
  components/documint/actions/create-document/create-document.mjs
  components/documint/actions/list-templates/list-templates.mjs
  components/documint/documint.app.mjs
  components/documint/package.json
  pnpm-lock.yaml
Labels: action

#9150 [Components] The Odds API #8049
  components/the_odds_api/.gitignore
  components/the_odds_api/actions/fetch-current-odds/fetch-current-odds.mjs
  components/the_odds_api/actions/get-upcoming-events/get-upcoming-events.mjs
  components/the_odds_api/app/the_odds_api.app.ts
  components/the_odds_api/common/constants.mjs
  components/the_odds_api/package.json
  components/the_odds_api/sources/new-odd-updated/new-odd-updated.mjs
  components/the_odds_api/sources/new-sport-event/new-sport-event.mjs
  components/the_odds_api/the_odds_api.app.mjs
  pnpm-lock.yaml
Labels: action

#9210 [Components] usersketch #9109
  components/usersketch/actions/common/constants.mjs
  components/usersketch/actions/create-event/create-event.mjs
  components/usersketch/actions/create-user/create-user.mjs
  components/usersketch/package.json
  components/usersketch/usersketch.app.mjs
  pnpm-lock.yaml
Labels: action

#9243 New Components - gravity_forms
  components/gravity_forms/.gitignore
  components/gravity_forms/actions/create-entry/create-entry.mjs
  components/gravity_forms/app/gravity_forms.app.ts
  components/gravity_forms/gravity_forms.app.mjs
  components/gravity_forms/package.json
  components/gravity_forms/sources/form-submitted/form-submitted.mjs
  components/gravity_forms/sources/form-submitted/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9211 New Components - postalytics
  components/postalytics/actions/common/base.mjs
  components/postalytics/actions/create-contact/create-contact.mjs
  components/postalytics/actions/list-contacts/list-contacts.mjs
  components/postalytics/actions/send-track-postcard-letter/send-track-postcard-letter.mjs
  components/postalytics/common/contants.mjs
  components/postalytics/package.json
  components/postalytics/postalytics.app.mjs
  components/postalytics/sources/new-campaign-event-instant/new-campaign-event-instant.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9290 docs: file stores typo
  docs/docs/projects/file-stores/reference/README.md
Labels: triaged, User submitted

#9293 docs: file stores typo
  docs/docs/projects/file-stores/README.md
Labels: triaged, User submitted

#9256 New Components - circle
  components/circle/.gitignore
  components/circle/actions/create-comment/create-comment.mjs
  components/circle/actions/create-post/create-post.mjs
  components/circle/app/circle.app.ts
  components/circle/circle.app.mjs
  components/circle/package.json
  components/circle/sources/common/base.mjs
  components/circle/sources/new-comment-posted/new-comment-posted.mjs
  components/circle/sources/new-comment-posted/test-event.mjs
  components/circle/sources/new-post/new-post.mjs
  components/circle/sources/new-post/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9249 HookDeck - New Trigger - New Event Received
  components/hookdeck/package.json
  components/hookdeck/sources/new-event-received/new-event-received.mjs
  pnpm-lock.yaml
Labels: triaged

#9268 Docs
  docs/docs/code/nodejs/using-data-stores/README.md
  docs/docs/destinations/emit/README.md
Labels: triaged, User submitted

#9281 [FIX] salesforce terminology misalignment replaced object to record
  components/salesforce_rest_api/package.json
  components/salesforce_rest_api/sources/new-record-instant/new-record-instant.mjs
  components/salesforce_rest_api/sources/new-record/new-record.mjs
  components/salesforce_rest_api/sources/record-deleted-instant/record-deleted-instant.mjs
  components/salesforce_rest_api/sources/record-deleted/record-deleted.mjs
  pnpm-lock.yaml
Labels: enhancement, trigger / source, triaged

#9282 New Components - polygonscan
  components/polygonscan/actions/get-account-balance/get-account-balance.mjs
  components/polygonscan/actions/query-contract-abi/query-contract-abi.mjs
  components/polygonscan/actions/retrieve-transaction-details/retrieve-transaction-details.mjs
  components/polygonscan/common/constants.mjs
  components/polygonscan/package.json
  components/polygonscan/polygonscan.app.mjs
  components/polygonscan/sources/transaction-posted/test-event.mjs
  components/polygonscan/sources/transaction-posted/transaction-posted.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9301 New Components - whop
  components/whop/actions/create-checkout-session/create-checkout-session.mjs
  components/whop/actions/create-promo-code/create-promo-code.mjs
  components/whop/actions/terminate-membership/terminate-membership.mjs
  components/whop/common/contants.mjs
  components/whop/common/utils.mjs
  components/whop/package.json
  components/whop/sources/common/base.mjs
  components/whop/sources/new-membership-validated-instant/new-membership-validated-instant.mjs
  components/whop/sources/new-membership-validated-instant/test-event.mjs
  components/whop/sources/new-payment-failed-instant/new-payment-failed-instant.mjs
  components/whop/sources/new-payment-failed-instant/test-event.mjs
  components/whop/sources/new-payment-succeeded-instant/new-payment-succeeded-instant.mjs
  components/whop/sources/new-payment-succeeded-instant/test-event.mjs
  components/whop/whop.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9292 New Components - zoho_forms
  components/zoho_forms/actions/get-form-fields/get-form-fields.mjs
  components/zoho_forms/actions/list-forms/list-forms.mjs
  components/zoho_forms/package.json
  components/zoho_forms/sources/new-response-received-instant/new-response-received-instant.mjs
  components/zoho_forms/sources/new-response-received-instant/test-event.mjs
  components/zoho_forms/zoho_forms.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9241 [Components] nimble #9161
  components/nimble/actions/create-contact/create-contact.mjs
  components/nimble/actions/create-task/create-task.mjs
  components/nimble/actions/update-contact/update-contact.mjs
  components/nimble/nimble.app.mjs
  components/nimble/package.json
  components/nimble/sources/new-contact-created/new-contact-created.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#9299 [ACTION] Eden AI - Generate audio from text #7993
  components/eden_ai/actions/analyze-sentiment-in-text/analyze-sentiment-in-text.mjs
  components/eden_ai/actions/common/constants.mjs
  components/eden_ai/actions/detect-ai-content/detect-ai-content.mjs
  components/eden_ai/actions/generate-audio-from-text/generate-audio-from-text.mjs
  components/eden_ai/actions/generate-image/generate-image.mjs
  components/eden_ai/actions/translate-document/translate-document.mjs
  components/eden_ai/eden_ai.app.mjs
  components/eden_ai/package.json
Labels: action

#9342 [Components] urlbae #9263
  components/urlbae/actions/common/constants.mjs
  components/urlbae/actions/create-qrcode/create-qrcode.mjs
  components/urlbae/actions/shorten-url/shorten-url.mjs
  components/urlbae/package.json
  components/urlbae/urlbae.app.mjs
  pnpm-lock.yaml
Labels: action

#8503 Google merchant center new components
  components/bolt_iot/bolt_iot.app.mjs
  components/bugbug/bugbug.app.mjs
  components/codacy/codacy.app.mjs
  components/code_climate/code_climate.app.mjs
  components/codemagic/codemagic.app.mjs
  components/codescene/codescene.app.mjs
  components/customgpt/customgpt.app.mjs
  components/cutt_ly/cutt_ly.app.mjs
  components/dingconnect/dingconnect.app.mjs
  components/espocrm/espocrm.app.mjs
  components/fireberry/fireberry.app.mjs
  components/google_merchant_center/actions/create-product/create-product.mjs
  components/google_merchant_center/actions/update-product/update-product.mjs
  components/google_merchant_center/common/constants.mjs
  components/google_merchant_center/google_merchant_center.app.mjs
  components/google_merchant_center/package.json
  components/google_merchant_center/sources/new-product-added/new-product-added.mjs
  components/heygen/heygen.app.mjs
  components/illumidesk/illumidesk.app.mjs
  components/inmobile/inmobile.app.mjs
  components/kizeo_forms/kizeo_forms.app.mjs
  components/l3mbda/l3mbda.app.mjs
  components/linkly/linkly.app.mjs
  components/livechat/livechat.app.mjs
  components/mezmo/mezmo.app.mjs
  components/microsoft_power_bi/microsoft_power_bi.app.mjs
  components/recruitis/recruitis.app.mjs
  components/resource_guru/resource_guru.app.mjs
  components/sonarcloud/sonarcloud.app.mjs
  components/stripe/package.json
  components/stripe/sources/abandoned-cart/abandoned-cart.mjs
  components/turbot_pipes/turbot_pipes.app.mjs
  components/veriphone/veriphone.app.mjs
  components/yoprint/yoprint.app.mjs
  components/zagomail/zagomail.app.mjs
  components/zenrows/zenrows.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9396 [Components] zenrows #9264
  components/zenrows/actions/get-api-usage/get-api-usage.mjs
  components/zenrows/actions/scrape-url-autoparse/scrape-url-autoparse.mjs
  components/zenrows/actions/scrape-url-css-selectors/scrape-url-css-selectors.mjs
  components/zenrows/package.json
  components/zenrows/zenrows.app.mjs
  pnpm-lock.yaml
Labels: action

#9436 New Components - nifty
  components/nifty/.gitignore
  components/nifty/actions/assign-task/assign-task.mjs
  components/nifty/actions/create-message/create-message.mjs
  components/nifty/actions/create-project/create-project.mjs
  components/nifty/app/nifty.app.ts
  components/nifty/common/constants.mjs
  components/nifty/common/utils.mjs
  components/nifty/nifty.app.mjs
  components/nifty/package.json
  components/nifty/sources/common/base.mjs
  components/nifty/sources/new-message-posted/new-message-posted.mjs
  components/nifty/sources/new-message-posted/test-event.mjs
  components/nifty/sources/new-task-created/new-task-created.mjs
  components/nifty/sources/new-task-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9358 New Components - fidel_api
  components/fidel_api/.gitignore
  components/fidel_api/actions/create-program/create-program.mjs
  components/fidel_api/actions/delete-card/delete-card.mjs
  components/fidel_api/actions/link-card/link-card.mjs
  components/fidel_api/app/fidel_api.app.ts
  components/fidel_api/common/constants.mjs
  components/fidel_api/common/utils.mjs
  components/fidel_api/fidel_api.app.mjs
  components/fidel_api/package.json
  components/fidel_api/sources/card-linked/card-linked.mjs
  components/fidel_api/sources/card-linked/test-event.mjs
  components/fidel_api/sources/common/base.mjs
  components/fidel_api/sources/transaction-completed-instant/test-event.mjs
  components/fidel_api/sources/transaction-completed-instant/transaction-completed-instant.mjs
  pnpm-lock.yaml
Labels: ai-assisted
