Repository PipedreamHQ/pipedream, pull requests merged in 2023-10, with the labels that each got.

#8258 [Components] Translate.com #8187
  components/translate_com/.gitignore
  components/translate_com/actions/translate-text/translate-text.mjs
  components/translate_com/app/translate_com.app.ts
  components/translate_com/package.json
  components/translate_com/translate_com.app.mjs
Labels: action

#8278 Slack block kit builder action
  components/slack/actions/common/build-blocks.mjs
  components/slack/actions/common/send-message.mjs
  components/slack/actions/reply-to-a-message/reply-to-a-message.mjs
  components/slack/actions/send-block-kit-message/send-block-kit-message.mjs
  components/slack/actions/send-custom-message/send-custom-message.mjs
  components/slack/actions/send-direct-message/send-direct-message.mjs
  components/slack/actions/send-group-message/send-group-message.mjs
  components/slack/actions/send-large-message/send-large-message.mjs
  components/slack/actions/send-message-private-channel/send-message-private-channel.mjs
  components/slack/actions/send-message-public-channel/send-message-public-channel.mjs
  components/slack/package.json
Labels: triaged

#8209 [Components] PhoneBurner #6777
  components/phoneburner/.gitignore
  components/phoneburner/actions/create-contact/create-contact.mjs
  components/phoneburner/actions/get-contact/get-contact.mjs
  components/phoneburner/actions/get-contacts/get-contacts.mjs
  components/phoneburner/actions/update-contact/update-contact.mjs
  components/phoneburner/app/phoneburner.app.ts
  components/phoneburner/package.json
  components/phoneburner/phoneburner.app.mjs
  pnpm-lock.yaml
Labels: action

#8285 [Components] Payhip #8182
  components/payhip/.gitignore
  components/payhip/actions/disable-license-key/disable-license-key.mjs
  components/payhip/actions/enable-license-key/enable-license-key.mjs
  components/payhip/actions/verify-license-key/verify-license-key.mjs
  components/payhip/app/payhip.app.ts
  components/payhip/package.json
  components/payhip/payhip.app.mjs
  pnpm-lock.yaml
Labels: action

#8366 Script adjustment to ignore test event files
  scripts/findBadKeys.js
Labels: triaged

#8249 #8090 - Ringover new action
  components/ringover/.gitignore
  components/ringover/actions/create-contact/create-contact.mjs
  components/ringover/app/ringover.app.ts
  components/ringover/package.json
  components/ringover/ringover.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#8380 [Components] TrackingTime #8276
  components/trackingtime/actions/start-tracking-time/start-tracking-time.mjs
  components/trackingtime/actions/stop-tracking-time/stop-tracking-time.mjs
  components/trackingtime/package.json
  components/trackingtime/trackingtime.app.mjs
  pnpm-lock.yaml
Labels: action

#8347 #8017 - Jira Service Desk new components
  components/jira_service_desk/.gitignore
  components/jira_service_desk/actions/create-comment-on-request/create-comment-on-request.mjs
  components/jira_service_desk/actions/create-request/create-request.mjs
  components/jira_service_desk/app/jira_service_desk.app.ts
  components/jira_service_desk/jira_service_desk.app.mjs
  components/jira_service_desk/package.json
  components/jira_service_desk/sources/common.mjs
  components/jira_service_desk/sources/new-request-created/new-request-created.mjs
  components/jira_service_desk/sources/new-request-created/test-event.mjs
  components/jira_service_desk/sources/request-status-updated/request-status-updated.mjs
  components/jira_service_desk/sources/request-status-updated/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#8426 #8319 - Docsbot AI
  components/docsbot_ai/actions/ask-question/ask-question.mjs
  components/docsbot_ai/actions/create-source/create-source.mjs
  components/docsbot_ai/actions/upload-source-file/upload-source-file.mjs
  components/docsbot_ai/docsbot_ai.app.mjs
  components/docsbot_ai/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#8387 #8318 - Aivoov new action
  components/aivoov/actions/convert-text-to-speech/convert-text-to-speech.mjs
  components/aivoov/aivoov.app.mjs
  components/aivoov/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#8413 [Components] Piggy #8188
  components/piggy/.gitignore
  components/piggy/actions/common/constants.mjs
  components/piggy/actions/create-contact-attribute/create-contact-attribute.mjs
  components/piggy/actions/find-or-create-contact/find-or-create-contact.mjs
  components/piggy/app/piggy.app.ts
  components/piggy/package.json
  components/piggy/piggy.app.mjs
  components/piggy/sources/new-contact-created/new-contact-created.mjs
  pnpm-lock.yaml
Labels: action

#8513 airtable_oauth: search-records.mjs bugfix field name with spaces
  components/airtable_oauth/actions/search-records/search-records.mjs
  components/airtable_oauth/package.json
Labels: triaged, User submitted

#8458 [Components] Airmeet #7862
  components/airmeet/.gitignore
  components/airmeet/actions/add-authorized-attendee/add-authorized-attendee.mjs
  components/airmeet/actions/common/constants.mjs
  components/airmeet/actions/create-airmeet/create-airmeet.mjs
  components/airmeet/airmeet.app.mjs
  components/airmeet/app/airmeet.app.ts
  components/airmeet/package.json
  pnpm-lock.yaml
Labels: action

#8467 [ACTION] Added Github Create Pull Request
  components/github/actions/create-branch/create-branch.mjs
  components/github/actions/create-issue-comment/create-issue-comment.mjs
  components/github/actions/create-issue/create-issue.mjs
  components/github/actions/create-or-update-file-contents/create-or-update-file-contents.mjs
  components/github/actions/create-pull-request/create-pull-request.mjs
  components/github/actions/create-repository/create-repository.mjs
  components/github/actions/get-issue-assignees/get-issue-assignees.mjs
  components/github/actions/get-repository-content/get-repository-content.mjs
  components/github/actions/get-repository/get-repository.mjs
  components/github/actions/get-reviewers/get-reviewers.mjs
  components/github/actions/search-issues-and-pull-requests/search-issues-and-pull-requests.mjs
  components/github/actions/update-issue/update-issue.mjs
  components/github/github.app.mjs
  components/github/package.json
  components/github/sources/new-card-in-column/new-card-in-column.mjs
  components/github/sources/new-commit/new-commit.mjs
  components/github/sources/new-discussion/new-discussion.mjs
  components/github/sources/new-gist/new-gist.mjs
  components/github/sources/new-issue-with-status/new-issue-with-status.mjs
  components/github/sources/new-mention/new-mention.mjs
  components/github/sources/new-notification/new-notification.mjs
  components/github/sources/new-organization/new-organization.mjs
  components/github/sources/new-repository/new-repository.mjs
  components/github/sources/new-review-request/new-review-request.mjs
  components/github/sources/new-security-alert/new-security-alert.mjs
  components/github/sources/new-team/new-team.mjs
  components/github/sources/webhook-events/webhook-events.mjs
Labels: triaged, User submitted

#8543 Formbricks new components
  components/formbricks/formbricks.app.mjs
  components/formbricks/package.json
  components/formbricks/sources/response-created/response-created.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#8509 [Components] AirOps #8178
  components/airops/.gitignore
  components/airops/actions/run-workflow/run-workflow.mjs
  components/airops/airops.app.mjs
  components/airops/app/airops.app.ts
  components/airops/package.json
  pnpm-lock.yaml
Labels: action

#8648 docs/Workflows/Triggers: Fix GitHub capitalization
  docs/docs/workflows/steps/triggers/README.md
Labels: triaged, User submitted

#8528 Productlane new components
  components/productlane/actions/create-contact/create-contact.mjs
  components/productlane/actions/create-feedback/create-feedback.mjs
  components/productlane/actions/upvote-project/upvote-project.mjs
  components/productlane/common/constants.mjs
  components/productlane/package.json
  components/productlane/productlane.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#8717 Docs - add Python pinning package versions
  docs/docs/code/python/README.md
Labels: docs
