Repository PipedreamHQ/pipedream, pull requests merged in 2023-11, with the labels that each got.

#8743 New Components - sonix
  components/sonix/actions/create-new-translation/create-new-translation.mjs
  components/sonix/actions/get-text-transcript/get-text-transcript.mjs
  components/sonix/actions/upload-media/upload-media.mjs
  components/sonix/common/constants.mjs
  components/sonix/common/utils.mjs
  components/sonix/package.json
  components/sonix/sonix.app.mjs
  components/sonix/sources/media-upload-complete/media-upload-complete.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#8764 Calendly deprecation
  components/calendly/README.md
  components/calendly/calendly.app.js
  components/calendly/package.json
  components/calendly/sources/common-polling.js
  components/calendly/sources/common-webhook.js
  components/calendly/sources/invitee-canceled/invitee-canceled.js
  components/calendly/sources/invitee-created/invitee-created.js
  components/calendly/sources/new-event-type/new-event-type.js
  components/calendly/sources/new-event/new-event.js
  components/calendly_v2/README.md
  pnpm-lock.yaml
Labels: triaged

#8799 Adding ServiceNow troubleshooting guidance
  components/servicenow/README.md
Labels: triaged, User submitted

#8763 New Components - Lightspeed VT
  components/lightspeed_vt/actions/create-new-user/create-new-user.mjs
  components/lightspeed_vt/common/constants.mjs
  components/lightspeed_vt/lightspeed_vt.app.mjs
  components/lightspeed_vt/package.json
  components/lightspeed_vt/sources/new-user-added/new-user-added.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#8629 [Components] lob #8614
  components/lob/actions/cancel-postcard/cancel-postcard.ts
  components/lob/actions/create-letter/create-letter.ts
  components/lob/actions/create-postcard/create-postcard.ts
  components/lob/actions/list-postcards/list-postcards.ts
  components/lob/actions/retrieve-postcard/retrieve-postcard.ts
  components/lob/app/common/constants.ts
  components/lob/app/lob.app.ts
  components/lob/package.json
  pnpm-lock.yaml
Labels: action, triaged

#8812 [Components] Kickbox #8710
  components/kickbox/actions/verify-email-batch/verify-email-batch.mjs
  components/kickbox/actions/verify-email/verify-email.mjs
  components/kickbox/kickbox.app.mjs
  components/kickbox/package.json
  pnpm-lock.yaml
Labels: action

#8752 [Components] Doppler #8656
  components/doppler_marketing_automation/.gitignore
  components/doppler_marketing_automation/actions/add-subscriber/add-subscriber.mjs
  components/doppler_marketing_automation/actions/get-subscriber/get-subscriber.mjs
  components/doppler_marketing_automation/actions/remove-subscriber/remove-subscriber.mjs
  components/doppler_marketing_automation/app/doppler_marketing_automation.app.ts
  components/doppler_marketing_automation/doppler_marketing_automation.app.mjs
  components/doppler_marketing_automation/package.json
  pnpm-lock.yaml
Labels: action

#8809 Meetingpulse new components
  components/meetingpulse/meetingpulse.app.mjs
  components/meetingpulse/package.json
  components/meetingpulse/sources/common.mjs
  components/meetingpulse/sources/new-contribution-to-topic/new-contribution-to-topic.mjs
  components/meetingpulse/sources/new-lead-generated/new-lead-generated.mjs
  components/meetingpulse/sources/new-poll-data/new-poll-data.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#8778 New Components - Satismeter
  components/satismeter/package.json
  components/satismeter/satismeter.app.mjs
  components/satismeter/sources/new-survey-response/new-survey-response.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#8863 Originality AI new components
  components/originality_ai/actions/detect-ai-content/detect-ai-content.mjs
  components/originality_ai/actions/detect-ai-from-url/detect-ai-from-url.mjs
  components/originality_ai/actions/scan-content-for-plagiarism-and-readability/scan-content-for-plagiarism-and-readability.mjs
  components/originality_ai/common/constants.mjs
  components/originality_ai/originality_ai.app.mjs
  components/originality_ai/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#8878 New Components - discogs
  components/discogs/actions/create-marketplace-listing/create-marketplace-listing.mjs
  components/discogs/actions/update-order/update-order.mjs
  components/discogs/common/constants.mjs
  components/discogs/common/utils.mjs
  components/discogs/discogs.app.mjs
  components/discogs/package.json
  components/discogs/sources/common/base.mjs
  components/discogs/sources/new-order-received/new-order-received.mjs
  components/discogs/sources/new-order-received/test-event.mjs
  components/discogs/sources/order-cancelled/order-cancelled.mjs
  components/discogs/sources/order-cancelled/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#8825 New Components - convenia
  components/convenia/actions/create-leave-of-absence-for-employee/create-leave-of-absence-for-employee.mjs
  components/convenia/convenia.app.mjs
  components/convenia/package.json
  components/convenia/sources/new-dismissal/new-dismissal.mjs
  components/convenia/sources/new-dismissal/test-event.mjs
  components/convenia/sources/new-vacation-request/new-vacation-request.mjs
  components/convenia/sources/new-vacation-request/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#8832 New Components - endorsal
  components/endorsal/actions/create-contact/create-contact.mjs
  components/endorsal/actions/create-testimonial/create-testimonial.mjs
  components/endorsal/actions/list-testimonials/list-testimonials.mjs
  components/endorsal/common/constants.mjs
  components/endorsal/common/utils.mjs
  components/endorsal/endorsal.app.mjs
  components/endorsal/package.json
  components/endorsal/sources/new-approved-testimonial/new-approved-testimonial.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#8785 New Components - Gladia
  components/gladia/actions/send-audio-for-transcription/send-audio-for-transcription.mjs
  components/gladia/common/constants.mjs
  components/gladia/common/utils.mjs
  components/gladia/gladia.app.mjs
  components/gladia/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#8884 [Components] UpLead #8784
  components/uplead/actions/get-company-by-domain/get-company-by-domain.mjs
  components/uplead/actions/get-contact-by-email/get-contact-by-email.mjs
  components/uplead/package.json
  components/uplead/uplead.app.mjs
  pnpm-lock.yaml
Labels: action

#8906 #8855 - OpenAI new components
  components/openai/actions/cancel-run/cancel-run.mjs
  components/openai/actions/chat/chat.mjs
  components/openai/actions/classify-items-into-categories/classify-items-into-categories.mjs
  components/openai/actions/common/common.mjs
  components/openai/actions/create-assistant/create-assistant.mjs
  components/openai/actions/create-embeddings/create-embeddings.mjs
  components/openai/actions/create-fine-tuning-job/create-fine-tuning-job.mjs
  components/openai/actions/create-image/create-image.mjs
  components/openai/actions/create-message/create-message.mjs
  components/openai/actions/create-run/create-run.mjs
  components/openai/actions/create-speech/create-speech.mjs
  components/openai/actions/create-thread-and-run/create-thread-and-run.mjs
  components/openai/actions/create-thread/create-thread.mjs
  components/openai/actions/create-transcription/create-transcription.mjs
  components/openai/actions/delete-file/delete-file.mjs
  components/openai/actions/list-files/list-files.mjs
  components/openai/actions/list-messages/list-messages.mjs
  components/openai/actions/list-run-steps/list-run-steps.mjs
  components/openai/actions/list-runs/list-runs.mjs
  components/openai/actions/modify-assistant/modify-assistant.mjs
  components/openai/actions/modify-message/modify-message.mjs
  components/openai/actions/modify-run/modify-run.mjs
  components/openai/actions/retrieve-file-content/retrieve-file-content.mjs
  components/openai/actions/retrieve-file/retrieve-file.mjs
  components/openai/actions/retrieve-run-step/retrieve-run-step.mjs
  components/openai/actions/retrieve-run/retrieve-run.mjs
  components/openai/actions/send-prompt/send-prompt.mjs
  components/openai/actions/submit-tool-outputs-to-run/submit-tool-outputs-to-run.mjs
  components/openai/actions/summarize/summarize.mjs
  components/openai/actions/translate-text/translate-text.mjs
  components/openai/actions/upload-file/upload-file.mjs
  components/openai/common/constants.mjs
  components/openai/openai.app.mjs
  components/openai/package.json
  components/openai/sources/common.mjs
  components/openai/sources/new-file-created/new-file-created.mjs
  components/openai/sources/new-fine-tuning-job-created/new-fine-tuning-job-created.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#8917 Adding filter to Notion "Updated Pages in Database" source
  components/notion/package.json
  components/notion/sources/updated-page/updated-page.mjs
Labels: triaged, User submitted

#8625 Cometly new component
  components/cometly/actions/send-event/send-event.mjs
  components/cometly/cometly.app.mjs
  components/cometly/common/constants.mjs
  components/cometly/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#8943 [Components] bouncer #8807
  components/bouncer/actions/verify-email-batch/verify-email-batch.mjs
  components/bouncer/actions/verify-email/verify-email.mjs
  components/bouncer/bouncer.app.mjs
  components/bouncer/package.json
  pnpm-lock.yaml
Labels: action

#8414 New Components - ilovepdf
  components/aftership/aftership.app.mjs
  components/alphamoon/alphamoon.app.mjs
  components/appdrag/appdrag.app.mjs
  components/blink/blink.app.mjs
  components/conversion_tools/conversion_tools.app.mjs
  components/document360/document360.app.mjs
  components/dynapictures/dynapictures.app.mjs
  components/ewebinar/ewebinar.app.mjs
  components/freshlearn/freshlearn.app.mjs
  components/helpcrunch/helpcrunch.app.mjs
  components/ilovepdf/.gitignore
  components/ilovepdf/actions/process-files/process-files.mjs
  components/ilovepdf/app/ilovepdf.app.ts
  components/ilovepdf/ilovepdf.app.mjs
  components/ilovepdf/package.json
  components/ilovepdf/sources/new-task-completed/new-task-completed.mjs
  components/jw_player/jw_player.app.mjs
  components/kaleido/kaleido.app.mjs
  components/koala_ai/koala_ai.app.mjs
  components/nexweave/nexweave.app.mjs
  components/orca_scan/orca_scan.app.mjs
  components/pingdom/pingdom.app.mjs
  components/postalytics/postalytics.app.mjs
  components/productive_io/productive_io.app.mjs
  components/rafflys/rafflys.app.mjs
  components/reapit_foundations/reapit_foundations.app.mjs
  components/scrapingant/scrapingant.app.mjs
  components/shipday/shipday.app.mjs
  components/sms_alert/sms_alert.app.mjs
  components/sparkpost/sparkpost.app.mjs
  components/truss/truss.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#8953 Nexweave new components
  components/nexweave/actions/common.mjs
  components/nexweave/actions/create-campaign-experience/create-campaign-experience.mjs
  components/nexweave/actions/create-image-experience-from-template/create-image-experience-from-template.mjs
  components/nexweave/actions/create-video-experience-from-template/create-video-experience-from-template.mjs
  components/nexweave/nexweave.app.mjs
  components/nexweave/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#8955 [ACTION] Clickup - Start a Time Entry #8516
  components/clickup/actions/create-chat-view-comment/create-chat-view-comment.mjs
  components/clickup/actions/create-checklist-item/create-checklist-item.mjs
  components/clickup/actions/create-checklist/create-checklist.mjs
  components/clickup/actions/create-folder/create-folder.mjs
  components/clickup/actions/create-list-comment/create-list-comment.mjs
  components/clickup/actions/create-list/create-list.mjs
  components/clickup/actions/create-space/create-space.mjs
  components/clickup/actions/create-task-comment/create-task-comment.mjs
  components/clickup/actions/create-task-from-template/create-task-from-template.mjs
  components/clickup/actions/create-task/create-task.mjs
  components/clickup/actions/create-view-comment/create-view-comment.mjs
  components/clickup/actions/delete-checklist-item/delete-checklist-item.mjs
  components/clickup/actions/delete-checklist/delete-checklist.mjs
  components/clickup/actions/delete-comment/delete-comment.mjs
  components/clickup/actions/delete-folder/delete-folder.mjs
  components/clickup/actions/delete-list/delete-list.mjs
  components/clickup/actions/delete-space/delete-space.mjs
  components/clickup/actions/delete-task/delete-task.mjs
  components/clickup/actions/get-custom-fields/get-custom-fields.mjs
  components/clickup/actions/get-folder-views/get-folder-views.mjs
  components/clickup/actions/get-folder/get-folder.mjs
  components/clickup/actions/get-folders/get-folders.mjs
  components/clickup/actions/get-list-comments/get-list-comments.mjs
  components/clickup/actions/get-list-views/get-list-views.mjs
  components/clickup/actions/get-list/get-list.mjs
  components/clickup/actions/get-lists/get-lists.mjs
  components/clickup/actions/get-space-views/get-space-views.mjs
  components/clickup/actions/get-space/get-space.mjs
  components/clickup/actions/get-spaces/get-spaces.mjs
  components/clickup/actions/get-task-comments/get-task-comments.mjs
  components/clickup/actions/get-task-templates/get-task-templates.mjs
  components/clickup/actions/get-task/get-task.mjs
  components/clickup/actions/get-tasks/get-tasks.mjs
  components/clickup/actions/get-team-views/get-team-views.mjs
  components/clickup/actions/get-view-comments/get-view-comments.mjs
  components/clickup/actions/get-view-tasks/get-view-tasks.mjs
  components/clickup/actions/get-view/get-view.mjs
  components/clickup/actions/remove-task-custom-field/remove-task-custom-field.mjs
  components/clickup/actions/start-time-entry/start-time-entry.mjs
  components/clickup/actions/stop-time-entry/stop-time-entry.mjs
  components/clickup/actions/update-checklist-item/update-checklist-item.mjs
  components/clickup/actions/update-checklist/update-checklist.mjs
  components/clickup/actions/update-comment/update-comment.mjs
  components/clickup/actions/update-folder/update-folder.mjs
  components/clickup/actions/update-list/update-list.mjs
  components/clickup/actions/update-space/update-space.mjs
  components/clickup/actions/update-task-custom-field/update-task-custom-field.mjs
  components/clickup/actions/update-task/update-task.mjs
  components/clickup/clickup.app.mjs
  components/clickup/package.json
  components/clickup/sources/new-folder/new-folder.mjs
  components/clickup/sources/new-list/new-list.mjs
  components/clickup/sources/new-task-advanced/new-task-advanced.mjs
  components/clickup/sources/new-task/new-task.mjs
  components/clickup/sources/updated-task/updated-task.mjs
Labels: action

#8901 New Components - diffchecker
  components/diffchecker/.gitignore
  components/diffchecker/actions/compare-image/compare-image.mjs
  components/diffchecker/actions/compare-pdf/compare-pdf.mjs
  components/diffchecker/actions/compare-text/compare-text.mjs
  components/diffchecker/app/diffchecker.app.ts
  components/diffchecker/common/utils.mjs
  components/diffchecker/diffchecker.app.mjs
  components/diffchecker/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#8976 New Components - orca_scan
  components/orca_scan/actions/add-update-row/add-update-row.mjs
  components/orca_scan/actions/find-row/find-row.mjs
  components/orca_scan/orca_scan.app.mjs
  components/orca_scan/package.json
  components/orca_scan/sources/common/base.mjs
  components/orca_scan/sources/new-row/new-row.mjs
  components/orca_scan/sources/new-row/test-event.mjs
  components/orca_scan/sources/new-sheet/new-sheet.mjs
  components/orca_scan/sources/new-sheet/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#8995 New Components - knorish
  components/knorish/.gitignore
  components/knorish/actions/add-user-in-course/add-user-in-course.mjs
  components/knorish/actions/create-user/create-user.mjs
  components/knorish/app/knorish.app.ts
  components/knorish/common/constants.mjs
  components/knorish/knorish.app.mjs
  components/knorish/package.json
  components/knorish/sources/bundle-purchased/bundle-purchased.mjs
  components/knorish/sources/bundle-purchased/test-event.mjs
  components/knorish/sources/common/base.mjs
  components/knorish/sources/new-signup/new-signup.mjs
  components/knorish/sources/new-signup/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#8998 Echtpost Postcards new components
  components/echtpost_postcards/actions/create-card/create-card.mjs
  components/echtpost_postcards/actions/create-contact/create-contact.mjs
  components/echtpost_postcards/app/echtpost_postcards.app.ts
  components/echtpost_postcards/echtpost_postcards.app.mjs
  components/echtpost_postcards/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#9002 New Components - aftership
  components/aftership/actions/create-tracking/create-tracking.mjs
  components/aftership/actions/get-tracking/get-tracking.mjs
  components/aftership/actions/update-tracking/update-tracking.mjs
  components/aftership/aftership.app.mjs
  components/aftership/common/constants.mjs
  components/aftership/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#8462 Update new-contact-property-change.mjs
  components/hubspot/package.json
  components/hubspot/sources/new-contact-property-change/new-contact-property-change.mjs
Labels: triaged, User submitted

#9049 New Components - neetoinvoice
  components/neetoinvoice/neetoinvoice.app.mjs
  components/neetoinvoice/package.json
  components/neetoinvoice/sources/common/base.mjs
  components/neetoinvoice/sources/new-client/new-client.mjs
  components/neetoinvoice/sources/new-client/test-event.mjs
  components/neetoinvoice/sources/new-invoice/new-invoice.mjs
  components/neetoinvoice/sources/new-invoice/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9042 New Components - callpage
  components/callpage/actions/create-sms/create-sms.mjs
  components/callpage/callpage.app.mjs
  components/callpage/common/constants.mjs
  components/callpage/package.json
  components/callpage/sources/new-call-event/new-call-event.mjs
  components/callpage/sources/new-call-event/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9000 SMS Alert premium actions
  components/hubspot/package.json
  components/hubspot/sources/new-contact-property-change/new-contact-property-change.mjs
  components/sms_alert/actions/create-contact/create-contact.mjs
  components/sms_alert/actions/schedule-sms/schedule-sms.mjs
  components/sms_alert/actions/send-sms/send-sms.mjs
  components/sms_alert/package.json
  components/sms_alert/sms_alert.app.mjs
Labels: ai-assisted

#9083 #8771 Document360 new components
  components/document360/actions/create-document/create-document.mjs
  components/document360/document360.app.mjs
  components/document360/package.json
  components/document360/sources/new-article-in-project-version/new-article-in-project-version.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9090 Fix obviously broken Instapaper integration
  components/instapaper/actions/add-url/add-url.mjs
  components/instapaper/package.json
  pnpm-lock.yaml
Labels: triaged, User submitted

#9047 Fix examples in Python docs
  docs/docs/code/python/README.md
Labels: docs

#8987 [Components] basecamp #8696
  components/basecamp/actions/create-campfire-message/create-campfire-message.mjs
  components/basecamp/actions/create-card/create-card.mjs
  components/basecamp/actions/create-comment/create-comment.mjs
  components/basecamp/actions/create-message/create-message.mjs
  components/basecamp/actions/create-todo-item/create-todo-item.mjs
  components/basecamp/basecamp.app.mjs
  components/basecamp/package.json
  components/basecamp/sources/new-comment-created/new-comment-created.mjs
  components/basecamp/sources/new-event-by-webhook-type/new-event-by-webhook-type.mjs
  components/basecamp/sources/new-message-created/new-message-created.mjs
  components/basecamp/sources/new-to-do-item-created/new-to-do-item-created.mjs
  components/basecamp/sources/new-to-do-item-status/new-to-do-item-status.mjs
  components/basecamp/sources/new-to-do-list-created/new-to-do-list-created.mjs
Labels: action

#9101 New Components - manychat
  components/manychat/actions/add-tag-user/add-tag-user.mjs
  components/manychat/actions/find-user-custom-field/find-user-custom-field.mjs
  components/manychat/actions/send-dynamic-message-user/send-dynamic-message-user.mjs
  components/manychat/common/utils.mjs
  components/manychat/manychat.app.mjs
  components/manychat/package.json
  components/manychat/sources/new-or-updated-custom-field/new-or-updated-custom-field.mjs
  components/manychat/sources/new-or-updated-custom-field/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9098 [Components] Blink #8768
  components/blink/actions/get-feed-event/get-feed-event.mjs
  components/blink/actions/post-feed/post-feed.mjs
  components/blink/blink.app.mjs
  components/blink/package.json
  pnpm-lock.yaml
Labels: action

#8890 New Components - brilliant-directories
  components/brilliant_directories/actions/create-post/create-post.mjs
  components/brilliant_directories/actions/create-user/create-user.mjs
  components/brilliant_directories/actions/update-post/update-post.mjs
  components/brilliant_directories/brilliant_directories.app.mjs
  components/brilliant_directories/common/utils.mjs
  components/brilliant_directories/package.json
  pnpm-lock.yaml
Labels: ai-assisted
