Repository PipedreamHQ/pipedream, pull requests merged in 2023-05, with the labels that each got.

#6213 Removing Calendar API related source and references from Hubspot component
  components/hubspot/actions/add-contact-to-list/add-contact-to-list.mjs
  components/hubspot/actions/batch-create-or-update-contact/batch-create-or-update-contact.mjs
  components/hubspot/actions/create-associations/create-associations.mjs
  components/hubspot/actions/create-company/create-company.mjs
  components/hubspot/actions/create-contact/create-contact.mjs
  components/hubspot/actions/create-deal/create-deal.mjs
  components/hubspot/actions/create-engagement/create-engagement.mjs
  components/hubspot/actions/create-or-update-contact/create-or-update-contact.mjs
  components/hubspot/actions/enroll-contact-into-workflow/enroll-contact-into-workflow.mjs
  components/hubspot/actions/get-company/get-company.mjs
  components/hubspot/actions/get-contact/get-contact.mjs
  components/hubspot/actions/get-deal/get-deal.mjs
  components/hubspot/actions/get-file-public-url/get-file-public-url.mjs
  components/hubspot/actions/search-crm/search-crm.mjs
  components/hubspot/actions/update-company/update-company.mjs
  components/hubspot/actions/update-contact/update-contact.mjs
  components/hubspot/common/constants.mjs
  components/hubspot/hubspot.app.mjs
  components/hubspot/package.json
  components/hubspot/sources/company-updated/company-updated.mjs
  components/hubspot/sources/contact-updated/contact-updated.mjs
  components/hubspot/sources/delete-blog-article/delete-blog-article.mjs
  components/hubspot/sources/line-item-updated/line-item-updated.mjs
  components/hubspot/sources/new-blog-article/new-blog-article.mjs
  components/hubspot/sources/new-company-property-change/new-company-property-change.mjs
  components/hubspot/sources/new-company/new-company.mjs
  components/hubspot/sources/new-contact-in-list/new-contact-in-list.mjs
  components/hubspot/sources/new-contact-property-change/new-contact-property-change.mjs
  components/hubspot/sources/new-contact/new-contact.mjs
  components/hubspot/sources/new-deal-in-stage/new-deal-in-stage.mjs
  components/hubspot/sources/new-deal-property-change/new-deal-property-change.mjs
  components/hubspot/sources/new-deal-updated/new-deal-updated.mjs
  components/hubspot/sources/new-deal/new-deal.mjs
  components/hubspot/sources/new-email-event/new-email-event.mjs
  components/hubspot/sources/new-email-subscriptions-timeline/new-email-subscriptions-timeline.mjs
  components/hubspot/sources/new-engagement/new-engagement.mjs
  components/hubspot/sources/new-event/new-event.mjs
  components/hubspot/sources/new-form-submission/new-form-submission.mjs
  components/hubspot/sources/new-line-item/new-line-item.mjs
  components/hubspot/sources/new-or-updated-crm-object/new-or-updated-crm-object.mjs
  components/hubspot/sources/new-product/new-product.mjs
  components/hubspot/sources/new-social-media-message/new-social-media-message.mjs
  components/hubspot/sources/new-task/new-task.mjs
  components/hubspot/sources/new-ticket-property-change/new-ticket-property-change.mjs
  components/hubspot/sources/new-ticket/new-ticket.mjs
  components/hubspot/sources/product-updated/product-updated.mjs
  components/hubspot/sources/updated-blog-article/updated-blog-article.mjs
  pnpm-lock.yaml
Labels: triaged

#6188 [FEATURE] Slack - New Reaction Added (Instant): include item_user and user data #6173
  components/slack/package.json
  components/slack/sources/new-reaction-added/new-reaction-added.mjs
Labels: enhancement

#5673 Fix sendgrid ASM config
  components/sendgrid/actions/add-email-to-global-suppression/add-email-to-global-suppression.mjs
  components/sendgrid/actions/add-or-update-contact/add-or-update-contact.mjs
  components/sendgrid/actions/common/common.mjs
  components/sendgrid/actions/create-contact-list/create-contact-list.mjs
  components/sendgrid/actions/delete-blocks/delete-blocks.mjs
  components/sendgrid/actions/delete-bounces/delete-bounces.mjs
  components/sendgrid/actions/delete-contacts/delete-contacts.mjs
  components/sendgrid/actions/delete-global-suppression/delete-global-suppression.mjs
  components/sendgrid/actions/delete-list/delete-list.mjs
  components/sendgrid/actions/get-a-block/get-a-block.mjs
  components/sendgrid/actions/get-a-global-suppression/get-a-global-suppression.mjs
  components/sendgrid/actions/get-all-bounces/get-all-bounces.mjs
  components/sendgrid/actions/get-contact-lists/get-contact-lists.mjs
  components/sendgrid/actions/list-blocks/list-blocks.mjs
  components/sendgrid/actions/list-global-suppressions/list-global-suppressions.mjs
  components/sendgrid/actions/remove-contact-from-list/remove-contact-from-list.mjs
  components/sendgrid/actions/search-contacts/search-contacts.mjs
  components/sendgrid/actions/send-email-multiple-recipients/send-email-multiple-recipients.mjs
  components/sendgrid/actions/send-email-single-recipient/send-email-single-recipient.mjs
  components/sendgrid/actions/validate-email/validate-email.mjs
  components/sendgrid/package.json
  components/sendgrid/sendgrid.app.mjs
  components/sendgrid/sources/events/events.mjs
  components/sendgrid/sources/new-contact/new-contact.mjs
Labels: triaged, User submitted

#6239 [Nordigen] Can now select multiple scopes
  components/nordigen/actions/create-requisition-link/create-requisition-link.mjs
  components/nordigen/actions/delete-requisition-link/delete-requisition-link.mjs
  components/nordigen/actions/get-account-balances/get-account-balances.mjs
  components/nordigen/actions/get-account-details/get-account-details.mjs
  components/nordigen/actions/get-account-metadata/get-account-metadata.mjs
  components/nordigen/actions/get-account-transactions/get-account-transactions.mjs
  components/nordigen/nordigen.app.mjs
  components/nordigen/package.json
  components/nordigen/sources/new-transaction/new-transaction.mjs
Labels: triaged, User submitted

#6233 [ACTION] Helper Function: Random Item: return multiple
  components/helper_functions/actions/random-item-from-list/random-item-from-list.mjs
  components/helper_functions/package.json
Labels: triaged, User submitted

#6219 [Sources] Dear Systems
  components/dear/package.json
  components/dear/sources/available-stock-level-change/available-stock-level-change.mjs
  components/dear/sources/customer-updated/customer-updated.mjs
  components/dear/sources/sale-shipment-tracking-number-change/sale-shipment-tracking-number-change.mjs
  components/dear/sources/supplier-updated/supplier-updated.mjs
Labels: triaged

#6230 [Action] Modifying Calendly Get Event to accept event URL instead of UUID
  components/calendly_v2/README.md
  components/calendly_v2/actions/create-scheduling-link/create-scheduling-link.mjs
  components/calendly_v2/actions/get-event/get-event.mjs
  components/calendly_v2/actions/list-event-invitees/list-event-invitees.mjs
  components/calendly_v2/actions/list-events/list-events.mjs
  components/calendly_v2/actions/list-webhook-subscriptions/list-webhook-subscriptions.mjs
  components/calendly_v2/calendly_v2.app.mjs
  components/calendly_v2/package.json
  components/calendly_v2/sources/invitee-action/invitee-action.mjs
  pnpm-lock.yaml
Labels: triaged

#6207 [TRIGGER] ZeroTier Online/Offline Node no longer works due to API change #6193
  components/zerotier/package.json
  components/zerotier/sources/common/common.mjs
  components/zerotier/sources/new-node-join/new-node-join.mjs
  components/zerotier/sources/new-node-left/new-node-left.mjs
  components/zerotier/sources/new-node-offline/new-node-offline.mjs
  components/zerotier/sources/new-node-online/new-node-online.mjs
  pnpm-lock.yaml
Labels: enhancement

#6164 [ACTION] Dropbox - Download File to tmp dir #5990
  components/dropbox/actions/download-file-to-tmp/download-file-to-tmp.mjs
  components/dropbox/package.json
  pnpm-lock.yaml
Labels: action

#6298 [Nordigen][Source] Update props
  components/nordigen/package.json
  components/nordigen/sources/new-transaction/new-transaction.mjs
Labels: triaged, User submitted

#6386 [Postgres] Republish components
  components/postgresql/actions/delete-rows/delete-rows.mjs
  components/postgresql/actions/execute-custom-query/execute-custom-query.mjs
  components/postgresql/actions/find-row-custom-query/find-row-custom-query.mjs
  components/postgresql/actions/find-row/find-row.mjs
  components/postgresql/actions/insert-row/insert-row.mjs
  components/postgresql/actions/update-row/update-row.mjs
  components/postgresql/package.json
  components/postgresql/postgresql.app.mjs
  components/postgresql/sources/new-column/new-column.mjs
  components/postgresql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/postgresql/sources/new-row-custom-query/new-row-custom-query.mjs
  components/postgresql/sources/new-row/new-row.mjs
  components/postgresql/sources/new-table/new-table.mjs
  pnpm-lock.yaml
Labels: triaged

#6422 [BugFix] Zoom Admin - List Webinar Participants
  components/zoom_admin/actions/list-webinar-participants/list-webinar-participants.mjs
  components/zoom_admin/package.json
  pnpm-lock.yaml
Labels: triaged

#6403 Converting string props takerProfitPrice and stopLossPrice to float
  components/bingx/actions/trade-new-order/trade-new-order.mjs
  components/bingx/package.json
Labels: enhancement, triaged

#6410 [Sources] Fix Snowflake Failed Task
  components/snowflake/actions/insert-multiple-rows/insert-multiple-rows.mjs
  components/snowflake/actions/insert-row/insert-row.mjs
  components/snowflake/package.json
  components/snowflake/snowflake.app.mjs
  components/snowflake/sources/change-to-warehouse/change-to-warehouse.mjs
  components/snowflake/sources/common.mjs
  components/snowflake/sources/failed-task-in-schema/failed-task-in-schema.mjs
  components/snowflake/sources/new-database/new-database.mjs
  components/snowflake/sources/new-role/new-role.mjs
  components/snowflake/sources/new-row/new-row.mjs
  components/snowflake/sources/new-schema/new-schema.mjs
  components/snowflake/sources/new-table/new-table.mjs
  components/snowflake/sources/new-user/new-user.mjs
  components/snowflake/sources/query-results/query-results.mjs
Labels: triaged

#6349 [BUG] Convert HTML to Markdown Unexpected token '||=' #6220
  components/formatting/actions/convert-html-to-markdown/convert-html-to-markdown.ts
  components/formatting/actions/convert-markdown-to-html/convert-markdown-to-html.ts
  components/formatting/package.json
  components/formatting/tsconfig.json
  pnpm-lock.yaml
Labels: bug

#6366 Readwise: Support List Document
  components/readwise/actions/get-highlight-details/get-highlight-details.mjs
  components/readwise/actions/list-highlights/list-highlights.mjs
  components/readwise/package.json
  components/readwise/readwise.app.mjs
  components/readwise/sources/new-documents/new-documents.mjs
  components/readwise/sources/new-highlights/new-highlights.mjs
Labels: triaged, User submitted

#6515 Bugfix/zoom admin list webinar participants
  components/zoom_admin/actions/add-meeting-registrant/add-meeting-registrant.mjs
  components/zoom_admin/actions/add-webinar-panelist/add-webinar-panelist.mjs
  components/zoom_admin/actions/add-webinar-registrant/add-webinar-registrant.mjs
  components/zoom_admin/actions/create-meeting/create-meeting.mjs
  components/zoom_admin/actions/create-webinar/create-webinar.mjs
  components/zoom_admin/actions/delete-cloud-recording/delete-cloud-recording.mjs
  components/zoom_admin/actions/delete-meeting/delete-meeting.mjs
  components/zoom_admin/actions/delete-webinar-panelist/delete-webinar-panelist.mjs
  components/zoom_admin/actions/delete-webinar/delete-webinar.mjs
  components/zoom_admin/actions/end-meeting/end-meeting.mjs
  components/zoom_admin/actions/get-meeting/get-meeting.mjs
  components/zoom_admin/actions/get-webinar/get-webinar.mjs
  components/zoom_admin/actions/list-cloud-recordings/list-cloud-recordings.mjs
  components/zoom_admin/actions/list-meeting-registrants/list-meeting-registrants.mjs
  components/zoom_admin/actions/list-meetings/list-meetings.mjs
  components/zoom_admin/actions/list-webinar-participants/list-webinar-participants.mjs
  components/zoom_admin/actions/list-webinar-registrants/list-webinar-registrants.mjs
  components/zoom_admin/actions/list-webinars/list-webinars.mjs
  components/zoom_admin/actions/update-meeting/update-meeting.mjs
  components/zoom_admin/actions/update-webinar-registrant-status/update-webinar-registrant-status.mjs
  components/zoom_admin/actions/update-webinar/update-webinar.mjs
  components/zoom_admin/package.json
  components/zoom_admin/sources/account-created/account-created.mjs
  components/zoom_admin/sources/account-settings-updated/account-settings-updated.mjs
  components/zoom_admin/sources/account-updated/account-updated.mjs
  components/zoom_admin/sources/custom-events/custom-events.mjs
  components/zoom_admin/sources/meeting-created/meeting-created.mjs
  components/zoom_admin/sources/meeting-deleted/meeting-deleted.mjs
  components/zoom_admin/sources/meeting-ended/meeting-ended.mjs
  components/zoom_admin/sources/meeting-started/meeting-started.mjs
  components/zoom_admin/sources/meeting-updated/meeting-updated.mjs
  components/zoom_admin/sources/recording-completed/recording-completed.mjs
  components/zoom_admin/sources/user-activated/user-activated.mjs
  components/zoom_admin/sources/user-created/user-created.mjs
  components/zoom_admin/sources/user-deactivated/user-deactivated.mjs
  components/zoom_admin/sources/user-deleted/user-deleted.mjs
  components/zoom_admin/sources/user-invitation-accepted/user-invitation-accepted.mjs
  components/zoom_admin/sources/user-updated/user-updated.mjs
  components/zoom_admin/sources/webinar-changes-to-panelists/webinar-changes-to-panelists.mjs
  components/zoom_admin/sources/webinar-created/webinar-created.mjs
  components/zoom_admin/sources/webinar-deleted/webinar-deleted.mjs
  components/zoom_admin/sources/webinar-ended/webinar-ended.mjs
  components/zoom_admin/sources/webinar-started/webinar-started.mjs
  components/zoom_admin/sources/webinar-updated/webinar-updated.mjs
  components/zoom_admin/zoom_admin.app.mjs
Labels: triaged

#6486 [Sources] Snowflake - Part 3
  components/snowflake/package.json
  components/snowflake/sources/common-delete.mjs
  components/snowflake/sources/deleted-role/deleted-role.mjs
  components/snowflake/sources/deleted-user/deleted-user.mjs
  components/visualping/actions/update-job/update-job.mjs
  components/visualping/common/utils.mjs
  components/visualping/package.json
  pnpm-lock.yaml
Labels: triaged

#6578 [Supabase] Fix deployment action
  components/supabase/actions/select-row/select-row.mjs
  components/supabase/package.json
  pnpm-lock.yaml
Labels: triaged

#6581 [TRIGGER] Calendly - New Event Created #6575
  components/calendly_v2/package.json
  components/calendly_v2/sources/new-event-scheduled/new-event-scheduled.mjs
Labels: enhancement

#6609 Vestaboard Create Message Update - allow characters prop to be string or array
  components/vestaboard/actions/create-message/create-message.mjs
  components/vestaboard/package.json
  pnpm-lock.yaml
Labels: triaged

#6094 Twitter OAuth 1.0a auth implementation
  components/twitter/actions/add-user-to-list/add-user-to-list.ts
  components/twitter/actions/create-tweet/create-tweet.ts
  components/twitter/actions/delete-tweet/delete-tweet.ts
  components/twitter/actions/follow-user/follow-user.ts
  components/twitter/actions/get-tweet/get-tweet.ts
  components/twitter/actions/get-user/get-user.ts
  components/twitter/actions/like-tweet/like-tweet.ts
  components/twitter/actions/list-favorites/list-favorites.ts
  components/twitter/actions/list-followers/list-followers.ts
  components/twitter/actions/list-lists/list-lists.ts
  components/twitter/actions/list-mentions/list-mentions.ts
  components/twitter/actions/list-user-tweets/list-user-tweets.ts
  components/twitter/actions/retweet/retweet.ts
  components/twitter/actions/simple-search-in-list/simple-search-in-list.ts
  components/twitter/actions/simple-search/simple-search.ts
  components/twitter/actions/unfollow-user/unfollow-user.ts
  components/twitter/actions/unlike-tweet/unlike-tweet.ts
  components/twitter/app/twitter.app.ts
  components/twitter/common/errorMessage.ts
  components/twitter/package.json
  components/twitter/sources/common/base.ts
  components/twitter/sources/new-follower-of-user/new-follower-of-user.ts
  components/twitter/sources/new-list-followed/new-list-followed.ts
  components/twitter/sources/new-tweet-in-list/new-tweet-in-list.ts
  components/twitter/sources/new-tweet-liked-by-user/new-tweet-liked-by-user.ts
  components/twitter/sources/new-tweet-posted-by-user/new-tweet-posted-by-user.ts
  components/twitter/sources/new-tweet-posted-matching-query/new-tweet-posted-matching-query.ts
  components/twitter/sources/new-unfollower-of-user/new-unfollower-of-user.ts
  components/twitter/sources/new-user-followed/new-user-followed.ts
  pnpm-lock.yaml
Labels: triaged

#6560 [ACTION] Update Threads API endpoint and docs link
  components/threads/actions/delete-thread/delete-thread.mjs
  components/threads/actions/post-chat-message/post-chat-message.mjs
  components/threads/actions/post-thread/post-thread.mjs
  components/threads/package.json
  components/threads/threads.app.mjs
Labels: triaged, User submitted

#6639 [TRIGGER] PayPal #6627
  components/paypal/actions/get-user-info/get-user-info.mjs
  components/paypal/actions/userinfo/userinfo.mjs
  components/paypal/package.json
  components/paypal/paypal.app.mjs
  components/paypal/sources/common/common.mjs
  components/paypal/sources/new-payment-event/new-payment-event.mjs
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: trigger / source, refactor
