Repository PipedreamHQ/pipedream, pull requests merged in 2023-02, with the labels that each got.

#5388 Update create-file-from-template.mjs
  components/google_drive/actions/create-file-from-template/create-file-from-template.mjs
  components/google_drive/package.json
Labels: triaged, User submitted

#5325 [BUG] PostgreSQL "New Row" trigger fails to connect when SSL is required on database #5290
  components/postgresql/actions/delete-rows/delete-rows.mjs
  components/postgresql/actions/execute-custom-query/execute-custom-query.mjs
  components/postgresql/actions/find-row-custom-query/find-row-custom-query.mjs
  components/postgresql/actions/find-row/find-row.mjs
  components/postgresql/actions/insert-row/insert-row.mjs
  components/postgresql/actions/update-row/update-row.mjs
  components/postgresql/package.json
  components/postgresql/postgresql.app.mjs
  components/postgresql/sources/common.mjs
  components/postgresql/sources/new-column/new-column.mjs
  components/postgresql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/postgresql/sources/new-row-custom-query/new-row-custom-query.mjs
  components/postgresql/sources/new-row/new-row.mjs
  components/postgresql/sources/new-table/new-table.mjs
Labels: bug

#5380 [Components] statuspage #5331
  components/statuspage/actions/common/constants.mjs
  components/statuspage/actions/create-incident/create-incident.mjs
  components/statuspage/actions/update-incident/update-incident.mjs
  components/statuspage/package.json
  components/statuspage/sources/common/common.mjs
  components/statuspage/sources/incident-updated/incident-updated.mjs
  components/statuspage/sources/new-incident-created/new-incident-created.mjs
  components/statuspage/statuspage.app.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#5391 [ENHANCMENT] PagerDuty: New or Updated incident - add more data in event body #5377
  components/pagerduty/package.json
  components/pagerduty/sources/common-webhook.mjs
  components/pagerduty/sources/new-oncall-rotation/new-oncall-rotation.mjs
  components/pagerduty/sources/new-or-updated-incident/new-or-updated-incident.mjs
Labels: refactor

#5447 Hubspot - Bug fix to New Deal In Stage
  components/hubspot/actions/add-contact-to-list/add-contact-to-list.mjs
  components/hubspot/actions/batch-create-or-update-contact/batch-create-or-update-contact.mjs
  components/hubspot/actions/create-associations/create-associations.mjs
  components/hubspot/actions/create-company/create-company.mjs
  components/hubspot/actions/create-contact/create-contact.mjs
  components/hubspot/actions/create-deal/create-deal.mjs
  components/hubspot/actions/create-engagement/create-engagement.mjs
  components/hubspot/actions/create-or-update-contact/create-or-update-contact.mjs
  components/hubspot/actions/enroll-contact-into-workflow/enroll-contact-into-workflow.mjs
  components/hubspot/actions/get-company/get-company.mjs
  components/hubspot/actions/get-contact/get-contact.mjs
  components/hubspot/actions/get-deal/get-deal.mjs
  components/hubspot/actions/get-file-public-url/get-file-public-url.mjs
  components/hubspot/actions/search-crm/search-crm.mjs
  components/hubspot/actions/update-company/update-company.mjs
  components/hubspot/actions/update-contact/update-contact.mjs
  components/hubspot/common/constants.mjs
  components/hubspot/hubspot.app.mjs
  components/hubspot/package.json
  components/hubspot/sources/common.mjs
  components/hubspot/sources/company-updated/company-updated.mjs
  components/hubspot/sources/contact-updated/contact-updated.mjs
  components/hubspot/sources/deal-updated/deal-updated.mjs
  components/hubspot/sources/delete-blog-article/delete-blog-article.mjs
  components/hubspot/sources/line-item-updated/line-item-updated.mjs
  components/hubspot/sources/new-blog-article/new-blog-article.mjs
  components/hubspot/sources/new-company/new-company.mjs
  components/hubspot/sources/new-contact-in-list/new-contact-in-list.mjs
  components/hubspot/sources/new-contact/new-contact.mjs
  components/hubspot/sources/new-deal-in-stage/new-deal-in-stage.mjs
  components/hubspot/sources/new-deal/new-deal.mjs
  components/hubspot/sources/new-email-event/new-email-event.mjs
  components/hubspot/sources/new-email-subscriptions-timeline/new-email-subscriptions-timeline.mjs
  components/hubspot/sources/new-engagement/new-engagement.mjs
  components/hubspot/sources/new-event/new-event.mjs
  components/hubspot/sources/new-form-submission/new-form-submission.mjs
  components/hubspot/sources/new-line-item/new-line-item.mjs
  components/hubspot/sources/new-or-updated-crm-object/new-or-updated-crm-object.mjs
  components/hubspot/sources/new-product/new-product.mjs
  components/hubspot/sources/new-social-media-message/new-social-media-message.mjs
  components/hubspot/sources/new-task/new-task.mjs
  components/hubspot/sources/new-ticket/new-ticket.mjs
  components/hubspot/sources/product-updated/product-updated.mjs
  components/hubspot/sources/updated-blog-article/updated-blog-article.mjs
Labels: triaged

#5445 Twitter - update Upload Media action to use form-data
  components/twitter/actions/upload-media/upload-media.mjs
  components/twitter/package.json
  pnpm-lock.yaml
Labels: triaged

#5513 Typeform: fix the month in formatted dates
  components/typeform/package.json
  components/typeform/sources/common/common.mjs
  components/typeform/sources/common/utils.mjs
  components/typeform/sources/new-submission/new-submission.mjs
Labels: triaged, User submitted

#5503 Transferwise #5444
  components/wise/actions/create-transfer/create-transfer.mjs
  components/wise/actions/get-exchange-rates/get-exchange-rates.mjs
  components/wise/actions/get-transfer/get-transfer.mjs
  components/wise/package.json
  components/wise/sources/common/common.mjs
  components/wise/sources/new-transfer-completed/new-transfer-completed.mjs
  components/wise/sources/new-transfer-created/new-transfer-created.mjs
  components/wise/wise.app.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#5504 [TRIGGER] Wise - Transfer state changed #5456
  components/wise/package.json
  components/wise/sources/new-transfer-state-changed/new-transfer-state-changed.mjs
Labels: trigger / source

#5546 [Notion] Enable Update Page to work without async options
  components/notion/actions/append-block/append-block.mjs
  components/notion/actions/create-page-from-database/create-page-from-database.mjs
  components/notion/actions/create-page/create-page.mjs
  components/notion/actions/duplicate-page/duplicate-page.mjs
  components/notion/actions/update-page/update-page.mjs
  components/notion/common/notion-page-properties.mjs
  components/notion/package.json
  pnpm-lock.yaml
Labels: triaged

#5545 [FEATURE] Include response headers in HTTP actions #5512
  components/http/actions/custom-request/custom-request.mjs
  components/http/actions/get-request/get-request.mjs
  components/http/actions/post-request/post-request.mjs
  components/http/actions/put-request/put-request.mjs
  components/http/package.json
Labels: enhancement

#5565 Added an option to return reponse headers on HTTP action
  components/http/actions/custom-request/custom-request.mjs
  components/http/actions/get-request/get-request.mjs
  components/http/actions/post-request/post-request.mjs
  components/http/actions/put-request/put-request.mjs
  components/http/package.json
Labels: refactor
