Repository PipedreamHQ/pipedream, pull requests merged in 2023-04, with the labels that each got.

#5914 [Components] Anthropic (Claude) #5897
  components/anthropic/.gitignore
  components/anthropic/actions/chat/chat.mjs
  components/anthropic/actions/common/constants.mjs
  components/anthropic/app/anthropic.app.mjs
  components/anthropic/app/anthropic.app.ts
  components/anthropic/package.json
Labels: action

#5924 fix:broken link in components/api
  docs/docs/components/api/README.md
Labels: triaged, User submitted

#5929 [OpenAI] Fix memory exceeded for large audio files (30+ min)
  components/openai/actions/chat/chat.mjs
  components/openai/actions/classify-items-into-categories/classify-items-into-categories.mjs
  components/openai/actions/create-embeddings/create-embeddings.mjs
  components/openai/actions/create-image/create-image.mjs
  components/openai/actions/create-transcription/create-transcription.mjs
  components/openai/actions/send-prompt/send-prompt.mjs
  components/openai/actions/summarize/summarize.mjs
  components/openai/actions/translate-text/translate-text.mjs
  components/openai/app/openai.app.mjs
  components/openai/package.json
  pnpm-lock.yaml
Labels: bug, enhancement, triaged

#5963 [Sources] ProWorkFlow: Company Created
  components/proworkflow/package.json
  components/proworkflow/sources/new-company-created/new-company-created.mjs
Labels: triaged, User submitted

#5995 feat[asana]: emit new event each time a tag is added to any task
  components/asana/package.json
  components/asana/sources/tags-added-to-any-task/tags-added-to-any-task.mjs
Labels: triaged, User submitted

#5996 GoDial #3639
  components/godial/.gitignore
  components/godial/action/add-contact/add-contact.mjs
  components/godial/action/add-member/add-member.mjs
  components/godial/action/common/constants.mjs
  components/godial/app/godial.app.mjs
  components/godial/app/godial.app.ts
  components/godial/package.json
  components/godial/sources/new-updated-contact/new-updated-contact.mjs
Labels: action, trigger / source

#6023 [ACTION] PandaDoc - Create Document: add optional prop for folder
  components/pandadoc/actions/create-document-from-file/create-document-from-file.mjs
  components/pandadoc/package.json
Labels: triaged, User submitted

#6046 Fix mispelling in readwise app
  components/readwise/actions/get-highlight-details/get-highlight-details.mjs
  components/readwise/actions/list-highlights/list-highlights.mjs
  components/readwise/package.json
  components/readwise/readwise.app.mjs
  components/readwise/sources/new-highlights/new-highlights.mjs
Labels: triaged, User submitted

#6082 correcting types
  types/package.json
  types/src/index.ts
Labels: triaged, User submitted

#6073 [Components] Habitify #6035
  components/habitify/.gitignore
  components/habitify/app/habitify.app.mjs
  components/habitify/app/habitify.app.ts
  components/habitify/package.json
  components/habitify/sources/new-habit-created/new-habit-created.mjs
  pnpm-lock.yaml
Labels: trigger / source

#6145 [Browserless] New Actions
  components/browserless/actions/scrape-url-list/scrape-url-list.mjs
  components/browserless/actions/scrape-url/scrape-url.mjs
  components/browserless/browserless.app.mjs
  components/browserless/package.json
  pnpm-lock.yaml
Labels: triaged

#6062 [APP] visualping #6013
  components/visualping/.gitignore
  components/visualping/app/visualping.app.mjs
  components/visualping/app/visualping.app.ts
  components/visualping/package.json
  components/visualping/sources/new-job-created/new-job-created.mjs
  components/visualping/sources/new-job-event/new-job-event.mjs
Labels: trigger / source

#6107 [FEATURE] Add prop to set Custom Document ID for Firebase - Create Document action #6105
  components/firebase_admin_sdk/actions/create-document/create-document.mjs
  components/firebase_admin_sdk/actions/create-realtime-db-record/create-realtime-db-record.mjs
  components/firebase_admin_sdk/actions/list-documents/list-documents.mjs
  components/firebase_admin_sdk/actions/replicate-event-firestore/replicate-event-firestore.mjs
  components/firebase_admin_sdk/actions/update-document/update-document.mjs
  components/firebase_admin_sdk/firebase_admin_sdk.app.mjs
  components/firebase_admin_sdk/package.json
  components/firebase_admin_sdk/sources/new-child-object/new-child-object.mjs
  components/firebase_admin_sdk/sources/new-doc-in-firestore-collection/new-doc-in-firestore-collection.mjs
  pnpm-lock.yaml
Labels: enhancement
