Repository PipedreamHQ/pipedream, pull requests merged in 2023-03, with the labels that each got.

#5608 fix(crove_app): allow to pass custom name to generate pdf from templa…
  components/crove_app/actions/complete-document/complete-document.mjs
  components/crove_app/actions/create-document/create-document.mjs
  components/crove_app/actions/create-invitation-link/create-invitation-link.mjs
  components/crove_app/actions/generate-pdf-from-document/generate-pdf-from-document.mjs
  components/crove_app/actions/generate-template-pdf/generate-template-pdf.mjs
  components/crove_app/actions/get-document-details/get-document-details.mjs
  components/crove_app/actions/send-document/send-document.mjs
  components/crove_app/actions/submit-document/submit-document.mjs
  components/crove_app/actions/update-document-details/update-document-details.mjs
  components/crove_app/actions/update-document/update-document.mjs
  components/crove_app/crove_app.app.mjs
  components/crove_app/package.json
  components/crove_app/sources/document-completed/document-completed.mjs
  components/crove_app/sources/document-created/document-created.mjs
  components/crove_app/sources/document-submitted/document-submitted.mjs
Labels: triaged, User submitted

#5563 [BUG] DM Received Slack Trigger emits on every DM *sent* as well as received #5560
  components/slack/package.json
  components/slack/sources/new-direct-message/new-direct-message.mjs
Labels: bug

#5633 New OpenAI actions (Chat, Whisper, etc.)
  .tool-versions
  components/openai/actions/chat/chat.mjs
  components/openai/actions/classify-items-into-categories/classify-items-into-categories.mjs
  components/openai/actions/common/common-helper.mjs
  components/openai/actions/common/common.mjs
  components/openai/actions/common/constants.mjs
  components/openai/actions/common/lang.mjs
  components/openai/actions/create-embeddings/create-embeddings.mjs
  components/openai/actions/create-image/create-image.mjs
  components/openai/actions/create-transcription/create-transcription.mjs
  components/openai/actions/send-prompt/send-prompt.mjs
  components/openai/actions/summarize/summarize.mjs
  components/openai/actions/translate-text/translate-text.mjs
  components/openai/app/openai.app.mjs
  components/openai/openai.app.mjs
  components/openai/package.json
  package.json
  pnpm-lock.yaml
Labels: triaged

#5656 BREAKING CHANGE(crove_app): Modify actions and sources to remove unnecessary data from document payload before returning
  components/crove_app/actions/complete-document/complete-document.mjs
  components/crove_app/actions/create-document/create-document.mjs
  components/crove_app/actions/create-invitation-link/create-invitation-link.mjs
  components/crove_app/actions/generate-pdf-from-document/generate-pdf-from-document.mjs
  components/crove_app/actions/generate-template-pdf/generate-template-pdf.mjs
  components/crove_app/actions/get-document-details/get-document-details.mjs
  components/crove_app/actions/submit-document/submit-document.mjs
  components/crove_app/actions/update-document-details/update-document-details.mjs
  components/crove_app/actions/update-document/update-document.mjs
  components/crove_app/package.json
  components/crove_app/sources/common.mjs
  components/crove_app/sources/document-completed/document-completed.mjs
  components/crove_app/sources/document-created/document-created.mjs
  components/crove_app/sources/document-submitted/document-submitted.mjs
Labels: triaged, User submitted

#5544 [FEATURE] @pipedream/platform axios should support the ability to create custom axios constructor, or pass all standard axios options #5497
  platform/dist/axios.js
  platform/lib/axios.ts
  platform/lib/index.ts
Labels: enhancement

#5702 [IMPROVEMENT] Add List filter to Clickup - New Updated Task source #5658
  components/clickup/package.json
  components/clickup/sources/updated-task/updated-task.mjs
Labels: enhancement

#5716 Dump platform package.json version to 1.4.0
  platform/package.json
Labels: refactor

#5727 [GitHub Actions] Fail step if any error in publishing
  .github/workflows/publish-components.yaml
Labels: triaged

#5650 Wise: Get Balance action #5626
  components/wise/actions/create-transfer/create-transfer.mjs
  components/wise/actions/fund-transfer/fund-transfer.mjs
  components/wise/actions/get-balance/get-balance.mjs
  components/wise/actions/get-exchange-rates/get-exchange-rates.mjs
  components/wise/actions/get-transfer/get-transfer.mjs
  components/wise/package.json
  components/wise/sources/common/common.mjs
  components/wise/sources/new-transfer-completed/new-transfer-completed.mjs
  components/wise/sources/new-transfer-created/new-transfer-created.mjs
  components/wise/sources/new-transfer-state-changed/new-transfer-state-changed.mjs
  components/wise/wise.app.mjs
Labels: action

#5729 Wise: fix Profile prop names on business accounts
  components/wise/actions/create-transfer/create-transfer.mjs
  components/wise/actions/fund-transfer/fund-transfer.mjs
  components/wise/actions/get-balance/get-balance.mjs
  components/wise/actions/get-exchange-rates/get-exchange-rates.mjs
  components/wise/actions/get-transfer/get-transfer.mjs
  components/wise/package.json
  components/wise/sources/new-transfer-completed/new-transfer-completed.mjs
  components/wise/sources/new-transfer-created/new-transfer-created.mjs
  components/wise/sources/new-transfer-state-changed/new-transfer-state-changed.mjs
  components/wise/wise.app.mjs
Labels: triaged, User submitted

#5715 Few minor wording mistakes.
  docs/docs/troubleshooting/README.md
Labels: triaged, User submitted

#5773 Fixed bug with authenticated endpoint - Platform Axios Lib
  platform/dist/axios.js
  platform/lib/axios.ts
  platform/package.json
Labels: bug, triaged

#5734 Moved quote creation to one new action - Wise
  components/wise/actions/common/constants.mjs
  components/wise/actions/create-quote/create-quote.mjs
  components/wise/actions/create-transfer/create-transfer.mjs
  components/wise/package.json
Labels: enhancement, triaged

#5772 [BUG] BigCartel sources throw Error: Request failed with status code 404 #5554
  components/big_cartel/big_cartel.app.mjs
  components/big_cartel/package.json
  components/big_cartel/sources/new-order/new-order.mjs
  components/big_cartel/sources/new-product/new-product.mjs
Labels: bug

#5799 [ACTION] Search Categories #5755
  components/twitch/actions/block-user/block-user.mjs
  components/twitch/actions/check-channel-subscription/check-channel-subscription.mjs
  components/twitch/actions/delete-video/delete-video.mjs
  components/twitch/actions/get-channel-editors/get-channel-editors.mjs
  components/twitch/actions/get-channel-information/get-channel-information.mjs
  components/twitch/actions/get-channel-teams/get-channel-teams.mjs
  components/twitch/actions/get-clips/get-clips.mjs
  components/twitch/actions/get-followed-channels/get-followed-channels.mjs
  components/twitch/actions/get-followers/get-followers.mjs
  components/twitch/actions/get-my-followers/get-my-followers.mjs
  components/twitch/actions/get-stream-by-user/get-stream-by-user.mjs
  components/twitch/actions/get-top-games/get-top-games.mjs
  components/twitch/actions/get-users/get-users.mjs
  components/twitch/actions/get-videos/get-videos.mjs
  components/twitch/actions/search-channels/search-channels.mjs
  components/twitch/actions/search-games/search-games.mjs
  components/twitch/actions/unblock-user/unblock-user.mjs
  components/twitch/actions/update-channel/update-channel.mjs
  components/twitch/package.json
  components/twitch/sources/followed-streams/followed-streams.mjs
  components/twitch/sources/new-clip-by-streamer/new-clip-by-streamer.mjs
  components/twitch/sources/new-clips/new-clips.mjs
  components/twitch/sources/new-follower/new-follower.mjs
  components/twitch/sources/new-videos/new-videos.mjs
  components/twitch/sources/streams-by-game/streams-by-game.mjs
  components/twitch/sources/streams-by-streamer/streams-by-streamer.mjs
  components/twitch/twitch.app.mjs
Labels: bug

#5814 [TRIGGER] GitHub New Discussion #5520
  components/github/package.json
  components/github/sources/new-discussion/new-discussion.mjs
Labels: enhancement

#5825 [FEATURE] TLS support on MySql Connection #5800
  components/mysql/actions/common/utils.mjs
  components/mysql/actions/create-row/create-row.mjs
  components/mysql/actions/delete-row/delete-row.mjs
  components/mysql/actions/execute-query/execute-query.mjs
  components/mysql/actions/execute-stored-procedure/execute-stored-procedure.mjs
  components/mysql/actions/find-row/find-row.mjs
  components/mysql/actions/update-row/update-row.mjs
  components/mysql/mysql.app.mjs
  components/mysql/package.json
  components/mysql/sources/common.mjs
  components/mysql/sources/new-column/new-column.mjs
  components/mysql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/mysql/sources/new-row-custom-query/new-row-custom-query.mjs
  components/mysql/sources/new-row/new-row.mjs
  components/mysql/sources/new-table/new-table.mjs
Labels: enhancement

#5858 [Components] Weatherbit.io #5808
  components/weatherbit_io/.gitignore
  components/weatherbit_io/actions/fetch-current-weather/fetch-current-weather.mjs
  components/weatherbit_io/actions/fetch-daily-forecast-weather/fetch-daily-forecast-weather.mjs
  components/weatherbit_io/actions/fetch-historical-weather-data/fetch-historical-weather-data.mjs
  components/weatherbit_io/app/weatherbit_io.app.ts
  components/weatherbit_io/package.json
  components/weatherbit_io/weatherbit_io.app.mjs
  pnpm-lock.yaml
Labels: action

#5875 [Pipedream] Generate component code action
  components/pipedream/actions/generate-component-code/generate-component-code.mjs
  components/pipedream/package.json
  pnpm-lock.yaml
Labels: triaged

#5891 [ACTION] Jira - Get Users #5890
  components/jira/actions/get-users/get-users.mjs
  components/jira/package.json
Labels: action

#5881 OpenAI Create Image: add defaults to match API behavior
  components/openai/actions/create-image/create-image.mjs
  components/openai/package.json
Labels: triaged, User submitted
