Repository PipedreamHQ/pipedream, pull requests merged in 2023-07, with the labels that each got.

#6801 [Components] Trakt #6628
  components/trakt/.gitignore
  components/trakt/actions/add-to-watchlist/add-to-watchlist.mjs
  components/trakt/actions/common/utils.mjs
  components/trakt/actions/remove-from-watchlist/remove-from-watchlist.mjs
  components/trakt/app/trakt.app.ts
  components/trakt/package.json
  components/trakt/sources/common/common.mjs
  components/trakt/sources/common/constants.mjs
  components/trakt/sources/new-show-or-movie-rated/new-show-or-movie-rated.mjs
  components/trakt/sources/new-show-or-movie-watched/new-show-or-movie-watched.mjs
  components/trakt/trakt.app.mjs
Labels: action, trigger / source

#7090 [FEATURE] Github Create Branch prop improvement #6975
  components/github/actions/create-branch/create-branch.mjs
  components/github/actions/create-issue-comment/create-issue-comment.mjs
  components/github/actions/create-issue/create-issue.mjs
  components/github/actions/create-or-update-file-contents/create-or-update-file-contents.mjs
  components/github/actions/create-repository/create-repository.mjs
  components/github/actions/get-issue-assignees/get-issue-assignees.mjs
  components/github/actions/get-repository-content/get-repository-content.mjs
  components/github/actions/get-repository/get-repository.mjs
  components/github/actions/get-reviewers/get-reviewers.mjs
  components/github/actions/search-issues-and-pull-requests/search-issues-and-pull-requests.mjs
  components/github/actions/update-issue/update-issue.mjs
  components/github/github.app.mjs
  components/github/package.json
  components/github/sources/new-card-in-column/new-card-in-column.mjs
  components/github/sources/new-commit/new-commit.mjs
  components/github/sources/new-discussion/new-discussion.mjs
  components/github/sources/new-gist/new-gist.mjs
  components/github/sources/new-issue-with-status/new-issue-with-status.mjs
  components/github/sources/new-mention/new-mention.mjs
  components/github/sources/new-notification/new-notification.mjs
  components/github/sources/new-organization/new-organization.mjs
  components/github/sources/new-repository/new-repository.mjs
  components/github/sources/new-review-request/new-review-request.mjs
  components/github/sources/new-security-alert/new-security-alert.mjs
  components/github/sources/new-team/new-team.mjs
  components/github/sources/webhook-events/webhook-events.mjs
Labels: enhancement

#7031 Ghost Admin API with Featured Image
  components/ghost_org_admin_api/actions/create-post/create-post.mjs
  components/ghost_org_admin_api/package.json
Labels: triaged, User submitted

#7135 [BUG] Shopify Partner - New App Installs source does not emit new event #7121
  components/shopify_partner/actions/verify-webhook/verify-webhook.mjs
  components/shopify_partner/package.json
  components/shopify_partner/shopify_partner.app.mjs
  components/shopify_partner/sources/new-app-charges/new-app-charges.mjs
  components/shopify_partner/sources/new-app-installs/new-app-installs.mjs
  components/shopify_partner/sources/new-app-relationship-events/new-app-relationship-events.mjs
  components/shopify_partner/sources/new-app-uninstalls/new-app-uninstalls.mjs
Labels: bug

#7153 [BUG] Gorgias - New ticket source failed with the account having more than 5000 tickets #7133
  components/gorgias_oauth/package.json
  components/gorgias_oauth/sources/common/constants.mjs
  components/gorgias_oauth/sources/ticket-created/ticket-created.mjs
  components/gorgias_oauth/sources/ticket-message-created/ticket-message-created.mjs
  components/gorgias_oauth/sources/ticket-updated/ticket-updated.mjs
Labels: bug

#7172 [FEATURE] Add async options to list movies and shows props
  components/trakt/actions/add-to-watchlist/add-to-watchlist.mjs
  components/trakt/actions/remove-from-watchlist/remove-from-watchlist.mjs
  components/trakt/package.json
  components/trakt/sources/new-show-or-movie-rated/new-show-or-movie-rated.mjs
  components/trakt/sources/new-show-or-movie-watched/new-show-or-movie-watched.mjs
  components/trakt/trakt.app.mjs
Labels: enhancement, triaged

#7204 [BUG] Datastore - Get or create record returns No data found for key when the value is 0 #7187
  components/data_stores/actions/get-record-or-create/get-record-or-create.mjs
  components/data_stores/package.json
Labels: bug

#7210 RSS - Bug fix for source New Item From Multiple Feeds
  components/rss/actions/merge-rss-feeds/merge-rss-feeds.ts
  components/rss/app/rss.app.ts
  components/rss/package.json
  components/rss/sources/new-item-from-multiple-feeds/new-item-from-multiple-feeds.ts
  components/rss/sources/new-item-in-feed/new-item-in-feed.ts
  components/rss/sources/random-item-in-multiple-feeds/random-item-in-multiple-feeds.ts
Labels: triaged

#7252 [FEATURE] Ticktick: Create Ticket - add priority prop #7239
  components/ticktick/actions/create-task/create-task.mjs
  components/ticktick/package.json
  pnpm-lock.yaml
Labels: enhancement

#7238 [TRIGGER] Freshservice - New Ticket #7200
  components/freshservice/freshservice.app.mjs
  components/freshservice/package.json
  components/freshservice/sources/new-ticket/new-ticket.mjs
  pnpm-lock.yaml
Labels: trigger / source

#7290 Adjusting findBadKeys to not match mixed quotes
  scripts/findBadKeys.js
Labels: triaged

#7355 Fixing path bug on Dropbox "Move a File/Folder" action
  components/dropbox/actions/move-file-folder/move-file-folder.mjs
  components/dropbox/package.json
  pnpm-lock.yaml
Labels: bug, triaged

#7356 [Components] Axonaut #6418
  components/axonaut/.gitignore
  components/axonaut/actions/create-company/create-company.mjs
  components/axonaut/actions/create-employee/create-employee.mjs
  components/axonaut/actions/update-company/update-company.mjs
  components/axonaut/actions/update-employee/update-employee.mjs
  components/axonaut/app/axonaut.app.ts
  components/axonaut/axonaut.app.mjs
  components/axonaut/package.json
  pnpm-lock.yaml
Labels: action

#7380 [BUG] SendGrid - BCC handling not optimal #7375
  components/sendgrid/actions/send-email-single-recipient/send-email-single-recipient.mjs
  components/sendgrid/package.json
Labels: bug

#7401 GitHub source bugfix
  components/github/package.json
  components/github/sources/new-card-in-column/new-card-in-column.mjs
Labels: triaged
