Repository PipedreamHQ/pipedream, pull requests merged in 2023-06, with the labels that each got.

#6685 [Components] Hootsuite #6613
  components/hootsuite/.gitignore
  components/hootsuite/app/hootsuite.app.ts
  components/hootsuite/hootsuite.app.mjs
  components/hootsuite/package.json
  components/hootsuite/sources/common/constants.mjs
  components/hootsuite/sources/new-post-created/new-post-created.mjs
  pnpm-lock.yaml
Labels: trigger / source

#6691 [BUG] Discourse - New Threads categories async prop broken #6641
  components/discourse/actions/create-post/create-post.mjs
  components/discourse/actions/create-topic/create-topic.mjs
  components/discourse/discourse.app.mjs
  components/discourse/package.json
  components/discourse/sources/new-posts-added/new-posts-added.mjs
  components/discourse/sources/new-topics-added/new-topics-added.mjs
  components/discourse/sources/new-users-added/new-users-added.mjs
Labels: bug

#6726 [FEATURE] Add DimensionFilter to Google Analytics: Run Report in G4A action #6724
  components/google_analytics/actions/run-report-in-ga4/run-report-in-ga4.mjs
  components/google_analytics/package.json
Labels: enhancement

#6712 [Bugxfix] Snowflake - Failed Task in Schema
  components/snowflake/actions/insert-multiple-rows/insert-multiple-rows.mjs
  components/snowflake/actions/insert-row/insert-row.mjs
  components/snowflake/package.json
  components/snowflake/snowflake.app.mjs
  components/snowflake/sources/change-to-warehouse/change-to-warehouse.mjs
  components/snowflake/sources/common.mjs
  components/snowflake/sources/deleted-role/deleted-role.mjs
  components/snowflake/sources/deleted-user/deleted-user.mjs
  components/snowflake/sources/failed-task-in-schema/failed-task-in-schema.mjs
  components/snowflake/sources/new-database/new-database.mjs
  components/snowflake/sources/new-role/new-role.mjs
  components/snowflake/sources/new-row/new-row.mjs
  components/snowflake/sources/new-schema/new-schema.mjs
  components/snowflake/sources/new-table/new-table.mjs
  components/snowflake/sources/new-user/new-user.mjs
  components/snowflake/sources/query-results/query-results.mjs
  components/snowflake/sources/updated-role/updated-role.mjs
  components/snowflake/sources/updated-user/updated-user.mjs
  components/snowflake/sources/usage-monitor/usage-monitor.mjs
Labels: triaged

#6231 [Docs] Adding useQuery related information
  docs/docs/components/api/README.md
Labels: docs

#6736 [Source] Snowflake - Add regex to getFailedTasksInDatabase
  components/snowflake/actions/insert-multiple-rows/insert-multiple-rows.mjs
  components/snowflake/actions/insert-row/insert-row.mjs
  components/snowflake/package.json
  components/snowflake/snowflake.app.mjs
  components/snowflake/sources/change-to-warehouse/change-to-warehouse.mjs
  components/snowflake/sources/common.mjs
  components/snowflake/sources/deleted-role/deleted-role.mjs
  components/snowflake/sources/deleted-user/deleted-user.mjs
  components/snowflake/sources/failed-task-in-schema/failed-task-in-schema.mjs
  components/snowflake/sources/new-database/new-database.mjs
  components/snowflake/sources/new-role/new-role.mjs
  components/snowflake/sources/new-row/new-row.mjs
  components/snowflake/sources/new-schema/new-schema.mjs
  components/snowflake/sources/new-table/new-table.mjs
  components/snowflake/sources/new-user/new-user.mjs
  components/snowflake/sources/query-results/query-results.mjs
  components/snowflake/sources/updated-role/updated-role.mjs
  components/snowflake/sources/updated-user/updated-user.mjs
  components/snowflake/sources/usage-monitor/usage-monitor.mjs
Labels: triaged

#6809 Bumping upload-media action version to 0.0.4
  components/twitter/actions/upload-media/upload-media.ts
  components/twitter/package.json
Labels: bug

#6917 Bugfix: updating "extract email address" regex
  components/formatting/actions/extract-email-address/extract-email-address.ts
  components/formatting/package.json
  pnpm-lock.yaml
Labels: bug, triaged

#6939 add pandadoc send document action
  components/pandadoc/actions/create-document-attachment/create-document-attachment.mjs
  components/pandadoc/actions/create-document-from-file/create-document-from-file.mjs
  components/pandadoc/actions/create-document-from-template/create-document-from-template.mjs
  components/pandadoc/actions/create-folder/create-folder.mjs
  components/pandadoc/actions/create-or-update-contact/create-or-update-contact.mjs
  components/pandadoc/actions/document-details/document-details.mjs
  components/pandadoc/actions/list-contacts/list-contacts.mjs
  components/pandadoc/actions/list-document-attachments/list-document-attachments.mjs
  components/pandadoc/actions/list-documents/list-documents.mjs
  components/pandadoc/actions/list-folders/list-folders.mjs
  components/pandadoc/actions/send-document/send-document.mjs
  components/pandadoc/package.json
  components/pandadoc/pandadoc.app.mjs
  components/pandadoc/sources/document-creation-failed/document-creation-failed.mjs
  components/pandadoc/sources/document-deleted/document-deleted.mjs
  components/pandadoc/sources/document-state-changed/document-state-changed.mjs
  components/pandadoc/sources/document-updated/document-updated.mjs
  components/pandadoc/sources/recipient-completed/recipient-completed.mjs
Labels: triaged, User submitted

#7095 Update pricing README.md
  docs/docs/pricing/README.md
Labels: triaged, User submitted
