Repository PipedreamHQ/pipedream, pull requests merged in 2024-12, with the labels that each got.

#14685 New Components - grain
  components/amazon_selling_partner/amazon_selling_partner.app.mjs
  components/bigdatacorp/bigdatacorp.app.mjs
  components/checkout_com/checkout_com.app.mjs
  components/grain/actions/get-recording/get-recording.mjs
  components/grain/common/constants.mjs
  components/grain/common/utils.mjs
  components/grain/grain.app.mjs
  components/grain/package.json
  components/grain/sources/common/base.mjs
  components/grain/sources/new-highlight-instant/new-highlight-instant.mjs
  components/grain/sources/new-highlight-instant/test-event.mjs
  components/grain/sources/new-recording-instant/new-recording-instant.mjs
  components/grain/sources/new-recording-instant/test-event.mjs
  components/grain/sources/new-story-instant/new-story-instant.mjs
  components/grain/sources/new-story-instant/test-event.mjs
  components/grain/sources/removed-highlight-instant/removed-highlight-instant.mjs
  components/grain/sources/removed-highlight-instant/test-event.mjs
  components/grain/sources/removed-recording-instant/removed-recording-instant.mjs
  components/grain/sources/removed-recording-instant/test-event.mjs
  components/grain/sources/removed-story-instant/removed-story-instant.mjs
  components/grain/sources/removed-story-instant/test-event.mjs
  components/grain/sources/updated-highlight-instant/test-event.mjs
  components/grain/sources/updated-highlight-instant/updated-highlight-instant.mjs
  components/grain/sources/updated-recording-instant/test-event.mjs
  components/grain/sources/updated-recording-instant/updated-recording-instant.mjs
  components/grain/sources/updated-story-instant/test-event.mjs
  components/grain/sources/updated-story-instant/updated-story-instant.mjs
  components/mailgenius/mailgenius.app.mjs
  components/microsoft_teams_bot/microsoft_teams_bot.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14793 [Components] attractwell
  components/attractwell/actions/create-update-contact/create-update-contact.mjs
  components/attractwell/actions/lesson-approval/lesson-approval.mjs
  components/attractwell/attractwell.app.mjs
  components/attractwell/common/constants.mjs
  components/attractwell/common/utils.mjs
  components/attractwell/package.json
  components/attractwell/sources/common/trigger-contexts.mjs
  components/attractwell/sources/common/trigger-names.mjs
  components/attractwell/sources/common/webhook.mjs
  components/attractwell/sources/contact-joins-vault-instant/contact-joins-vault-instant.mjs
  components/attractwell/sources/new-event-registration-instant/new-event-registration-instant.mjs
  components/attractwell/sources/new-lead-from-landing-page-instant/new-lead-from-landing-page-instant.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#14887 Fix dynamic props in the Connect demo app
  packages/connect-react/package.json
  packages/connect-react/src/hooks/form-context.tsx
  pnpm-lock.yaml
Labels: bug, dependencies, tracked internally, prioritized

#14703 New Components - ortto
  components/ortto/.gitignore
  components/ortto/actions/create-custom-activity/create-custom-activity.mjs
  components/ortto/actions/create-person/create-person.mjs
  components/ortto/actions/opt-out-sms/opt-out-sms.mjs
  components/ortto/app/ortto.app.ts
  components/ortto/common/constants.mjs
  components/ortto/common/utils.mjs
  components/ortto/ortto.app.mjs
  components/ortto/package.json
  components/ortto/sources/common/base.mjs
  components/ortto/sources/new-contact-created/new-contact-created.mjs
  components/ortto/sources/new-contact-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14883 Amend the Component API methods in the SDK
  components/rejoiner/rejoiner.app.mjs
  packages/sdk/package.json
  packages/sdk/src/shared/index.ts
Labels: enhancement, docs, pd-api, tracked internally, prioritized

#14841 Webflow v2 migration 2024 12 11
  components/webflow/actions/create-collection-item/create-collection-item.mjs
  components/webflow/actions/delete-collection-item/delete-collection-item.mjs
  components/webflow/actions/fulfill-order/fulfill-order.mjs
  components/webflow/actions/get-collection-item/get-collection-item.mjs
  components/webflow/actions/get-collection/get-collection.mjs
  components/webflow/actions/get-item-inventory/get-item-inventory.mjs
  components/webflow/actions/get-order/get-order.mjs
  components/webflow/actions/get-site/get-site.mjs
  components/webflow/actions/list-collection-items/list-collection-items.mjs
  components/webflow/actions/list-collections/list-collections.mjs
  components/webflow/actions/list-orders/list-orders.mjs
  components/webflow/actions/list-sites/list-sites.mjs
  components/webflow/actions/publish-site/publish-site.mjs
  components/webflow/actions/refund-order/refund-order.mjs
  components/webflow/actions/unfulfill-order/unfulfill-order.mjs
  components/webflow/actions/update-collection-item/update-collection-item.mjs
  components/webflow/actions/update-item-inventory/update-item-inventory.mjs
  components/webflow/actions/update-order/update-order.mjs
  components/webflow/package.json
  components/webflow/sources/changed-collection-item/changed-collection-item.mjs
  components/webflow/sources/changed-ecommerce-inventory/changed-ecommerce-inventory.mjs
  components/webflow/sources/changed-ecommerce-order/changed-ecommerce-order.mjs
  components/webflow/sources/common/common.mjs
  components/webflow/sources/new-collection-item/new-collection-item.mjs
  components/webflow/sources/new-deleted-collection-item/new-deleted-collection-item.mjs
  components/webflow/sources/new-ecommerce-order/new-ecommerce-order.mjs
  components/webflow/sources/new-form-submission/new-form-submission.mjs
  components/webflow/sources/new-site-published/new-site-published.mjs
  components/webflow/webflow.app.mjs
  components/webflow_v2/package.json
  components/webflow_v2/webflow_v2.app.mjs
  pnpm-lock.yaml
Labels: DO NOT MERGE

#14861 New Components - ironclad
  components/ironclad/actions/create-record/create-record.mjs
  components/ironclad/actions/launch-workflow/launch-workflow.mjs
  components/ironclad/actions/update-workflow/update-workflow.mjs
  components/ironclad/common/utils.mjs
  components/ironclad/ironclad.app.mjs
  components/ironclad/package.json
  components/ironclad/sources/common/base.mjs
  components/ironclad/sources/common/events.mjs
  components/ironclad/sources/new-approval-event-instant/new-approval-event-instant.mjs
  components/ironclad/sources/new-approval-event-instant/test-event.mjs
  components/ironclad/sources/new-workflow-document-event-instant/new-workflow-document-event-instant.mjs
  components/ironclad/sources/new-workflow-document-event-instant/test-event.mjs
  components/ironclad/sources/new-workflow-event-instant/new-workflow-event-instant.mjs
  components/ironclad/sources/new-workflow-event-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14855 New Components - signaturit
  components/signaturit/.gitignore
  components/signaturit/actions/create-certified-email/create-certified-email.mjs
  components/signaturit/actions/create-signature-request-from-template/create-signature-request-from-template.mjs
  components/signaturit/actions/send-signature-request-reminder/send-signature-request-reminder.mjs
  components/signaturit/app/signaturit.app.ts
  components/signaturit/common/constants.mjs
  components/signaturit/common/utils.mjs
  components/signaturit/package.json
  components/signaturit/signaturit.app.mjs
  components/signaturit/sources/common/base.mjs
  components/signaturit/sources/new-signed-document/new-signed-document.mjs
  components/signaturit/sources/new-signed-document/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14763 [New Component] Gistly YouTube Transcript API
  components/gistly/README.md
  components/gistly/actions/get-transcript/get-transcript.mjs
  components/gistly/gistly.app.mjs
  components/gistly/package.json
  pnpm-lock.yaml
Labels: User submitted

#14931 Document the Connect component API
  docs-v2/.tool-versions
  docs-v2/pages/connect/_meta.tsx
  docs-v2/pages/connect/api.mdx
  docs-v2/pages/connect/components.mdx
  docs-v2/pages/connect/use-cases.mdx
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  packages/sdk/src/shared/index.ts
  pnpm-lock.yaml
Labels: question, dependencies, docs, tracked internally, prioritized

#14925 Google Calendar improvements to New or Updated Event source
  components/google_calendar/package.json
  components/google_calendar/sources/new-or-updated-event-instant/new-or-updated-event-instant.mjs
  pnpm-lock.yaml
Labels: User submitted

#15004 New Components - rejoiner
  components/rejoiner/actions/add-customer-to-list/add-customer-to-list.mjs
  components/rejoiner/actions/start-journey/start-journey.mjs
  components/rejoiner/actions/update-customer-profile/update-customer-profile.mjs
  components/rejoiner/package.json
  components/rejoiner/rejoiner.app.mjs
  components/rejoiner/sources/new-contact-in-list/new-contact-in-list.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15009 New Components - circleci
  components/circleci/actions/get-job-artifacts/get-job-artifacts.mjs
  components/circleci/actions/rerun-workflow/rerun-workflow.mjs
  components/circleci/actions/trigger-pipeline/trigger-pipeline.mjs
  components/circleci/circleci.app.mjs
  components/circleci/package.json
  components/circleci/sources/common/base.mjs
  components/circleci/sources/new-job-completed-instant/new-job-completed-instant.mjs
  components/circleci/sources/new-job-completed-instant/test-event.mjs
  components/circleci/sources/new-workflow-completed-instant/new-workflow-completed-instant.mjs
  components/circleci/sources/new-workflow-completed-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14973 New Components - pennylane
  components/pennylane/actions/create-billing-subscription/create-billing-subscription.mjs
  components/pennylane/actions/create-customer-invoice/create-customer-invoice.mjs
  components/pennylane/actions/create-customer/create-customer.mjs
  components/pennylane/common/constants.mjs
  components/pennylane/common/utils.mjs
  components/pennylane/package.json
  components/pennylane/pennylane.app.mjs
  components/pennylane/sources/common/base.mjs
  components/pennylane/sources/new-billing-subscription/new-billing-subscription.mjs
  components/pennylane/sources/new-billing-subscription/test-event.mjs
  components/pennylane/sources/new-customer-invoice/new-customer-invoice.mjs
  components/pennylane/sources/new-customer-invoice/test-event.mjs
  components/pennylane/sources/new-customer/new-customer.mjs
  components/pennylane/sources/new-customer/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14994 New Components - lusha
  components/lusha/actions/company-enrich/company-enrich.mjs
  components/lusha/actions/company-search/company-search.mjs
  components/lusha/actions/contact-enrich/contact-enrich.mjs
  components/lusha/actions/contact-search/contact-search.mjs
  components/lusha/actions/find-company/find-company.mjs
  components/lusha/actions/find-contact/find-contact.mjs
  components/lusha/common/utils.mjs
  components/lusha/lusha.app.mjs
  components/lusha/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#15076 New Components - kenjo
  components/kenjo/actions/create-attendance-entry/create-attendance-entry.mjs
  components/kenjo/actions/create-employee/create-employee.mjs
  components/kenjo/actions/create-leave-request/create-leave-request.mjs
  components/kenjo/kenjo.app.mjs
  components/kenjo/package.json
  components/kenjo/sources/common/base.mjs
  components/kenjo/sources/new-company-created/new-company-created.mjs
  components/kenjo/sources/new-employee-created/new-employee-created.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15013 New Components - boldsign
  components/bluesky/bluesky.app.mjs
  components/boldsign/actions/send-document-template/send-document-template.mjs
  components/boldsign/boldsign.app.mjs
  components/boldsign/common/constants.mjs
  components/boldsign/common/utils.mjs
  components/boldsign/package.json
  components/boldsign/sources/common/base.mjs
  components/boldsign/sources/new-document-completed/new-document-completed.mjs
  components/boldsign/sources/new-document-completed/test-event.mjs
  components/boldsign/sources/new-document-declined/new-document-declined.mjs
  components/boldsign/sources/new-document-declined/test-event.mjs
  components/boldsign/sources/new-document-sent/new-document-sent.mjs
  components/boldsign/sources/new-document-sent/test-event.mjs
  components/breathe/breathe.app.mjs
  components/change_photos/change_photos.app.mjs
  components/kafka/kafka.app.mjs
  components/openrouter/openrouter.app.mjs
  components/quriiri/quriiri.app.mjs
  components/scrapegraphai/scrapegraphai.app.mjs
  components/screenshot_fyi/screenshot_fyi.app.mjs
  components/taleez/taleez.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15106 New Components - scrapegraphai
  components/scrapegraphai/actions/start-local-scraper/start-local-scraper.mjs
  components/scrapegraphai/actions/start-markdownify/start-markdownify.mjs
  components/scrapegraphai/actions/start-smart-scraper/start-smart-scraper.mjs
  components/scrapegraphai/package.json
  components/scrapegraphai/scrapegraphai.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted
