Repository PipedreamHQ/pipedream, pull requests merged in 2024-09, with the labels that each got.

#13803 New Components - deputy
  components/deputy/actions/create-employee/create-employee.mjs
  components/deputy/actions/create-location/create-location.mjs
  components/deputy/actions/start-shift/start-shift.mjs
  components/deputy/deputy.app.mjs
  components/deputy/package.json
  components/deputy/sources/common/base.mjs
  components/deputy/sources/new-colleague-created/new-colleague-created.mjs
  components/deputy/sources/new-colleague-created/test-event.mjs
  components/deputy/sources/new-post-created/new-post-created.mjs
  components/deputy/sources/new-post-created/test-event.mjs
  components/deputy/sources/new-timesheet-saved/new-timesheet-saved.mjs
  components/deputy/sources/new-timesheet-saved/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13799 New Components - page_x
  components/page_x/actions/add-new-lead/add-new-lead.mjs
  components/page_x/package.json
  components/page_x/page_x.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13778 New Components - scrapfly
  components/scrapfly/actions/account-info/account-info.mjs
  components/scrapfly/actions/ai-data-extraction/ai-data-extraction.mjs
  components/scrapfly/actions/scrape-page/scrape-page.mjs
  components/scrapfly/common/constants.mjs
  components/scrapfly/common/utils.mjs
  components/scrapfly/package.json
  components/scrapfly/scrapfly.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13783 New Components - storeganise
  components/storeganise/actions/add-invoice-payment/add-invoice-payment.mjs
  components/storeganise/actions/mark-invoice-paid/mark-invoice-paid.mjs
  components/storeganise/package.json
  components/storeganise/sources/common/base.mjs
  components/storeganise/sources/new-invoice-created/new-invoice-created.mjs
  components/storeganise/sources/new-invoice-created/test-event.mjs
  components/storeganise/sources/new-unit-rental-created/new-unit-rental-created.mjs
  components/storeganise/sources/new-unit-rental-created/test-event.mjs
  components/storeganise/sources/new-user-created/new-user-created.mjs
  components/storeganise/sources/new-user-created/test-event.mjs
  components/storeganise/storeganise.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13867 New Components - krispcall
  components/krispcall/actions/add-contact/add-contact.mjs
  components/krispcall/actions/delete-contact/delete-contact.mjs
  components/krispcall/actions/new-mms/new-mms.mjs
  components/krispcall/actions/new-sms/new-sms.mjs
  components/krispcall/common/utils.mjs
  components/krispcall/krispcall.app.mjs
  components/krispcall/package.json
  components/krispcall/sources/common/base.mjs
  components/krispcall/sources/new-contact-instant/new-contact-instant.mjs
  components/krispcall/sources/new-contact-instant/test-event.mjs
  components/krispcall/sources/new-sms-or-mms-instant/new-sms-or-mms-instant.mjs
  components/krispcall/sources/new-sms-or-mms-instant/test-event.mjs
  components/krispcall/sources/new-voicemail-instant/new-voicemail-instant.mjs
  components/krispcall/sources/new-voicemail-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13883 New Components - agiliron
  components/agiliron/actions/create-contact/create-contact.mjs
  components/agiliron/actions/create-event/create-event.mjs
  components/agiliron/actions/create-lead/create-lead.mjs
  components/agiliron/agiliron.app.mjs
  components/agiliron/common/constants.mjs
  components/agiliron/common/utils.mjs
  components/agiliron/package.json
  components/agiliron/sources/common/base.mjs
  components/agiliron/sources/new-contact-created/new-contact-created.mjs
  components/agiliron/sources/new-contact-created/test-event.mjs
  components/agiliron/sources/new-lead-created/new-lead-created.mjs
  components/agiliron/sources/new-lead-created/test-event.mjs
  components/agiliron/sources/new-task-created/new-task-created.mjs
  components/agiliron/sources/new-task-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13897 New Components - akkio
  components/akkio/actions/make-prediction/make-prediction.mjs
  components/akkio/akkio.app.mjs
  components/akkio/common/utils.mjs
  components/akkio/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#13901 New Components - alerty
  components/alerty/actions/notify-devices/notify-devices.mjs
  components/alerty/alerty.app.mjs
  components/alerty/common/constants.mjs
  components/alerty/common/utils.mjs
  components/alerty/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#13722 refactor: Use Query API for Qdrant
  components/qdrant/actions/search-points/search-points.mjs
  components/qdrant/package.json
  pnpm-lock.yaml
Labels: User submitted

#13929 New Components - jigsawstack
  components/jigsawstack/actions/object-detection/object-detection.mjs
  components/jigsawstack/actions/sentiment-analysis/sentiment-analysis.mjs
  components/jigsawstack/actions/verify-email/verify-email.mjs
  components/jigsawstack/common/utils.mjs
  components/jigsawstack/jigsawstack.app.mjs
  components/jigsawstack/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#13769 New Components - gptzero_detect_ai
  components/gptzero_detect_ai/actions/scan-file/scan-file.mjs
  components/gptzero_detect_ai/actions/scan-text/scan-text.mjs
  components/gptzero_detect_ai/common/utils.mjs
  components/gptzero_detect_ai/gptzero_detect_ai.app.mjs
  components/gptzero_detect_ai/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#13875 New Components - agrello
  components/agrello/actions/get-document/get-document.mjs
  components/agrello/agrello.app.mjs
  components/agrello/common/utils.mjs
  components/agrello/package.json
  components/agrello/sources/common/base.mjs
  components/agrello/sources/new-document/new-document.mjs
  components/agrello/sources/new-document/test-event.mjs
  components/agrello/sources/new-signature-instant/new-signature-instant.mjs
  components/agrello/sources/new-signature-instant/test-event.mjs
  components/agrello/sources/new-signed-document-instant/new-signed-document-instant.mjs
  components/agrello/sources/new-signed-document-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13935 New Components - adhook
  components/adhook/actions/create-calendar-event/create-calendar-event.mjs
  components/adhook/actions/create-update-post/create-update-post.mjs
  components/adhook/adhook.app.mjs
  components/adhook/common/constants.mjs
  components/adhook/common/utils.mjs
  components/adhook/package.json
  components/adhook/sources/common/base.mjs
  components/adhook/sources/new-post/new-post.mjs
  components/adhook/sources/new-post/test-event.mjs
  components/adhook/sources/updated-post/test-event.mjs
  components/adhook/sources/updated-post/updated-post.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13983 Abstract OAuth implementation in the SDK
  packages/sdk/package-lock.json
  packages/sdk/package.json
  packages/sdk/src/server/index.ts
  pnpm-lock.yaml
Labels: enhancement, dependencies, pd-api, javascript, prioritized, strategic-app

#14040 Invoke workflows via the SDK
  packages/sdk/src/server/index.ts
Labels: enhancement, pd-api, javascript, prioritized

#13934 New Components - nioleads
  components/nioleads/actions/find-email/find-email.mjs
  components/nioleads/actions/verify-email/verify-email.mjs
  components/nioleads/nioleads.app.mjs
  components/nioleads/package.json
  components/nioleads/sources/new-contact-added/new-contact-added.mjs
  components/nioleads/sources/new-contact-added/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14064 New Components - offlight
  components/offlight/actions/create-task/create-task.mjs
  components/offlight/offlight.app.mjs
  components/offlight/package.json
  components/offlight/sources/new-task-done-instant/new-task-done-instant.mjs
  components/offlight/sources/new-task-done-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13995 New Components - the_bookie
  components/the_bookie/actions/create-contact/create-contact.mjs
  components/the_bookie/actions/create-sales-invoice/create-sales-invoice.mjs
  components/the_bookie/actions/find-contact/find-contact.mjs
  components/the_bookie/common/constants.mjs
  components/the_bookie/common/utils.mjs
  components/the_bookie/package.json
  components/the_bookie/sources/common/base.mjs
  components/the_bookie/sources/new-contact-created/new-contact-created.mjs
  components/the_bookie/sources/new-contact-created/test-event.mjs
  components/the_bookie/sources/new-invoice-created/new-invoice-created.mjs
  components/the_bookie/sources/new-invoice-created/test-event.mjs
  components/the_bookie/sources/new-invoice-paid/new-invoice-paid.mjs
  components/the_bookie/sources/new-invoice-paid/test-event.mjs
  components/the_bookie/the_bookie.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14082 [Components] Certifier: Add `create-group` action
  components/certifier/actions/create-group/create-group.mjs
  components/certifier/actions/issue-credential/issue-credential.mjs
  components/certifier/certifier.app.mjs
  components/certifier/package.json
Labels: User submitted

#14043 New Components - dust
  components/dust/actions/talk-assistant/talk-assistant.mjs
  components/dust/actions/upsert-document/upsert-document.mjs
  components/dust/common/constants.mjs
  components/dust/dust.app.mjs
  components/dust/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#14078 New Components - talenthr
  components/talenthr/actions/create-employee/create-employee.mjs
  components/talenthr/actions/respond-time-off-request/respond-time-off-request.mjs
  components/talenthr/actions/update-employee/update-employee.mjs
  components/talenthr/common/constants.mjs
  components/talenthr/common/utils.mjs
  components/talenthr/package.json
  components/talenthr/sources/common/base.mjs
  components/talenthr/sources/new-ats-application/new-ats-application.mjs
  components/talenthr/sources/new-ats-application/test-event.mjs
  components/talenthr/sources/new-employee/new-employee.mjs
  components/talenthr/sources/new-employee/test-event.mjs
  components/talenthr/talenthr.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted
