Repository PipedreamHQ/pipedream, pull requests merged in 2024-01, with the labels that each got.

#9500 New Components - scraptio
  components/scraptio/.gitignore
  components/scraptio/actions/scrape-url/scrape-url.mjs
  components/scraptio/app/scraptio.app.ts
  components/scraptio/package.json
  components/scraptio/scraptio.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9477 New Components - digitalriver
  components/digitalriver/.gitignore
  components/digitalriver/actions/cancel-order/cancel-order.mjs
  components/digitalriver/actions/create-product/create-product.mjs
  components/digitalriver/actions/update-customer-information/update-customer-information.mjs
  components/digitalriver/app/digitalriver.app.ts
  components/digitalriver/common/constants.mjs
  components/digitalriver/common/utils.mjs
  components/digitalriver/digitalriver.app.mjs
  components/digitalriver/package.json
  components/digitalriver/sources/common/base.mjs
  components/digitalriver/sources/new-order-completed/new-order-completed.mjs
  components/digitalriver/sources/new-order-completed/test-event.mjs
  components/digitalriver/sources/new-payment-status-updated/new-payment-status-updated.mjs
  components/digitalriver/sources/new-payment-status-updated/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9691 Use different request parameters when using a shared drive
  components/google_drive/package.json
  components/google_drive/sources/changes-to-specific-files-shared-drive/changes-to-specific-files-shared-drive.mjs
  components/google_drive/sources/changes-to-specific-files/changes-to-specific-files.mjs
  components/google_drive/sources/common-webhook.mjs
  components/google_drive/sources/new-files-instant/new-files-instant.mjs
  components/google_drive/sources/new-or-modified-comments/new-or-modified-comments.mjs
  components/google_drive/sources/new-or-modified-files/new-or-modified-files.mjs
  components/google_drive/sources/new-or-modified-folders/new-or-modified-folders.mjs
  components/google_drive/sources/new-spreadsheet/new-spreadsheet.mjs
  pnpm-lock.yaml
Labels: triaged

#9623 New Components - diabatix_coldstream
  components/diabatix_coldstream/.gitignore
  components/diabatix_coldstream/actions/fetch-simulation-results/fetch-simulation-results.mjs
  components/diabatix_coldstream/actions/run-simulation/run-simulation.mjs
  components/diabatix_coldstream/actions/update-project/update-project.mjs
  components/diabatix_coldstream/app/diabatix_coldstream.app.ts
  components/diabatix_coldstream/diabatix_coldstream.app.mjs
  components/diabatix_coldstream/package.json
  components/diabatix_coldstream/sources/project-upgraded/project-upgraded.mjs
  components/diabatix_coldstream/sources/project-upgraded/test-event.mjs
  components/diabatix_coldstream/sources/simulation-completed/simulation-completed.mjs
  components/diabatix_coldstream/sources/simulation-completed/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9574 [ACTION][Google Drive] Replace file from id
  components/google_drive/actions/upload-file/upload-file.mjs
  components/google_drive/package.json
Labels: triaged, User submitted

#9470 New Components - onepagecrm
  components/onepagecrm/.gitignore
  components/onepagecrm/actions/create-contact/create-contact.mjs
  components/onepagecrm/actions/delete-contact/delete-contact.mjs
  components/onepagecrm/actions/update-deal/update-deal.mjs
  components/onepagecrm/app/onepagecrm.app.ts
  components/onepagecrm/common/constants.mjs
  components/onepagecrm/common/utils.mjs
  components/onepagecrm/onepagecrm.app.mjs
  components/onepagecrm/package.json
  components/onepagecrm/sources/common/base.mjs
  components/onepagecrm/sources/new-contact-created/new-contact-created.mjs
  components/onepagecrm/sources/new-contact-created/test-event.mjs
  components/onepagecrm/sources/new-deal-closed/new-deal-closed.mjs
  components/onepagecrm/sources/new-deal-closed/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9793 Google Sheets npm module: add google_drive dependency
  components/google_sheets/package.json
  pnpm-lock.yaml
Labels: triaged, User submitted

#9430 add support for markdown description in clickup create task action
  components/clickup/actions/create-task/create-task.mjs
  components/clickup/package.json
Labels: triaged, User submitted

#9730 Telegram new api 7.0 preview options
  components/telegram_bot_api/actions/create-chat-invite-link/create-chat-invite-link.mjs
  components/telegram_bot_api/actions/delete-message/delete-message.mjs
  components/telegram_bot_api/actions/edit-media-message/edit-media-message.mjs
  components/telegram_bot_api/actions/edit-text-message/edit-text-message.mjs
  components/telegram_bot_api/actions/export-chat-invite-link/export-chat-invite-link.mjs
  components/telegram_bot_api/actions/forward-message/forward-message.mjs
  components/telegram_bot_api/actions/get-num-members-in-chat/get-num-members-in-chat.mjs
  components/telegram_bot_api/actions/kick-chat-member/kick-chat-member.mjs
  components/telegram_bot_api/actions/list-administrators-in-chat/list-administrators-in-chat.mjs
  components/telegram_bot_api/actions/list-chats/list-chats.mjs
  components/telegram_bot_api/actions/list-updates/list-updates.mjs
  components/telegram_bot_api/actions/pin-message/pin-message.mjs
  components/telegram_bot_api/actions/promote-chat-member/promote-chat-member.mjs
  components/telegram_bot_api/actions/restrict-chat-member/restrict-chat-member.mjs
  components/telegram_bot_api/actions/send-album/send-album.mjs
  components/telegram_bot_api/actions/send-audio-file/send-audio-file.mjs
  components/telegram_bot_api/actions/send-document-or-image/send-document-or-image.mjs
  components/telegram_bot_api/actions/send-media-by-url-or-id/send-media-by-url-or-id.mjs
  components/telegram_bot_api/actions/send-photo/send-photo.mjs
  components/telegram_bot_api/actions/send-sticker/send-sticker.mjs
  components/telegram_bot_api/actions/send-text-message-or-reply/send-text-message-or-reply.mjs
  components/telegram_bot_api/actions/send-video-note/send-video-note.mjs
  components/telegram_bot_api/actions/send-video/send-video.mjs
  components/telegram_bot_api/actions/send-voice-message/send-voice-message.mjs
  components/telegram_bot_api/actions/set-chat-permissions/set-chat-permissions.mjs
  components/telegram_bot_api/actions/unpin-message/unpin-message.mjs
  components/telegram_bot_api/package.json
  components/telegram_bot_api/sources/channel-updates/channel-updates.mjs
  components/telegram_bot_api/sources/message-updates/message-updates.mjs
  components/telegram_bot_api/sources/new-bot-command-received/new-bot-command-received.mjs
  components/telegram_bot_api/sources/new-updates/new-updates.mjs
  components/telegram_bot_api/telegram_bot_api.app.mjs
  package-lock.json
Labels: triaged, User submitted

#9800 Including common file exception in key check
  pnpm-lock.yaml
  scripts/findBadKeys.js
Labels: triaged

#9802 Adjusting 'duplicate keys' script
  scripts/findDuplicateKeys.js
Labels: triaged

#9679 New Components - gleap
  components/gleap/actions/create-track-event/create-track-event.mjs
  components/gleap/common/constants.mjs
  components/gleap/gleap.app.mjs
  components/gleap/package.json
  components/gleap/sources/common/base.mjs
  components/gleap/sources/new-feedback-created/new-feedback-created.mjs
  components/gleap/sources/new-feedback-created/test-event.mjs
  components/gleap/sources/new-feedback-updated/new-feedback-updated.mjs
  components/gleap/sources/new-feedback-updated/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9773 New Components - omise
  components/omise/.gitignore
  components/omise/actions/create-charge/create-charge.mjs
  components/omise/actions/create-customer/create-customer.mjs
  components/omise/actions/update-customer/update-customer.mjs
  components/omise/app/omise.app.ts
  components/omise/common/constants.mjs
  components/omise/common/utils.mjs
  components/omise/omise.app.mjs
  components/omise/package.json
  components/omise/sources/charge-refunded/charge-refunded.mjs
  components/omise/sources/charge-refunded/test-event.mjs
  components/omise/sources/common/base.mjs
  components/omise/sources/payment-received/payment-received.mjs
  components/omise/sources/payment-received/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9789 New Components - ezeep_blue
  components/ezeep_blue/.gitignore
  components/ezeep_blue/actions/create-print-job/create-print-job.mjs
  components/ezeep_blue/actions/get-print-job-status/get-print-job-status.mjs
  components/ezeep_blue/actions/list-printers/list-printers.mjs
  components/ezeep_blue/app/ezeep_blue.app.ts
  components/ezeep_blue/common/constants.mjs
  components/ezeep_blue/common/utils.mjs
  components/ezeep_blue/ezeep_blue.app.mjs
  components/ezeep_blue/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#9692 New Components - imagga
  components/imagga/.gitignore
  components/imagga/actions/analyze-image/analyze-image.mjs
  components/imagga/actions/process-batch/process-batch.mjs
  components/imagga/app/imagga.app.ts
  components/imagga/common/constants.mjs
  components/imagga/common/utils.mjs
  components/imagga/imagga.app.mjs
  components/imagga/package.json
  components/imagga/sources/new-batch-processed/new-batch-processed.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9831 Fix GSheets Upsert Row hidden sheet cleanup
  components/google_sheets/actions/upsert-row/upsert-row.mjs
  components/google_sheets/package.json
Labels: triaged

#9821 New Components - klenty
  components/klenty/.gitignore
  components/klenty/actions/add-prospect/add-prospect.mjs
  components/klenty/actions/start-cadence/start-cadence.mjs
  components/klenty/actions/update-prospect/update-prospect.mjs
  components/klenty/app/klenty.app.ts
  components/klenty/common/constants.mjs
  components/klenty/klenty.app.mjs
  components/klenty/package.json
  components/klenty/sources/cadence-started/cadence-started.mjs
  components/klenty/sources/cadence-started/test-event.mjs
  components/klenty/sources/common/base.mjs
  components/klenty/sources/email-bounced/email-bounced.mjs
  components/klenty/sources/email-bounced/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9835 New Components - intellihr
  components/intellihr/actions/create-person/create-person.mjs
  components/intellihr/actions/find-person/find-person.mjs
  components/intellihr/actions/update-person/update-person.mjs
  components/intellihr/common/constants.mjs
  components/intellihr/common/utils.mjs
  components/intellihr/intellihr.app.mjs
  components/intellihr/package.json
  components/intellihr/sources/common/base.mjs
  components/intellihr/sources/new-job-instant/new-job-instant.mjs
  components/intellihr/sources/new-job-instant/test-event.mjs
  components/intellihr/sources/new-person-instant/new-person-instant.mjs
  components/intellihr/sources/new-person-instant/test-event.mjs
  components/intellihr/sources/new-training-instant/new-training-instant.mjs
  components/intellihr/sources/new-training-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9868 New Components - stannp
  components/stannp/.gitignore
  components/stannp/actions/create-campaign/create-campaign.mjs
  components/stannp/actions/create-recipient/create-recipient.mjs
  components/stannp/actions/get-campaign/get-campaign.mjs
  components/stannp/app/stannp.app.ts
  components/stannp/common/constants.mjs
  components/stannp/common/utils.mjs
  components/stannp/package.json
  components/stannp/sources/common/base.mjs
  components/stannp/sources/new-campaign-created/new-campaign-created.mjs
  components/stannp/sources/new-recipient-created/new-recipient-created.mjs
  components/stannp/stannp.app.mjs
  components/stannp/yarn.lock
  pnpm-lock.yaml
Labels: ai-assisted

#9867 New Components - workamajig
  components/workamajig/actions/create-activity/create-activity.mjs
  components/workamajig/actions/create-company/create-company.mjs
  components/workamajig/actions/update-contact/update-contact.mjs
  components/workamajig/common/constants.mjs
  components/workamajig/common/utils.mjs
  components/workamajig/package.json
  components/workamajig/sources/common/base-polling.mjs
  components/workamajig/sources/new-activity/new-activity.mjs
  components/workamajig/sources/new-activity/test-event.mjs
  components/workamajig/sources/new-company/new-company.mjs
  components/workamajig/sources/new-company/test-event.mjs
  components/workamajig/sources/updated-opportunity/test-event.mjs
  components/workamajig/sources/updated-opportunity/updated-opportunity.mjs
  components/workamajig/workamajig.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9923 New Components - surveycto
  components/surveycto/package.json
  components/surveycto/sources/new-submission/new-submission.mjs
  components/surveycto/sources/new-submission/test-event.mjs
  components/surveycto/surveycto.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9879 [Components] renderform #9844
  components/renderform/actions/create-image/create-image.mjs
  components/renderform/actions/list-templates/list-templates.mjs
  components/renderform/actions/take-screenshot/take-screenshot.mjs
  components/renderform/package.json
  components/renderform/renderform.app.mjs
  components/renderform/sources/new-render-result/new-render-result.mjs
Labels: action, trigger / source

#9971 [Components] airslate #9480
  components/airslate/actions/create-new-organization/create-new-organization.mjs
  components/airslate/actions/create-new-template/create-new-template.mjs
  components/airslate/actions/update-template/update-template.mjs
  components/airslate/airslate.app.mjs
  components/airslate/common/constants.mjs
  components/airslate/package.json
  pnpm-lock.yaml
Labels: action

#9922 New Components - google_ads
  components/dailybot/dailybot.app.mjs
  components/google_ads/.gitignore
  components/google_ads/actions/add-contact-to-list-by-email/add-contact-to-list-by-email.mjs
  components/google_ads/app/google_ads.app.ts
  components/google_ads/google_ads.app.mjs
  components/google_ads/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#9727 New Components - referrizer
  components/referrizer/.gitignore
  components/referrizer/actions/common/base.mjs
  components/referrizer/actions/create-loyalty-reward/create-loyalty-reward.mjs
  components/referrizer/actions/create-visit/create-visit.mjs
  components/referrizer/actions/update-loyalty-reward/update-loyalty-reward.mjs
  components/referrizer/app/referrizer.app.ts
  components/referrizer/package.json
  components/referrizer/referrizer.app.mjs
  components/referrizer/sources/common/base.mjs
  components/referrizer/sources/new-loyalty-reward-created/new-loyalty-reward-created.mjs
  components/referrizer/sources/new-loyalty-reward-created/test-event.mjs
  components/referrizer/sources/new-loyalty-reward-redeemed/new-loyalty-reward-redeemed.mjs
  components/referrizer/sources/new-loyalty-reward-redeemed/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10008 New Components - timebuzzer
  components/timebuzzer/actions/create-activity/create-activity.mjs
  components/timebuzzer/actions/list-activities/list-activities.mjs
  components/timebuzzer/actions/update-activity/update-activity.mjs
  components/timebuzzer/common/constants.mjs
  components/timebuzzer/package.json
  components/timebuzzer/sources/new-activity-instant/new-activity-instant.mjs
  components/timebuzzer/sources/new-activity-instant/test-event.mjs
  components/timebuzzer/timebuzzer.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#9927 New Components - waiverfile
  components/airparser/airparser.app.mjs
  components/airslate/actions/create-new-organization/create-new-organization.mjs
  components/airslate/actions/create-new-template/create-new-template.mjs
  components/airslate/actions/update-template/update-template.mjs
  components/airslate/common/constants.mjs
  components/airslate/package.json
  components/autom/autom.app.mjs
  components/cody/cody.app.mjs
  components/cufinder/cufinder.app.mjs
  components/cults/cults.app.mjs
  components/deel/deel.app.mjs
  components/expedy/expedy.app.mjs
  components/findymail/findymail.app.mjs
  components/publisherkit/publisherkit.app.mjs
  components/retailed/retailed.app.mjs
  components/uberduck/uberduck.app.mjs
  components/waiverfile/actions/create-event-category/create-event-category.mjs
  components/waiverfile/actions/search-waivers/search-waivers.mjs
  components/waiverfile/actions/update-event/update-event.mjs
  components/waiverfile/package.json
  components/waiverfile/sources/common/base-webhook.mjs
  components/waiverfile/sources/edit-event-instant/edit-event-instant.mjs
  components/waiverfile/sources/edit-event-instant/test-event.mjs
  components/waiverfile/sources/new-event-instant/new-event-instant.mjs
  components/waiverfile/sources/new-event-instant/test-event.mjs
  components/waiverfile/sources/new-waiver-instant/new-waiver-instant.mjs
  components/waiverfile/sources/new-waiver-instant/test-event.mjs
  components/waiverfile/waiverfile.app.mjs
  components/white_swan/white_swan.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10011 New Components - fireberry
  components/fireberry/actions/create-account/create-account.mjs
  components/fireberry/actions/create-article/create-article.mjs
  components/fireberry/actions/list-accounts/list-accounts.mjs
  components/fireberry/actions/list-articles/list-articles.mjs
  components/fireberry/fireberry.app.mjs
  components/fireberry/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10003 [Components] frontegg #9485
  components/frontegg/actions/create-template/create-template.mjs
  components/frontegg/common/constants.mjs
  components/frontegg/frontegg.app.mjs
  components/frontegg/package.json
  pnpm-lock.yaml
Labels: action

#9999 [Components] northflank #9455
  components/northflank/actions/create-domain/create-domain.mjs
  components/northflank/actions/create-project/create-project.mjs
  components/northflank/actions/get-domains/get-domains.mjs
  components/northflank/actions/get-projects/get-projects.mjs
  components/northflank/common/constants.mjs
  components/northflank/northflank.app.mjs
  components/northflank/package.json
  pnpm-lock.yaml
Labels: action

#10084 New Components - cufinder
  components/cufinder/actions/find-company-email/find-company-email.mjs
  components/cufinder/actions/find-company-phone/find-company-phone.mjs
  components/cufinder/actions/find-company-website/find-company-website.mjs
  components/cufinder/cufinder.app.mjs
  components/cufinder/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10050 New Components - findymail
  components/findymail/actions/create-list/create-list.mjs
  components/findymail/actions/delete-list/delete-list.mjs
  components/findymail/actions/list-contact-lists/list-contact-lists.mjs
  components/findymail/findymail.app.mjs
  components/findymail/package.json
  pnpm-lock.yaml
Labels: action, ai-assisted

#10083 New Components - retailed
  components/retailed/actions/get-usage/get-usage.mjs
  components/retailed/package.json
  components/retailed/retailed.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10014 New Components - proabono
  components/proabono/actions/create-customer/create-customer.mjs
  components/proabono/actions/create-subscription/create-subscription.mjs
  components/proabono/actions/retrieve-customer/retrieve-customer.mjs
  components/proabono/common/constants.mjs
  components/proabono/package.json
  components/proabono/proabono.app.mjs
  components/proabono/sources/common/base-polling.mjs
  components/proabono/sources/new-customer-created/new-customer-created.mjs
  components/proabono/sources/new-customer-created/test-event.mjs
  components/proabono/sources/new-offer-created/new-offer-created.mjs
  components/proabono/sources/new-offer-created/test-event.mjs
  components/proabono/sources/new-subscription-created/new-subscription-created.mjs
  components/proabono/sources/new-subscription-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted
