Repository PipedreamHQ/pipedream, pull requests merged in 2024-11, with the labels that each got.

#14481 New Components - checkvist
  components/checkvist/actions/create-list-item/create-list-item.mjs
  components/checkvist/actions/create-multiple-list-items/create-multiple-list-items.mjs
  components/checkvist/actions/create-new-list/create-new-list.mjs
  components/checkvist/checkvist.app.mjs
  components/checkvist/common/constants.mjs
  components/checkvist/common/utils.mjs
  components/checkvist/package.json
  components/checkvist/sources/common/base.mjs
  components/checkvist/sources/new-list-item/new-list-item.mjs
  components/checkvist/sources/new-list-item/test-event.mjs
  components/checkvist/sources/new-list/new-list.mjs
  components/checkvist/sources/new-list/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14504 [FIX] Columns AI - Fixed error when published the components
  components/columns_ai/package.json
Labels: bug

#14499 New Components - tldr
  components/tldr/actions/summarize-text/summarize-text.mjs
  components/tldr/package.json
  components/tldr/tldr.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14447 New Components - crowdin
  components/crowdin/.gitignore
  components/crowdin/actions/add-file/add-file.mjs
  components/crowdin/actions/create-project/create-project.mjs
  components/crowdin/actions/translate-via-machine-translation/translate-via-machine-translation.mjs
  components/crowdin/app/crowdin.app.ts
  components/crowdin/common/constants.mjs
  components/crowdin/common/utils.mjs
  components/crowdin/crowdin.app.mjs
  components/crowdin/package.json
  components/crowdin/sources/common/base-instant.mjs
  components/crowdin/sources/common/base.mjs
  components/crowdin/sources/file-approved-instant/file-approved-instant.mjs
  components/crowdin/sources/file-approved-instant/test-event.mjs
  components/crowdin/sources/new-comment-issue-instant/new-comment-issue-instant.mjs
  components/crowdin/sources/new-comment-issue-instant/test-event.mjs
  components/crowdin/sources/new-directory/new-directory.mjs
  components/crowdin/sources/new-directory/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14552 New Components - flexisign
  components/flexisign/actions/send-document-using-template/send-document-using-template.mjs
  components/flexisign/common/utils.mjs
  components/flexisign/flexisign.app.mjs
  components/flexisign/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#14505 New Components - openphone
  components/openphone/actions/create-contact/create-contact.mjs
  components/openphone/actions/send-message/send-message.mjs
  components/openphone/actions/update-contact/update-contact.mjs
  components/openphone/common/utils.mjs
  components/openphone/openphone.app.mjs
  components/openphone/package.json
  components/openphone/sources/common/base.mjs
  components/openphone/sources/new-call-recording-completed-instant/new-call-recording-completed-instant.mjs
  components/openphone/sources/new-call-recording-completed-instant/test-event.mjs
  components/openphone/sources/new-incoming-call-completed-instant/new-incoming-call-completed-instant.mjs
  components/openphone/sources/new-incoming-call-completed-instant/test-event.mjs
  components/openphone/sources/new-outgoing-call-completed-instant/new-outgoing-call-completed-instant.mjs
  components/openphone/sources/new-outgoing-call-completed-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14594 Docs - broken links in docs/components
  docs-v2/pages/components/index.mdx
Labels: User submitted

#14625 [Action] Spotify - Get currently playing track
  components/spotify/actions/get-currently-playing-track/get-currently-playing-track.mjs
  components/spotify/package.json
  pnpm-lock.yaml
Labels: User submitted

#14629 New Components - skyvern
  components/skyvern/actions/create-run-task/create-run-task.mjs
  components/skyvern/actions/get-workflow/get-workflow.mjs
  components/skyvern/actions/run-workflow/run-workflow.mjs
  components/skyvern/common/utils.mjs
  components/skyvern/package.json
  components/skyvern/skyvern.app.mjs
  components/skyvern/sources/new-or-updated-workflow/new-or-updated-workflow.mjs
  components/skyvern/sources/new-or-updated-workflow/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14577 New Components - ignisign
  components/ignisign/actions/create-signature-request/create-signature-request.mjs
  components/ignisign/actions/create-signer/create-signer.mjs
  components/ignisign/actions/get-signature-proof/get-signature-proof.mjs
  components/ignisign/common/constants.mjs
  components/ignisign/common/utils.mjs
  components/ignisign/ignisign.app.mjs
  components/ignisign/package.json
  components/ignisign/sources/new-signature-proof-instant/new-signature-proof-instant.mjs
  components/ignisign/sources/new-signature-proof-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14617 New Components - help_scout
  components/help_scout/actions/add-note/add-note.mjs
  components/help_scout/actions/create-customer/create-customer.mjs
  components/help_scout/actions/send-reply/send-reply.mjs
  components/help_scout/common/constants.mjs
  components/help_scout/common/utils.mjs
  components/help_scout/help_scout.app.mjs
  components/help_scout/package.json
  components/help_scout/sources/common/base.mjs
  components/help_scout/sources/new-conversation-assigned-instant/new-conversation-assigned-instant.mjs
  components/help_scout/sources/new-conversation-assigned-instant/test-event.mjs
  components/help_scout/sources/new-conversation-created-instant/new-conversation-created-instant.mjs
  components/help_scout/sources/new-conversation-created-instant/test-event.mjs
  components/help_scout/sources/new-customer-instant/new-customer-instant.mjs
  components/help_scout/sources/new-customer-instant/test-event.mjs
  components/help_scout/yarn.lock
  pnpm-lock.yaml
Labels: ai-assisted

#14633 New Components - zoho-sheet
  components/zoho_sheet/.gitignore
  components/zoho_sheet/actions/create-row/create-row.mjs
  components/zoho_sheet/actions/search-delete-row/search-delete-row.mjs
  components/zoho_sheet/actions/update-row/update-row.mjs
  components/zoho_sheet/app/zoho_sheet.app.ts
  components/zoho_sheet/common/utils.mjs
  components/zoho_sheet/package.json
  components/zoho_sheet/sources/common/base.mjs
  components/zoho_sheet/sources/new-or-updated-row-instant/new-or-updated-row-instant.mjs
  components/zoho_sheet/sources/new-or-updated-row-instant/test-event.mjs
  components/zoho_sheet/sources/new-row-instant/new-row-instant.mjs
  components/zoho_sheet/sources/new-row-instant/test-event.mjs
  components/zoho_sheet/sources/new-workbook-instant/new-workbook-instant.mjs
  components/zoho_sheet/sources/new-workbook-instant/test-event.mjs
  components/zoho_sheet/zoho_sheet.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14642 Backend request improvements
  packages/sdk/CHANGELOG.md
  packages/sdk/package-lock.json
  packages/sdk/package.json
  packages/sdk/src/server/index.ts
Labels: enhancement, pd-api, javascript, tracked internally, prioritized

#14643 Update Github new star reference
  components/github/README.md
Labels: User submitted

#14657 Retrieve credentials for a single account
  packages/sdk/CHANGELOG.md
  packages/sdk/package-lock.json
  packages/sdk/package.json
  packages/sdk/src/server/__tests__/server.test.ts
  packages/sdk/src/server/index.ts
Labels: bug, javascript, tracked internally

#14663 Fix broken export
  packages/sdk/CHANGELOG.md
  packages/sdk/package-lock.json
  packages/sdk/package.json
  packages/sdk/src/server/index.ts
Labels: bug, javascript, tracked internally

#14690 [FEATURE] New prop to Gong action
  components/gong/actions/add-new-call/add-new-call.mjs
  components/gong/actions/list-calls/list-calls.mjs
  components/gong/actions/retrieve-transcripts-of-calls/retrieve-transcripts-of-calls.mjs
  components/gong/gong.app.mjs
  components/gong/package.json
  components/gong/sources/new-call/new-call.mjs
  pnpm-lock.yaml
Labels: action

#14656 New Components - cats
  components/cats/actions/add-candidate-pipeline/add-candidate-pipeline.mjs
  components/cats/actions/create-candidate/create-candidate.mjs
  components/cats/actions/create-contact/create-contact.mjs
  components/cats/cats.app.mjs
  components/cats/common/utils.mjs
  components/cats/package.json
  components/cats/sources/common/base.mjs
  components/cats/sources/new-activity-instant/new-activity-instant.mjs
  components/cats/sources/new-activity-instant/test-event.mjs
  components/cats/sources/new-candidate-instant/new-candidate-instant.mjs
  components/cats/sources/new-candidate-instant/test-event.mjs
  components/cats/sources/new-contact-instant/new-contact-instant.mjs
  components/cats/sources/new-contact-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted
