Repository PipedreamHQ/pipedream, pull requests merged in 2024-05, with the labels that each got.

#11706 Publish Platform Types
  platform/.gitignore
  platform/dist/axios.d.ts
  platform/dist/constants.d.ts
  platform/dist/errors.d.ts
  platform/dist/index.d.ts
  platform/dist/sql-prop.d.ts
  platform/dist/sql-proxy.d.ts
  platform/dist/utils.d.ts
  platform/lib/sql-prop.ts
  platform/package.json
Labels: tracked internally, prioritized, strategic-app

#11619 New Components - infobip
  components/infobip/actions/send-sms/send-sms.mjs
  components/infobip/actions/send-viber-text-message/send-viber-text-message.mjs
  components/infobip/actions/send-whatsapp-text-message/send-whatsapp-text-message.mjs
  components/infobip/common/constants.mjs
  components/infobip/infobip.app.mjs
  components/infobip/package.json
  components/infobip/sources/common/base.mjs
  components/infobip/sources/new-sms-message-instant/new-sms-message-instant.mjs
  components/infobip/sources/new-sms-message-instant/test-event.mjs
  components/infobip/sources/new-whatsapp-message-instant/new-whatsapp-message-instant.mjs
  components/infobip/sources/new-whatsapp-message-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11698 Google postmaster improvement
  components/google_postmaster_tools_api/google_postmaster_tools_api.app.mjs
  components/google_postmaster_tools_api/package.json
  components/google_postmaster_tools_api/sources/new-matched-traffic-stats/new-matched-traffic-stats.mjs
Labels: triaged

#11697 New Components - reishost
  components/reishost/actions/send-console-command/send-console-command.mjs
  components/reishost/package.json
  components/reishost/reishost.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11675 New Components - sare
  components/sare/actions/add-email/add-email.mjs
  components/sare/actions/remove-from-group/remove-from-group.mjs
  components/sare/actions/send-email/send-email.mjs
  components/sare/common/utils.mjs
  components/sare/package.json
  components/sare/sare.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11786 New Components - flipando
  components/flipando/actions/get-all-apps/get-all-apps.mjs
  components/flipando/actions/get-task/get-task.mjs
  components/flipando/actions/run-app/run-app.mjs
  components/flipando/flipando.app.mjs
  components/flipando/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11628 New Components - vryno
  components/vryno/actions/create-unique-lead/create-unique-lead.mjs
  components/vryno/package.json
  components/vryno/vryno.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11802 New Components - orimon
  components/orimon/actions/send-message/send-message.mjs
  components/orimon/orimon.app.mjs
  components/orimon/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11403 New Components - tripadvisor_content_api
  components/tripadvisor_content_api/actions/location-details/location-details.mjs
  components/tripadvisor_content_api/actions/location-reviews/location-reviews.mjs
  components/tripadvisor_content_api/actions/location-search/location-search.mjs
  components/tripadvisor_content_api/package.json
  components/tripadvisor_content_api/tripadvisor_content_api.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11652 Google Drive Triggers text/usability improvements
  components/google_drive/actions/add-file-sharing-preference/add-file-sharing-preference.mjs
  components/google_drive/actions/copy-file/copy-file.mjs
  components/google_drive/actions/create-file-from-template/create-file-from-template.mjs
  components/google_drive/actions/create-file-from-text/create-file-from-text.mjs
  components/google_drive/actions/create-file/create-file.mjs
  components/google_drive/actions/create-folder/create-folder.mjs
  components/google_drive/actions/create-shared-drive/create-shared-drive.mjs
  components/google_drive/actions/delete-file/delete-file.mjs
  components/google_drive/actions/delete-shared-drive/delete-shared-drive.mjs
  components/google_drive/actions/download-file/download-file.mjs
  components/google_drive/actions/find-file/find-file.mjs
  components/google_drive/actions/find-folder/find-folder.mjs
  components/google_drive/actions/find-forms/find-forms.mjs
  components/google_drive/actions/find-spreadsheets/find-spreadsheets.mjs
  components/google_drive/actions/get-folder-id-for-path/get-folder-id-for-path.mjs
  components/google_drive/actions/get-shared-drive/get-shared-drive.mjs
  components/google_drive/actions/list-files/list-files.mjs
  components/google_drive/actions/move-file-to-trash/move-file-to-trash.mjs
  components/google_drive/actions/move-file/move-file.mjs
  components/google_drive/actions/replace-file/replace-file.mjs
  components/google_drive/actions/search-shared-drives/search-shared-drives.mjs
  components/google_drive/actions/update-file/update-file.mjs
  components/google_drive/actions/update-shared-drive/update-shared-drive.mjs
  components/google_drive/actions/upload-file/upload-file.mjs
  components/google_drive/common/constants.mjs
  components/google_drive/common/utils.mjs
  components/google_drive/google_drive.app.mjs
  components/google_drive/package.json
  components/google_drive/sources/changes-to-specific-files-shared-drive/changes-to-specific-files-shared-drive.mjs
  components/google_drive/sources/changes-to-specific-files/changes-to-specific-files.mjs
  components/google_drive/sources/common-dedupe-changes.mjs
  components/google_drive/sources/common-webhook.mjs
  components/google_drive/sources/new-files-instant/new-files-instant.mjs
  components/google_drive/sources/new-or-modified-comments/new-or-modified-comments.mjs
  components/google_drive/sources/new-or-modified-files/new-or-modified-files.mjs
  components/google_drive/sources/new-or-modified-folders/new-or-modified-folders.mjs
  components/google_drive/sources/new-shared-drive/new-shared-drive.mjs
  components/google_drive/sources/new-spreadsheet/new-spreadsheet.mjs
  components/google_slides/package.json
  components/google_slides/sources/new-presentation/new-presentation.mjs
Labels: triaged

#11840 New Components - bilflo
  components/bilflo/actions/assign-contract-job-to-invoice/assign-contract-job-to-invoice.mjs
  components/bilflo/actions/create-client/create-client.mjs
  components/bilflo/actions/create-contract-job/create-contract-job.mjs
  components/bilflo/bilflo.app.mjs
  components/bilflo/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11830 New Components - cradl_ai
  components/cradl_ai/actions/common/common.mjs
  components/cradl_ai/actions/parse-document-human-in-loop/parse-document-human-in-loop.mjs
  components/cradl_ai/actions/parse-document/parse-document.mjs
  components/cradl_ai/common/constants.mjs
  components/cradl_ai/cradl_ai.app.mjs
  components/cradl_ai/package.json
  components/cradl_ai/sources/new-document-parsing-completed-instant/new-document-parsing-completed-instant.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11846 ESLint PR check improvement
  .eslintignore
  .github/workflows/pull-request-checks.yaml
Labels: triaged

#11813 New Components - timetonic
  components/timetonic/actions/common/create-update-row.mjs
  components/timetonic/actions/create-row/create-row.mjs
  components/timetonic/actions/delete-row/delete-row.mjs
  components/timetonic/actions/search-rows/search-rows.mjs
  components/timetonic/actions/update-row/update-row.mjs
  components/timetonic/common/constants.mjs
  components/timetonic/package.json
  components/timetonic/sources/common/base.mjs
  components/timetonic/sources/new-table-row-in-view/new-table-row-in-view.mjs
  components/timetonic/sources/new-table-row/new-table-row.mjs
  components/timetonic/sources/row-deleted/row-deleted.mjs
  components/timetonic/sources/row-updated/row-updated.mjs
  components/timetonic/timetonic.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11711 Google Sheet Sources/Triggers Improvements
  components/google_sheets/actions/add-multiple-rows/add-multiple-rows.mjs
  components/google_sheets/actions/add-single-row/add-single-row.mjs
  components/google_sheets/actions/clear-cell/clear-cell.mjs
  components/google_sheets/actions/clear-row/clear-row.mjs
  components/google_sheets/actions/copy-worksheet/copy-worksheet.mjs
  components/google_sheets/actions/create-column/create-column.mjs
  components/google_sheets/actions/create-spreadsheet/create-spreadsheet.mjs
  components/google_sheets/actions/create-worksheet/create-worksheet.mjs
  components/google_sheets/actions/delete-row/delete-row.mjs
  components/google_sheets/actions/delete-rows/delete-rows.mjs
  components/google_sheets/actions/delete-worksheet/delete-worksheet.mjs
  components/google_sheets/actions/find-row-vlookup/find-row-vlookup.mjs
  components/google_sheets/actions/find-row/find-row.mjs
  components/google_sheets/actions/get-cell/get-cell.mjs
  components/google_sheets/actions/get-spreadsheet-by-id/get-spreadsheet-by-id.mjs
  components/google_sheets/actions/get-values-in-range/get-values-in-range.mjs
  components/google_sheets/actions/get-values/get-values.mjs
  components/google_sheets/actions/insert-anchored-note/insert-anchored-note.mjs
  components/google_sheets/actions/insert-comment/insert-comment.mjs
  components/google_sheets/actions/list-worksheets/list-worksheets.mjs
  components/google_sheets/actions/update-cell/update-cell.mjs
  components/google_sheets/actions/update-row/update-row.mjs
  components/google_sheets/actions/update-rows/update-rows.mjs
  components/google_sheets/actions/upsert-row/upsert-row.mjs
  components/google_sheets/common/constants.mjs
  components/google_sheets/google_sheets.app.mjs
  components/google_sheets/package.json
  components/google_sheets/sources/common/http-based/base.mjs
  components/google_sheets/sources/common/new-row-added.mjs
  components/google_sheets/sources/common/new-updates.mjs
  components/google_sheets/sources/new-comment/new-comment.mjs
  components/google_sheets/sources/new-comment/test-event.mjs
  components/google_sheets/sources/new-row-added-shared-drive/new-row-added-shared-drive.mjs
  components/google_sheets/sources/new-row-added-shared-drive/test-event.mjs
  components/google_sheets/sources/new-row-added/new-row-added.mjs
  components/google_sheets/sources/new-row-added/test-event.mjs
  components/google_sheets/sources/new-updates-shared-drive/new-updates-shared-drive.mjs
  components/google_sheets/sources/new-updates-shared-drive/test-event.mjs
  components/google_sheets/sources/new-updates/new-updates.mjs
  components/google_sheets/sources/new-worksheet-shared-drive/new-worksheet-shared-drive.mjs
  components/google_sheets/sources/new-worksheet/new-worksheet.mjs
  components/google_sheets/sources/new-worksheet/test-event.mjs
Labels: triaged

#11782 Google Sheets Actions Improvements
  components/google_sheets/actions/add-column/add-column.mjs
  components/google_sheets/actions/add-multiple-rows/add-multiple-rows.mjs
  components/google_sheets/actions/add-single-row/add-single-row.mjs
  components/google_sheets/actions/clear-cell/clear-cell.mjs
  components/google_sheets/actions/clear-rows/clear-rows.mjs
  components/google_sheets/actions/copy-worksheet/copy-worksheet.mjs
  components/google_sheets/actions/create-spreadsheet/create-spreadsheet.mjs
  components/google_sheets/actions/create-worksheet/create-worksheet.mjs
  components/google_sheets/actions/delete-row/delete-row.mjs
  components/google_sheets/actions/delete-rows/delete-rows.mjs
  components/google_sheets/actions/delete-worksheet/delete-worksheet.mjs
  components/google_sheets/actions/find-row-vlookup/find-row-vlookup.mjs
  components/google_sheets/actions/find-row/find-row.mjs
  components/google_sheets/actions/get-cell/get-cell.mjs
  components/google_sheets/actions/get-spreadsheet-by-id/get-spreadsheet-by-id.mjs
  components/google_sheets/actions/get-values-in-range/get-values-in-range.mjs
  components/google_sheets/actions/get-values/get-values.mjs
  components/google_sheets/actions/insert-anchored-note/insert-anchored-note.mjs
  components/google_sheets/actions/insert-comment/insert-comment.mjs
  components/google_sheets/actions/list-worksheets/list-worksheets.mjs
  components/google_sheets/actions/update-cell/update-cell.mjs
  components/google_sheets/actions/update-multiple-rows/update-multiple-rows.mjs
  components/google_sheets/actions/update-row/update-row.mjs
  components/google_sheets/actions/upsert-row/upsert-row.mjs
  components/google_sheets/common/utils.mjs
  components/google_sheets/google_sheets.app.mjs
  components/google_sheets/package.json
  components/google_sheets/sources/new-comment/new-comment.mjs
  components/google_sheets/sources/new-row-added/new-row-added.mjs
  components/google_sheets/sources/new-updates/new-updates.mjs
  components/google_sheets/sources/new-worksheet/new-worksheet.mjs
  components/leadiq/leadiq.app.mjs
  components/pro_ledger/pro_ledger.app.mjs
  components/summit/summit.app.mjs
  components/wiza/wiza.app.mjs
Labels: triaged

#11823 New Components - twenty
  components/twenty/actions/create-update-delete-record/create-update-delete-record.mjs
  components/twenty/common/utils.mjs
  components/twenty/package.json
  components/twenty/sources/new-record-modified-instant/new-record-modified-instant.mjs
  components/twenty/sources/new-record-modified-instant/test-event.mjs
  components/twenty/twenty.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11931 New Components - chatfly
  components/chatfly/actions/send-message/send-message.mjs
  components/chatfly/chatfly.app.mjs
  components/chatfly/common/utils.mjs
  components/chatfly/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11933 New Components - thoughtly
  components/thoughtly/actions/create-contact/create-contact.mjs
  components/thoughtly/actions/trigger-call/trigger-call.mjs
  components/thoughtly/common/utils.mjs
  components/thoughtly/package.json
  components/thoughtly/sources/new-response-instant/new-response-instant.mjs
  components/thoughtly/sources/new-response-instant/test-event.mjs
  components/thoughtly/thoughtly.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11944 New Components - platerecognizer
  components/platerecognizer/actions/run-recognition/run-recognition.mjs
  components/platerecognizer/common/utils.mjs
  components/platerecognizer/package.json
  components/platerecognizer/platerecognizer.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11955 New Components - boloforms
  components/boloforms/actions/send-form/send-form.mjs
  components/boloforms/actions/send-template-signature/send-template-signature.mjs
  components/boloforms/boloforms.app.mjs
  components/boloforms/common/utils.mjs
  components/boloforms/package.json
  components/boloforms/sources/common/base.mjs
  components/boloforms/sources/new-response-instant/new-response-instant.mjs
  components/boloforms/sources/new-response-instant/test-event.mjs
  components/boloforms/sources/new-signature-completed-instant/new-signature-completed-instant.mjs
  components/boloforms/sources/new-signature-completed-instant/test-event.mjs
  components/boloforms/sources/new-template-response-instant/new-template-response-instant.mjs
  components/boloforms/sources/new-template-response-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12003 feat(slack/send-block-kit-message): allow to set unfurl properties in block messages
  components/slack/actions/send-block-kit-message/send-block-kit-message.mjs
  components/slack/package.json
Labels: triaged, User submitted

#11930 OpenAI Improvements
  components/openai/actions/analyze-image-content/analyze-image-content.mjs
  components/openai/actions/cancel-run/cancel-run.mjs
  components/openai/actions/chat-with-assistant/chat-with-assistant.mjs
  components/openai/actions/chat/chat.mjs
  components/openai/actions/classify-items-into-categories/classify-items-into-categories.mjs
  components/openai/actions/common/common-assistants.mjs
  components/openai/actions/common/common-helper.mjs
  components/openai/actions/common/constants.mjs
  components/openai/actions/convert-text-to-speech/convert-text-to-speech.mjs
  components/openai/actions/create-assistant/create-assistant.mjs
  components/openai/actions/create-batch/create-batch.mjs
  components/openai/actions/create-embeddings/create-embeddings.mjs
  components/openai/actions/create-fine-tuning-job/create-fine-tuning-job.mjs
  components/openai/actions/create-image/create-image.mjs
  components/openai/actions/create-message/create-message.mjs
  components/openai/actions/create-moderation/create-moderation.mjs
  components/openai/actions/create-run/create-run.mjs
  components/openai/actions/create-thread-and-run/create-thread-and-run.mjs
  components/openai/actions/create-thread/create-thread.mjs
  components/openai/actions/create-transcription/create-transcription.mjs
  components/openai/actions/delete-file/delete-file.mjs
  components/openai/actions/list-files/list-files.mjs
  components/openai/actions/list-messages/list-messages.mjs
  components/openai/actions/list-run-steps/list-run-steps.mjs
  components/openai/actions/list-runs/list-runs.mjs
  components/openai/actions/modify-assistant/modify-assistant.mjs
  components/openai/actions/modify-message/modify-message.mjs
  components/openai/actions/modify-run/modify-run.mjs
  components/openai/actions/retrieve-file-content/retrieve-file-content.mjs
  components/openai/actions/retrieve-file/retrieve-file.mjs
  components/openai/actions/retrieve-run-step/retrieve-run-step.mjs
  components/openai/actions/retrieve-run/retrieve-run.mjs
  components/openai/actions/send-prompt/send-prompt.mjs
  components/openai/actions/submit-tool-outputs-to-run/submit-tool-outputs-to-run.mjs
  components/openai/actions/summarize/summarize.mjs
  components/openai/actions/translate-text/translate-text.mjs
  components/openai/actions/upload-file/upload-file.mjs
  components/openai/common/constants.mjs
  components/openai/openai.app.mjs
  components/openai/package.json
  components/openai/sources/common/common.mjs
  components/openai/sources/new-batch-completed/new-batch-completed.mjs
  components/openai/sources/new-batch-completed/test-event.mjs
  components/openai/sources/new-file-created/new-file-created.mjs
  components/openai/sources/new-file-created/test-event.mjs
  components/openai/sources/new-fine-tuning-job-created/new-fine-tuning-job-created.mjs
  components/openai/sources/new-fine-tuning-job-created/test-event.mjs
  components/openai/sources/new-run-state-changed/new-run-state-changed.mjs
  components/openai/sources/new-run-state-changed/test-event.mjs
Labels: triaged

#10612 New Components - zixflow
  components/zixflow/actions/common/constants.mjs
  components/zixflow/actions/create-activity/create-activity.mjs
  components/zixflow/actions/delete-activity/delete-activity.mjs
  components/zixflow/actions/get-activities/get-activities.mjs
  components/zixflow/actions/update-activity/update-activity.mjs
  components/zixflow/package.json
  components/zixflow/zixflow.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11996 New Components - summit
  components/summit/actions/list-models/list-models.mjs
  components/summit/actions/run-model/run-model.mjs
  components/summit/package.json
  components/summit/sources/new-model-added/new-model-added.mjs
  components/summit/summit.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12010 New Components - linguapop
  components/linguapop/actions/create-test-invitation/create-test-invitation.mjs
  components/linguapop/linguapop.app.mjs
  components/linguapop/package.json
  components/linguapop/sources/new-placement-test-result-instant/new-placement-test-result-instant.mjs
  components/linguapop/sources/new-placement-test-result-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11963 New Components - detectify
  components/detectify/detectify.app.mjs
  components/detectify/package.json
  components/detectify/sources/common/base.mjs
  components/detectify/sources/new-high-risk-finding/new-high-risk-finding.mjs
  components/detectify/sources/new-high-risk-finding/test-event.mjs
  components/detectify/sources/new-medium-risk-finding/new-medium-risk-finding.mjs
  components/detectify/sources/new-medium-risk-finding/test-event.mjs
  components/detectify/sources/new-scan-started/new-scan-started.mjs
  components/detectify/sources/new-scan-started/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11997 New Components - apify
  components/apify/actions/run-actor/run-actor.mjs
  components/apify/actions/scrape-single-url/scrape-single-url.mjs
  components/apify/actions/set-key-value-store-record/set-key-value-store-record.mjs
  components/apify/apify.app.mjs
  components/apify/common/constants.mjs
  components/apify/common/utils.mjs
  components/apify/package.json
  components/apify/sources/common/base.mjs
  components/apify/sources/new-finished-actor-run-instant/new-finished-actor-run-instant.mjs
  components/apify/sources/new-finished-actor-run-instant/test-event.mjs
  components/apify/sources/new-finished-task-run-instant/new-finished-task-run-instant.mjs
  components/apify/sources/new-finished-task-run-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12121 SQL Prop Type Improvements
  platform/dist/index.d.ts
  platform/dist/sql-prop.d.ts
  platform/dist/sql-prop.js
  platform/lib/index.ts
  platform/lib/sql-prop.ts
  platform/package.json
Labels: enhancement, component ee, refactor, tracked internally, prioritized, strategic-app

#12112 Implement/refactor `getSchema` for the SQL prop
  components/mysql/actions/create-row/create-row.mjs
  components/mysql/actions/delete-row/delete-row.mjs
  components/mysql/actions/execute-query/execute-query.mjs
  components/mysql/actions/execute-raw-query/execute-raw-query.mjs
  components/mysql/actions/execute-stored-procedure/execute-stored-procedure.mjs
  components/mysql/actions/find-row/find-row.mjs
  components/mysql/actions/update-row/update-row.mjs
  components/mysql/mysql.app.mjs
  components/mysql/package.json
  components/mysql/sources/new-column/new-column.mjs
  components/mysql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/mysql/sources/new-row-custom-query/new-row-custom-query.mjs
  components/mysql/sources/new-row/new-row.mjs
  components/mysql/sources/new-table/new-table.mjs
  components/postgresql/actions/delete-rows/delete-rows.mjs
  components/postgresql/actions/execute-custom-query/execute-custom-query.mjs
  components/postgresql/actions/find-row-custom-query/find-row-custom-query.mjs
  components/postgresql/actions/find-row/find-row.mjs
  components/postgresql/actions/insert-row/insert-row.mjs
  components/postgresql/actions/update-row/update-row.mjs
  components/postgresql/actions/upsert-row/upsert-row.mjs
  components/postgresql/package.json
  components/postgresql/postgresql.app.mjs
  components/postgresql/sources/new-column/new-column.mjs
  components/postgresql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/postgresql/sources/new-row-custom-query/new-row-custom-query.mjs
  components/postgresql/sources/new-row/new-row.mjs
  components/postgresql/sources/new-table/new-table.mjs
  components/snowflake/actions/insert-multiple-rows/insert-multiple-rows.mjs
  components/snowflake/actions/insert-row/insert-row.mjs
  components/snowflake/package.json
  components/snowflake/snowflake.app.mjs
  components/snowflake/sources/change-to-warehouse/change-to-warehouse.mjs
  components/snowflake/sources/deleted-role/deleted-role.mjs
  components/snowflake/sources/deleted-user/deleted-user.mjs
  components/snowflake/sources/failed-task-in-schema/failed-task-in-schema.mjs
  components/snowflake/sources/new-database/new-database.mjs
  components/snowflake/sources/new-role/new-role.mjs
  components/snowflake/sources/new-row/new-row.mjs
  components/snowflake/sources/new-schema/new-schema.mjs
  components/snowflake/sources/new-table/new-table.mjs
  components/snowflake/sources/new-user/new-user.mjs
  components/snowflake/sources/query-results/query-results.mjs
  components/snowflake/sources/updated-role/updated-role.mjs
  components/snowflake/sources/updated-user/updated-user.mjs
  components/snowflake/sources/usage-monitor/usage-monitor.mjs
  pnpm-lock.yaml
Labels: enhancement, component ee, javascript, refactor, tracked internally, prioritized, strategic-app

#12132 Snowflake minor fixes
  components/snowflake/actions/insert-multiple-rows/insert-multiple-rows.mjs
  components/snowflake/actions/insert-row/insert-row.mjs
  components/snowflake/package.json
  components/snowflake/snowflake.app.mjs
  components/snowflake/sources/change-to-warehouse/change-to-warehouse.mjs
  components/snowflake/sources/deleted-role/deleted-role.mjs
  components/snowflake/sources/deleted-user/deleted-user.mjs
  components/snowflake/sources/failed-task-in-schema/failed-task-in-schema.mjs
  components/snowflake/sources/new-database/new-database.mjs
  components/snowflake/sources/new-role/new-role.mjs
  components/snowflake/sources/new-row/new-row.mjs
  components/snowflake/sources/new-schema/new-schema.mjs
  components/snowflake/sources/new-table/new-table.mjs
  components/snowflake/sources/new-user/new-user.mjs
  components/snowflake/sources/query-results/query-results.mjs
  components/snowflake/sources/updated-role/updated-role.mjs
  components/snowflake/sources/updated-user/updated-user.mjs
  components/snowflake/sources/usage-monitor/usage-monitor.mjs
Labels: bug, enhancement, triaged, component ee, javascript, tracked internally, prioritized, strategic-app

#12009 New Components - hippo_video
  components/hippo_video/actions/create-contact/create-contact.mjs
  components/hippo_video/actions/send-personalization-request/send-personalization-request.mjs
  components/hippo_video/actions/upload-video/upload-video.mjs
  components/hippo_video/common/constants.mjs
  components/hippo_video/common/utils.mjs
  components/hippo_video/hippo_video.app.mjs
  components/hippo_video/package.json
  components/hippo_video/sources/new-triggered-event-instant/new-triggered-event-instant.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12158 New Components - dpd2
  components/dpd2/common/constants.mjs
  components/dpd2/dpd2.app.mjs
  components/dpd2/package.json
  components/dpd2/sources/new-purchase-created/new-purchase-created.mjs
  components/dpd2/sources/new-purchase-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12154 New Components - albus
  components/albus/actions/ask-question/ask-question.mjs
  components/albus/albus.app.mjs
  components/albus/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#12155 New Components - neuronwriter
  components/neuronwriter/actions/create-new-query/create-new-query.mjs
  components/neuronwriter/actions/get-content-saved/get-content-saved.mjs
  components/neuronwriter/actions/get-query-details/get-query-details.mjs
  components/neuronwriter/common/constants.mjs
  components/neuronwriter/neuronwriter.app.mjs
  components/neuronwriter/package.json
  components/neuronwriter/sources/common/base.mjs
  components/neuronwriter/sources/new-done-query/new-done-query.mjs
  components/neuronwriter/sources/new-done-query/test-event.mjs
  components/neuronwriter/sources/new-query-processed/new-query-processed.mjs
  components/neuronwriter/sources/new-query-processed/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted
