Repository PipedreamHQ/pipedream, pull requests merged in 2024-04, with the labels that each got.

#11157 New Components - leiga
  components/leiga/actions/create-issue/create-issue.mjs
  components/leiga/leiga.app.mjs
  components/leiga/package.json
  components/leiga/sources/common/base.mjs
  components/leiga/sources/deleted-issue-instant/deleted-issue-instant.mjs
  components/leiga/sources/deleted-issue-instant/test-event.mjs
  components/leiga/sources/new-issue-instant/new-issue-instant.mjs
  components/leiga/sources/new-issue-instant/test-event.mjs
  components/leiga/sources/updated-issue-instant/test-event.mjs
  components/leiga/sources/updated-issue-instant/updated-issue-instant.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11213 New Components - sendx
  components/sendx/actions/add-tag-contact/add-tag-contact.mjs
  components/sendx/actions/create-update-contact/create-update-contact.mjs
  components/sendx/actions/remove-tag-contact/remove-tag-contact.mjs
  components/sendx/common/utils.mjs
  components/sendx/package.json
  components/sendx/sendx.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11222 Remove archived apps: Discord Webhook, Vercel, and MySQL SSL
  .github/workflows/pull-request-checks.yaml
  components/discord_webhook/README.md
  components/discord_webhook/actions/send-message-advanced/send-message-advanced.mjs
  components/discord_webhook/actions/send-message-common.mjs
  components/discord_webhook/actions/send-message-with-file/send-message-with-file.mjs
  components/discord_webhook/actions/send-message/send-message.mjs
  components/discord_webhook/discord_webhook.app.mjs
  components/discord_webhook/package.json
  components/mysql_ssl/actions/create-row/create-row.mjs
  components/mysql_ssl/actions/delete-row/delete-row.mjs
  components/mysql_ssl/actions/execute-query/execute-query.mjs
  components/mysql_ssl/actions/execute-stored-procedure/execute-stored-procedure.mjs
  components/mysql_ssl/actions/find-row/find-row.mjs
  components/mysql_ssl/actions/update-row/update-row.mjs
  components/mysql_ssl/common/utils.mjs
  components/mysql_ssl/mysql_ssl.app.mjs
  components/mysql_ssl/package.json
  components/mysql_ssl/sources/new-column/new-column.mjs
  components/mysql_ssl/sources/new-or-updated-row/new-or-updated-row.mjs
  components/mysql_ssl/sources/new-row-custom-query/new-row-custom-query.mjs
  components/mysql_ssl/sources/new-row/new-row.mjs
  components/mysql_ssl/sources/new-table/new-table.mjs
  components/vercel/actions/cancel-deployment/cancel-deployment.mjs
  components/vercel/actions/create-deployment/create-deployment.mjs
  components/vercel/actions/list-deployments/list-deployments.mjs
  components/vercel/package.json
  components/vercel/sources/new-deployment/new-deployment.mjs
  components/vercel/vercel.app.mjs
  components/vercel_token_auth/actions/cancel-deployment/cancel-deployment.mjs
  components/vercel_token_auth/actions/create-deployment/create-deployment.mjs
  components/vercel_token_auth/actions/list-deployments/list-deployments.mjs
  components/vercel_token_auth/common/constants.mjs
  components/vercel_token_auth/common/override-app.mjs
  components/vercel_token_auth/package.json
  components/vercel_token_auth/sources/new-deployment/new-deployment.mjs
  components/vercel_token_auth/vercel_token_auth.app.mjs
  pnpm-lock.yaml
Labels: triaged

#11277 Fix calls to unbounded MySQL app methods
  components/mysql/actions/create-row/create-row.mjs
  components/mysql/actions/delete-row/delete-row.mjs
  components/mysql/actions/execute-query/execute-query.mjs
  components/mysql/actions/execute-raw-query/execute-raw-query.mjs
  components/mysql/actions/execute-stored-procedure/execute-stored-procedure.mjs
  components/mysql/actions/find-row/find-row.mjs
  components/mysql/actions/update-row/update-row.mjs
  components/mysql/mysql.app.mjs
  components/mysql/package.json
  components/mysql/sources/new-column/new-column.mjs
  components/mysql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/mysql/sources/new-row-custom-query/new-row-custom-query.mjs
  components/mysql/sources/new-row/new-row.mjs
  components/mysql/sources/new-table/new-table.mjs
Labels: bug, javascript, prioritized, actions

#11145 New Components - dingconnect
  components/dingconnect/actions/estimate-prices/estimate-prices.mjs
  components/dingconnect/actions/get-balance/get-balance.mjs
  components/dingconnect/actions/get-products/get-products.mjs
  components/dingconnect/dingconnect.app.mjs
  components/dingconnect/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11235 New Components - paigo
  components/paigo/actions/add-credits/add-credits.mjs
  components/paigo/actions/create-dimension/create-dimension.mjs
  components/paigo/actions/create-offering/create-offering.mjs
  components/paigo/actions/get-invoice/get-invoice.mjs
  components/paigo/actions/measure-usage/measure-usage.mjs
  components/paigo/actions/onboard-customer/onboard-customer.mjs
  components/paigo/common/constants.mjs
  components/paigo/package.json
  components/paigo/paigo.app.mjs
  components/paigo/sources/common/base.mjs
  components/paigo/sources/entitlement-threshold-reached-instant/entitlement-threshold-reached-instant.mjs
  components/paigo/sources/entitlement-threshold-reached-instant/test-event.mjs
  components/paigo/sources/new-customer-instant/new-customer-instant.mjs
  components/paigo/sources/new-customer-instant/test-event.mjs
  components/paigo/sources/new-invoice-instant/new-invoice-instant.mjs
  components/paigo/sources/new-invoice-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11245 New Components - defastra
  components/defastra/actions/common/base.mjs
  components/defastra/actions/deep-email-check/deep-email-check.mjs
  components/defastra/actions/deep-phone-check/deep-phone-check.mjs
  components/defastra/defastra.app.mjs
  components/defastra/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11271 New Components - anymail_finder
  components/anymail_finder/actions/search-all-emails-on-company/search-all-emails-on-company.mjs
  components/anymail_finder/actions/search-email/search-email.mjs
  components/anymail_finder/anymail_finder.app.mjs
  components/anymail_finder/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11285 New Components - dex
  components/dex/actions/create-note/create-note.mjs
  components/dex/actions/create-reminder/create-reminder.mjs
  components/dex/actions/create-update-contact/create-update-contact.mjs
  components/dex/common/constants.mjs
  components/dex/common/utils.mjs
  components/dex/dex.app.mjs
  components/dex/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11253 New Components - wildapricot
  components/wildapricot/actions/add-update-contact-member/add-update-contact-member.mjs
  components/wildapricot/actions/add-update-event-registration/add-update-event-registration.mjs
  components/wildapricot/actions/delete-event-registration/delete-event-registration.mjs
  components/wildapricot/common/constants.mjs
  components/wildapricot/package.json
  components/wildapricot/sources/common/base.mjs
  components/wildapricot/sources/new-contact-or-member-updated/new-contact-or-member-updated.mjs
  components/wildapricot/sources/new-contact-or-member-updated/test-event.mjs
  components/wildapricot/sources/new-event-registration-created/new-event-registration-created.mjs
  components/wildapricot/sources/new-event-registration-created/test-event.mjs
  components/wildapricot/sources/new-payments-received/new-payments-received.mjs
  components/wildapricot/sources/new-payments-received/test-event.mjs
  components/wildapricot/wildapricot.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11283 New Components - google_meet
  components/google_calendar/actions/common/create-event-common.mjs
  components/google_calendar/actions/create-event/create-event.mjs
  components/google_calendar/actions/update-event/update-event.mjs
  components/google_calendar/package.json
  components/google_meet/actions/schedule-meeting/schedule-meeting.mjs
  components/google_meet/google_meet.app.mjs
  components/google_meet/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11143 New Components - blazemeter
  components/blazemeter/actions/create-project/create-project.mjs
  components/blazemeter/actions/list-projects/list-projects.mjs
  components/blazemeter/actions/list-workspaces/list-workspaces.mjs
  components/blazemeter/blazemeter.app.mjs
  components/blazemeter/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11294 Remove DOM type definitions from types package
  types/package-lock.json
  types/package.json
  types/src/index.ts
  types/tsconfig.json
Labels: triaged

#11144 New Components - builtwith 
  components/builtwith/actions/get-domain-relationships/get-domain-relationships.mjs
  components/builtwith/actions/get-domain-technologies/get-domain-technologies.mjs
  components/builtwith/actions/get-profile-websites/get-profile-websites.mjs
  components/builtwith/builtwith.app.mjs
  components/builtwith/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11238 New Components - codacy
  components/codacy/actions/delete-integration/delete-integration.mjs
  components/codacy/actions/get-user/get-user.mjs
  components/codacy/actions/list-integrations/list-integrations.mjs
  components/codacy/actions/list-organizations/list-organizations.mjs
  components/codacy/codacy.app.mjs
  components/codacy/common/constants.mjs
  components/codacy/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10371 Toggl docs
  components/toggl/README.md
  components/toggl/actions/get-current-time-entry/get-current-time-entry.mjs
  components/toggl/actions/get-time-entries/get-time-entries.mjs
  components/toggl/actions/get-time-entry/get-time-entry.mjs
  components/toggl/package.json
  pnpm-lock.yaml
Labels: triaged, User submitted

#11374 Fix calls to unbounded PostgreSQL app methods
  components/postgresql/actions/delete-rows/delete-rows.mjs
  components/postgresql/actions/execute-custom-query/execute-custom-query.mjs
  components/postgresql/actions/find-row-custom-query/find-row-custom-query.mjs
  components/postgresql/actions/find-row/find-row.mjs
  components/postgresql/actions/insert-row/insert-row.mjs
  components/postgresql/actions/update-row/update-row.mjs
  components/postgresql/actions/upsert-row/upsert-row.mjs
  components/postgresql/package.json
  components/postgresql/postgresql.app.mjs
  components/postgresql/sources/new-column/new-column.mjs
  components/postgresql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/postgresql/sources/new-row-custom-query/new-row-custom-query.mjs
  components/postgresql/sources/new-row/new-row.mjs
  components/postgresql/sources/new-table/new-table.mjs
  pnpm-lock.yaml
Labels: bug, prioritized, strategic-app, actions

#11151 New Components - outreach
  components/outreach/actions/add-prospect-sequence/add-prospect-sequence.mjs
  components/outreach/actions/create-account/create-account.mjs
  components/outreach/actions/create-prospect/create-prospect.mjs
  components/outreach/common/constants.mjs
  components/outreach/common/utils.mjs
  components/outreach/outreach.app.mjs
  components/outreach/package.json
  components/outreach/sources/common/base.mjs
  components/outreach/sources/new-call-instant/new-call-instant.mjs
  components/outreach/sources/new-email-instant/new-email-instant.mjs
  components/outreach/sources/new-task-instant/new-task-instant.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11284 New Components - shift4
  components/shift4/actions/create-charge/create-charge.mjs
  components/shift4/actions/create-customer/create-customer.mjs
  components/shift4/actions/create-plan/create-plan.mjs
  components/shift4/actions/create-token/create-token.mjs
  components/shift4/common/constants.mjs
  components/shift4/common/utils.mjs
  components/shift4/package.json
  components/shift4/shift4.app.mjs
  components/shift4/sources/charge-updated/charge-updated.mjs
  components/shift4/sources/charge-updated/test-event.mjs
  components/shift4/sources/common/base.mjs
  components/shift4/sources/new-charge/new-charge.mjs
  components/shift4/sources/new-charge/test-event.mjs
  components/shift4/sources/new-customer/new-customer.mjs
  components/shift4/sources/new-customer/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11372 New Components - timing
  components/timing/actions/create-time-entry/create-time-entry.mjs
  components/timing/actions/start-timer/start-timer.mjs
  components/timing/actions/stop-timer/stop-timer.mjs
  components/timing/package.json
  components/timing/sources/common/base.mjs
  components/timing/sources/new-project/new-project.mjs
  components/timing/sources/new-project/test-event.mjs
  components/timing/sources/new-time-entry/new-time-entry.mjs
  components/timing/sources/new-time-entry/test-event.mjs
  components/timing/sources/new-timer-started-running/new-timer-started-running.mjs
  components/timing/sources/new-timer-started-running/test-event.mjs
  components/timing/timing.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11288 New Components - cinc
  components/cinc/actions/create-lead/create-lead.mjs
  components/cinc/actions/get-lead/get-lead.mjs
  components/cinc/cinc.app.mjs
  components/cinc/common/constants.mjs
  components/cinc/package.json
  components/cinc/sources/common/base.mjs
  components/cinc/sources/lead-details-updated/lead-details-updated.mjs
  components/cinc/sources/new-lead-created/new-lead-created.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11291 New Components - sendsms
  components/sendsms/actions/add-contact/add-contact.mjs
  components/sendsms/actions/check-blocklist/check-blocklist.mjs
  components/sendsms/actions/send-message-with-unsubscribe-link/send-message-with-unsubscribe-link.mjs
  components/sendsms/actions/send-message/send-message.mjs
  components/sendsms/package.json
  components/sendsms/sendsms.app.mjs
Labels: ai-assisted

#11401 Republish Piggy & Mattermost components
  components/mattermost/actions/post-message/post-message.ts
  components/mattermost/package.json
  components/mattermost/sources/new-message-sent-in-channel/new-message-sent-in-channel.ts
  components/piggy/actions/find-or-create-contact/find-or-create-contact.mjs
  components/piggy/package.json
  pnpm-lock.yaml
Labels: triaged

#11373 New Components - mailcheck
  components/mailcheck/actions/create-batch-operation/create-batch-operation.mjs
  components/mailcheck/actions/get-batch-operation-status/get-batch-operation-status.mjs
  components/mailcheck/actions/validate-single-email/validate-single-email.mjs
  components/mailcheck/common/utils.mjs
  components/mailcheck/mailcheck.app.mjs
  components/mailcheck/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11375 New Components - nextcloud
  components/nextcloud/actions/create-share/create-share.mjs
  components/nextcloud/actions/delete-share/delete-share.mjs
  components/nextcloud/actions/get-shares/get-shares.mjs
  components/nextcloud/nextcloud.app.mjs
  components/nextcloud/package.json
  components/nextcloud/sources/new-share-created/new-share-created.mjs
  components/nextcloud/sources/new-share-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11379 New Components - sendy
  components/sendy/actions/add-update-subscriber/add-update-subscriber.mjs
  components/sendy/actions/create-draft-campaign/create-draft-campaign.mjs
  components/sendy/actions/unsubscribe-email/unsubscribe-email.mjs
  components/sendy/common/utils.mjs
  components/sendy/package.json
  components/sendy/sendy.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11385 New Components - new_york_times
  components/new_york_times/new_york_times.app.mjs
  components/new_york_times/package.json
  components/new_york_times/sources/new-article/new-article.mjs
  components/new_york_times/sources/new-article/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11384 New Components - onstrategy
  components/onstrategy/onstrategy.app.mjs
  components/onstrategy/package.json
  components/onstrategy/sources/new-goal-added/new-goal-added.mjs
  components/onstrategy/sources/new-goal-added/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11396 New Components - rocketchat
  components/rocket_chat/actions/create-channel/create-channel.mjs
  components/rocket_chat/actions/send-direct-message/send-direct-message.mjs
  components/rocket_chat/actions/set-status/set-status.mjs
  components/rocket_chat/common/constants.mjs
  components/rocket_chat/package.json
  components/rocket_chat/rocket_chat.app.mjs
  components/rocket_chat/sources/common/base.mjs
  components/rocket_chat/sources/new-channel-created/new-channel-created.mjs
  components/rocket_chat/sources/new-channel-created/test-event.mjs
  components/rocket_chat/sources/new-message-public-channel/new-message-public-channel.mjs
  components/rocket_chat/sources/new-message-public-channel/test-event.mjs
  components/rocket_chat/sources/new-user-created/new-user-created.mjs
  components/rocket_chat/sources/new-user-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11244 New Components - thinkific
  components/thinkific/actions/create-user/create-user.mjs
  components/thinkific/actions/enroll-user/enroll-user.mjs
  components/thinkific/actions/update-user/update-user.mjs
  components/thinkific/common/constants.mjs
  components/thinkific/package.json
  components/thinkific/sources/common/base.mjs
  components/thinkific/sources/lesson-completed-instant/lesson-completed-instant.mjs
  components/thinkific/sources/lesson-completed-instant/test-event.mjs
  components/thinkific/sources/new-full-enrollment-instant/new-full-enrollment-instant.mjs
  components/thinkific/sources/new-full-enrollment-instant/test-event.mjs
  components/thinkific/sources/new-order-instant/new-order-instant.mjs
  components/thinkific/sources/new-order-instant/test-event.mjs
  components/thinkific/thinkific.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11233 New Components - similarweb_digitalrank_api
  components/similarweb_digitalrank_api/actions/get-ranked-sites/get-ranked-sites.mjs
  components/similarweb_digitalrank_api/actions/get-subscription-status/get-subscription-status.mjs
  components/similarweb_digitalrank_api/actions/get-website-rank/get-website-rank.mjs
  components/similarweb_digitalrank_api/package.json
  components/similarweb_digitalrank_api/similarweb_digitalrank_api.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11376 New Components - diffbot
  components/diffbot/actions/enhance-entity/enhance-entity.mjs
  components/diffbot/actions/extract-page/extract-page.mjs
  components/diffbot/diffbot.app.mjs
  components/diffbot/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11441 New Components - small_improvements
  components/small_improvements/.gitignore
  components/small_improvements/actions/create-meeting-notes/create-meeting-notes.mjs
  components/small_improvements/actions/list-users/list-users.mjs
  components/small_improvements/app/small_improvements.app.ts
  components/small_improvements/package.json
  components/small_improvements/small_improvements.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11301 New Components - sevdesk
  components/sevdesk/actions/cancel-invoice/cancel-invoice.mjs
  components/sevdesk/actions/create-invoice/create-invoice.mjs
  components/sevdesk/actions/send-invoice-email/send-invoice-email.mjs
  components/sevdesk/common/constants.mjs
  components/sevdesk/package.json
  components/sevdesk/sevdesk.app.mjs
  components/sevdesk/sources/common/base.mjs
  components/sevdesk/sources/new-contact/new-contact.mjs
  components/sevdesk/sources/new-contact/test-event.mjs
  components/sevdesk/sources/new-order/new-order.mjs
  components/sevdesk/sources/new-order/test-event.mjs
  components/sevdesk/sources/new-voucher/new-voucher.mjs
  components/sevdesk/sources/new-voucher/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11480 New Components - ambivo
  components/ambivo/actions/get-contacts/get-contacts.mjs
  components/ambivo/actions/get-leads/get-leads.mjs
  components/ambivo/ambivo.app.mjs
  components/ambivo/package.json
  components/ambivo/sources/common/base.mjs
  components/ambivo/sources/contact-status-updated/contact-status-updated.mjs
  components/ambivo/sources/contact-status-updated/test-event.mjs
  components/ambivo/sources/new-contact-created/new-contact-created.mjs
  components/ambivo/sources/new-contact-created/test-event.mjs
  components/ambivo/sources/new-lead-created/new-lead-created.mjs
  components/ambivo/sources/new-lead-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11474 New Components - icypeas
  components/icypeas/actions/domain-search/domain-search.mjs
  components/icypeas/actions/email-verification/email-verification.mjs
  components/icypeas/actions/get-single-result/get-single-result.mjs
  components/icypeas/common/constants.mjs
  components/icypeas/icypeas.app.mjs
  components/icypeas/package.json
  components/icypeas/sources/new-single-result/new-single-result.mjs
  components/icypeas/sources/new-single-result/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11495 SQL Prop Interface
  platform/dist/index.js
  platform/dist/sql-prop.js
  platform/lib/index.ts
  platform/lib/sql-prop.ts
  platform/package-lock.json
  platform/package.json
  pnpm-lock.yaml
Labels: enhancement, dependencies, javascript, tracked internally, prioritized, strategic-app

#11548 SQL Proxy interface improvements
  platform/dist/sql-proxy.js
  platform/lib/sql-proxy.ts
  platform/package.json
Labels: enhancement, javascript, tracked internally, prioritized

#11538 api4ai – Updated READMEs to conform to guidelines.
  components/api4ai/README.md
  components/api4ai/actions/alcohol-label-recognition/README.md
  components/api4ai/actions/background-removal/README.md
  components/api4ai/actions/brand-recognition/README.md
  components/api4ai/actions/car-image-background-removal/README.md
  components/api4ai/actions/furniture-and-household-item-recognition/README.md
  components/api4ai/actions/image-anonymization/README.md
  components/api4ai/actions/nsfw-image-recognition/README.md
Labels: triaged, User submitted

#11580 SQL Proxy interface updates
  components/mysql/actions/create-row/create-row.mjs
  components/mysql/actions/delete-row/delete-row.mjs
  components/mysql/actions/execute-query/execute-query.mjs
  components/mysql/actions/execute-raw-query/execute-raw-query.mjs
  components/mysql/actions/execute-stored-procedure/execute-stored-procedure.mjs
  components/mysql/actions/find-row/find-row.mjs
  components/mysql/actions/update-row/update-row.mjs
  components/mysql/mysql.app.mjs
  components/mysql/package.json
  components/mysql/sources/new-column/new-column.mjs
  components/mysql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/mysql/sources/new-row-custom-query/new-row-custom-query.mjs
  components/mysql/sources/new-row/new-row.mjs
  components/mysql/sources/new-table/new-table.mjs
  components/postgresql/actions/delete-rows/delete-rows.mjs
  components/postgresql/actions/execute-custom-query/execute-custom-query.mjs
  components/postgresql/actions/find-row-custom-query/find-row-custom-query.mjs
  components/postgresql/actions/find-row/find-row.mjs
  components/postgresql/actions/insert-row/insert-row.mjs
  components/postgresql/actions/update-row/update-row.mjs
  components/postgresql/actions/upsert-row/upsert-row.mjs
  components/postgresql/package.json
  components/postgresql/postgresql.app.mjs
  components/postgresql/sources/new-column/new-column.mjs
  components/postgresql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/postgresql/sources/new-row-custom-query/new-row-custom-query.mjs
  components/postgresql/sources/new-row/new-row.mjs
  components/postgresql/sources/new-table/new-table.mjs
  pnpm-lock.yaml
Labels: dependencies, javascript, tracked internally, prioritized, strategic-app

#11517 New Components - kadoa
  components/kadoa/actions/start-workflow/start-workflow.mjs
  components/kadoa/kadoa.app.mjs
  components/kadoa/package.json
  components/kadoa/sources/new-workflow-finished-instant/new-workflow-finished-instant.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11431 New Components - codat
  components/codat/codat.app.mjs
  components/codat/common/event-types.mjs
  components/codat/package.json
  components/codat/sources/new-webhook-message-instant/new-webhook-message-instant.mjs
  components/codat/sources/new-webhook-message-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11455 New Components - fireflies
  components/fireflies/actions/find-meeting-by-id/find-meeting-by-id.mjs
  components/fireflies/actions/find-recent-meeting/find-recent-meeting.mjs
  components/fireflies/actions/upload-audio/upload-audio.mjs
  components/fireflies/common/constants.mjs
  components/fireflies/common/mutations.mjs
  components/fireflies/common/queries.mjs
  components/fireflies/fireflies.app.mjs
  components/fireflies/package.json
  components/fireflies/sources/new-meeting-created/new-meeting-created.mjs
  components/fireflies/sources/new-meeting-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11404 New Components - acuity-scheduling
  components/acuity_scheduling/actions/add-blocked-off-time/add-blocked-off-time.mjs
  components/acuity_scheduling/actions/find-appointments-by-client-info/find-appointments-by-client-info.mjs
  components/acuity_scheduling/acuity_scheduling.app.mjs
  components/acuity_scheduling/common/utils.mjs
  components/acuity_scheduling/package.json
  components/acuity_scheduling/sources/appointment-canceled-instant/appointment-canceled-instant.mjs
  components/acuity_scheduling/sources/appointment-canceled-instant/test-event.mjs
  components/acuity_scheduling/sources/common/base.mjs
  components/acuity_scheduling/sources/new-appointment-instant/new-appointment-instant.mjs
  components/acuity_scheduling/sources/new-appointment-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11600 Fix doc typo for Google-Sheets action: add-single-row
  components/google_sheets/actions/add-single-row/add-single-row.mjs
  components/google_sheets/package.json
Labels: triaged, User submitted

#11377 New Components - codemagic
  components/codemagic/actions/add-application/add-application.mjs
  components/codemagic/actions/create-variable/create-variable.mjs
  components/codemagic/actions/list-application/list-application.mjs
  components/codemagic/codemagic.app.mjs
  components/codemagic/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11598 New Components - softr
  components/softr/.gitignore
  components/softr/actions/create-user/create-user.mjs
  components/softr/actions/delete-user/delete-user.mjs
  components/softr/actions/generate-magic-link/generate-magic-link.mjs
  components/softr/app/softr.app.ts
  components/softr/package.json
  components/softr/softr.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11493 New Components - smartroutes
  components/smartroutes/actions/create-order/create-order.mjs
  components/smartroutes/common/utils.mjs
  components/smartroutes/package.json
  components/smartroutes/smartroutes.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11488 New Components - faktoora
  components/faktoora/actions/create-invoice/create-invoice.mjs
  components/faktoora/actions/get-invoice/get-invoice.mjs
  components/faktoora/common/utils.mjs
  components/faktoora/faktoora.app.mjs
  components/faktoora/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11609 New Components - tinypng
  components/tinypng/actions/compress-image/compress-image.mjs
  components/tinypng/actions/convert-image/convert-image.mjs
  components/tinypng/actions/resize-image/resize-image.mjs
  components/tinypng/common/constants.mjs
  components/tinypng/common/utils.mjs
  components/tinypng/package.json
  components/tinypng/tinypng.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11545 New Components - relevance_ai
  components/relevance_ai/actions/message-agent/message-agent.mjs
  components/relevance_ai/actions/run-tool/run-tool.mjs
  components/relevance_ai/common/constants.mjs
  components/relevance_ai/common/utils.mjs
  components/relevance_ai/package.json
  components/relevance_ai/relevance_ai.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11610 New Components - skillzrun
  components/skillzrun/actions/create-user-with-offers/create-user-with-offers.mjs
  components/skillzrun/actions/upsert-user/upsert-user.mjs
  components/skillzrun/common/constants.mjs
  components/skillzrun/package.json
  components/skillzrun/skillzrun.app.mjs
  components/skillzrun/sources/new-user-created/new-user-created.mjs
  components/skillzrun/sources/new-user-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11622 Implement `getSchema` method for MySQL and PostgreSQL
  components/mysql/actions/create-row/create-row.mjs
  components/mysql/actions/delete-row/delete-row.mjs
  components/mysql/actions/execute-query/execute-query.mjs
  components/mysql/actions/execute-raw-query/execute-raw-query.mjs
  components/mysql/actions/execute-stored-procedure/execute-stored-procedure.mjs
  components/mysql/actions/find-row/find-row.mjs
  components/mysql/actions/update-row/update-row.mjs
  components/mysql/mysql.app.mjs
  components/mysql/package.json
  components/mysql/sources/new-column/new-column.mjs
  components/mysql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/mysql/sources/new-row-custom-query/new-row-custom-query.mjs
  components/mysql/sources/new-row/new-row.mjs
  components/mysql/sources/new-table/new-table.mjs
  components/postgresql/actions/delete-rows/delete-rows.mjs
  components/postgresql/actions/execute-custom-query/execute-custom-query.mjs
  components/postgresql/actions/find-row-custom-query/find-row-custom-query.mjs
  components/postgresql/actions/find-row/find-row.mjs
  components/postgresql/actions/insert-row/insert-row.mjs
  components/postgresql/actions/update-row/update-row.mjs
  components/postgresql/actions/upsert-row/upsert-row.mjs
  components/postgresql/package.json
  components/postgresql/postgresql.app.mjs
  components/postgresql/sources/new-column/new-column.mjs
  components/postgresql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/postgresql/sources/new-row-custom-query/new-row-custom-query.mjs
  components/postgresql/sources/new-row/new-row.mjs
  components/postgresql/sources/new-table/new-table.mjs
Labels: tracked internally, prioritized, strategic-app

#11636 Echo raw API errors when publishing a component
  .github/workflows/publish-components.yaml
Labels: bug

#11596 New Components - overledger
  components/overledger/actions/execute-signed-transaction/execute-signed-transaction.mjs
  components/overledger/actions/prepare-smart-contract-transaction/prepare-smart-contract-transaction.mjs
  components/overledger/common/constants.mjs
  components/overledger/common/utils.mjs
  components/overledger/overledger.app.mjs
  components/overledger/package.json
  components/overledger/sources/common/base.mjs
  components/overledger/sources/new-contract-event-instant/new-contract-event-instant.mjs
  components/overledger/sources/new-contract-event-instant/test-event.mjs
  components/overledger/sources/watch-new-account-event-instant/test-event.mjs
  components/overledger/sources/watch-new-account-event-instant/watch-new-account-event-instant.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11611 New Components - forcemanager
  components/forcemanager/actions/create-opportunity/create-opportunity.mjs
  components/forcemanager/actions/find-contact/find-contact.mjs
  components/forcemanager/actions/list-users/list-users.mjs
  components/forcemanager/forcemanager.app.mjs
  components/forcemanager/package.json
  components/forcemanager/sources/common/base.mjs
  components/forcemanager/sources/new-activity/new-activity.mjs
  components/forcemanager/sources/new-activity/test-event.mjs
  components/forcemanager/sources/new-contact/new-contact.mjs
  components/forcemanager/sources/new-contact/test-event.mjs
  components/forcemanager/sources/new-opportunity/new-opportunity.mjs
  components/forcemanager/sources/new-opportunity/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11621 New Components - bytenite
  components/bytenite/actions/create-job/create-job.mjs
  components/bytenite/actions/get-job-results/get-job-results.mjs
  components/bytenite/actions/start-job/start-job.mjs
  components/bytenite/bytenite.app.mjs
  components/bytenite/common/constants.mjs
  components/bytenite/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11635 New Components - google-vertex-ai
  components/google_vertex_ai/actions/analyze-image-video/analyze-image-video.mjs
  components/google_vertex_ai/actions/analyze-text-sentiment/analyze-text-sentiment.mjs
  components/google_vertex_ai/actions/classify-text/classify-text.mjs
  components/google_vertex_ai/google_vertex_ai.app.mjs
  components/google_vertex_ai/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11615 Cleaning up example actions and adding common ones (Beebole team)
  components/beebole_app/actions/create-company/create-company.mjs
  components/beebole_app/actions/list-companies/list-companies.mjs
  components/beebole_app/actions/list-untimed-employees/list-untimed-employees.mjs
  components/beebole_app/actions/run-report/run-report.mjs
  components/beebole_app/actions/update-company/update-company.mjs
  components/beebole_app/beebole_app.app.mjs
  components/beebole_app/package.json
Labels: triaged, User submitted
