Repository PipedreamHQ/pipedream, pull requests merged in 2024-06, with the labels that each got.

#12199 Fix `rowCount` type in MySQL schema
  components/mysql/actions/create-row/create-row.mjs
  components/mysql/actions/delete-row/delete-row.mjs
  components/mysql/actions/execute-query/execute-query.mjs
  components/mysql/actions/execute-raw-query/execute-raw-query.mjs
  components/mysql/actions/execute-stored-procedure/execute-stored-procedure.mjs
  components/mysql/actions/find-row/find-row.mjs
  components/mysql/actions/update-row/update-row.mjs
  components/mysql/mysql.app.mjs
  components/mysql/package.json
  components/mysql/sources/new-column/new-column.mjs
  components/mysql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/mysql/sources/new-row-custom-query/new-row-custom-query.mjs
  components/mysql/sources/new-row/new-row.mjs
  components/mysql/sources/new-table/new-table.mjs
Labels: bug, javascript, tracked internally, prioritized, strategic-app

#12184 Slack updates to send-message action
  components/slack/actions/add-emoji-reaction/add-emoji-reaction.mjs
  components/slack/actions/archive-channel/archive-channel.mjs
  components/slack/actions/create-channel/create-channel.mjs
  components/slack/actions/create-reminder/create-reminder.mjs
  components/slack/actions/delete-file/delete-file.mjs
  components/slack/actions/delete-message/delete-message.mjs
  components/slack/actions/find-message/find-message.mjs
  components/slack/actions/find-user-by-email/find-user-by-email.mjs
  components/slack/actions/get-file/get-file.mjs
  components/slack/actions/invite-user-to-channel/invite-user-to-channel.mjs
  components/slack/actions/kick-user/kick-user.mjs
  components/slack/actions/list-channels/list-channels.mjs
  components/slack/actions/list-files/list-files.mjs
  components/slack/actions/list-group-members/list-group-members.mjs
  components/slack/actions/list-members-in-channel/list-members-in-channel.mjs
  components/slack/actions/list-replies/list-replies.mjs
  components/slack/actions/list-users/list-users.mjs
  components/slack/actions/reply-to-a-message/reply-to-a-message.mjs
  components/slack/actions/send-custom-message/send-custom-message.mjs
  components/slack/actions/send-large-message/send-large-message.mjs
  components/slack/actions/send-message/send-message.mjs
  components/slack/actions/set-channel-description/set-channel-description.mjs
  components/slack/actions/set-channel-topic/set-channel-topic.mjs
  components/slack/actions/set-status/set-status.mjs
  components/slack/actions/update-group-members/update-group-members.mjs
  components/slack/actions/update-message/update-message.mjs
  components/slack/actions/update-profile/update-profile.mjs
  components/slack/actions/upload-file/upload-file.mjs
  components/slack/actions/verify-slack-signature/verify-slack-signature.mjs
  components/slack/common/constants.mjs
  components/slack/package.json
  components/slack/slack.app.mjs
  components/slack/sources/new-channel-created/new-channel-created.mjs
  components/slack/sources/new-direct-message/new-direct-message.mjs
  components/slack/sources/new-interaction-event-received/new-interaction-event-received.mjs
  components/slack/sources/new-keyword-mention/new-keyword-mention.mjs
  components/slack/sources/new-message-in-channels/new-message-in-channels.mjs
  components/slack/sources/new-reaction-added/new-reaction-added.mjs
  components/slack/sources/new-user-mention/new-user-mention.mjs
  components/slack_bot/actions/send-message/send-message.mjs
  components/slack_bot/package.json
Labels: triaged

#12078 New Components - upbooks
  components/upbooks/actions/add-employee/add-employee.mjs
  components/upbooks/actions/create-expense-category/create-expense-category.mjs
  components/upbooks/actions/record-outward-payment/record-outward-payment.mjs
  components/upbooks/common/constants.mjs
  components/upbooks/common/utils.mjs
  components/upbooks/package.json
  components/upbooks/sources/new-data/new-data.mjs
  components/upbooks/sources/new-data/test-event.mjs
  components/upbooks/upbooks.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12143 New Components - ispring_learn
  components/ispring_learn/actions/enroll-users-in-courses/enroll-users-in-courses.mjs
  components/ispring_learn/actions/list-enrollments/list-enrollments.mjs
  components/ispring_learn/actions/update-user/update-user.mjs
  components/ispring_learn/common/constants.mjs
  components/ispring_learn/common/utils.mjs
  components/ispring_learn/ispring_learn.app.mjs
  components/ispring_learn/package.json
  components/ispring_learn/sources/common/base.mjs
  components/ispring_learn/sources/new-completion-instant/new-completion-instant.mjs
  components/ispring_learn/sources/new-completion-instant/test-event.mjs
  components/ispring_learn/sources/new-enrollment-instant/new-enrollment-instant.mjs
  components/ispring_learn/sources/new-enrollment-instant/test-event.mjs
  components/ispring_learn/sources/new-registration-instant/new-registration-instant.mjs
  components/ispring_learn/sources/new-registration-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12218 New Components - flippingbook
  components/flippingbook/actions/create-flipbook/create-flipbook.mjs
  components/flippingbook/actions/find-flipbook-by-title/find-flipbook-by-title.mjs
  components/flippingbook/actions/update-flipbook/update-flipbook.mjs
  components/flippingbook/flippingbook.app.mjs
  components/flippingbook/package.json
  components/flippingbook/sources/common/base.mjs
  components/flippingbook/sources/new-flipbook-instant/new-flipbook-instant.mjs
  components/flippingbook/sources/new-flipbook-instant/test-event.mjs
  components/flippingbook/sources/new-lead-instant/new-lead-instant.mjs
  components/flippingbook/sources/new-lead-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12230 Google ads followup adjustment
  components/google_ads/actions/create-report/create-report.mjs
  components/google_ads/package.json
Labels: triaged

#12340 SQL Interface Cleanup
  platform/dist/sql-prop.d.ts
  platform/dist/sql-prop.js
  platform/dist/sql-proxy.d.ts
  platform/dist/sql-proxy.js
  platform/dist/sql.d.ts
  platform/dist/sql.js
  platform/lib/sql-prop.ts
  platform/lib/sql-proxy.ts
  platform/lib/sql.ts
  platform/package.json
Labels: enhancement, javascript, refactor, tracked internally, prioritized

#12232 New Components - botpenguin
  components/botpenguin/actions/add-whatsapp-contact/add-whatsapp-contact.mjs
  components/botpenguin/actions/send-whatsapp-message/send-whatsapp-message.mjs
  components/botpenguin/actions/update-contact-attributes/update-contact-attributes.mjs
  components/botpenguin/botpenguin.app.mjs
  components/botpenguin/package.json
  components/botpenguin/sources/common/base.mjs
  components/botpenguin/sources/new-contact-created/new-contact-created.mjs
  components/botpenguin/sources/new-contact-created/test-event.mjs
  components/botpenguin/sources/new-incoming-message/new-incoming-message.mjs
  components/botpenguin/sources/new-incoming-message/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12243 New Components - speechace
  components/speechace/actions/score-scripted-recording/score-scripted-recording.mjs
  components/speechace/actions/transcribe-and-score-recording/transcribe-and-score-recording.mjs
  components/speechace/package.json
  components/speechace/speechace.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12357 Enable private key auth in Snowflake
  components/snowflake/actions/execute-sql-query/execute-sql-query.mjs
  components/snowflake/actions/insert-multiple-rows/insert-multiple-rows.mjs
  components/snowflake/actions/insert-row/insert-row.mjs
  components/snowflake/package.json
  components/snowflake/snowflake.app.mjs
  components/snowflake/sources/change-to-warehouse/change-to-warehouse.mjs
  components/snowflake/sources/deleted-role/deleted-role.mjs
  components/snowflake/sources/deleted-user/deleted-user.mjs
  components/snowflake/sources/failed-task-in-schema/failed-task-in-schema.mjs
  components/snowflake/sources/new-database/new-database.mjs
  components/snowflake/sources/new-role/new-role.mjs
  components/snowflake/sources/new-row/new-row.mjs
  components/snowflake/sources/new-schema/new-schema.mjs
  components/snowflake/sources/new-table/new-table.mjs
  components/snowflake/sources/new-user/new-user.mjs
  components/snowflake/sources/query-results/query-results.mjs
  components/snowflake/sources/updated-role/updated-role.mjs
  components/snowflake/sources/updated-user/updated-user.mjs
  components/snowflake/sources/usage-monitor/usage-monitor.mjs
  pnpm-lock.yaml
Labels: enhancement, trigger / source, refactor, tracked internally, prioritized, strategic-app, actions

#12331 New Components - height
  components/height/actions/create-task/create-task.mjs
  components/height/actions/search-tasks/search-tasks.mjs
  components/height/actions/update-task/update-task.mjs
  components/height/height.app.mjs
  components/height/package.json
  components/height/sources/common/base.mjs
  components/height/sources/common/tasks.mjs
  components/height/sources/new-completed-task/new-completed-task.mjs
  components/height/sources/new-completed-task/test-event.mjs
  components/height/sources/new-task-added/new-task-added.mjs
  components/height/sources/new-task-added/test-event.mjs
  components/height/sources/new-updated-task/new-updated-task.mjs
  components/height/sources/new-updated-task/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12375 New Components - repliq
  components/repliq/actions/get-credits-count/get-credits-count.mjs
  components/repliq/actions/launch-template/launch-template.mjs
  components/repliq/common/props.mjs
  components/repliq/package.json
  components/repliq/repliq.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12377 New Components - acymailing
  components/acymailing/actions/add-update-user/add-update-user.mjs
  components/acymailing/actions/email-user/email-user.mjs
  components/acymailing/actions/subscribe-user/subscribe-user.mjs
  components/acymailing/acymailing.app.mjs
  components/acymailing/common/constants.mjs
  components/acymailing/common/utils.mjs
  components/acymailing/package.json
  components/acymailing/sources/common/base.mjs
  components/acymailing/sources/new-confirmed-user/new-confirmed-user.mjs
  components/acymailing/sources/new-subscribed-user/new-subscribed-user.mjs
  components/acymailing/sources/new-unsubscribed-user/new-unsubscribed-user.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12439 New Components - okta
  components/okta/actions/create-user/create-user.mjs
  components/okta/actions/get-user/get-user.mjs
  components/okta/actions/update-user/update-user.mjs
  components/okta/common/constants.mjs
  components/okta/okta.app.mjs
  components/okta/package.json
  components/okta/sources/watch-new-events/test-event.mjs
  components/okta/sources/watch-new-events/watch-new-events.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12453 New Components - gorgias_oauth
  components/gorgias_oauth/actions/create-customer/create-customer.mjs
  components/gorgias_oauth/actions/create-ticket/create-ticket.mjs
  components/gorgias_oauth/actions/list-tickets/list-tickets.mjs
  components/gorgias_oauth/actions/retrieve-customer/retrieve-customer.mjs
  components/gorgias_oauth/actions/update-customer/update-customer.mjs
  components/gorgias_oauth/actions/update-ticket/update-ticket.mjs
  components/gorgias_oauth/common/utils.mjs
  components/gorgias_oauth/gorgias_oauth.app.mjs
  components/gorgias_oauth/package.json
  components/gorgias_oauth/sources/ticket-created/ticket-created.mjs
  components/gorgias_oauth/sources/ticket-message-created/ticket-message-created.mjs
  components/gorgias_oauth/sources/ticket-updated/ticket-updated.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12467 [Components] Certifier
  components/certifier/README.md
  components/certifier/actions/issue-credential/issue-credential.mjs
  components/certifier/certifier.app.mjs
  components/certifier/package.json
  pnpm-lock.yaml
Labels: triaged, User submitted

#12523 New Components - vivomeetings
  components/vivomeetings/actions/create-conference/create-conference.mjs
  components/vivomeetings/actions/get-conference-recordings/get-conference-recordings.mjs
  components/vivomeetings/actions/update-conference/update-conference.mjs
  components/vivomeetings/common/constants.mjs
  components/vivomeetings/common/utils.mjs
  components/vivomeetings/package.json
  components/vivomeetings/sources/new-meeting/new-meeting.mjs
  components/vivomeetings/sources/new-meeting/test-event.mjs
  components/vivomeetings/vivomeetings.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12515 New Components - documentpro
  components/documentpro/actions/new-document/new-document.mjs
  components/documentpro/common/utils.mjs
  components/documentpro/documentpro.app.mjs
  components/documentpro/package.json
  components/documentpro/sources/new-document-updated-instant/new-document-updated-instant.mjs
  components/documentpro/sources/new-document-updated-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12478 New Components - transifex
  components/transifex/actions/download-file/download-file.mjs
  components/transifex/actions/upload-file/upload-file.mjs
  components/transifex/common/utils.mjs
  components/transifex/package.json
  components/transifex/sources/common/base.mjs
  components/transifex/sources/new-localization-activity-completed-instant/new-localization-activity-completed-instant.mjs
  components/transifex/sources/new-localization-activity-completed-instant/test-event.mjs
  components/transifex/sources/new-task-for-set-of-strings-instant/new-task-for-set-of-strings-instant.mjs
  components/transifex/sources/new-task-for-set-of-strings-instant/test-event.mjs
  components/transifex/transifex.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12577 New Components - clickfunnels
  components/clickfunnels/actions/apply-tag-contact/apply-tag-contact.mjs
  components/clickfunnels/actions/remove-tag-contact/remove-tag-contact.mjs
  components/clickfunnels/actions/update-create-contact/update-create-contact.mjs
  components/clickfunnels/clickfunnels.app.mjs
  components/clickfunnels/common/utils.mjs
  components/clickfunnels/package.json
  components/clickfunnels/sources/common/base.mjs
  components/clickfunnels/sources/new-contact-identified-instant/new-contact-identified-instant.mjs
  components/clickfunnels/sources/new-contact-identified-instant/test-event.mjs
  components/clickfunnels/sources/new-one-time-order-paid-instant/new-one-time-order-paid-instant.mjs
  components/clickfunnels/sources/new-one-time-order-paid-instant/test-event.mjs
  components/clickfunnels/sources/new-subscription-invoice-paid-instant/new-subscription-invoice-paid-instant.mjs
  components/clickfunnels/sources/new-subscription-invoice-paid-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12343 New Components - survser
  components/survser/package.json
  components/survser/sources/new-survey-response/new-survey-response.mjs
  components/survser/sources/new-survey-response/test-event.mjs
  components/survser/survser.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12622 docs: CLI via Nix
  docs-v2/pages/cli/install.mdx
Labels: triaged, User submitted

#12618 Document process for supporting DB components
  docs-v2/pages/components/guidelines.mdx
Labels: docs, javascript, tracked internally, prioritized, strategic-app
