Repository PipedreamHQ/pipedream, pull requests merged in 2024-07, with the labels that each got.

#12623 New Components - invision_community
  components/invision_community/actions/create-forum-topic/create-forum-topic.mjs
  components/invision_community/actions/create-member/create-member.mjs
  components/invision_community/actions/update-member/update-member.mjs
  components/invision_community/common/utils.mjs
  components/invision_community/invision_community.app.mjs
  components/invision_community/package.json
  components/invision_community/sources/common/base.mjs
  components/invision_community/sources/new-forum-topic-instant/new-forum-topic-instant.mjs
  components/invision_community/sources/new-forum-topic-instant/test-event.mjs
  components/invision_community/sources/new-member-instant/new-member-instant.mjs
  components/invision_community/sources/new-member-instant/test-event.mjs
  components/invision_community/sources/new-topic-post-instant/new-topic-post-instant.mjs
  components/invision_community/sources/new-topic-post-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12519 Google Ads - Create Report improvement
  components/google_ads/actions/add-contact-to-list-by-email/add-contact-to-list-by-email.mjs
  components/google_ads/actions/create-customer-list/create-customer-list.mjs
  components/google_ads/actions/create-report/common-constants.mjs
  components/google_ads/actions/create-report/create-report.mjs
  components/google_ads/actions/send-offline-conversion/send-offline-conversion.mjs
  components/google_ads/common/queries.mjs
  components/google_ads/common/resources/ad.mjs
  components/google_ads/common/resources/adGroup.mjs
  components/google_ads/common/resources/campaign.mjs
  components/google_ads/common/resources/customer.mjs
  components/google_ads/common/utils.mjs
  components/google_ads/google_ads.app.mjs
  components/google_ads/package.json
  components/google_ads/sources/new-campaign-created/new-campaign-created.mjs
  components/google_ads/sources/new-lead-form-entry/new-lead-form-entry.mjs
Labels: triaged

#12625 New Components - leadoku
  components/leadoku/leadoku.app.mjs
  components/leadoku/package.json
  components/leadoku/sources/common/base.mjs
  components/leadoku/sources/new-connection/new-connection.mjs
  components/leadoku/sources/new-responder/new-responder.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12690 New Components - fillout
  components/fillout/fillout.app.mjs
  components/fillout/package.json
  components/fillout/sources/new-submission-instant/new-submission-instant.mjs
  components/fillout/sources/new-submission-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12702 New Components - faceup
  components/faceup/faceup.app.mjs
  components/faceup/package.json
  components/faceup/sources/new-internal-comment-instant/new-internal-comment-instant.mjs
  components/faceup/sources/new-internal-comment-instant/test-event.mjs
  components/faceup/sources/new-message-instant/new-message-instant.mjs
  components/faceup/sources/new-message-instant/test-event.mjs
  components/faceup/sources/new-report-instant/new-report-instant.mjs
  components/faceup/sources/new-report-instant/test-event.mjs
Labels: ai-assisted

#12742 New Components - poper
  components/poper/package.json
  components/poper/poper.app.mjs
  components/poper/sources/new-lead/new-lead.mjs
  components/poper/sources/new-lead/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12734 New Components - _21risk
  components/_21risk/_21risk.app.mjs
  components/_21risk/package.json
  components/_21risk/sources/common/base.mjs
  components/_21risk/sources/new-action/new-action.mjs
  components/_21risk/sources/new-action/test-event.mjs
  components/_21risk/sources/new-auditor/new-auditor.mjs
  components/_21risk/sources/new-auditor/test-event.mjs
  components/_21risk/sources/new-report/new-report.mjs
  components/_21risk/sources/new-report/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12743 New Components - 2chat
  components/_2chat/_2chat.app.mjs
  components/_2chat/actions/check-phone-number-whatsapp/check-phone-number-whatsapp.mjs
  components/_2chat/actions/create-contact/create-contact.mjs
  components/_2chat/actions/send-whatsapp-text-message/send-whatsapp-text-message.mjs
  components/_2chat/common/constants.mjs
  components/_2chat/package.json
  components/_2chat/sources/common/base.mjs
  components/_2chat/sources/new-conversation-instant/new-conversation-instant.mjs
  components/_2chat/sources/new-conversation-instant/test-event.mjs
  components/_2chat/sources/new-message-instant/new-message-instant.mjs
  components/_2chat/sources/new-message-instant/test-event.mjs
  components/_2chat/sources/new-whatsapp-order-instant/new-whatsapp-order-instant.mjs
  components/_2chat/sources/new-whatsapp-order-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12756 New Components - ramp
  components/ramp/actions/create-user-invite/create-user-invite.mjs
  components/ramp/actions/issue-virtual-card/issue-virtual-card.mjs
  components/ramp/actions/upload-receipt/upload-receipt.mjs
  components/ramp/common/constants.mjs
  components/ramp/package.json
  components/ramp/ramp.app.mjs
  components/ramp/sources/common/base.mjs
  components/ramp/sources/common/common.mjs
  components/ramp/sources/new-transaction-created/new-transaction-created.mjs
  components/ramp/sources/new-transaction-created/test-event.mjs
  components/ramp/sources/new-transactions/new-transactions.mjs
  components/ramp/sources/transaction-status-updated/test-event.mjs
  components/ramp/sources/transaction-status-updated/transaction-status-updated.mjs
  components/ramp/sources/transfer-payment-updated/test-event.mjs
  components/ramp/sources/transfer-payment-updated/transfer-payment-updated.mjs
  components/ramp_sandbox/actions/create-user-invite/create-user-invite.mjs
  components/ramp_sandbox/actions/issue-virtual-card/issue-virtual-card.mjs
  components/ramp_sandbox/actions/upload-receipt/upload-receipt.mjs
  components/ramp_sandbox/package.json
  components/ramp_sandbox/ramp_sandbox.app.mjs
  components/ramp_sandbox/sources/common/base.mjs
  components/ramp_sandbox/sources/new-transaction-created/new-transaction-created.mjs
  components/ramp_sandbox/sources/new-transaction-created/test-event.mjs
  components/ramp_sandbox/sources/transaction-status-updated/test-event.mjs
  components/ramp_sandbox/sources/transaction-status-updated/transaction-status-updated.mjs
  components/ramp_sandbox/sources/transfer-payment-updated/test-event.mjs
  components/ramp_sandbox/sources/transfer-payment-updated/transfer-payment-updated.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12808 fix(types): missing user prop definitions
  types/src/index.ts
Labels: triaged, User submitted

#11962 New Components - pidj
  components/pidj/actions/create-contact/create-contact.mjs
  components/pidj/actions/initiate-survey/initiate-survey.mjs
  components/pidj/actions/send-message/send-message.mjs
  components/pidj/common/constants.mjs
  components/pidj/package.json
  components/pidj/pidj.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12749 New Components - parma
  components/parma/actions/create-note/create-note.mjs
  components/parma/actions/create-relationship/create-relationship.mjs
  components/parma/actions/find-relationship/find-relationship.mjs
  components/parma/package.json
  components/parma/parma.app.mjs
  components/parma/sources/new-relationship/new-relationship.mjs
  components/parma/sources/new-relationship/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12805 Azure SQL & Microsoft SQL Server - add schema to table names
  components/azure_sql/actions/execute-query/execute-query.mjs
  components/azure_sql/actions/execute-raw-query/execute-raw-query.mjs
  components/azure_sql/actions/insert-row/insert-row.mjs
  components/azure_sql/azure_sql.app.mjs
  components/azure_sql/package.json
  components/azure_sql/sources/new-column/new-column.mjs
  components/azure_sql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/microsoft_sql_server/actions/execute-query/execute-query.mjs
  components/microsoft_sql_server/actions/execute-raw-query/execute-raw-query.mjs
  components/microsoft_sql_server/actions/insert-row/insert-row.mjs
  components/microsoft_sql_server/microsoft_sql_server.app.mjs
  components/microsoft_sql_server/package.json
  components/microsoft_sql_server/sources/new-column/new-column.mjs
  components/microsoft_sql_server/sources/new-or-updated-row/new-or-updated-row.mjs
Labels: triaged

#12810 New Components - adobe_photoshop
  components/adobe_photoshop/actions/remove-background-from-image/remove-background-from-image.mjs
  components/adobe_photoshop/adobe_photoshop.app.mjs
  components/adobe_photoshop/common/constants.mjs
  components/adobe_photoshop/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#12703 New Components - deftship
  components/deftship/actions/create-freight-order/create-freight-order.mjs
  components/deftship/actions/create-parcel-order/create-parcel-order.mjs
  components/deftship/actions/get-insurance-rate/get-insurance-rate.mjs
  components/deftship/common/constants.mjs
  components/deftship/deftship.app.mjs
  components/deftship/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#12831 New Components - canva
  components/canva/actions/create-design-import-job/create-design-import-job.mjs
  components/canva/actions/create-design/create-design.mjs
  components/canva/actions/export-design/export-design.mjs
  components/canva/actions/upload-asset/upload-asset.mjs
  components/canva/canva.app.mjs
  components/canva/common/constants.mjs
  components/canva/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#12846 New Components - waitlist
  components/waitlist/package.json
  components/waitlist/sources/common/base.mjs
  components/waitlist/sources/new-list/new-list.mjs
  components/waitlist/sources/new-list/test-event.mjs
  components/waitlist/sources/new-subscriber/new-subscriber.mjs
  components/waitlist/sources/new-subscriber/test-event.mjs
  components/waitlist/waitlist.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12856 New Components - peach
  components/peach/actions/create-contact/create-contact.mjs
  components/peach/actions/send-template-message/send-template-message.mjs
  components/peach/common/utils.mjs
  components/peach/package.json
  components/peach/peach.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12768 Updating to latest Shopify Partner API Version
  components/shopify_partner/actions/verify-webhook/verify-webhook.mjs
  components/shopify_partner/package.json
  components/shopify_partner/shopify_partner.app.mjs
  components/shopify_partner/sources/new-app-charges/new-app-charges.mjs
  components/shopify_partner/sources/new-app-installs/new-app-installs.mjs
  components/shopify_partner/sources/new-app-relationship-events/new-app-relationship-events.mjs
  components/shopify_partner/sources/new-app-uninstalls/new-app-uninstalls.mjs
Labels: triaged, User submitted

#12815 New Components - ikas
  components/ikas/ikas.app.mjs
  components/ikas/package.json
  components/ikas/sources/common/base.mjs
  components/ikas/sources/new-customer-instant/new-customer-instant.mjs
  components/ikas/sources/new-customer-instant/test-event.mjs
  components/ikas/sources/new-order-instant/new-order-instant.mjs
  components/ikas/sources/new-order-instant/test-event.mjs
  components/ikas/sources/new-product-instant/new-product-instant.mjs
  components/ikas/sources/new-product-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12858 Dropbox Usability Updates
  components/dropbox/actions/create-a-text-file/create-a-text-file.mjs
  components/dropbox/actions/create-folder/create-folder.mjs
  components/dropbox/actions/create-or-append-to-a-text-file/create-or-append-to-a-text-file.mjs
  components/dropbox/actions/create-update-share-link/common.mjs
  components/dropbox/actions/create-update-share-link/create-update-share-link.mjs
  components/dropbox/actions/delete-file-folder/delete-file-folder.mjs
  components/dropbox/actions/download-file-to-tmp/download-file-to-tmp.mjs
  components/dropbox/actions/list-file-folders-in-a-folder/list-file-folders-in-a-folder.mjs
  components/dropbox/actions/list-file-revisions/list-file-revisions.mjs
  components/dropbox/actions/move-file-folder/move-file-folder.mjs
  components/dropbox/actions/rename-file-folder/rename-file-folder.mjs
  components/dropbox/actions/restore-a-file/restore-a-file.mjs
  components/dropbox/actions/search-files-folders/search-files-folders.mjs
  components/dropbox/actions/upload-file/upload-file.mjs
  components/dropbox/common/consts.mjs
  components/dropbox/dropbox.app.mjs
  components/dropbox/package.json
  components/dropbox/sources/all-updates/all-updates.mjs
  components/dropbox/sources/all-updates/test-event.mjs
  components/dropbox/sources/common/common.mjs
  components/dropbox/sources/new-file/new-file.mjs
  components/dropbox/sources/new-folder/new-folder.mjs
  components/dropbox/sources/new-folder/test-event.mjs
Labels: triaged

#12910 New Components - mailblaze
  components/mailblaze/actions/add-subscriber/add-subscriber.mjs
  components/mailblaze/actions/common/base.mjs
  components/mailblaze/actions/update-subscriber/update-subscriber.mjs
  components/mailblaze/mailblaze.app.mjs
  components/mailblaze/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#12927 New Components - typeflowai
  components/typeflowai/package.json
  components/typeflowai/sources/common/base.mjs
  components/typeflowai/sources/new-response-created/new-response-created.mjs
  components/typeflowai/sources/new-response-created/test-event.mjs
  components/typeflowai/sources/new-response-finished/new-response-finished.mjs
  components/typeflowai/sources/new-response-finished/test-event.mjs
  components/typeflowai/sources/new-response-updated/new-response-updated.mjs
  components/typeflowai/sources/new-response-updated/test-event.mjs
  components/typeflowai/typeflowai.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12926 New Components - specific
  components/specific/actions/create-conversation/create-conversation.mjs
  components/specific/actions/find-company/find-company.mjs
  components/specific/actions/update-create-contact/update-create-contact.mjs
  components/specific/common/utils.mjs
  components/specific/package.json
  components/specific/sources/common/base.mjs
  components/specific/sources/new-contact-instant/new-contact-instant.mjs
  components/specific/sources/new-contact-instant/test-event.mjs
  components/specific/sources/new-conversation-instant/new-conversation-instant.mjs
  components/specific/sources/new-conversation-instant/test-event.mjs
  components/specific/specific.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12900 New Components - documerge
  components/documerge/actions/combine-files/combine-files.mjs
  components/documerge/actions/convert-file-to-pdf/convert-file-to-pdf.mjs
  components/documerge/actions/get-document-fields/get-document-fields.mjs
  components/documerge/documerge.app.mjs
  components/documerge/package.json
  components/documerge/sources/common/base.mjs
  components/documerge/sources/new-merged-document-instant/new-merged-document-instant.mjs
  components/documerge/sources/new-merged-document-instant/test-event.mjs
  components/documerge/sources/new-merged-route-instant/new-merged-route-instant.mjs
  components/documerge/sources/new-merged-route-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12949 New Components - v7_go
  components/v7_go/actions/create-entity/create-entity.mjs
  components/v7_go/actions/create-project/create-project.mjs
  components/v7_go/actions/update-entity/update-entity.mjs
  components/v7_go/common/constants.mjs
  components/v7_go/package.json
  components/v7_go/sources/common/base.mjs
  components/v7_go/sources/complete-entity-instant/complete-entity-instant.mjs
  components/v7_go/sources/complete-entity-instant/test-event.mjs
  components/v7_go/sources/complete-field-instant/complete-field-instant.mjs
  components/v7_go/sources/complete-field-instant/test-event.mjs
  components/v7_go/sources/new-entity-instant/new-entity-instant.mjs
  components/v7_go/sources/new-entity-instant/test-event.mjs
  components/v7_go/v7_go.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12642 New Components - dropboard
  components/dropboard/actions/create-client/create-client.mjs
  components/dropboard/actions/create-job/create-job.mjs
  components/dropboard/actions/find-or-create-client/find-or-create-client.mjs
  components/dropboard/common/utils.mjs
  components/dropboard/dropboard.app.mjs
  components/dropboard/package.json
  components/dropboard/sources/common/base.mjs
  components/dropboard/sources/new-candidate-instant/new-candidate-instant.mjs
  components/dropboard/sources/new-candidate-instant/test-event.mjs
  components/dropboard/sources/new-client-member-instant/new-client-member-instant.mjs
  components/dropboard/sources/new-client-member-instant/test-event.mjs
  components/dropboard/sources/new-job-instant/new-job-instant.mjs
  components/dropboard/sources/new-job-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#12843 New Components - _1crm
  components/_1crm/_1crm.app.mjs
  components/_1crm/actions/common/base.mjs
  components/_1crm/actions/create-contact/create-contact.mjs
  components/_1crm/actions/create-lead/create-lead.mjs
  components/_1crm/actions/update-contact/update-contact.mjs
  components/_1crm/actions/update-lead/update-lead.mjs
  components/_1crm/common/constants.mjs
  components/_1crm/package.json
  components/_1crm/yarn.lock
  pnpm-lock.yaml
Labels: ai-assisted

#13003 New Components - pdffiller
  components/pdffiller/actions/create-distributable-form-generate-link/create-distributable-form-generate-link.mjs
  components/pdffiller/actions/find-document/find-document.mjs
  components/pdffiller/actions/upload-document/upload-document.mjs
  components/pdffiller/common/constants.mjs
  components/pdffiller/common/utils.mjs
  components/pdffiller/package.json
  components/pdffiller/pdffiller.app.mjs
  components/pdffiller/sources/common/base-polling.mjs
  components/pdffiller/sources/common/base-webhook.mjs
  components/pdffiller/sources/new-document/new-document.mjs
  components/pdffiller/sources/new-document/test-event.mjs
  components/pdffiller/sources/new-filled-form-instant/new-filled-form-instant.mjs
  components/pdffiller/sources/new-filled-form-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted
