Repository PipedreamHQ/pipedream, pull requests merged in 2024-10, with the labels that each got.

#14115 New Components - l2s
  components/l2s/actions/create-shortened-url/create-shortened-url.mjs
  components/l2s/common/utils.mjs
  components/l2s/l2s.app.mjs
  components/l2s/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#14133 New Components - moaform
  components/moaform/common/constants.mjs
  components/moaform/moaform.app.mjs
  components/moaform/package.json
  components/moaform/sources/new-submission-instant/new-submission-instant.mjs
  components/moaform/sources/new-submission-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14203 New Components - Docnify
  components/attio/attio.app.mjs
  components/bitbadges/bitbadges.app.mjs
  components/docnify/actions/add-recipient-to-document/add-recipient-to-document.mjs
  components/docnify/actions/create-document-from-template/create-document-from-template.mjs
  components/docnify/actions/send-document/send-document.mjs
  components/docnify/docnify.app.mjs
  components/docnify/package.json
  components/docnify/sources/common/base.mjs
  components/docnify/sources/new-document-completed/new-document-completed.mjs
  components/docnify/sources/new-document-completed/test-event.mjs
  components/docnify/sources/new-document-created/new-document-created.mjs
  components/docnify/sources/new-document-created/test-event.mjs
  components/docnify/sources/new-document-signed/new-document-signed.mjs
  components/docnify/sources/new-document-signed/test-event.mjs
  components/if_else/if_else.app.mjs
  components/switch/switch.app.mjs
  pnpm-lock.yaml
Labels: User submitted

#14066 New Components - highergov
  components/highergov/highergov.app.mjs
  components/highergov/package.json
  components/highergov/sources/new-pursuit-added-instant/new-pursuit-added-instant.mjs
  components/highergov/sources/new-pursuit-added-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14221 New Components - allocadence
  components/allocadence/actions/create-customer-order/create-customer-order.mjs
  components/allocadence/actions/create-purchase-order/create-purchase-order.mjs
  components/allocadence/allocadence.app.mjs
  components/allocadence/common/constants.mjs
  components/allocadence/common/utils.mjs
  components/allocadence/package.json
  components/allocadence/sources/common/base.mjs
  components/allocadence/sources/new-customer-order/new-customer-order.mjs
  components/allocadence/sources/new-customer-order/test-event.mjs
  components/allocadence/sources/new-purchase-order/new-purchase-order.mjs
  components/allocadence/sources/new-purchase-order/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14153 New Components - helpspot
  components/helpspot/actions/common/request-base.mjs
  components/helpspot/actions/create-request/create-request.mjs
  components/helpspot/actions/update-request/update-request.mjs
  components/helpspot/common/constants.mjs
  components/helpspot/common/utils.mjs
  components/helpspot/helpspot.app.mjs
  components/helpspot/package.json
  components/helpspot/sources/common/base.mjs
  components/helpspot/sources/new-request/new-request.mjs
  components/helpspot/sources/new-request/test-event.mjs
  components/helpspot/sources/request-update/request-update.mjs
  components/helpspot/sources/request-update/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14143 New Components - vida
  components/vida/actions/provide-context/provide-context.mjs
  components/vida/package.json
  components/vida/sources/common/base.mjs
  components/vida/sources/new-conversation-instant/new-conversation-instant.mjs
  components/vida/sources/new-conversation-instant/test-event.mjs
  components/vida/sources/new-incoming-conversation-instant/new-incoming-conversation-instant.mjs
  components/vida/sources/new-incoming-conversation-instant/test-event.mjs
  components/vida/vida.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14278 [Components] ollama: new action components
  components/ollama/actions/copy-model/copy-model.mjs
  components/ollama/actions/create-model/create-model.mjs
  components/ollama/actions/delete-model/delete-model.mjs
  components/ollama/actions/generate-chat-completion/generate-chat-completion.mjs
  components/ollama/actions/generate-completion/generate-completion.mjs
  components/ollama/actions/generate-embeddings/generate-embeddings.mjs
  components/ollama/actions/list-local-models/list-local-models.mjs
  components/ollama/actions/pull-model/pull-model.mjs
  components/ollama/actions/push-model/push-model.mjs
  components/ollama/actions/show-model-information/show-model-information.mjs
  components/ollama/common/utils.mjs
  components/ollama/ollama.app.mjs
  components/ollama/package.json
  pnpm-lock.yaml
Labels: action

#14237 New Components - pdfmonkey
  components/pdfmonkey/.gitignore
  components/pdfmonkey/actions/delete-document/delete-document.mjs
  components/pdfmonkey/actions/find-document/find-document.mjs
  components/pdfmonkey/actions/generate-document/generate-document.mjs
  components/pdfmonkey/app/pdfmonkey.app.ts
  components/pdfmonkey/common/constants.mjs
  components/pdfmonkey/package.json
  components/pdfmonkey/pdfmonkey.app.mjs
  components/pdfmonkey/sources/new-document-generated/new-document-generated.mjs
  components/pdfmonkey/sources/new-document-generated/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13961 New Components - fakturoid
  components/fakturoid/actions/cancel-uncancel-invoice/cancel-uncancel-invoice.mjs
  components/fakturoid/actions/create-invoice/create-invoice.mjs
  components/fakturoid/actions/pay-remove-payment-invoice/pay-remove-payment-invoice.mjs
  components/fakturoid/common/constants.mjs
  components/fakturoid/common/utils.mjs
  components/fakturoid/fakturoid.app.mjs
  components/fakturoid/package.json
  components/fakturoid/sources/common/base.mjs
  components/fakturoid/sources/invoice-updated/invoice-updated.mjs
  components/fakturoid/sources/invoice-updated/test-event.mjs
  components/fakturoid/sources/new-contact/new-contact.mjs
  components/fakturoid/sources/new-contact/test-event.mjs
  components/fakturoid/sources/new-invoice/new-invoice.mjs
  components/fakturoid/sources/new-invoice/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14276 New Components - wati
  components/wati/.gitignore
  components/wati/actions/add-contact/add-contact.mjs
  components/wati/actions/send-template-message/send-template-message.mjs
  components/wati/actions/update-contact-attribute/update-contact-attribute.mjs
  components/wati/app/wati.app.ts
  components/wati/package.json
  components/wati/sources/common/base.mjs
  components/wati/sources/new-contact-created/new-contact-created.mjs
  components/wati/sources/new-contact-created/test-event.mjs
  components/wati/sources/new-incoming-message/new-incoming-message.mjs
  components/wati/sources/new-incoming-message/test-event.mjs
  components/wati/wati.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14331 New Components - teach_n_go
  components/teach_n_go/actions/create-prospect/create-prospect.mjs
  components/teach_n_go/actions/create-student/create-student.mjs
  components/teach_n_go/common/constants.mjs
  components/teach_n_go/common/utils.mjs
  components/teach_n_go/package.json
  components/teach_n_go/sources/common/base.mjs
  components/teach_n_go/sources/new-class/new-class.mjs
  components/teach_n_go/sources/new-class/test-event.mjs
  components/teach_n_go/sources/new-student/new-student.mjs
  components/teach_n_go/sources/new-student/test-event.mjs
  components/teach_n_go/teach_n_go.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14352 New Components - deepimage
  components/deepimage/actions/auto-enhance/auto-enhance.mjs
  components/deepimage/actions/remove-background/remove-background.mjs
  components/deepimage/actions/upscale/upscale.mjs
  components/deepimage/common/constants.mjs
  components/deepimage/common/utils.mjs
  components/deepimage/deepimage.app.mjs
  components/deepimage/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#14378 New Components - smstools
  components/smstools/actions/add-contact-opt-out/add-contact-opt-out.mjs
  components/smstools/actions/add-contact/add-contact.mjs
  components/smstools/actions/send-sms/send-sms.mjs
  components/smstools/package.json
  components/smstools/smstools.app.mjs
  components/smstools/sources/new-inbound-message/new-inbound-message.mjs
  components/smstools/sources/new-inbound-message/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14307 New Components - everhour
  components/everhour/actions/create-task/create-task.mjs
  components/everhour/actions/start-timer/start-timer.mjs
  components/everhour/actions/stop-timer/stop-timer.mjs
  components/everhour/common/constants.mjs
  components/everhour/common/utils.mjs
  components/everhour/everhour.app.mjs
  components/everhour/package.json
  components/everhour/sources/common/base.mjs
  components/everhour/sources/new-client-instant/new-client-instant.mjs
  components/everhour/sources/new-client-instant/test-event.mjs
  components/everhour/sources/new-task-instant/new-task-instant.mjs
  components/everhour/sources/new-task-instant/test-event.mjs
  components/everhour/sources/task-time-updated-instant/task-time-updated-instant.mjs
  components/everhour/sources/task-time-updated-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#14422 Upgrade Supabase JS Client
  components/supabase/actions/delete-row/delete-row.mjs
  components/supabase/actions/insert-row/insert-row.mjs
  components/supabase/actions/remote-procedure-call/remote-procedure-call.mjs
  components/supabase/actions/select-row/select-row.mjs
  components/supabase/actions/update-row/update-row.mjs
  components/supabase/actions/upsert-row/upsert-row.mjs
  components/supabase/package.json
  components/supabase/sources/new-row-added/new-row-added.mjs
  components/supabase/sources/new-webhook-event/new-webhook-event.mjs
  components/supabase/supabase.app.mjs
  pnpm-lock.yaml
Labels: bug, dependencies, javascript

#14423 New Components - papersign
  components/papersign/actions/copy-document/copy-document.mjs
  components/papersign/actions/get-document/get-document.mjs
  components/papersign/actions/send-document/send-document.mjs
  components/papersign/common/constants.mjs
  components/papersign/common/utils.mjs
  components/papersign/package.json
  components/papersign/papersign.app.mjs
  components/papersign/sources/common/base.mjs
  components/papersign/sources/new-document-completed-instant/new-document-completed-instant.mjs
  components/papersign/sources/new-document-completed-instant/test-event.mjs
  components/papersign/sources/new-event-instant/new-event-instant.mjs
  components/papersign/sources/new-event-instant/test-event.mjs
  components/papersign/sources/new-signer-signed-instant/new-signer-signed-instant.mjs
  components/papersign/sources/new-signer-signed-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted
