Repository PipedreamHQ/pipedream, pull requests merged in 2024-08, with the labels that each got.

#12965 New Components - otter_waiver
  components/otter_waiver/otter_waiver.app.mjs
  components/otter_waiver/package.json
  components/otter_waiver/sources/common/base.mjs
  components/otter_waiver/sources/new-check-in-instant/new-check-in-instant.mjs
  components/otter_waiver/sources/new-check-in-instant/test-event.mjs
  components/otter_waiver/sources/new-signee-instant/new-signee-instant.mjs
  components/otter_waiver/sources/new-signee-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13018 New Paystack Action: Charge Authorization
  components/paystack/actions/charge-authorization/charge-authorization.mjs
  components/paystack/actions/fetch-transaction/fetch-transaction.mjs
  components/paystack/actions/initialize-transaction/initialize-transaction.mjs
  components/paystack/actions/list-transactions/list-transactions.mjs
  components/paystack/actions/verify-transaction/verify-transaction.mjs
  components/paystack/package.json
  components/paystack/paystack.app.mjs
Labels: triaged, User submitted

#13101 [Google My Business] small fixes on last run timestamp
  components/google_my_business/package.json
  components/google_my_business/sources/common.ts
  components/google_my_business/sources/new-post-created/new-post-created.ts
  components/google_my_business/sources/new-review-created/new-review-created.ts
Labels: triaged

#13116 New Are na Actions: Get Authenticated User & Search
  components/are_na/actions/get-authenticated-user/get-authenticated-user.mjs
  components/are_na/actions/search/search.mjs
  components/are_na/are_na.app.mjs
  components/are_na/package.json
  pnpm-lock.yaml
Labels: triaged, User submitted

#13040 New Components - hubstaff
  components/hubstaff/actions/create-task/create-task.mjs
  components/hubstaff/actions/list-tasks/list-tasks.mjs
  components/hubstaff/actions/update-task/update-task.mjs
  components/hubstaff/common/constants.mjs
  components/hubstaff/common/utils.mjs
  components/hubstaff/hubstaff.app.mjs
  components/hubstaff/package.json
  components/hubstaff/sources/common/base.mjs
  components/hubstaff/sources/new-client/new-client.mjs
  components/hubstaff/sources/new-client/test-event.mjs
  components/hubstaff/sources/new-schedule/new-schedule.mjs
  components/hubstaff/sources/new-schedule/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13126 New Components - gami5d
  components/gami5d/actions/record-observation/record-observation.mjs
  components/gami5d/gami5d.app.mjs
  components/gami5d/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#13119 New Components - whautomate
  components/whautomate/actions/assign-tags-contact/assign-tags-contact.mjs
  components/whautomate/actions/create-contact/create-contact.mjs
  components/whautomate/actions/send-whatsapp-template-message/send-whatsapp-template-message.mjs
  components/whautomate/common/constants.mjs
  components/whautomate/common/utils.mjs
  components/whautomate/package.json
  components/whautomate/sources/common/base.mjs
  components/whautomate/sources/new-appointment-cancelled-instant/new-appointment-cancelled-instant.mjs
  components/whautomate/sources/new-appointment-cancelled-instant/test-event.mjs
  components/whautomate/sources/new-appointment-scheduled-instant/new-appointment-scheduled-instant.mjs
  components/whautomate/sources/new-appointment-scheduled-instant/test-event.mjs
  components/whautomate/sources/new-client-created-instant/new-client-created-instant.mjs
  components/whautomate/sources/new-client-created-instant/test-event.mjs
  components/whautomate/whautomate.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13359 New Components - blogify
  components/blogify/blogify.app.mjs
  components/blogify/package.json
  components/blogify/sources/new-blog-instant/new-blog-instant.mjs
  components/blogify/sources/new-blog-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13130 New Components - dart
  components/dart/actions/create-task/create-task.mjs
  components/dart/actions/find-or-create-task/find-or-create-task.mjs
  components/dart/actions/update-task/update-task.mjs
  components/dart/common/constants.mjs
  components/dart/dart.app.mjs
  components/dart/package.json
  components/dart/sources/common/base.mjs
  components/dart/sources/new-doc-created/new-doc-created.mjs
  components/dart/sources/new-doc-created/test-event.mjs
  components/dart/sources/new-doc-updated/new-doc-updated.mjs
  components/dart/sources/new-doc-updated/test-event.mjs
  components/dart/sources/new-task-created/new-task-created.mjs
  components/dart/sources/new-task-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13138 New Components - airfocus
  components/airfocus/actions/create-item/create-item.mjs
  components/airfocus/actions/delete-item/delete-item.mjs
  components/airfocus/actions/search-item/search-item.mjs
  components/airfocus/actions/update-item/update-item.mjs
  components/airfocus/airfocus.app.mjs
  components/airfocus/common/constants.mjs
  components/airfocus/common/utils.mjs
  components/airfocus/package.json
  components/airfocus/sources/common/base.mjs
  components/airfocus/sources/new-item-created-or-updated/new-item-created-or-updated.mjs
  components/airfocus/sources/new-item-created-or-updated/test-event.mjs
  components/airfocus/sources/new-item-created/new-item-created.mjs
  components/airfocus/sources/new-item-created/test-event.mjs
  components/airfocus/sources/new-item-updated/new-item-updated.mjs
  components/airfocus/sources/new-item-updated/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13493 add actions in app
  components/remote_retrieval/README.md
  components/remote_retrieval/actions/get-pending-orders/get-pending-orders.mjs
  components/remote_retrieval/actions/get-specific-order/get-specific-order.mjs
  components/remote_retrieval/common/constants.mjs
  components/remote_retrieval/common/utils.mjs
  components/remote_retrieval/package.json
  components/remote_retrieval/remote_retrieval.app.mjs
  pnpm-lock.yaml
Labels: triaged, User submitted

#13496 New Components - cloudpresenter
  components/cloudpresenter/actions/create-contact/create-contact.mjs
  components/cloudpresenter/actions/update-contact/update-contact.mjs
  components/cloudpresenter/cloudpresenter.app.mjs
  components/cloudpresenter/common/utils.mjs
  components/cloudpresenter/package.json
  components/cloudpresenter/sources/new-contact-created/new-contact-created.mjs
  components/cloudpresenter/sources/new-contact-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13251 New Components - byteforms
  components/byteforms/byteforms.app.mjs
  components/byteforms/package.json
  components/byteforms/sources/new-submission/new-submission.mjs
  components/byteforms/sources/new-submission/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13571 Adding Github org admin check
  components/github/github.app.mjs
  components/github/package.json
  components/github/sources/common/common-webhook-orgs.mjs
  components/github/sources/common/utils.mjs
  components/github/sources/new-issue-with-status/new-issue-with-status.mjs
Labels: triaged

#13154 New Components - connecteam
  components/connecteam/actions/create-shift/create-shift.mjs
  components/connecteam/actions/create-user/create-user.mjs
  components/connecteam/actions/delete-shift/delete-shift.mjs
  components/connecteam/common/constants.mjs
  components/connecteam/common/utils.mjs
  components/connecteam/connecteam.app.mjs
  components/connecteam/package.json
  components/connecteam/sources/common/base.mjs
  components/connecteam/sources/new-form-submission/new-form-submission.mjs
  components/connecteam/sources/new-form-submission/test-event.mjs
  components/connecteam/sources/new-shift-schedule/new-shift-schedule.mjs
  components/connecteam/sources/new-shift-schedule/test-event.mjs
  components/connecteam/sources/new-user/new-user.mjs
  components/connecteam/sources/new-user/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13494 New Components - rentman
  components/rentman/actions/create-item/create-item.mjs
  components/rentman/actions/find-item/find-item.mjs
  components/rentman/actions/update-item/update-item.mjs
  components/rentman/common/constants.mjs
  components/rentman/common/props.mjs
  components/rentman/common/utils.mjs
  components/rentman/node_modules/@pipedream/platform
  components/rentman/package.json
  components/rentman/rentman.app.mjs
  components/rentman/sources/common/base.mjs
  components/rentman/sources/new-file-updated/new-file-updated.mjs
  components/rentman/sources/new-file-updated/test-event.mjs
  components/rentman/sources/new-item-created/new-item-created.mjs
  components/rentman/sources/new-item-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13577 New Components - heyzine
  components/heyzine/actions/create-flipbook/create-flipbook.mjs
  components/heyzine/heyzine.app.mjs
  components/heyzine/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#13501 New Components - gagelist
  components/gagelist/actions/create-gage/create-gage.mjs
  components/gagelist/actions/find-gage-by-id/find-gage-by-id.mjs
  components/gagelist/actions/update-gage/update-gage.mjs
  components/gagelist/common/constants.mjs
  components/gagelist/gagelist.app.mjs
  components/gagelist/package.json
  components/gagelist/sources/common/base.mjs
  components/gagelist/sources/new-calibration/new-calibration.mjs
  components/gagelist/sources/new-calibration/test-event.mjs
  components/gagelist/sources/new-gage/new-gage.mjs
  components/gagelist/sources/new-gage/test-event.mjs
  components/gagelist/sources/new-manufacturer/new-manufacturer.mjs
  components/gagelist/sources/new-manufacturer/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13575 New Components - addresszen
  components/addresszen/actions/freeform-verify-correct-us-address/freeform-verify-correct-us-address.mjs
  components/addresszen/actions/verify-correct-us-address-city-state/verify-correct-us-address-city-state.mjs
  components/addresszen/actions/verify-correct-us-address-zip-code/verify-correct-us-address-zip-code.mjs
  components/addresszen/addresszen.app.mjs
  components/addresszen/common/constants.mjs
  components/addresszen/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#13574 New Components - firecrawl
  components/firecrawl/actions/crawl-url/crawl-url.mjs
  components/firecrawl/actions/get-crawl-status/get-crawl-status.mjs
  components/firecrawl/actions/scrape-page/scrape-page.mjs
  components/firecrawl/common/utils.mjs
  components/firecrawl/firecrawl.app.mjs
  components/firecrawl/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#13619 Update documentation on workflow memory setting
  docs-v2/pages/workflows/settings.mdx
Labels: docs

#13616 New Components - activecalculator
  components/activecalculator/activecalculator.app.mjs
  components/activecalculator/common/constants.mjs
  components/activecalculator/common/utils.mjs
  components/activecalculator/package.json
  components/activecalculator/sources/new-submission-instant/new-submission-instant.mjs
  components/activecalculator/sources/new-submission-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13705 New Components - swapcard_exhibitor
  components/swapcard_exhibitor/common/constants.mjs
  components/swapcard_exhibitor/common/queries.mjs
  components/swapcard_exhibitor/package.json
  components/swapcard_exhibitor/sources/common/base.mjs
  components/swapcard_exhibitor/sources/new-connection/new-connection.mjs
  components/swapcard_exhibitor/sources/new-connection/test-event.mjs
  components/swapcard_exhibitor/swapcard_exhibitor.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13697 New Components - signerx
  components/signerx/actions/send-template-signatures/send-template-signatures.mjs
  components/signerx/actions/upload-package/upload-package.mjs
  components/signerx/common/utils.mjs
  components/signerx/package.json
  components/signerx/signerx.app.mjs
  components/signerx/sources/common/base.mjs
  components/signerx/sources/new-package-created/new-package-created.mjs
  components/signerx/sources/new-package-created/test-event.mjs
  components/signerx/sources/new-package-published/new-package-published.mjs
  components/signerx/sources/new-package-published/test-event.mjs
  components/signerx/sources/new-package-signed/new-package-signed.mjs
  components/signerx/sources/new-package-signed/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13717 New Components - docsautomator
  components/docsautomator/actions/create-document/create-document.mjs
  components/docsautomator/common/utils.mjs
  components/docsautomator/docsautomator.app.mjs
  components/docsautomator/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#13711 New Components - supabase_management_api
  components/supabase_management_api/actions/create-project/create-project.mjs
  components/supabase_management_api/actions/generate-typescript-types/generate-typescript-types.mjs
  components/supabase_management_api/common/constants.mjs
  components/supabase_management_api/package.json
  components/supabase_management_api/sources/new-backup-completed/new-backup-completed.mjs
  components/supabase_management_api/supabase_management_api.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13728 New Components - gozen_growth
  components/gozen_growth/actions/create-or-update-contact/create-or-update-contact.mjs
  components/gozen_growth/gozen_growth.app.mjs
  components/gozen_growth/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#13708 New Components - adrapid
  components/adrapid/actions/create-banner/create-banner.mjs
  components/adrapid/actions/get-banner/get-banner.mjs
  components/adrapid/adrapid.app.mjs
  components/adrapid/common/constants.mjs
  components/adrapid/common/utils.mjs
  components/adrapid/package.json
  components/adrapid/sources/new-banner-ready/new-banner-ready.mjs
  components/adrapid/sources/new-banner-ready/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#13621 New Components - launchnotes
  components/launchnotes/actions/create-announcement/create-announcement.mjs
  components/launchnotes/actions/create-subscription/create-subscription.mjs
  components/launchnotes/common/constants.mjs
  components/launchnotes/common/mutations.mjs
  components/launchnotes/common/queries.mjs
  components/launchnotes/common/utils.mjs
  components/launchnotes/launchnotes.app.mjs
  components/launchnotes/package.json
  components/launchnotes/sources/common/base.mjs
  components/launchnotes/sources/new-announcement-published/new-announcement-published.mjs
  components/launchnotes/sources/new-announcement-published/test-event.mjs
  components/launchnotes/sources/new-announcement-scheduled/new-announcement-scheduled.mjs
  components/launchnotes/sources/new-announcement-scheduled/test-event.mjs
  components/launchnotes/sources/new-subscription-created/new-subscription-created.mjs
  components/launchnotes/sources/new-subscription-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted
