Repository PipedreamHQ/pipedream, pull requests merged in 2024-02, with the labels that each got.

#10145 New Components - findymail
  components/findymail/actions/create-list/create-list.mjs
  components/findymail/actions/delete-list/delete-list.mjs
  components/findymail/actions/find-email-name-domain/find-email-name-domain.mjs
  components/findymail/actions/find-email/find-email.mjs
  components/findymail/actions/list-contact-lists/list-contact-lists.mjs
  components/findymail/actions/verify-email/verify-email.mjs
  components/findymail/findymail.app.mjs
  components/findymail/package.json
  components/findymail/sources/new-saved-contact/new-saved-contact.mjs
  components/findymail/sources/new-saved-contact/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10136 New Components - publisherkit
  components/publisherkit/actions/create-image/create-image.mjs
  components/publisherkit/package.json
  components/publisherkit/publisherkit.app.mjs
  components/publisherkit/sources/new-template/new-template.mjs
  components/publisherkit/sources/new-template/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10123 New Components - airparser
  components/airparser/actions/extract-data-document/extract-data-document.mjs
  components/airparser/actions/upload-document-parse/upload-document-parse.mjs
  components/airparser/airparser.app.mjs
  components/airparser/package.json
  components/airparser/sources/new-document-parsed/new-document-parsed.mjs
  components/facebook_marketing/facebook_marketing.app.mjs
  components/twitter_ads/twitter_ads.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10018 New Components - *autom*
  components/autom/actions/bing-search/bing-search.mjs
  components/autom/actions/brave-search/brave-search.mjs
  components/autom/actions/google-search/google-search.mjs
  components/autom/autom.app.mjs
  components/autom/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10143 New Components - uberduck
  components/uberduck/actions/generate-lyrics/generate-lyrics.mjs
  components/uberduck/actions/get-voice-samples/get-voice-samples.mjs
  components/uberduck/actions/get-voices/get-voices.mjs
  components/uberduck/package.json
  components/uberduck/uberduck.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10131 New Components - semgrep
  components/semgrep/actions/get-deployments/get-deployments.mjs
  components/semgrep/actions/get-findings/get-findings.mjs
  components/semgrep/actions/get-projects/get-projects.mjs
  components/semgrep/actions/update-project/update-project.mjs
  components/semgrep/package.json
  components/semgrep/semgrep.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10192 Python docs improvements for 3.12
  docs/docs/.vuepress/configs/sidebarConfig.js
  docs/docs/code/nodejs/README.md
  docs/docs/code/nodejs/delay/README.md
  docs/docs/code/python/README.md
  docs/docs/code/python/auth/README.md
  docs/docs/code/python/delay/README.md
  docs/docs/code/python/http-requests/README.md
  docs/docs/code/python/using-data-stores/README.md
  docs/docs/code/python/working-with-files/README.md
  vercel.json
Labels: docs

#10208 New Components - livesession
  components/livesession/common/constants.mjs
  components/livesession/livesession.app.mjs
  components/livesession/package.json
  components/livesession/sources/new-session/new-session.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10211 New Components - dailybot
  components/dailybot/actions/give-kudos/give-kudos.mjs
  components/dailybot/actions/send-message/send-message.mjs
  components/dailybot/common/constants.mjs
  components/dailybot/common/utils.mjs
  components/dailybot/dailybot.app.mjs
  components/dailybot/package.json
  components/dailybot/sources/common/base.mjs
  components/dailybot/sources/kudos-given-instant/kudos-given-instant.mjs
  components/dailybot/sources/kudos-given-instant/test-event.mjs
  components/dailybot/sources/new-check-in-response-completed-instant/new-check-in-response-completed-instant.mjs
  components/dailybot/sources/new-check-in-response-completed-instant/test-event.mjs
  components/dailybot/sources/new-form-response-completed-instant/new-form-response-completed-instant.mjs
  components/dailybot/sources/new-form-response-completed-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10148 New Components - dexatel
  components/dexatel/actions/create-contact/create-contact.mjs
  components/dexatel/actions/send-bulk-sms/send-bulk-sms.mjs
  components/dexatel/actions/send-single-sms/send-single-sms.mjs
  components/dexatel/common/utils.mjs
  components/dexatel/dexatel.app.mjs
  components/dexatel/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10150 Add parameterizedSearch method to Salesforce REST API component
  components/salesforce_rest_api/actions/add-contact-to-campaign/add-contact-to-campaign.mjs
  components/salesforce_rest_api/actions/add-lead-to-campaign/add-lead-to-campaign.mjs
  components/salesforce_rest_api/actions/convert-soap-xml-to-json/convert-soap-xml-to-json.mjs
  components/salesforce_rest_api/actions/create-account/create-account.mjs
  components/salesforce_rest_api/actions/create-attachment/create-attachment.mjs
  components/salesforce_rest_api/actions/create-campaign/create-campaign.mjs
  components/salesforce_rest_api/actions/create-case/create-case.mjs
  components/salesforce_rest_api/actions/create-casecomment/create-casecomment.mjs
  components/salesforce_rest_api/actions/create-contact/create-contact.mjs
  components/salesforce_rest_api/actions/create-event/create-event.mjs
  components/salesforce_rest_api/actions/create-lead/create-lead.mjs
  components/salesforce_rest_api/actions/create-note/create-note.mjs
  components/salesforce_rest_api/actions/create-opportunity/create-opportunity.mjs
  components/salesforce_rest_api/actions/create-record/create-record.mjs
  components/salesforce_rest_api/actions/create-task/create-task.mjs
  components/salesforce_rest_api/actions/delete-opportunity/delete-opportunity.mjs
  components/salesforce_rest_api/actions/delete-record/delete-record.mjs
  components/salesforce_rest_api/actions/find-create-record/find-create-record.mjs
  components/salesforce_rest_api/actions/find-records/find-records.mjs
  components/salesforce_rest_api/actions/get-sobject-fields-values/get-sobject-fields-values.mjs
  components/salesforce_rest_api/actions/insert-blob-data/insert-blob-data.mjs
  components/salesforce_rest_api/actions/post-feed-to-chatter/post-feed-to-chatter.mjs
  components/salesforce_rest_api/actions/search-string/search-string.mjs
  components/salesforce_rest_api/actions/soql-search/soql-search.mjs
  components/salesforce_rest_api/actions/sosl-search/sosl-search.mjs
  components/salesforce_rest_api/actions/update-account/update-account.mjs
  components/salesforce_rest_api/actions/update-contact/update-contact.mjs
  components/salesforce_rest_api/actions/update-opportunity/update-opportunity.mjs
  components/salesforce_rest_api/actions/update-record/update-record.mjs
  components/salesforce_rest_api/package.json
  components/salesforce_rest_api/salesforce_rest_api.app.mjs
  components/salesforce_rest_api/sources/new-outbound-message/new-outbound-message.mjs
  components/salesforce_rest_api/sources/new-record-instant/new-record-instant.mjs
  components/salesforce_rest_api/sources/new-record/new-record.mjs
  components/salesforce_rest_api/sources/object-updated-instant/object-updated-instant.mjs
  components/salesforce_rest_api/sources/object-updated/object-updated.mjs
  components/salesforce_rest_api/sources/record-deleted-instant/record-deleted-instant.mjs
  components/salesforce_rest_api/sources/record-deleted/record-deleted.mjs
  components/salesforce_rest_api/sources/updated-field-on-record-instant/updated-field-on-record-instant.mjs
  components/salesforce_rest_api/sources/updated-field-on-record/updated-field-on-record.mjs
  pnpm-lock.yaml
Labels: triaged, User submitted

#10119 New Components - omnisend
  components/omnisend/.gitignore
  components/omnisend/actions/start-campaign/start-campaign.mjs
  components/omnisend/actions/track-event/track-event.mjs
  components/omnisend/actions/update-contact/update-contact.mjs
  components/omnisend/app/omnisend.app.ts
  components/omnisend/common/constants.mjs
  components/omnisend/common/utils.mjs
  components/omnisend/omnisend.app.mjs
  components/omnisend/package.json
  components/omnisend/sources/common/base.mjs
  components/omnisend/sources/new-contact-created/new-contact-created.mjs
  components/omnisend/sources/new-contact-created/test-event.mjs
  components/omnisend/sources/new-order-completed/new-order-completed.mjs
  components/omnisend/sources/new-order-completed/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10232 New Components - altoviz
  components/altoviz/actions/create-customer/create-customer.mjs
  components/altoviz/actions/create-product/create-product.mjs
  components/altoviz/actions/find-product/find-product.mjs
  components/altoviz/actions/send-sales-invoice/send-sales-invoice.mjs
  components/altoviz/altoviz.app.mjs
  components/altoviz/package.json
  components/altoviz/sources/common/base-webhook.mjs
  components/altoviz/sources/new-contact-instant/new-contact-instant.mjs
  components/altoviz/sources/new-contact-instant/test-event.mjs
  components/altoviz/sources/new-product-instant/new-product-instant.mjs
  components/altoviz/sources/new-product-instant/test-event.mjs
  components/altoviz/sources/new-sales-invoice-instant/new-sales-invoice-instant.mjs
  components/altoviz/sources/new-sales-invoice-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10237 New Components - jobber
  components/jobber/.gitignore
  components/jobber/actions/create-client/create-client.mjs
  components/jobber/actions/create-quote/create-quote.mjs
  components/jobber/actions/create-request/create-request.mjs
  components/jobber/app/jobber.app.ts
  components/jobber/jobber.app.mjs
  components/jobber/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10191 New Components - white-swan
  components/white_swan/actions/create-pre-fill-info/create-pre-fill-info.mjs
  components/white_swan/actions/get-referred-clients-info/get-referred-clients-info.mjs
  components/white_swan/actions/submit-complete-plan-request/submit-complete-plan-request.mjs
  components/white_swan/common/constants.mjs
  components/white_swan/common/utils.mjs
  components/white_swan/package.json
  components/white_swan/sources/common/base-polling.mjs
  components/white_swan/sources/new-earnings-event/new-earnings-event.mjs
  components/white_swan/sources/new-personal-plan/new-personal-plan.mjs
  components/white_swan/white_swan.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10240 New Components - async_interview
  components/async_interview/async_interview.app.mjs
  components/async_interview/package.json
  components/async_interview/sources/new-interview-response/new-interview-response.mjs
  components/async_interview/sources/new-interview-response/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10204 New Components - sessions
  components/sessions/package.json
  components/sessions/sessions.app.mjs
  components/sessions/sources/common/polling.mjs
  components/sessions/sources/new-session-ended/new-session-ended.mjs
  components/sessions/sources/new-session-started/new-session-started.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10260 New Components - chargeblast
  components/chargeblast/chargeblast.app.mjs
  components/chargeblast/package.json
  components/chargeblast/sources/new-alert/new-alert.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10264 New Components - 0codekit
  components/_0codekit/_0codekit.app.mjs
  components/_0codekit/actions/compress-pdf/compress-pdf.mjs
  components/_0codekit/actions/read-barcode/read-barcode.mjs
  components/_0codekit/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10253 New Components - expedy
  components/expedy/actions/create-print-job/create-print-job.mjs
  components/expedy/expedy.app.mjs
  components/expedy/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10263 New Components - btcpay-server
  components/btcpay_server/actions/create-payment-request/create-payment-request.mjs
  components/btcpay_server/actions/get-store-on-chain-wallet-balance/get-store-on-chain-wallet-balance.mjs
  components/btcpay_server/btcpay_server.app.mjs
  components/btcpay_server/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10276 New Components - herobot_chatbot_marketing
  components/herobot_chatbot_marketing/actions/create-custom-field/create-custom-field.mjs
  components/herobot_chatbot_marketing/actions/create-user/create-user.mjs
  components/herobot_chatbot_marketing/actions/send-message/send-message.mjs
  components/herobot_chatbot_marketing/common/constants.mjs
  components/herobot_chatbot_marketing/common/utils.mjs
  components/herobot_chatbot_marketing/herobot_chatbot_marketing.app.mjs
  components/herobot_chatbot_marketing/package.json
  components/herobot_chatbot_marketing/sources/new-tag-added/new-tag-added.mjs
  components/herobot_chatbot_marketing/sources/new-tag-added/test-event.mjs
  components/herobot_chatbot_marketing/sources/new-user-created/new-user-created.mjs
  components/herobot_chatbot_marketing/sources/new-user-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10144 New Components - codescene
  components/codescene/actions/create-project/create-project.mjs
  components/codescene/actions/get-project-analysis/get-project-analysis.mjs
  components/codescene/actions/get-projects/get-projects.mjs
  components/codescene/codescene.app.mjs
  components/codescene/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10275 New Components - formpress
  components/_46elks/_46elks.app.mjs
  components/aevent/aevent.app.mjs
  components/buildchatbot/buildchatbot.app.mjs
  components/chatfai/chatfai.app.mjs
  components/craftboxx/craftboxx.app.mjs
  components/dopplerai/dopplerai.app.mjs
  components/formpress/formpress.app.mjs
  components/formpress/package.json
  components/formpress/sources/new-submission-instant/new-submission-instant.mjs
  components/formpress/sources/new-submission-instant/test-event.mjs
  components/mobygames/mobygames.app.mjs
  components/morningmate/morningmate.app.mjs
  components/ncscale/ncscale.app.mjs
  components/qualetics/qualetics.app.mjs
  components/reform/reform.app.mjs
  components/slite/slite.app.mjs
  components/tableau/tableau.app.mjs
  components/tpscheck/tpscheck.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10339 [Components] https_airbyte_com #9449
  components/https_airbyte_com/actions/create-workspace/create-workspace.mjs
  components/https_airbyte_com/actions/delete-workspace/delete-workspace.mjs
  components/https_airbyte_com/actions/list-workspaces/list-workspaces.mjs
  components/https_airbyte_com/actions/update-workspace/update-workspace.mjs
  components/https_airbyte_com/https_airbyte_com.app.mjs
  components/https_airbyte_com/package.json
  pnpm-lock.yaml
Labels: action

#10324 New Components - chaindesk
  components/chaindesk/.gitignore
  components/chaindesk/actions/submit-message/submit-message.mjs
  components/chaindesk/actions/update-agent/update-agent.mjs
  components/chaindesk/app/chaindesk.app.ts
  components/chaindesk/chaindesk.app.mjs
  components/chaindesk/package.json
  components/chaindesk/sources/new-response-generated/new-response-generated.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10357 New Components - morningmate
  components/morningmate/actions/create-notification/create-notification.mjs
  components/morningmate/actions/create-schedule/create-schedule.mjs
  components/morningmate/actions/create-task/create-task.mjs
  components/morningmate/common/constants.mjs
  components/morningmate/common/utils.mjs
  components/morningmate/morningmate.app.mjs
  components/morningmate/package.json
  components/scoredetect/scoredetect.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10387 New Components - reform
  components/reform/actions/common/utils.mjs
  components/reform/actions/extract-data-from-document/extract-data-from-document.mjs
  components/reform/actions/extract-data-from-text/extract-data-from-text.mjs
  components/reform/package.json
  components/reform/reform.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10320 New Components - qualetics
  components/chatbot_builder/chatbot_builder.app.mjs
  components/faraday/faraday.app.mjs
  components/mctime/mctime.app.mjs
  components/qualetics/actions/run-data-machine/run-data-machine.mjs
  components/qualetics/actions/send-data/send-data.mjs
  components/qualetics/package.json
  components/qualetics/qualetics.app.mjs
  components/shopwaive/shopwaive.app.mjs
  components/templated/templated.app.mjs
  components/yespo/yespo.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10262 Attempt to fix issue with escaped entities in RSS
  components/rss/actions/merge-rss-feeds/merge-rss-feeds.ts
  components/rss/app/rss.app.ts
  components/rss/package.json
  components/rss/sources/new-item-from-multiple-feeds/new-item-from-multiple-feeds.ts
  components/rss/sources/new-item-in-feed/new-item-in-feed.ts
  components/rss/sources/random-item-in-multiple-feeds/random-item-in-multiple-feeds.ts
Labels: triaged, User submitted

#10369 New Components - tpscheck
  components/tpscheck/actions/check-number/check-number.mjs
  components/tpscheck/package.json
  components/tpscheck/tpscheck.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10340 New Components - mx_technologies
  components/mx_technologies/.gitignore
  components/mx_technologies/actions/create-account/create-account.mjs
  components/mx_technologies/actions/create-user/create-user.mjs
  components/mx_technologies/app/mx_technologies.app.ts
  components/mx_technologies/common/constants.mjs
  components/mx_technologies/mx_technologies.app.mjs
  components/mx_technologies/package.json
  components/mx_technologies/sources/new-user-created/new-user-created.mjs
  components/mx_technologies/sources/new-user-created/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10354 New Components - turbot_pipes
  components/turbot_pipes/actions/create-organization/create-organization.mjs
  components/turbot_pipes/actions/delete-organization/delete-organization.mjs
  components/turbot_pipes/actions/update-organization/update-organization.mjs
  components/turbot_pipes/package.json
  components/turbot_pipes/turbot_pipes.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10381 New Components - mobygames
  components/mobygames/actions/list-games/list-games.mjs
  components/mobygames/actions/list-genres/list-genres.mjs
  components/mobygames/actions/list-platforms/list-platforms.mjs
  components/mobygames/mobygames.app.mjs
  components/mobygames/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10431 New Components - little_green_light
  components/little_green_light/.gitignore
  components/little_green_light/actions/add-gift/add-gift.mjs
  components/little_green_light/actions/create-constituent/create-constituent.mjs
  components/little_green_light/actions/update-constituent/update-constituent.mjs
  components/little_green_light/app/little_green_light.app.ts
  components/little_green_light/common/constants.mjs
  components/little_green_light/little_green_light.app.mjs
  components/little_green_light/package.json
  components/little_green_light/sources/common/base.mjs
  components/little_green_light/sources/new-constituent-created/new-constituent-created.mjs
  components/little_green_light/sources/new-constituent-created/test-event.mjs
  components/little_green_light/sources/new-gift-recorded/new-gift-recorded.mjs
  components/little_green_light/sources/new-gift-recorded/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10201 Update fraudlabs_pro component.
  components/api_bible/api_bible.app.mjs
  components/azure_speech_service/azure_speech_service.app.mjs
  components/fraudlabs_pro/actions/send-sms-verification/send-sms-verification.mjs
  components/fraudlabs_pro/actions/verify-otp/verify-otp.mjs
  components/fraudlabs_pro/package.json
  components/mailninja/mailninja.app.mjs
  components/salesforce_rest_api/salesforce_rest_api.app.mjs
  components/whatsable/whatsable.app.mjs
  pnpm-lock.yaml
Labels: triaged, User submitted

#10553 Docsearch dark theme
  docs-v2/styles/globals.css
  docs-v2/theme.config.tsx
  pnpm-lock.yaml
Labels: docs

#10360 New Components - _twocaptcha
  components/_twocaptcha/.gitignore
  components/_twocaptcha/_twocaptcha.app.mjs
  components/_twocaptcha/actions/check-account-balance/check-account-balance.mjs
  components/_twocaptcha/actions/retrieve-solution/retrieve-solution.mjs
  components/_twocaptcha/actions/submit-captcha/submit-captcha.mjs
  components/_twocaptcha/app/_twocaptcha.app.ts
  components/_twocaptcha/common/constants.mjs
  components/_twocaptcha/common/taskProps/amazon.mjs
  components/_twocaptcha/common/taskProps/arkose.mjs
  components/_twocaptcha/common/taskProps/audio.mjs
  components/_twocaptcha/common/taskProps/bounding.mjs
  components/_twocaptcha/common/taskProps/capy.mjs
  components/_twocaptcha/common/taskProps/click.mjs
  components/_twocaptcha/common/taskProps/cloudflare.mjs
  components/_twocaptcha/common/taskProps/cutcaptcha.mjs
  components/_twocaptcha/common/taskProps/cyber.mjs
  components/_twocaptcha/common/taskProps/datadome.mjs
  components/_twocaptcha/common/taskProps/draw.mjs
  components/_twocaptcha/common/taskProps/friendly.mjs
  components/_twocaptcha/common/taskProps/geetest.mjs
  components/_twocaptcha/common/taskProps/grid.mjs
  components/_twocaptcha/common/taskProps/hcap.mjs
  components/_twocaptcha/common/taskProps/index.mjs
  components/_twocaptcha/common/taskProps/key.mjs
  components/_twocaptcha/common/taskProps/lemin.mjs
  components/_twocaptcha/common/taskProps/mt.mjs
  components/_twocaptcha/common/taskProps/normal.mjs
  components/_twocaptcha/common/taskProps/proxy.mjs
  components/_twocaptcha/common/taskProps/reEnter.mjs
  components/_twocaptcha/common/taskProps/rev2.mjs
  components/_twocaptcha/common/taskProps/rev3.mjs
  components/_twocaptcha/common/taskProps/rotate.mjs
  components/_twocaptcha/common/taskProps/text.mjs
  components/_twocaptcha/node_modules/@pipedream/platform
  components/_twocaptcha/package.json
  components/_twocaptcha/sources/balance-updated/balance-updated.mjs
  components/_twocaptcha/sources/balance-updated/test-event.mjs
  components/_twocaptcha/sources/captcha-solved/captcha-solved.mjs
  components/_twocaptcha/sources/captcha-solved/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10273 [Components] whatsable #10268
  components/whatsable/actions/send-message/send-message.mjs
  components/whatsable/package.json
  components/whatsable/whatsable.app.mjs
  pnpm-lock.yaml
Labels: action

#10558 Included All Bookmarks, Unsorted and Trash in collections
  components/raindrop/actions/create-collection/create-collection.mjs
  components/raindrop/actions/delete-bookmark/delete-bookmark.mjs
  components/raindrop/actions/delete-collection/delete-collection.mjs
  components/raindrop/actions/get-bookmark/get-bookmark.mjs
  components/raindrop/actions/get-collection/get-collection.mjs
  components/raindrop/actions/list-collections/list-collections.mjs
  components/raindrop/actions/parse-bookmark-file/parse-bookmark-file.mjs
  components/raindrop/actions/retrieve-bookmarks/retrieve-bookmarks.mjs
  components/raindrop/actions/save/save.mjs
  components/raindrop/actions/update-bookmark/update-bookmark.mjs
  components/raindrop/actions/update-collection/update-collection.mjs
  components/raindrop/package.json
  components/raindrop/raindrop.app.mjs
  components/raindrop/sources/new-bookmark/new-bookmark.mjs
  pnpm-lock.yaml
Labels: triaged, User submitted

#10567 New Components - yespo
  components/yespo/actions/add-update-contact/add-update-contact.mjs
  components/yespo/actions/generate-event/generate-event.mjs
  components/yespo/actions/send-email/send-email.mjs
  components/yespo/common/constants.mjs
  components/yespo/common/utils.mjs
  components/yespo/package.json
  components/yespo/sources/common/base.mjs
  components/yespo/sources/new-contact-in-segment/new-contact-in-segment.mjs
  components/yespo/sources/new-contact-in-segment/test-event.mjs
  components/yespo/sources/new-contact/new-contact.mjs
  components/yespo/sources/new-contact/test-event.mjs
  components/yespo/yespo.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10379 New Components - chaftai
  components/chatfai/actions/generate-message/generate-message.mjs
  components/chatfai/actions/get-character/get-character.mjs
  components/chatfai/actions/search-characters/search-characters.mjs
  components/chatfai/chatfai.app.mjs
  components/chatfai/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10564 New Components - faraday
  components/faraday/actions/predict/predict.mjs
  components/faraday/faraday.app.mjs
  components/faraday/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10500 New Components - interseller
  components/interseller/actions/set-contact-replied/set-contact-replied.mjs
  components/interseller/actions/update-contact/update-contact.mjs
  components/interseller/common/constants.mjs
  components/interseller/interseller.app.mjs
  components/interseller/package.json
  components/interseller/sources/common/base.mjs
  components/interseller/sources/new-contact-replied/new-contact-replied.mjs
  components/interseller/sources/new-contact-replied/test-event.mjs
  components/interseller/sources/new-contact/new-contact.mjs
  components/interseller/sources/new-contact/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10588 New Components - ncscale
  components/ncscale/actions/push-log/push-log.mjs
  components/ncscale/ncscale.app.mjs
  components/ncscale/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10476 New Components - mctime
  components/mctime/actions/start-clocking/start-clocking.mjs
  components/mctime/actions/stop-clocking/stop-clocking.mjs
  components/mctime/common/constants.mjs
  components/mctime/mctime.app.mjs
  components/mctime/package.json
  components/mctime/sources/new-time-entry-started/new-time-entry-started.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10611 New Components - heedjy
  components/heedjy/heedjy.app.mjs
  components/heedjy/package.json
  components/heedjy/sources/new-app-published/new-app-published.mjs
  components/heedjy/sources/new-app-published/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10619 New Components - triggre
  components/triggre/actions/start-automation-flow/start-automation-flow.mjs
  components/triggre/package.json
  components/triggre/triggre.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10632 New Components - thoughtfulgpt
  components/thoughtful_gpt/actions/process-content-macro/process-content-macro.mjs
  components/thoughtful_gpt/actions/process-csv-files/process-csv-files.mjs
  components/thoughtful_gpt/package.json
  components/thoughtful_gpt/thoughtful_gpt.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10620 New Components - keysender
  components/keysender/actions/create-transaction/create-transaction.mjs
  components/keysender/common/constants.mjs
  components/keysender/keysender.app.mjs
  components/keysender/package.json
  pnpm-lock.yaml
Labels: ai-assisted
