Repository PipedreamHQ/pipedream, pull requests merged in 2024-03, with the labels that each got.

#10633 New Components - reviewflowz
  components/reviewflowz/package.json
  components/reviewflowz/reviewflowz.app.mjs
  components/reviewflowz/sources/new-review/new-review.mjs
  components/reviewflowz/sources/new-review/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10604 New Components - nutshell
  components/nutshell/actions/create-company/create-company.mjs
  components/nutshell/actions/create-contact/create-contact.mjs
  components/nutshell/actions/create-lead/create-lead.mjs
  components/nutshell/common/utils.mjs
  components/nutshell/nutshell.app.mjs
  components/nutshell/package.json
  components/nutshell/sources/common/base.mjs
  components/nutshell/sources/lead-won/lead-won.mjs
  components/nutshell/sources/lead-won/test-event.mjs
  components/nutshell/sources/new-lead/new-lead.mjs
  components/nutshell/sources/new-lead/test-event.mjs
  components/nutshell/sources/new-person/new-person.mjs
  components/nutshell/sources/new-person/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10642 Fix component subfolder filename mismatches
  components/bybit/actions/linear-position-set-auto-margin/linear-position-set-auto-margin.mjs
  components/bybit/actions/linear-position-set-trading-stop/linear-position-set-trading-stop.mjs
  components/bybit/package.json
  components/nocrm_io/package.json
  components/nocrm_io/sources/new-lead-status-changed/new-lead-status-changed.mjs
  components/ultramsg/action/send-document/send-document.mjs
  components/ultramsg/package.json
  components/upkeep/package.json
  components/upkeep/sources/purchase-order-status-change/purchase-order-status-change.mjs
  pnpm-lock.yaml
Labels: triaged

#10256 New Components - Paystack
  components/paystack/.gitignore
  components/paystack/actions/initialize-transaction/initialize-transaction.mjs
  components/paystack/app/paystack.app.mjs
  components/paystack/app/paystack.app.ts
  components/paystack/package.json
Labels: triaged, User submitted

#10623 New Components - castmagic
  components/castmagic/actions/get-transcription/get-transcription.mjs
  components/castmagic/actions/submit-transcription-request/submit-transcription-request.mjs
  components/castmagic/castmagic.app.mjs
  components/castmagic/common/constants.mjs
  components/castmagic/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10673 New Components - bluesky_by_unshape
  components/bluesky_by_unshape/actions/create-post/create-post.mjs
  components/bluesky_by_unshape/actions/get-post/get-post.mjs
  components/bluesky_by_unshape/actions/reply-post/reply-post.mjs
  components/bluesky_by_unshape/bluesky_by_unshape.app.mjs
  components/bluesky_by_unshape/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10638 Remove unpublished Linkedin and Shopify components
  components/linkedin/actions/analytics-finder-account-sample/analytics-finder-account-sample.mjs
  components/linkedin/actions/analytics-finder-campaign-sample/analytics-finder-campaign-sample.mjs
  components/linkedin/actions/query-analytics-finder/query-analytics-finder.mjs
  components/shopify/actions/create-customer/create-customer.mjs
  components/shopify/actions/create-order/create-order.mjs
  components/shopify/actions/search-customers/search-customers.mjs
  components/shopify/actions/update-customer/update-customer.mjs
Labels: triaged

#10653 New Components - contentgroove
  components/contentgroove/contentgroove.app.mjs
  components/contentgroove/package.json
  components/contentgroove/sources/new-media-processing-finished-instant/new-media-processing-finished-instant.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10475 New Components - templated
  components/templated/actions/create-render/create-render.mjs
  components/templated/actions/get-template/get-template.mjs
  components/templated/actions/list-template-layers/list-template-layers.mjs
  components/templated/actions/list-templates/list-templates.mjs
  components/templated/package.json
  components/templated/templated.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10471 New Components - rkvst
  components/rkvst/.gitignore
  components/rkvst/actions/create-asset/create-asset.mjs
  components/rkvst/actions/create-event/create-event.mjs
  components/rkvst/app/rkvst.app.ts
  components/rkvst/common/utils.mjs
  components/rkvst/package.json
  components/rkvst/rkvst.app.mjs
  components/rkvst/sources/asset-created/asset-created.mjs
  components/rkvst/sources/asset-created/test-event.mjs
  components/rkvst/sources/common/base.mjs
  components/rkvst/sources/new-event-detected/new-event-detected.mjs
  components/rkvst/sources/new-event-detected/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10785 New Components - lastpass
  components/anyflow/anyflow.app.mjs
  components/diffbot/diffbot.app.mjs
  components/dpd2/dpd2.app.mjs
  components/easypost/easypost.app.mjs
  components/graphy/graphy.app.mjs
  components/lastpass/actions/add-remove-user-in-groups/add-remove-user-in-groups.mjs
  components/lastpass/actions/delete-user/delete-user.mjs
  components/lastpass/common/constants.mjs
  components/lastpass/lastpass.app.mjs
  components/lastpass/package.json
  components/lastpass/sources/new-watch-events/new-watch-events.mjs
  components/lastpass/sources/new-watch-events/test-event.mjs
  components/papertrail/papertrail.app.mjs
  components/pulsetic/pulsetic.app.mjs
  components/reachmail/reachmail.app.mjs
  components/rollbar/rollbar.app.mjs
  components/sendcloud/sendcloud.app.mjs
  components/sendloop/sendloop.app.mjs
  components/similarweb_digitalrank_api/similarweb_digitalrank_api.app.mjs
  components/tento8/tento8.app.mjs
  components/wuf/wuf.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10672 New Components - token_metrics
  components/token_metrics/actions/get-market-metrics/get-market-metrics.mjs
  components/token_metrics/actions/get-tokens/get-tokens.mjs
  components/token_metrics/package.json
  components/token_metrics/token_metrics.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10749 New Components - all_images_ai
  components/all_images_ai/actions/buy-image/buy-image.mjs
  components/all_images_ai/actions/generate-images-advanced/generate-images-advanced.mjs
  components/all_images_ai/actions/get-image-generation/get-image-generation.mjs
  components/all_images_ai/all_images_ai.app.mjs
  components/all_images_ai/common/constants.mjs
  components/all_images_ai/package.json
  components/all_images_ai/sources/new-generation-image-update-instant/new-generation-image-update-instant.mjs
  components/all_images_ai/sources/new-generation-image-update-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10575 Fix pipedream/browsers module-name import in docs
  docs-v2/pages/code/nodejs/browser-automation.mdx
Labels: docs

#10859 New Components - dropmark
  components/dropmark/actions/get-activity/get-activity.mjs
  components/dropmark/actions/get-items-in-collection/get-items-in-collection.mjs
  components/dropmark/dropmark.app.mjs
  components/dropmark/package.json
  components/dropmark/sources/common/base.mjs
  components/dropmark/sources/new-activity/new-activity.mjs
  components/dropmark/sources/new-activity/test-event.mjs
  components/dropmark/sources/new-item-in-collection/new-item-in-collection.mjs
  components/dropmark/sources/new-item-in-collection/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10860 New Components - tawk_to
  components/tawk_to/package.json
  components/tawk_to/sources/chat-ended-instant/chat-ended-instant.mjs
  components/tawk_to/sources/common/base.mjs
  components/tawk_to/sources/new-chat-started-instant/new-chat-started-instant.mjs
  components/tawk_to/sources/new-ticket-instant/new-ticket-instant.mjs
  components/tawk_to/tawk_to.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10851 New Components - dux-soup
  components/dux_soup/actions/connect-profile/connect-profile.mjs
  components/dux_soup/actions/message-profile/message-profile.mjs
  components/dux_soup/actions/save-profile-lead/save-profile-lead.mjs
  components/dux_soup/dux_soup.app.mjs
  components/dux_soup/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10842 New Components - reachmail
  components/reachmail/actions/opt-out-recipient-from-list/opt-out-recipient-from-list.mjs
  components/reachmail/package.json
  components/reachmail/reachmail.app.mjs
  components/reachmail/sources/common/base.mjs
  components/reachmail/sources/new-bounce-instant/new-bounce-instant.mjs
  components/reachmail/sources/new-bounce-instant/test-event.mjs
  components/reachmail/sources/new-click-instant/new-click-instant.mjs
  components/reachmail/sources/new-click-instant/test-event.mjs
  components/reachmail/sources/new-open-instant/new-open-instant.mjs
  components/reachmail/sources/new-open-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10761 New Components - home_connect
  components/home_connect/actions/get-appliances/get-appliances.mjs
  components/home_connect/actions/get-programs/get-programs.mjs
  components/home_connect/actions/get-status/get-status.mjs
  components/home_connect/home_connect.app.mjs
  components/home_connect/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10864 New Components - helpspace
  components/helpspace/actions/create-customer/create-customer.mjs
  components/helpspace/actions/create-ticket/create-ticket.mjs
  components/helpspace/actions/update-customer/update-customer.mjs
  components/helpspace/common/utils.mjs
  components/helpspace/helpspace.app.mjs
  components/helpspace/package.json
  components/helpspace/sources/common/base.mjs
  components/helpspace/sources/new-customer/new-customer.mjs
  components/helpspace/sources/new-customer/test-event.mjs
  components/helpspace/sources/new-ticket/new-ticket.mjs
  components/helpspace/sources/new-ticket/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10763 New Components - chatbot_builder
  components/chatbot_builder/actions/create-tag/create-tag.mjs
  components/chatbot_builder/actions/delete-tag/delete-tag.mjs
  components/chatbot_builder/actions/list-tags/list-tags.mjs
  components/chatbot_builder/chatbot_builder.app.mjs
  components/chatbot_builder/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10862 New Components - freshmarketer
  components/freshmarketer/actions/add-update-contact/add-update-contact.mjs
  components/freshmarketer/actions/find-contact/find-contact.mjs
  components/freshmarketer/actions/remove-contact-from-list/remove-contact-from-list.mjs
  components/freshmarketer/common/constants.mjs
  components/freshmarketer/freshmarketer.app.mjs
  components/freshmarketer/package.json
  components/freshmarketer/sources/common/base.mjs
  components/freshmarketer/sources/new-contact-added-to-list/new-contact-added-to-list.mjs
  components/freshmarketer/sources/new-contact-added-to-list/test-event.mjs
  components/freshmarketer/sources/new-contact-removed-from-list/new-contact-removed-from-list.mjs
  components/freshmarketer/sources/new-contact-removed-from-list/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10770 New Components - fogbugz
  components/fogbugz/actions/create-case/create-case.mjs
  components/fogbugz/actions/list-projects/list-projects.mjs
  components/fogbugz/actions/update-person/update-person.mjs
  components/fogbugz/common/constants.mjs
  components/fogbugz/common/utils.mjs
  components/fogbugz/fogbugz.app.mjs
  components/fogbugz/package.json
  components/fogbugz/sources/common/base.mjs
  components/fogbugz/sources/new-case-in-filter/new-case-in-filter.mjs
  components/fogbugz/sources/new-case-in-filter/test-event.mjs
  components/fogbugz/sources/new-caseevent/new-caseevent.mjs
  components/fogbugz/sources/new-caseevent/test-event.mjs
  components/fogbugz/sources/new-person/new-person.mjs
  components/fogbugz/sources/new-person/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10888 New Components - hyperise
  components/hyperise/actions/create-personalised-short-link/create-personalised-short-link.mjs
  components/hyperise/hyperise.app.mjs
  components/hyperise/package.json
  components/hyperise/sources/new-image-impression/new-image-impression.mjs
  components/hyperise/sources/new-image-impression/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10897 New Components - html_2_pdf
  components/html_2_pdf/actions/generate-pdf/generate-pdf.mjs
  components/html_2_pdf/common/constants.mjs
  components/html_2_pdf/html_2_pdf.app.mjs
  components/html_2_pdf/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11004 New Components - azure_ai_vision
  components/azure_ai_vision/actions/extract-text-from-image/extract-text-from-image.mjs
  components/azure_ai_vision/azure_ai_vision.app.mjs
  components/azure_ai_vision/common/constants.mjs
  components/azure_ai_vision/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10956 New Components - easysendy
  components/easysendy/actions/add-subscriber/add-subscriber.mjs
  components/easysendy/easysendy.app.mjs
  components/easysendy/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#10881 New Components - sendcloud
  components/sendcloud/actions/create-a-parcel/create-a-parcel.mjs
  components/sendcloud/actions/list-parcels/list-parcels.mjs
  components/sendcloud/actions/update-a-parcel/update-a-parcel.mjs
  components/sendcloud/common/constants.mjs
  components/sendcloud/package.json
  components/sendcloud/sendcloud.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#10880 New Components - rollbar
  components/rollbar/actions/create-a-project/create-a-project.mjs
  components/rollbar/actions/delete-a-project/delete-a-project.mjs
  components/rollbar/actions/list-projects/list-projects.mjs
  components/rollbar/package.json
  components/rollbar/rollbar.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11050 New Components - php_point_of_sale
  components/php_point_of_sale/actions/create-register/create-register.mjs
  components/php_point_of_sale/actions/delete-register/delete-register.mjs
  components/php_point_of_sale/actions/get-registers/get-registers.mjs
  components/php_point_of_sale/package.json
  components/php_point_of_sale/php_point_of_sale.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11027 New Components - dynalist
  components/__1msg/__1msg.app.mjs
  components/beebole_app/beebole_app.app.mjs
  components/dynalist/actions/edit-document/edit-document.mjs
  components/dynalist/actions/get-document-content/get-document-content.mjs
  components/dynalist/actions/insert-document-content/insert-document-content.mjs
  components/dynalist/common/utils.mjs
  components/dynalist/dynalist.app.mjs
  components/dynalist/package.json
  components/loyverse/loyverse.app.mjs
  components/nyckel/nyckel.app.mjs
  components/saleor/saleor.app.mjs
  components/salespype/salespype.app.mjs
  components/teamioo/teamioo.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11049 New Components - shadertoy
  components/shadertoy/actions/access-assets/access-assets.mjs
  components/shadertoy/actions/get-shader/get-shader.mjs
  components/shadertoy/actions/list-shaders/list-shaders.mjs
  components/shadertoy/actions/search-shaders/search-shaders.mjs
  components/shadertoy/package.json
  components/shadertoy/shadertoy.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11008 New Components - surveysparrow
  components/surveysparrow/actions/common/share-base.mjs
  components/surveysparrow/actions/create-contact/create-contact.mjs
  components/surveysparrow/actions/create-survey/create-survey.mjs
  components/surveysparrow/actions/share-nps-survey-sms/share-nps-survey-sms.mjs
  components/surveysparrow/actions/share-survey-email/share-survey-email.mjs
  components/surveysparrow/actions/update-survey/update-survey.mjs
  components/surveysparrow/common/constants.mjs
  components/surveysparrow/package.json
  components/surveysparrow/sources/common/base.mjs
  components/surveysparrow/sources/new-ces-submission-instant/new-ces-submission-instant.mjs
  components/surveysparrow/sources/new-ces-submission-instant/test-event.mjs
  components/surveysparrow/sources/new-csat-submission-instant/new-csat-submission-instant.mjs
  components/surveysparrow/sources/new-csat-submission-instant/test-event.mjs
  components/surveysparrow/sources/new-nps-submission-instant/new-nps-submission-instant.mjs
  components/surveysparrow/sources/new-nps-submission-instant/test-event.mjs
  components/surveysparrow/sources/new-survey-response/new-survey-response.mjs
  components/surveysparrow/sources/new-survey-response/test-event.mjs
  components/surveysparrow/surveysparrow.app.mjs
Labels: ai-assisted

#11166 SQL Proxy Methods and Types
  platform/dist/sql-proxy.js
  platform/lib/sql-proxy.ts
  platform/package.json
Labels: enhancement, dependencies, javascript, tracked internally, prioritized, strategic-app

#11043 New Components - zoho-notebook
  components/zoho_notebook/actions/create-notebook/create-notebook.mjs
  components/zoho_notebook/actions/list-notebooks/list-notebooks.mjs
  components/zoho_notebook/common/constants.mjs
  components/zoho_notebook/package.json
  components/zoho_notebook/sources/common/base.mjs
  components/zoho_notebook/sources/new-audio-card/new-audio-card.mjs
  components/zoho_notebook/sources/new-checklist-card/new-checklist-card.mjs
  components/zoho_notebook/sources/new-notecard-in-notebook/new-notecard-in-notebook.mjs
  components/zoho_notebook/zoho_notebook.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#11116 New Components - beebole_app
  components/beebole_app/actions/create-company/create-company.mjs
  components/beebole_app/actions/list-companies/list-companies.mjs
  components/beebole_app/actions/update-company/update-company.mjs
  components/beebole_app/beebole_app.app.mjs
  components/beebole_app/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11198 Expose SQL proxy definitions
  platform/dist/index.js
  platform/lib/index.ts
  platform/package.json
Labels: enhancement, dependencies, prioritized, strategic-app

#11207 New Components - enrow
  components/enrow/actions/find-single-email/find-single-email.mjs
  components/enrow/actions/get-single-email-finder-result/get-single-email-finder-result.mjs
  components/enrow/enrow.app.mjs
  components/enrow/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#11201 Make `mysql` compliant with the SQL proxy
  components/mysql/actions/create-row/create-row.mjs
  components/mysql/actions/delete-row/delete-row.mjs
  components/mysql/actions/execute-query/execute-query.mjs
  components/mysql/actions/execute-raw-query/execute-raw-query.mjs
  components/mysql/actions/execute-stored-procedure/execute-stored-procedure.mjs
  components/mysql/actions/find-row/find-row.mjs
  components/mysql/actions/update-row/update-row.mjs
  components/mysql/mysql.app.mjs
  components/mysql/package.json
  components/mysql/sources/new-column/new-column.mjs
  components/mysql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/mysql/sources/new-row-custom-query/new-row-custom-query.mjs
  components/mysql/sources/new-row/new-row.mjs
  components/mysql/sources/new-table/new-table.mjs
  components/mysql_test/mysql_test.app.mjs
  components/mysql_test/package.json
  pnpm-lock.yaml
Labels: enhancement, dependencies, javascript, prioritized, strategic-app

#11202 Make `postgresql` compliant with the SQL proxy
  components/postgresql/actions/delete-rows/delete-rows.mjs
  components/postgresql/actions/execute-custom-query/execute-custom-query.mjs
  components/postgresql/actions/find-row-custom-query/find-row-custom-query.mjs
  components/postgresql/actions/find-row/find-row.mjs
  components/postgresql/actions/insert-row/insert-row.mjs
  components/postgresql/actions/update-row/update-row.mjs
  components/postgresql/actions/upsert-row/upsert-row.mjs
  components/postgresql/package.json
  components/postgresql/postgresql.app.mjs
  components/postgresql/sources/common.mjs
  components/postgresql/sources/new-column/new-column.mjs
  components/postgresql/sources/new-or-updated-row/new-or-updated-row.mjs
  components/postgresql/sources/new-row-custom-query/new-row-custom-query.mjs
  components/postgresql/sources/new-row/new-row.mjs
  components/postgresql/sources/new-table/new-table.mjs
  components/postgresql_test/package.json
  components/postgresql_test/postgresql_test.app.mjs
  pnpm-lock.yaml
Labels: enhancement, dependencies, javascript, prioritized, strategic-app
