Repository PipedreamHQ/pipedream, pull requests merged in 2025-04, with the labels that each got.

#16064 New Components - quriiri
  components/quriiri/actions/send-message/send-message.mjs
  components/quriiri/common/constants.mjs
  components/quriiri/package.json
  components/quriiri/quriiri.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16023 New Components - vectorshift
  components/botsonic/botsonic.app.mjs
  components/piped/piped.app.mjs
  components/rocketadmin/rocketadmin.app.mjs
  components/supadata/supadata.app.mjs
  components/timelink/timelink.app.mjs
  components/vectorshift/actions/add-data-to-knowledge-base/add-data-to-knowledge-base.mjs
  components/vectorshift/actions/create-pipeline/create-pipeline.mjs
  components/vectorshift/actions/run-pipeline/run-pipeline.mjs
  components/vectorshift/common/constants.mjs
  components/vectorshift/common/utils.mjs
  components/vectorshift/package.json
  components/vectorshift/sources/common/base.mjs
  components/vectorshift/sources/new-chatbot/new-chatbot.mjs
  components/vectorshift/sources/new-chatbot/test-event.mjs
  components/vectorshift/sources/new-knowledge-base/new-knowledge-base.mjs
  components/vectorshift/sources/new-knowledge-base/test-event.mjs
  components/vectorshift/sources/new-pipeline/new-pipeline.mjs
  components/vectorshift/sources/new-pipeline/test-event.mjs
  components/vectorshift/vectorshift.app.mjs
  components/voxapp/voxapp.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16191 New Components - docparser
  components/docparser/actions/fetch-document-url/fetch-document-url.mjs
  components/docparser/actions/upload-document/upload-document.mjs
  components/docparser/common/utils.mjs
  components/docparser/docparser.app.mjs
  components/docparser/package.json
  components/docparser/sources/common/base.mjs
  components/docparser/sources/new-document-data-available/new-document-data-available.mjs
  components/docparser/sources/new-document-data-available/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16154 New Components - lucca
  components/lucca/actions/approve-leave-request/approve-leave-request.mjs
  components/lucca/actions/update-user-info/update-user-info.mjs
  components/lucca/common/constants.mjs
  components/lucca/lucca.app.mjs
  components/lucca/package.json
  components/lucca/sources/common/base.mjs
  components/lucca/sources/new-expense-report/new-expense-report.mjs
  components/lucca/sources/new-expense-report/test-event.mjs
  components/lucca/sources/new-leave-request/new-leave-request.mjs
  components/lucca/sources/new-leave-request/test-event.mjs
  components/lucca/sources/new-user/new-user.mjs
  components/lucca/sources/new-user/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16105 New Components - bloomerang
  components/adyntel/adyntel.app.mjs
  components/agentset/agentset.app.mjs
  components/bloomerang/actions/add-interaction/add-interaction.mjs
  components/bloomerang/actions/create-constituent/create-constituent.mjs
  components/bloomerang/actions/create-donation/create-donation.mjs
  components/bloomerang/bloomerang.app.mjs
  components/bloomerang/common/constants.mjs
  components/bloomerang/package.json
  components/bloomerang/sources/common/base.mjs
  components/bloomerang/sources/new-constituent/new-constituent.mjs
  components/bloomerang/sources/new-constituent/test-event.mjs
  components/bloomerang/sources/new-donation/new-donation.mjs
  components/bloomerang/sources/new-donation/test-event.mjs
  components/bloomerang/sources/new-interaction/new-interaction.mjs
  components/bloomerang/sources/new-interaction/test-event.mjs
  components/changes_page/changes_page.app.mjs
  components/cvr_dev/cvr_dev.app.mjs
  components/hamsa/hamsa.app.mjs
  components/microbilt_developer/microbilt_developer.app.mjs
  components/milvus/milvus.app.mjs
  components/onehash/onehash.app.mjs
  components/public_record/public_record.app.mjs
  components/pushengage/pushengage.app.mjs
  components/satws/satws.app.mjs
  components/savvy_folders/savvy_folders.app.mjs
  components/speak_ai/speak_ai.app.mjs
  components/thesportsdb/thesportsdb.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16375 Fix missing Slack lodash, async-retry dependencies
  components/slack/package.json
  pnpm-lock.yaml
Labels: bug

#16443 Apollo search contacts bug fix
  components/apollo_io/actions/add-contacts-to-sequence/add-contacts-to-sequence.mjs
  components/apollo_io/actions/create-account/create-account.mjs
  components/apollo_io/actions/create-contact/create-contact.mjs
  components/apollo_io/actions/create-opportunity/create-opportunity.mjs
  components/apollo_io/actions/create-update-contact/create-update-contact.mjs
  components/apollo_io/actions/get-opportunity/get-opportunity.mjs
  components/apollo_io/actions/people-enrichment/people-enrichment.mjs
  components/apollo_io/actions/search-accounts/search-accounts.mjs
  components/apollo_io/actions/search-contacts/search-contacts.mjs
  components/apollo_io/actions/search-sequences/search-sequences.mjs
  components/apollo_io/actions/update-account-stage/update-account-stage.mjs
  components/apollo_io/actions/update-account/update-account.mjs
  components/apollo_io/actions/update-contact-stage/update-contact-stage.mjs
  components/apollo_io/actions/update-contact/update-contact.mjs
  components/apollo_io/actions/update-opportunity/update-opportunity.mjs
  components/apollo_io/apollo_io.app.mjs
  components/apollo_io/package.json
  components/apollo_io/sources/account-created/account-created.mjs
  components/apollo_io/sources/account-updated/account-updated.mjs
  components/apollo_io/sources/contact-created/contact-created.mjs
  components/apollo_io/sources/contact-updated/contact-updated.mjs
Labels: User submitted

#16405 New Components - peerdom
  components/peerdom/actions/assign-member-to-role/assign-member-to-role.mjs
  components/peerdom/actions/create-role/create-role.mjs
  components/peerdom/actions/update-role/update-role.mjs
  components/peerdom/common/constants.mjs
  components/peerdom/common/utils.mjs
  components/peerdom/package.json
  components/peerdom/peerdom.app.mjs
  components/peerdom/sources/common/base.mjs
  components/peerdom/sources/new-member/new-member.mjs
  components/peerdom/sources/new-member/test-event.mjs
  components/peerdom/sources/new-role/new-role.mjs
  components/peerdom/sources/new-role/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16425 New Components - convertapi
  components/convertapi/.gitignore
  components/convertapi/actions/convert-base64-encoded-file/convert-base64-encoded-file.mjs
  components/convertapi/actions/convert-file/convert-file.mjs
  components/convertapi/actions/convert-web-url/convert-web-url.mjs
  components/convertapi/app/convertapi.app.ts
  components/convertapi/common/constants.mjs
  components/convertapi/common/utils.mjs
  components/convertapi/convertapi.app.mjs
  components/convertapi/package.json
  pnpm-lock.yaml
Labels: ai-assisted
