Repository PipedreamHQ/pipedream, pull requests merged in 2025-05, with the labels that each got.

#16470 New Components - notiff_io
  components/notiff/actions/create-notification/create-notification.mjs
  components/notiff/common/utils.mjs
  components/notiff/notiff.app.mjs
  components/notiff/package.json
  components/notiff_io/actions/create-notification/create-notification.mjs
  components/notiff_io/notiff_io.app.mjs
  components/notiff_io/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#16490 feat(sdk): add configuredProps arg to updateTrigger method
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  packages/sdk/src/shared/index.ts
  pnpm-lock.yaml
Labels: enhancement, javascript

#16493 [Docs] Add Connect API endpoint for updating a deployed trigger
  docs-v2/pages/connect/api.mdx
Labels: docs

#16498 New Components - pexels
  components/pexels/actions/download-photo/download-photo.mjs
  components/pexels/actions/get-photo-details/get-photo-details.mjs
  components/pexels/actions/search-photos/search-photos.mjs
  components/pexels/common/constants.mjs
  components/pexels/package.json
  components/pexels/pexels.app.mjs
  components/pexels/sources/common/base.mjs
  components/pexels/sources/new-curated-photo/new-curated-photo.mjs
  components/pexels/sources/new-curated-photo/test-event.mjs
  components/pexels/sources/new-photo-by-search/new-photo-by-search.mjs
  components/pexels/sources/new-photo-by-search/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16504 New Components - kiwihr
  components/kiwihr/actions/create-employee/create-employee.mjs
  components/kiwihr/actions/update-employee-record/update-employee-record.mjs
  components/kiwihr/common/constants.mjs
  components/kiwihr/common/mutations.mjs
  components/kiwihr/common/queries.mjs
  components/kiwihr/common/utils.mjs
  components/kiwihr/kiwihr.app.mjs
  components/kiwihr/package.json
  components/kiwihr/sources/common/base.mjs
  components/kiwihr/sources/new-employee/new-employee.mjs
  components/kiwihr/sources/new-employee/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16567 New Components - letzai
  components/letzai/actions/create-image-edit/create-image-edit.mjs
  components/letzai/actions/create-new-image/create-new-image.mjs
  components/letzai/actions/get-image-information/get-image-information.mjs
  components/letzai/common/constants.mjs
  components/letzai/common/utils.mjs
  components/letzai/letzai.app.mjs
  components/letzai/package.json
  components/letzai/sources/common/base.mjs
  components/letzai/sources/new-image-edit/new-image-edit.mjs
  components/letzai/sources/new-image-edit/test-event.mjs
  components/letzai/sources/new-image/new-image.mjs
  components/letzai/sources/new-image/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16579 New Components - transloadit
  components/transloadit/actions/cancel-assembly/cancel-assembly.mjs
  components/transloadit/actions/create-assembly/create-assembly.mjs
  components/transloadit/actions/get-assembly-status/get-assembly-status.mjs
  components/transloadit/common/constants.mjs
  components/transloadit/common/utils.mjs
  components/transloadit/package.json
  components/transloadit/sources/common/base.mjs
  components/transloadit/sources/new-assembly-completed/new-assembly-completed.mjs
  components/transloadit/sources/new-assembly-completed/test-event.mjs
  components/transloadit/sources/new-assembly-error/new-assembly-error.mjs
  components/transloadit/sources/new-assembly-error/test-event.mjs
  components/transloadit/transloadit.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16590 New Components - meetstream_ai
  components/meetstream_ai/actions/create-bot/create-bot.mjs
  components/meetstream_ai/actions/get-audio/get-audio.mjs
  components/meetstream_ai/actions/get-bot-status/get-bot-status.mjs
  components/meetstream_ai/actions/get-transcription/get-transcription.mjs
  components/meetstream_ai/actions/remove-bot/remove-bot.mjs
  components/meetstream_ai/meetstream_ai.app.mjs
  components/meetstream_ai/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#16623 New Components - guru
  components/guru/.gitignore
  components/guru/actions/add-tag-to-card/add-tag-to-card.mjs
  components/guru/actions/create-card/create-card.mjs
  components/guru/actions/export-card-to-pdf/export-card-to-pdf.mjs
  components/guru/app/guru.app.ts
  components/guru/common/constants.mjs
  components/guru/common/utils.mjs
  components/guru/guru.app.mjs
  components/guru/package.json
  components/guru/sources/announcement-read-instant/announcement-read-instant.mjs
  components/guru/sources/announcement-read-instant/test-event.mjs
  components/guru/sources/card-updated-instant/card-updated-instant.mjs
  components/guru/sources/card-updated-instant/test-event.mjs
  components/guru/sources/common/base.mjs
  components/guru/sources/new-card-instant/new-card-instant.mjs
  components/guru/sources/new-card-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16596 New Components - slicktext
  components/slicktext/.gitignore
  components/slicktext/actions/add-contact-to-lists/add-contact-to-lists.mjs
  components/slicktext/actions/common/base.mjs
  components/slicktext/actions/create-contact/create-contact.mjs
  components/slicktext/actions/edit-contact/edit-contact.mjs
  components/slicktext/app/slicktext.app.ts
  components/slicktext/common/constants.mjs
  components/slicktext/common/utils.mjs
  components/slicktext/package.json
  components/slicktext/slicktext.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16714 New Components - browserbase
  components/browserbase/actions/create-context/create-context.mjs
  components/browserbase/actions/create-session/create-session.mjs
  components/browserbase/actions/list-projects/list-projects.mjs
  components/browserbase/browserbase.app.mjs
  components/browserbase/common/constants.mjs
  components/browserbase/common/utils.mjs
  components/browserbase/package.json
  components/browserbase/sources/common/base.mjs
  components/browserbase/sources/new-session/new-session.mjs
  components/browserbase/sources/new-session/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16722 New Components - pdforge
  components/pdforge/actions/common/base.mjs
  components/pdforge/actions/generate-pdf-from-html/generate-pdf-from-html.mjs
  components/pdforge/actions/generate-pdf-from-template/generate-pdf-from-template.mjs
  components/pdforge/common/utils.mjs
  components/pdforge/package.json
  components/pdforge/pdforge.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16712 New Components - scrapeless
  components/scrapeless/actions/get-scrape-result/get-scrape-result.mjs
  components/scrapeless/actions/submit-scrape-job/submit-scrape-job.mjs
  components/scrapeless/common/constants.mjs
  components/scrapeless/common/utils.mjs
  components/scrapeless/package.json
  components/scrapeless/scrapeless.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16692 New Components - selzy
  components/selzy/actions/create-campaign/create-campaign.mjs
  components/selzy/actions/create-email-message/create-email-message.mjs
  components/selzy/common/constants.mjs
  components/selzy/common/utils.mjs
  components/selzy/package.json
  components/selzy/selzy.app.mjs
  components/selzy/sources/common/base.mjs
  components/selzy/sources/new-campaign-status-instant/new-campaign-status-instant.mjs
  components/selzy/sources/new-campaign-status-instant/test-event.mjs
  components/selzy/sources/new-campaign/new-campaign.mjs
  components/selzy/sources/new-campaign/test-event.mjs
  components/selzy/sources/new-subscriber-instant/new-subscriber-instant.mjs
  components/selzy/sources/new-subscriber-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#16836 New Components - syncmate_by_assitro
  components/ringg_ai/ringg_ai.app.mjs
  components/rumi_ai/rumi_ai.app.mjs
  components/syncmate_by_assitro/actions/send-bulk-messages/send-bulk-messages.mjs
  components/syncmate_by_assitro/actions/send-message/send-message.mjs
  components/syncmate_by_assitro/common/utils.mjs
  components/syncmate_by_assitro/package.json
  components/syncmate_by_assitro/syncmate_by_assitro.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted
