Repository PipedreamHQ/pipedream, pull requests merged in 2025-02, with the labels that each got.

#15344 New Components - autodesk
  components/autodesk/actions/create-folder/create-folder.mjs
  components/autodesk/actions/upload-file/upload-file.mjs
  components/autodesk/autodesk.app.mjs
  components/autodesk/package.json
  components/autodesk/sources/common/base-polling.mjs
  components/autodesk/sources/common/base-webhook.mjs
  components/autodesk/sources/new-folder-instant/new-folder-instant.mjs
  components/autodesk/sources/new-folder-instant/test-event.mjs
  components/autodesk/sources/new-project-created/new-project-created.mjs
  components/autodesk/sources/new-project-created/test-event.mjs
  components/autodesk/sources/new-version-instant/new-version-instant.mjs
  components/autodesk/sources/new-version-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15439 New Components - gloria_ai
  components/gloria_ai/actions/create-lead/create-lead.mjs
  components/gloria_ai/gloria_ai.app.mjs
  components/gloria_ai/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#15469 New Components - vapi
  components/vapi/actions/create-call/create-call.mjs
  components/vapi/actions/update-assistant-settings/update-assistant-settings.mjs
  components/vapi/actions/upload-file/upload-file.mjs
  components/vapi/common/constants.mjs
  components/vapi/common/utils.mjs
  components/vapi/package.json
  components/vapi/sources/common/base.mjs
  components/vapi/sources/new-conversation/new-conversation.mjs
  components/vapi/sources/new-conversation/test-event.mjs
  components/vapi/vapi.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15456 New Components - tinyurl
  components/tinyurl/actions/create-shortened-link/create-shortened-link.mjs
  components/tinyurl/actions/retrieve-link-analytics/retrieve-link-analytics.mjs
  components/tinyurl/actions/update-link-metadata/update-link-metadata.mjs
  components/tinyurl/common/utils.mjs
  components/tinyurl/package.json
  components/tinyurl/sources/new-link-created/new-link-created.mjs
  components/tinyurl/tinyurl.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15497 New Components - refiner
  components/refiner/actions/identify-user/identify-user.mjs
  components/refiner/actions/track-event/track-event.mjs
  components/refiner/package.json
  components/refiner/refiner.app.mjs
  components/refiner/sources/common/base.mjs
  components/refiner/sources/new-segment-entry/new-segment-entry.mjs
  components/refiner/sources/new-segment-entry/test-event.mjs
  components/refiner/sources/new-survey-completion/new-survey-completion.mjs
  components/refiner/sources/new-survey-completion/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15525 New Components - salespype
  components/salespype/actions/add-contact-to-campaign/add-contact-to-campaign.mjs
  components/salespype/actions/create-contact/create-contact.mjs
  components/salespype/actions/create-task/create-task.mjs
  components/salespype/package.json
  components/salespype/salespype.app.mjs
  components/salespype/sources/common/base.mjs
  components/salespype/sources/contact-updated/contact-updated.mjs
  components/salespype/sources/new-campaign-created/new-campaign-created.mjs
  components/salespype/sources/new-contact-created/new-contact-created.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15502 New Components - deepseek
  components/deepseek/actions/create-chat-completion/create-chat-completion.mjs
  components/deepseek/actions/get-balance/get-balance.mjs
  components/deepseek/actions/list-models/list-models.mjs
  components/deepseek/common/constants.mjs
  components/deepseek/common/util.mjs
  components/deepseek/deepseek.app.mjs
  components/deepseek/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#15537 New Components - geoapify
  components/geoapify/actions/get-ip-location/get-ip-location.mjs
  components/geoapify/actions/get-route/get-route.mjs
  components/geoapify/actions/search-address/search-address.mjs
  components/geoapify/common/constants.mjs
  components/geoapify/geoapify.app.mjs
  components/geoapify/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#15539 New Components - mapbox
  components/mapbox/.gitignore
  components/mapbox/actions/create-tileset/create-tileset.mjs
  components/mapbox/actions/generate-directions/generate-directions.mjs
  components/mapbox/actions/geocode-address/geocode-address.mjs
  components/mapbox/app/mapbox.app.ts
  components/mapbox/common/constants.mjs
  components/mapbox/mapbox.app.mjs
  components/mapbox/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#15557 New Components - streamlabs
  components/streamlabs/actions/create-donation/create-donation.mjs
  components/streamlabs/actions/send-alert/send-alert.mjs
  components/streamlabs/actions/send-test-alert/send-test-alert.mjs
  components/streamlabs/common/currencies.mjs
  components/streamlabs/package.json
  components/streamlabs/streamlabs.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15598 New Components - axesso_data_service
  components/axesso_data_service/actions/get-product-details/get-product-details.mjs
  components/axesso_data_service/actions/list-reviews/list-reviews.mjs
  components/axesso_data_service/actions/search-products/search-products.mjs
  components/axesso_data_service/axesso_data_service.app.mjs
  components/axesso_data_service/common/constants.mjs
  components/axesso_data_service/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#15512 New Components - google_maps_platform
  components/google_maps_platform/.gitignore
  components/google_maps_platform/actions/get-place-details/get-place-details.mjs
  components/google_maps_platform/actions/search-places/search-places.mjs
  components/google_maps_platform/app/google_maps_platform.app.ts
  components/google_maps_platform/common/constants.mjs
  components/google_maps_platform/common/utils.mjs
  components/google_maps_platform/google_maps_platform.app.mjs
  components/google_maps_platform/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#15246 New Components - motive
  components/adobe_photoshop_lightroom/adobe_photoshop_lightroom.app.mjs
  components/applicantstack/applicantstack.app.mjs
  components/benchmarkone/benchmarkone.app.mjs
  components/claris_filemaker_server_admin_api/claris_filemaker_server_admin_api.app.mjs
  components/claris_filemaker_server_data_api/claris_filemaker_server_data_api.app.mjs
  components/claris_filemaker_server_odata_api/claris_filemaker_server_odata_api.app.mjs
  components/current_rms/current_rms.app.mjs
  components/elastic_cloud/elastic_cloud.app.mjs
  components/felt/felt.app.mjs
  components/globalping/globalping.app.mjs
  components/langfuse/langfuse.app.mjs
  components/mailtrap/mailtrap.app.mjs
  components/morgen/morgen.app.mjs
  components/motive/actions/find-user-details/find-user-details.mjs
  components/motive/common/util.mjs
  components/motive/motive.app.mjs
  components/motive/package.json
  components/motive/sources/common/base.mjs
  components/motive/sources/new-hours-of-service-violation/new-hours-of-service-violation.mjs
  components/motive/sources/new-hours-of-service-violation/test-event.mjs
  components/motive/sources/new-safety-event/new-safety-event.mjs
  components/motive/sources/new-safety-event/test-event.mjs
  components/office_365_management/office_365_management.app.mjs
  components/opnform/opnform.app.mjs
  components/ory/ory.app.mjs
  components/real_id/real_id.app.mjs
  components/referral_rocket/referral_rocket.app.mjs
  components/relintex_crm/relintex_crm.app.mjs
  components/seen/seen.app.mjs
  components/sinch_messagemedia/sinch_messagemedia.app.mjs
  components/stack_overflow_for_teams/stack_overflow_for_teams.app.mjs
  components/zep/zep.app.mjs
  components/zoho_tables/zoho_tables.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15558 New Components - polygon
  components/bitbucket_data_center/bitbucket_data_center.app.mjs
  components/brillium/brillium.app.mjs
  components/frontify/frontify.app.mjs
  components/membership_io/membership_io.app.mjs
  components/polygon/actions/get-company-financials/get-company-financials.mjs
  components/polygon/actions/get-historical-prices/get-historical-prices.mjs
  components/polygon/actions/get-stock-price/get-stock-price.mjs
  components/polygon/common/constants.mjs
  components/polygon/common/utils.mjs
  components/polygon/package.json
  components/polygon/polygon.app.mjs
  components/polygon/sources/common/base.mjs
  components/polygon/sources/new-market-news/new-market-news.mjs
  components/polygon/sources/new-market-news/test-event.mjs
  components/polygon/sources/new-stock-price-summary/new-stock-price-summary.mjs
  components/polygon/sources/new-stock-price-summary/test-event.mjs
  components/polygon/sources/new-stock-trade/new-stock-trade.mjs
  components/polygon/sources/new-stock-trade/test-event.mjs
  components/portabilling/portabilling.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15673 [FIX] SerpApi - issue with no_cache and q props
  components/serpapi/actions/scrape-search/scrape-search.mjs
  components/serpapi/package.json
  components/serpapi/serpapi.app.mjs
  pnpm-lock.yaml
Labels: bug, action

#15561 [Components] azure_storage - new components
  components/azure_storage/actions/create-container/create-container.mjs
  components/azure_storage/actions/delete-blob/delete-blob.mjs
  components/azure_storage/actions/upload-blob/upload-blob.mjs
  components/azure_storage/azure_storage.app.mjs
  components/azure_storage/common/constants.mjs
  components/azure_storage/common/utils.mjs
  components/azure_storage/package.json
  components/azure_storage/sources/blob-deleted/blob-deleted.mjs
  components/azure_storage/sources/blob-deleted/test-event.mjs
  components/azure_storage/sources/common/polling.mjs
  components/azure_storage/sources/new-blob-created/new-blob-created.mjs
  components/azure_storage/sources/new-blob-created/test-event.mjs
  components/azure_storage/sources/new-container-created/new-container-created.mjs
  components/azure_storage/sources/new-container-created/test-event.mjs
  pnpm-lock.yaml
Labels: action, trigger / source

#15734 New Components - opnform
  components/opnform/opnform.app.mjs
  components/opnform/package.json
  components/opnform/sources/new-submission-instant/new-submission-instant.mjs
  components/opnform/sources/new-submission-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15692 New Components - elastic_email
  components/elastic_email/.gitignore
  components/elastic_email/actions/add-contact/add-contact.mjs
  components/elastic_email/actions/send-email/send-email.mjs
  components/elastic_email/actions/unsubscribe-contact/unsubscribe-contact.mjs
  components/elastic_email/app/elastic_email.app.ts
  components/elastic_email/common/constants.mjs
  components/elastic_email/common/utils.mjs
  components/elastic_email/elastic_email.app.mjs
  components/elastic_email/package.json
  components/elastic_email/sources/common/base.mjs
  components/elastic_email/sources/new-contact-added/new-contact-added.mjs
  components/elastic_email/sources/new-contact-added/test-event.mjs
  components/elastic_email/sources/new-email-click/new-email-click.mjs
  components/elastic_email/sources/new-email-click/test-event.mjs
  components/elastic_email/sources/new-email-open/new-email-open.mjs
  components/elastic_email/sources/new-email-open/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted
