Repository PipedreamHQ/pipedream, pull requests merged in 2025-01, with the labels that each got.

#15111 New Components - screenshot_fyi
  components/screenshot_fyi/actions/create-screenshot/create-screenshot.mjs
  components/screenshot_fyi/package.json
  components/screenshot_fyi/screenshot_fyi.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15109 New Components - taleez
  components/taleez/actions/add-candidate-to-job/add-candidate-to-job.mjs
  components/taleez/actions/create-candidate/create-candidate.mjs
  components/taleez/actions/list-jobs/list-jobs.mjs
  components/taleez/package.json
  components/taleez/sources/common/base.mjs
  components/taleez/sources/new-candidate-created/new-candidate-created.mjs
  components/taleez/sources/new-job-listed/new-job-listed.mjs
  components/taleez/taleez.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15102 New Components - callerapi
  components/callerapi/actions/get-phone-number-information/get-phone-number-information.mjs
  components/callerapi/actions/get-phone-number-picture/get-phone-number-picture.mjs
  components/callerapi/callerapi.app.mjs
  components/callerapi/package.json
  components/richpanel/richpanel.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15125 New Components - alegra
  components/alegra/actions/create-contact/create-contact.mjs
  components/alegra/actions/create-invoice/create-invoice.mjs
  components/alegra/actions/find-contact/find-contact.mjs
  components/alegra/alegra.app.mjs
  components/alegra/common/constants.mjs
  components/alegra/common/utils.mjs
  components/alegra/package.json
  components/alegra/sources/common/base.mjs
  components/alegra/sources/new-client-instant/new-client-instant.mjs
  components/alegra/sources/new-client-instant/test-event.mjs
  components/alegra/sources/new-invoice-instant/new-invoice-instant.mjs
  components/alegra/sources/new-invoice-instant/test-event.mjs
  components/alegra/sources/new-item-instant/new-item-instant.mjs
  components/alegra/sources/new-item-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15108 New Components - richpanel
  components/azure_storage/azure_storage.app.mjs
  components/elevio/elevio.app.mjs
  components/homerun/homerun.app.mjs
  components/ragie/ragie.app.mjs
  components/refiner/refiner.app.mjs
  components/richpanel/actions/add-ticket-message/add-ticket-message.mjs
  components/richpanel/actions/create-ticket/create-ticket.mjs
  components/richpanel/actions/update-ticket-status/update-ticket-status.mjs
  components/richpanel/common/constants.mjs
  components/richpanel/common/utils.mjs
  components/richpanel/package.json
  components/richpanel/richpanel.app.mjs
  components/richpanel/sources/common/base.mjs
  components/richpanel/sources/new-message/new-message.mjs
  components/richpanel/sources/new-message/test-event.mjs
  components/richpanel/sources/new-ticket/new-ticket.mjs
  components/richpanel/sources/new-ticket/test-event.mjs
  components/typefully/typefully.app.mjs
  components/what_are_those/what_are_those.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15231 Fix toggling optional props in Connect
  packages/connect-react/package.json
  packages/connect-react/src/hooks/form-context.tsx
  pnpm-lock.yaml
Labels: bug, javascript, tracked internally, prioritized

#15201 New Components - easypromos
  components/easypromos/easypromos.app.mjs
  components/easypromos/package.json
  components/easypromos/sources/common/base.mjs
  components/easypromos/sources/new-coin-transaction/new-coin-transaction.mjs
  components/easypromos/sources/new-coin-transaction/test-event.mjs
  components/easypromos/sources/new-participation/new-participation.mjs
  components/easypromos/sources/new-participation/test-event.mjs
  components/easypromos/sources/new-user/new-user.mjs
  components/easypromos/sources/new-user/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15217 New Components - typefully
  components/typefully/actions/create-draft/create-draft.mjs
  components/typefully/actions/schedule-draft-next-slot/schedule-draft-next-slot.mjs
  components/typefully/actions/schedule-draft/schedule-draft.mjs
  components/typefully/package.json
  components/typefully/sources/common/base.mjs
  components/typefully/sources/new-draft-published/new-draft-published.mjs
  components/typefully/sources/new-draft-published/test-event.mjs
  components/typefully/sources/new-draft-scheduled/new-draft-scheduled.mjs
  components/typefully/sources/new-draft-scheduled/test-event.mjs
  components/typefully/typefully.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15228 New Components - instantly
  components/charthop/charthop.app.mjs
  components/instantly/actions/add-lead-campaign/add-lead-campaign.mjs
  components/instantly/actions/add-tags-campaign/add-tags-campaign.mjs
  components/instantly/actions/update-lead-status/update-lead-status.mjs
  components/instantly/common/constants.mjs
  components/instantly/common/utils.mjs
  components/instantly/instantly.app.mjs
  components/instantly/package.json
  components/instantly/sources/new-event-instant/new-event-instant.mjs
  components/instantly/sources/new-event-instant/test-event.mjs
  components/opensrs/opensrs.app.mjs
  components/xverify/xverify.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15301 New Components - egnyte
  components/egnyte/actions/create-folder/create-folder.mjs
  components/egnyte/actions/upload-file/upload-file.mjs
  components/egnyte/egnyte.app.mjs
  components/egnyte/package.json
  components/egnyte/sources/common/base.mjs
  components/egnyte/sources/new-file-in-folder/new-file-in-folder.mjs
  components/egnyte/sources/new-folder-added/new-folder-added.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15261 New Components - dixa
  components/dixa/actions/add-message/add-message.mjs
  components/dixa/actions/create-conversation/create-conversation.mjs
  components/dixa/actions/set-custom-contact-attributes/set-custom-contact-attributes.mjs
  components/dixa/actions/tag-conversation/tag-conversation.mjs
  components/dixa/dixa.app.mjs
  components/dixa/package.json
  components/dixa/sources/common/base.mjs
  components/dixa/sources/conversation-status-changed-instant/conversation-status-changed-instant.mjs
  components/dixa/sources/conversation-status-changed-instant/test-event.mjs
  components/dixa/sources/new-conversation-created-instant/new-conversation-created-instant.mjs
  components/dixa/sources/new-conversation-created-instant/test-event.mjs
  components/dixa/sources/new-customer-satisfaction-rating-instant/new-customer-satisfaction-rating-instant.mjs
  components/dixa/sources/new-customer-satisfaction-rating-instant/test-event.mjs
  components/dixa/sources/new-message-added-instant/new-message-added-instant.mjs
  components/dixa/sources/new-message-added-instant/test-event.mjs
  components/dixa/sources/new-tag-added-instant/new-tag-added-instant.mjs
  components/dixa/sources/new-tag-added-instant/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15311 New Components - ocrspace
  components/ocrspace/actions/common/process-base.mjs
  components/ocrspace/actions/process-image/process-image.mjs
  components/ocrspace/actions/process-pdf/process-pdf.mjs
  components/ocrspace/common/constants.mjs
  components/ocrspace/common/utils.mjs
  components/ocrspace/ocrspace.app.mjs
  components/ocrspace/package.json
  pnpm-lock.yaml
Labels: ai-assisted

#15322 New Components - ragie
  components/ragie/actions/create-document/create-document.mjs
  components/ragie/actions/update-document-file/update-document-file.mjs
  components/ragie/common/constants.mjs
  components/ragie/common/utils.mjs
  components/ragie/package.json
  components/ragie/ragie.app.mjs
  components/ragie/sources/common/base.mjs
  components/ragie/sources/new-connection/new-connection.mjs
  components/ragie/sources/new-connection/test-event.mjs
  components/ragie/sources/new-document/new-document.mjs
  components/ragie/sources/new-document/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#15357 Fix typo in SDK docs for `getAccountById`
  docs-v2/pages/connect/api.mdx
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  packages/sdk/src/server/index.ts
  pnpm-lock.yaml
Labels: docs, javascript, tracked internally, prioritized

#15385 Update SDK with new endpoints for triggers
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  packages/sdk/src/shared/component.ts
  packages/sdk/src/shared/index.ts
  pnpm-lock.yaml
Labels: enhancement, docs, javascript, tracked internally, prioritized

#15387 Update docs for the components API
  docs-v2/pages/connect/api.mdx
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  packages/sdk/src/shared/index.ts
Labels: enhancement, docs, javascript, tracked internally, prioritized
