Repository PipedreamHQ/pipedream, pull requests merged in 2025-06, with the labels that each got.

#16934 Fix SDK bug in the `deployTrigger` method
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  packages/sdk/src/shared/index.ts
  pnpm-lock.yaml
Labels: bug, pd-api, javascript, tracked internally, prioritized

#16938 Action enhancement - Gmail - Find email
  components/gmail/actions/create-draft/create-draft.mjs
  components/gmail/actions/find-email/find-email.mjs
  components/gmail/actions/send-email/send-email.mjs
  components/gmail/common/utils.mjs
  components/gmail/package.json
  pnpm-lock.yaml
Labels: User submitted

#16885 New Components - drimify
  components/drimify/drimify.app.mjs
  components/drimify/package.json
  components/drimify/sources/new-application-data/new-application-data.mjs
  components/drimify/sources/new-application-data/test-event.mjs
  pnpm-lock.yaml
Labels: ai-assisted

#17060 Codeqr new actions
  components/codeqr/README.md
  components/codeqr/actions/create-link/create-link.mjs
  components/codeqr/actions/create-qrcode/create-qrcode.mjs
  components/codeqr/actions/delete-link/delete-link.mjs
  components/codeqr/actions/delete-qrcode/delete-qrcode.mjs
  components/codeqr/actions/get-link-info/get-link-info.mjs
  components/codeqr/actions/get-qrcode-info/get-qrcode-info.mjs
  components/codeqr/codeqr.app.mjs
  components/codeqr/common/constants.mjs
  components/codeqr/package.json
  pnpm-lock.yaml
Labels: User submitted

#16940 [Components] zoom_admin - fix to get-meeting-recordings
  components/zoom_admin/actions/get-meeting-recordings/get-meeting-recordings.mjs
  components/zoom_admin/package.json
Labels: User submitted

#16967 [Components] zoom_admin - new components
  components/zoom_admin/actions/list-user-cloud-recordings/list-user-cloud-recordings.mjs
  components/zoom_admin/actions/list-users/list-users.mjs
  components/zoom_admin/package.json
  components/zoom_admin/zoom_admin.app.mjs
Labels: User submitted

#17044 New Components - picqer
  components/add_to_calendar_pro/add_to_calendar_pro.app.mjs
  components/arpoone/arpoone.app.mjs
  components/commonninja/commonninja.app.mjs
  components/openai_passthrough/openai_passthrough.app.mjs
  components/pembee/pembee.app.mjs
  components/phonely/phonely.app.mjs
  components/picqer/actions/add-order-comment/add-order-comment.mjs
  components/picqer/actions/add-return-comment/add-return-comment.mjs
  components/picqer/actions/create-order/create-order.mjs
  components/picqer/actions/get-customer/get-customer.mjs
  components/picqer/actions/get-order/get-order.mjs
  components/picqer/actions/get-picklist/get-picklist.mjs
  components/picqer/actions/get-status-per-order-line/get-status-per-order-line.mjs
  components/picqer/actions/search-orders/search-orders.mjs
  components/picqer/actions/update-order/update-order.mjs
  components/picqer/common/constants.mjs
  components/picqer/common/utils.mjs
  components/picqer/package.json
  components/picqer/picqer.app.mjs
  components/picqer/sources/common/base.mjs
  components/picqer/sources/new-event-instant/new-event-instant.mjs
  components/picqer/sources/new-event-instant/test-event.mjs
  components/postmaster/postmaster.app.mjs
  components/test_apps_for_switching_appslug_025/test_apps_for_switching_appslug_025.app.mjs
  pnpm-lock.yaml
Labels: ai-assisted
